create table ALLURL(
	ID int AUTO_INCREMENT NOT NULL,
	URL VARCHAR(256) NOT NULL UNIQUE,
	URL_ID int,
	DATE_TIME DATETIME,URL_TIMESTAMP DATETIME,
	TEXT_WEIGHT float,
	PRIMARY KEY(ID),
	FOREIGN KEY (URL_ID) REFERENCES ALLURL(ID)
)
;
create table IMAGE(
	ID int AUTO_INCREMENT NOT NULL,
	URL VARCHAR(256) NOT NULL UNIQUE,
	DATE_TIME DATETIME,
	IMAGE_WEIGHT float,
	PRIMARY KEY(ID)
)
;
create table HAS(
	PAGE_ID int NOT NULL,
	IMAGE_ID int NOT NULL,
	PRIMARY KEY(PAGE_ID,IMAGE_ID),
	FOREIGN KEY (PAGE_ID) REFERENCES ALLURL(ID),
	FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)
)
;
create table ISP(
	ID int AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	COUNTRY VARCHAR(5),
	PHONE VARCHAR(256),
	E_MAIL VARCHAR(256),
	IP_RANGE VARCHAR(256) NOT NULL UNIQUE,
	PRIMARY KEY(ID)
);

create table PORN_WEB(
	ID int AUTO_INCREMENT NOT NULL,
	URL VARCHAR(256) NOT NULL UNIQUE,
	IP_ADDRESS VARCHAR(256),
	DATE_TIME DATETIME,
	TOTAL_WEIGHT float,
	ISP_ID int,
	CHILD int NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ISP_ID) REFERENCES ISP(ID)
);
create table QUERIES(
	ID int AUTO_INCREMENT NOT NULL,
	POOL VARCHAR(256) NOT NULL UNIQUE,
	CHECKED int,
	PRIMARY KEY(ID)
)
;

