//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace WApplication.WebReference22 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://161.246.5.112/WService2/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TitleAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TitleAll(string a, string b, string c, string d, int count) {
            object[] results = this.Invoke("TitleAll", new object[] {
                        a,
                        b,
                        c,
                        d,
                        count});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTitleAll(string a, string b, string c, string d, int count, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TitleAll", new object[] {
                        a,
                        b,
                        c,
                        d,
                        count}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndTitleAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TitleSome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TitleSome(string a, string b, string c, string d, int count) {
            object[] results = this.Invoke("TitleSome", new object[] {
                        a,
                        b,
                        c,
                        d,
                        count});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTitleSome(string a, string b, string c, string d, int count, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TitleSome", new object[] {
                        a,
                        b,
                        c,
                        d,
                        count}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndTitleSome(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KeywordAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KeywordAll(string a, string b, string c, string d, int count) {
            object[] results = this.Invoke("KeywordAll", new object[] {
                        a,
                        b,
                        c,
                        d,
                        count});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginKeywordAll(string a, string b, string c, string d, int count, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("KeywordAll", new object[] {
                        a,
                        b,
                        c,
                        d,
                        count}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndKeywordAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KeywordSome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KeywordSome(string a, string b, string c, string d, int count) {
            object[] results = this.Invoke("KeywordSome", new object[] {
                        a,
                        b,
                        c,
                        d,
                        count});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginKeywordSome(string a, string b, string c, string d, int count, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("KeywordSome", new object[] {
                        a,
                        b,
                        c,
                        d,
                        count}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndKeywordSome(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Uname", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Uname() {
            object[] results = this.Invoke("Uname", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUname(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Uname", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUname(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listFac", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet listFac() {
            object[] results = this.Invoke("listFac", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistFac(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listFac", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistFac(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listDept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet listDept(string aa) {
            object[] results = this.Invoke("listDept", new object[] {
                        aa});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistDept(string aa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listDept", new object[] {
                        aa}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistDept(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listYear", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet listYear() {
            object[] results = this.Invoke("listYear", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistYear(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listYear", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistYear(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="listYear1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listYearWithFac", RequestElementName="listYearWithFac", RequestNamespace="http://tempuri.org/", ResponseElementName="listYearWithFacResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("listYearWithFacResult")]
        public System.Data.DataSet listYear(string fac) {
            object[] results = this.Invoke("listYear1", new object[] {
                        fac});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistYear1(string fac, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listYear1", new object[] {
                        fac}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistYear1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="listYear2")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listYearWithFacDept", RequestElementName="listYearWithFacDept", RequestNamespace="http://tempuri.org/", ResponseElementName="listYearWithFacDeptResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("listYearWithFacDeptResult")]
        public System.Data.DataSet listYear(string fac, string dept) {
            object[] results = this.Invoke("listYear2", new object[] {
                        fac,
                        dept});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistYear2(string fac, string dept, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listYear2", new object[] {
                        fac,
                        dept}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistYear2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/result", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string result() {
            object[] results = this.Invoke("result", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginresult(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("result", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string Endresult(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DetailP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DetailP(string jj) {
            object[] results = this.Invoke("DetailP", new object[] {
                        jj});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDetailP(string jj, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DetailP", new object[] {
                        jj}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndDetailP(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DetailA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DetailA(string jj) {
            object[] results = this.Invoke("DetailA", new object[] {
                        jj});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDetailA(string jj, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DetailA", new object[] {
                        jj}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndDetailA(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Name", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Name(string a, string kind) {
            object[] results = this.Invoke("Name", new object[] {
                        a,
                        kind});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginName(string a, string kind, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Name", new object[] {
                        a,
                        kind}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Group", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Group() {
            object[] results = this.Invoke("Group", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGroup(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Group", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGroup(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GroupDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GroupDB(string gr) {
            object[] results = this.Invoke("GroupDB", new object[] {
                        gr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGroupDB(string gr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GroupDB", new object[] {
                        gr}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGroupDB(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Mail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Mail(string gr) {
            object[] results = this.Invoke("Mail", new object[] {
                        gr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMail(string gr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Mail", new object[] {
                        gr}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndMail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
