## Process this file with automake to produce Makefile.in

## Created by Anjuta - will be overwritten
## If you don't want it to overwrite it,
## 	Please disable it in the Anjuta project configuration

isagmq_includedir = $(pkgincludedir)

isagmq_include_DATA = \
	common.h\
	dbmysql.h\
	implementfn.h\
	linklist.h\
	reentrant.h\
	serv_services.h\
	support_serv.h

EXTRA_DIST = $(isagmq_include_DATA)
