/*
 * GIS_v1.java
 *
 * Created on January 7, 2002, 3:05 PM
 */

//package GIS_v1;
import javax.swing.*;
//Cache Class
import COM.intersys.objects.*;
import COM.intersys.objects.attribute.*;
import COM.intersys.util.SysList;
import COM.intersys.util.CacheException;

/**
 *
 * @author  n'ai'
 */
public class GIS_v1 extends javax.swing.JFrame {
   
    /** Creates new form GIS_v1 */
    public GIS_v1() {
        //super("GIS_v1");
       initComponents();
	//Connect to Cache~ 
	try{
	   factory = new ObjectFactory( "cn_iptcp:127.0.0.1[1972]:MYPROJECT" );	
        } catch (Exception ex) {
            System.out.println( "Caught exception: " + ex.getClass().getName()
                                                     + ": " + ex.getMessage() );
	}
        GISDesktopPane = new JDesktopPane(); //a specialized layered pane
		Qframe = new QueryFrame(factory);
        //Qframe.factory=factory;
        Mframe = new MapFrame();
        Iframe=new InsertFrame(factory);
        Uframe=new UpdateFrame(factory);
        Qframe.setVisible(true); //necessary as of kestrel
		Mframe.setVisible(true);
        Uframe.setVisible(true);
        Iframe.setVisible(true);
        GISDesktopPane.add(Qframe);
        try {
            Qframe.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
        GISDesktopPane.add(Mframe);
        GISDesktopPane.add(Iframe);
        GISDesktopPane.add(Uframe);
        
        Qframe.MVector.addElement(Mframe);
        Qframe.UVector.addElement(Uframe);
        
        setContentPane(GISDesktopPane);
        GISDesktopPane.putClientProperty("JDesktopPane.dragMode", "outline");
    }

    protected void createFrame() {
        //MyInternalFrame frame = new MyInternalFrame();
	//QueryFrame Inframe = new QueryFrame();
        MapFrame Inframe = new MapFrame();
        Inframe.setVisible(true); //necessary as of kestrel
        GISDesktopPane.add(Inframe);
        try {
            Inframe.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        GISDesktopPane = new javax.swing.JDesktopPane();
        
        getContentPane().setLayout(null);
        
        setTitle("GIS Program");
        setName("GISFrame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        getContentPane().add(GISDesktopPane);
        GISDesktopPane.setBounds(0, 0, 427, 280);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(800, 600));
        setLocation((screenSize.width-800)/2,(screenSize.height-600)/2);
    }//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // Add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    
    
    public static void main(String args[]) {
        new GIS_v1().show();
/*        InternalFrameDemo frame = new InternalFrameDemo();
        frame.setVisible(true);
*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane GISDesktopPane;
    // End of variables declaration//GEN-END:variables
    private ObjectFactory  factory;
    private QueryFrame Qframe;
    private MapFrame Mframe;
    private InsertFrame Iframe;
    private UpdateFrame Uframe;



}
