/*
 * MapFrame.java
 *
 * Created on March 2, 2002, 5:11 PM
 */

//package GIS_v1;
import javax.swing.*;
import java.awt.Dimension;
import java.util.*;
/**
 *
 * @author  n'ai'
 */
public class MapFrame extends javax.swing.JInternalFrame {

    /** Creates new form MapFrame */
    public MapFrame() {
        
//----------------------------------Create DefaultTableModel--------------------------------------------
        VdefaultTable=new javax.swing.table.DefaultTableModel(
        new Object [][] {
        },
        new String [] {            
            "Village Name", "Village Area", "Population", "Show"
        }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };
            
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

	    };

        RdefaultTable=new javax.swing.table.DefaultTableModel(
        new String [] {
            "Road Name","Road Type", "Road Length", "Traffic", "Show"
        },0
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };
            
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

	    };
            
//----------------------------------------------------------------------------------------------------------------
       
       initComponents();
        MapScrollPane.setViewportView(DrawAreaPanel);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        RepresentPanel = new javax.swing.JPanel();
        RedTextField = new javax.swing.JTextField();
        RedLabel = new javax.swing.JLabel();
        MagentaTextField = new javax.swing.JTextField();
        MagentaLabel = new javax.swing.JLabel();
        PinkTextField = new javax.swing.JTextField();
        PinkLabel = new javax.swing.JLabel();
        BlueTextField = new javax.swing.JTextField();
        BlueLabel = new javax.swing.JLabel();
        CyanTextField = new javax.swing.JTextField();
        CyanLabel = new javax.swing.JLabel();
        GreenTextField = new javax.swing.JTextField();
        GreenLabel = new javax.swing.JLabel();
        MapPanel = new javax.swing.JPanel();
        MapScrollPane = new javax.swing.JScrollPane();
        AttributePanel = new javax.swing.JPanel();
        VAScrollPane = new javax.swing.JScrollPane();
        RAScrollPane = new javax.swing.JScrollPane();
        DetailPanel = new javax.swing.JPanel();
        DetailScrollPane = new javax.swing.JScrollPane();
        DetailTextArea = new javax.swing.JTextArea();
        
        setIconifiable(true);
        setTitle("MapFrame");
        setPreferredSize(new java.awt.Dimension(700, 500));
        RepresentPanel.setLayout(null);
        
        RepresentPanel.setBorder(new javax.swing.border.TitledBorder(null, "Color Represent", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), java.awt.Color.blue));
        RepresentPanel.setPreferredSize(new java.awt.Dimension(165, 460));
        RedTextField.setBackground(java.awt.Color.red);
        RedTextField.setEditable(false);
        RepresentPanel.add(RedTextField);
        RedTextField.setBounds(10, 30, 20, 21);
        
        RedLabel.setText(" Non-condition Village");
        RepresentPanel.add(RedLabel);
        RedLabel.setBounds(30, 30, 130, 20);
        
        MagentaTextField.setBackground(java.awt.Color.magenta);
        MagentaTextField.setEditable(false);
        RepresentPanel.add(MagentaTextField);
        MagentaTextField.setBounds(10, 60, 20, 21);
        
        MagentaLabel.setText(" Condition Village");
        RepresentPanel.add(MagentaLabel);
        MagentaLabel.setBounds(30, 60, 130, 20);
        
        PinkTextField.setBackground(java.awt.Color.pink);
        PinkTextField.setEditable(false);
        RepresentPanel.add(PinkTextField);
        PinkTextField.setBounds(10, 90, 20, 21);
        
        PinkLabel.setText(" Selected Village ");
        RepresentPanel.add(PinkLabel);
        PinkLabel.setBounds(30, 90, 130, 20);
        
        BlueTextField.setBackground(java.awt.Color.blue);
        BlueTextField.setEditable(false);
        RepresentPanel.add(BlueTextField);
        BlueTextField.setBounds(10, 120, 20, 21);
        
        BlueLabel.setText(" Non-condition Road");
        RepresentPanel.add(BlueLabel);
        BlueLabel.setBounds(30, 120, 130, 20);
        
        CyanTextField.setBackground(java.awt.Color.cyan);
        CyanTextField.setEditable(false);
        RepresentPanel.add(CyanTextField);
        CyanTextField.setBounds(10, 150, 20, 21);
        
        CyanLabel.setText(" Condition Road");
        RepresentPanel.add(CyanLabel);
        CyanLabel.setBounds(30, 150, 130, 20);
        
        GreenTextField.setBackground(java.awt.Color.green);
        GreenTextField.setEditable(false);
        RepresentPanel.add(GreenTextField);
        GreenTextField.setBounds(10, 180, 20, 21);
        
        GreenLabel.setText(" Selected Road");
        RepresentPanel.add(GreenLabel);
        GreenLabel.setBounds(30, 180, 130, 20);
        
        getContentPane().add(RepresentPanel, java.awt.BorderLayout.WEST);
        
        MapPanel.setLayout(new java.awt.BorderLayout());
        
        MapPanel.setPreferredSize(new java.awt.Dimension(685, 460));
        MapScrollPane.setBackground(java.awt.Color.white);
        MapScrollPane.setAlignmentX(1.0F);
        MapScrollPane.setAlignmentY(1.0F);
        MapScrollPane.setPreferredSize(new java.awt.Dimension(600, 400));
        MapPanel.add(MapScrollPane, java.awt.BorderLayout.CENTER);
        
        AttributePanel.setLayout(new java.awt.GridLayout(2, 0));
        
        VAScrollPane.setPreferredSize(new java.awt.Dimension(600, 75));
        VTable = new javax.swing.JTable(VdefaultTable);
        VTable.setCellSelectionEnabled(true);
        VTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VTableMousePressed(evt);
            }
        });
        VAScrollPane.setViewportView(VTable);
        
        AttributePanel.add(VAScrollPane);
        
        RAScrollPane.setPreferredSize(new java.awt.Dimension(600, 75));
        RTable = new javax.swing.JTable(RdefaultTable);
        RTable.setCellSelectionEnabled(true);
        RTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RTableMousePressed(evt);
            }
        });
        RAScrollPane.setViewportView(RTable);
        AttributePanel.add(RAScrollPane);
        
        MapPanel.add(AttributePanel, java.awt.BorderLayout.SOUTH);
        
        getContentPane().add(MapPanel, java.awt.BorderLayout.CENTER);
        
        DetailPanel.setLayout(new java.awt.BorderLayout());
        
        DetailPanel.setBorder(new javax.swing.border.TitledBorder(null, "Map Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), java.awt.Color.blue));
        DetailPanel.setPreferredSize(new java.awt.Dimension(800, 80));
        DetailScrollPane.setViewportView(DetailTextArea);
        
        DetailPanel.add(DetailScrollPane, java.awt.BorderLayout.CENTER);
        
        getContentPane().add(DetailPanel, java.awt.BorderLayout.NORTH);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(700, 500));
        setLocation((screenSize.width-700)/2,(screenSize.height-500)/2);
    }//GEN-END:initComponents
    public void addMapDetail(String Atdate,String Vcon,String Rcon)
    {
        String str;
        str=" At Date : "+Atdate+
            "\n Village Condition : "+ Vcon+
            "\n Road Condition : "+ Rcon;
        DetailTextArea.removeAll();
        DetailTextArea.setText(str);
    }
    
    private void VTableMousePressed(java.awt.event.MouseEvent evt) 
    {
        String val;
        // Add your handling code here:
        int i=VTable.getSelectedColumn();
        int j=VTable.getSelectedRow();
        
        if (i== 3)
        {
            System.out.print(Integer.toString(j)+","+Integer.toString(i)+" : ");
            val=VTable.getValueAt(j,i).toString();
            System.out.println(val);
            if (val=="true")
            {   DrawAreaPanel.VAShow.setElementAt("false",j);}
            else 
            {   DrawAreaPanel.VAShow.setElementAt("true",j);}
            System.out.println("Pass VTableMousePressed");
            DrawAreaPanel.repaint();
        }
        else
        {
            System.out.println("Hello");
        }
    }
    
    private void RTableMousePressed(java.awt.event.MouseEvent evt) 
    {   
        String val;
        // Add your handling code here:
            int i=RTable.getSelectedColumn();
            int j=RTable.getSelectedRow();
        
        if (i== 4)
        {
            System.out.print(Integer.toString(j)+","+Integer.toString(i)+" : ");
            val=RTable.getValueAt(j,i).toString();
            System.out.println(val);
            if(val=="true")
            {
                DrawAreaPanel.RAShow.setElementAt("false",j);
            }
            else
            {
                DrawAreaPanel.RAShow.setElementAt("true",j);
            }
            DrawAreaPanel.repaint();
        }
        else
        {
            System.out.println("Hello");
        }
    }
    
    public void AddVillageAttribute()
    {
        System.out.println("AddVillageAttribute");
        Vector va=new Vector();
        va=DrawAreaPanel.VillageAttribute;
        Vector rowData=new Vector();
        VillageContainer vc;
         //co++;
        System.out.println("DrawAreaPanel.VillageAttribute Count : "+ Integer.toString(va.size()));
        for(int i=0; i<va.size(); i++)
        {
            vc=(VillageContainer)va.elementAt(i);
            rowData.addElement(vc.Name);
            rowData.addElement(Double.toString(vc.area));
            rowData.addElement(Double.toString(vc.population));
            rowData.addElement(Boolean.valueOf("false"));
	    VdefaultTable.addRow(rowData);
            rowData = new Vector();
        }
    }

    public void AddRoadAttribute()
    {/*	public double   roadlong,roadtraffic;
	public int roadtype;*/
        Vector ra=new Vector();
        ra=DrawAreaPanel.RoadAttribute;
        Vector rowData=new Vector();
        RoadContainer rc;
       //co++;
        for(int i=0; i<ra.size(); i++)
        {
            rc=(RoadContainer)ra.elementAt(i);
            rowData.addElement(rc.Name);
            rowData.addElement(Integer.toString(rc.roadtype));
            rowData.addElement(Double.toString(rc.roadlong));
            rowData.addElement(Double.toString(rc.roadtraffic));
            rowData.addElement(Boolean.valueOf("false"));
	    RdefaultTable.addRow(rowData);
            rowData = new Vector();
        }
    }

    public void resetAPoint(int count,Vector AShow)
    {
        if(AShow.size()>0)
        {
            System.out.print("AShow.size() = ");
            System.out.println(AShow.size());
            AShow.clear();
        }
        else { System.out.println("AShow.size() = 0");}
        
        for (int i=0;i<count;i++)
        {   AShow.addElement("false");    }        
        System.out.println("ResetAPoint Finish");
    }
    
    public void clearTable()
    {
        int count;
        int i;
        System.out.println("Clear Table");
        System.out.print("RdefaultTable.getRowCount() : ");
        count=VdefaultTable.getRowCount();
//        System.out.println(vcount);
        for(i=0; i<count; i++)
        {
            VdefaultTable.removeRow(0);
            //System.out.println(i);
        }
        count=RdefaultTable.getRowCount();
        System.out.println(count);        
        for(i=0; i<count; i++)
        {
            RdefaultTable.removeRow(0);
            System.out.println(i);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RepresentPanel;
    private javax.swing.JTextField RedTextField;
    private javax.swing.JLabel RedLabel;
    private javax.swing.JTextField MagentaTextField;
    private javax.swing.JLabel MagentaLabel;
    private javax.swing.JTextField PinkTextField;
    private javax.swing.JLabel PinkLabel;
    private javax.swing.JTextField BlueTextField;
    private javax.swing.JLabel BlueLabel;
    private javax.swing.JTextField CyanTextField;
    private javax.swing.JLabel CyanLabel;
    private javax.swing.JTextField GreenTextField;
    private javax.swing.JLabel GreenLabel;
    private javax.swing.JPanel MapPanel;
    private javax.swing.JScrollPane MapScrollPane;
    private javax.swing.JPanel AttributePanel;
    private javax.swing.JScrollPane VAScrollPane;
    private javax.swing.JScrollPane RAScrollPane;
    private javax.swing.JPanel DetailPanel;
    private javax.swing.JScrollPane DetailScrollPane;
    private javax.swing.JTextArea DetailTextArea;
    // End of variables declaration//GEN-END:variables
    
    public DrawMapPanel DrawAreaPanel=new DrawMapPanel();
    private javax.swing.JTable VTable,RTable;
    private javax.swing.table.DefaultTableModel VdefaultTable,RdefaultTable;
    
    //public String test="Hello";
    //public javax.swing.JTextField Test;
    private int co=0;
}
