Attribute VB_Name = "mdlDTD"
Option Explicit

Public Const dtdPROpen = "\\Market\B2B\dtd\PROpen.dtd"
Public Const dtdBuyerTS = "\\Market\B2B\dtd\BuyerTransactionAccept.dtd"
Public Const dtdIVAccept = "\\Market\B2B\dtd\InvoiceAccept.dtd"
Public Const dtdIVReject = "\\Market\B2B\dtd\InvoiceReject.dtd"
Public Const dtdIVSent = "\\Market\B2B\dtd\InvoiceSent.dtd"
Public Const dtdIVBuyer = "\\Market\B2B\dtd\InvoiceToBuyer.dtd"
Public Const dtdMTS = "\\Market\B2B\dtd\MarketTransactionAccept.dtd"
Public Const dtdOrderNo = "\\Market\B2B\dtd\OrderNo.dtd"
Public Const dtdPOAccept = "\\Market\B2B\dtd\POAccept.dtd"
Public Const dtdPOReject = "\\Market\B2B\dtd\POReject.dtd"
Public Const dtdPOSeller = "\\Market\B2B\dtd\POSeller.dtd"
Public Const dtdPOSent = "\\Market\B2B\dtd\POSent.dtd"
Public Const dtdPRNo = "\\Market\B2B\dtd\PRNo.dtd"
Public Const dtdPRReject = "\\Market\B2B\dtd\PRReject.dtd"
Public Const dtdTSPaid = "\\Market\B2B\dtd\TransactionPaid.dtd"
Public Const dtdTSReject = "\\Market\B2B\dtd\TransactionReject.dtd"
Public Const dtdIVRecv = "\\Market\B2B\dtd\InvoiceReceive.dtd"
Public Const dtdBuyerTSSign = "\\Market\B2B\dtd\BuyerTransactionAcceptSign.dtd"
Public Const dtdPartnerPO = "\\Market\B2B\dtd\dtdPartnerPO.dtd"
