devide = 1
maxframe = 30 -- start at 0
for nCount = 1 to 16 do 
(
		if (nCount == 1 ) then whatbox = $box001
		if (nCount == 2 ) then whatbox = $box002
		if (nCount == 3 ) then whatbox = $box003
		if (nCount == 4 ) then whatbox = $box004
		if (nCount == 5 ) then whatbox = $box005
		if (nCount == 6 ) then whatbox = $box006
		if (nCount == 7 ) then whatbox = $box007
		if (nCount == 8 ) then whatbox = $box008
		if (nCount == 9 ) then whatbox = $box009
		if (nCount == 10) then whatbox = $box010
		if (nCount == 11) then whatbox = $box011
		if (nCount == 12) then whatbox = $box012
		if (nCount == 13) then whatbox = $box013
		if (nCount == 14) then whatbox = $box014
		if (nCount == 15) then whatbox = $box015
		if (nCount == 16) then whatbox = $box016
				
		myObj =	copy whatbox
		select myObj
		max unlink

		progressUpdate 0
		animate on for c in 0 to maxframe do at time c
		(
			if (getProgressCancel())==true then exit
			progressUpdate c
			if ( (c - ((c/devide)*devide) ) == 0 ) then
			(
				myObj.transform = whatbox.transform
			)
			if (c == maxframe) then
			(
				myObj.transform = whatbox.transform
			)
		)
		
		
)