fileint = createfile "c:\abc.int"


bMesh = $Box01.mesh




format "Maetee Supreanruey and Anusorn Krasantisuk format\n\n" to:fileint



format "%\n" bMesh.numverts to:fileint 
for i = 1 to bMesh.numverts do 
(
	verts1 = getvert bMesh i
	format "% % %\n"  verts1.x verts1.z verts1.y to:fileint 
)


format "%\n" bMesh.numfaces to:fileint 
for x = 1 to bMesh.numfaces do
(
	face = getface bMesh x
	p0 = face.x as integer
	p2 = face.y as integer
	p1 = face.z as integer
	
	format "% % %\n" (p0-1) (p1-1) (p2-1) to:fileint 
)

format "%\n" (bMesh.numtverts) to:fileint 
for abc = 1 to bMesh.numtverts do
(
	xxx = gettvert bMesh abc

	format "% %\n" xxx.x xxx.y to:fileint 
)


format "%\n" (bMesh.numfaces ) to:fileint 
for aaa = 1 to bMesh.numfaces do
(
	test = getTVface bMesh aaa

	p0 = test.x  as integer
	p2 = test.y  as integer
	p1 = test.z  as integer	

	format "% % %\n" (p0-1) (p1-1) (p2-1) to:fileint
)

close fileint 

