
	<TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="0">
		<TR>
			<TD ALIGN=LEFT VALIGN=TOP  >
				<br>	
				<IMG SRC ="<%= "/" & siteRoot %>/assets/images/house2.jpg" width=170 height=60 " ALT="house">
				<br><br><br>
				<A HREF="<%= pageURL("search.asp") %>">	<IMG SRC ="<%= "/" & siteRoot %>/assets/images/search1.jpg"  WIDTH="140" HEIGHT="60" BORDER="0"  ALIGN="TOP"ALT="Search"></A>
				<br><br>	<br>
				<A HREF="<%= pageURL("default.asp") %>"><img src="<%= "/" & siteRoot %>/assets/images/home1.jpg" WIDTH="140" HEIGHT="60" BORDER="0"  ALIGN="TOP"ALT="Home"></A>
				<br><br>	<br>
				<img src="<%= "/" & siteRoot %>/assets/images/home1.jpg" WIDTH="140" HEIGHT="60" BORDER="0"  ALIGN="TOP"ALT="Home">
				<br><br>	<br>
				<img src="<%= "/" & siteRoot %>/assets/images/home1.jpg"WIDTH="140" HEIGHT="60" BORDER="0"  ALIGN="TOP"ALT="Home">
				<br><br>
			</TD>