<%@ LANGUAGE=vbscript enablesessionstate=false LCID=1054 %>
<!--#INCLUDE FILE="i_shop.asp" --> 
<HTML>
<HEAD>
<TITLE><%= displayName %> : Profile</TITLE>
</HEAD>
<!--#INCLUDE FILE="main.htm" -->
<BODY BGCOLOR="#FFFFFF">
<BR>
			<TABLE WIDTH="80%" BORDER="0" ALIGN="center">
					<TR>	<TD ALIGN="center">บริษัท ธนิกา ดีเวลล็อปเม็นท์ จำกัด </TD></TR>
					<TR><TD ALIGN="center">9/151 หมู่ 6 ถนนนาวงประชาพัฒนา</TD></TR>
					<TR><TD ALIGN="center">แขวงสีกัน เขตดอนเมือง กรุงเทพฯ 10210 </TD></TR>
					<TR><TD ALIGN="center">โทร 565 - 5253 , 565 - 5254 , 565 - 5255 </TD></TR>
					<TR><TD ALIGN="center">Fax 565 - 5112 </TD></TR>
			</TABLE>
<BR><BR>
			<TABLE WIDTH="60%" BORDER="1" ALIGN="center" >
					<TR>	<TD Colspan="2" ALIGN="Left" BGCOLOR="#66CCCC">&nbsp รายละเอียดของโครงการ</TD></TR>
					<TR><TD width="10%" BGCOLOR="#66CCCC"> &nbsp </TD><TD ALIGN="Left" BGCOLOR="#CCFFFF"> &nbsp ทุกโครงการ ฯ ประกอบด้วย สปอร์ตคลับ สระว่ายน้ำ และ สวนพฤษชาติ </TD></TR>
					<TR><TD width="10%" BGCOLOR="#66CCCC"> &nbsp </TD><TD ALIGN="Left" BGCOLOR="#CCFFFF"> &nbsp จัดให้มียามรักษาความปลอดภัย ตลอด 24 ชม. ในบริเวณที่มีรั้วล้อมรอบโดยเฉพาะ</TD></TR>
					<TR><TD width="10%" BGCOLOR="#66CCCC"> &nbsp </TD><TD ALIGN="Left" BGCOLOR="#CCFFFF"> &nbsp ติดตั้งระบบบำบัดน้ำเสียในทุกหลังคาเรือน </TD></TR>
					<TR><TD width="10%" BGCOLOR="#66CCCC"> &nbsp </TD><TD ALIGN="Left" BGCOLOR="#CCFFFF"> &nbsp รวมมิตเตอร์น้ำ ไฟฟ้า( 15 แอมป์ ) พร้อมเครื่องตัดไฟ </TD></TR>
			</TABLE><BR>
</BODY>
</HTML>