#Edit CAGE Database connection here
DRIVER=QMYSQL3
DBNAME=cage
USER=cage
PASSWD=honeypot
HOST=logserver
PORT=3306
#Edit SNORT Database connection here
DRIVER=QMYSQL3
DBNAME=snort
USER=snort
PASSWD=honeypot
HOST=logserver
PORT=3306
#Edit SAMHAIN Database connection here
DRIVER=QMYSQL3
DBNAME=samhain
USER=samhain
PASSWD=honeypot
HOST=logserver
PORT=3306
#Edit SEBEK Database connection here
DRIVER=QMYSQL3
DBNAME=sebek
USER=sebek
PASSWD=honeypot
HOST=logserver
PORT=3306
