#!/bin/bash
#get protocol field from rule
#argument1 is file (redirect firewall rule)
#argument2 is rule number
rule=`expr $2 + 2`
#get protocol field from file
prot=`cat $1 | grep -n ' ' | grep -m 1 $rule: | cut -d':' -f2 |cut -b12- | cut -d' ' -f1`
#call get port number from rule
source getport $1 $2