<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:conv="http://www.openuri.org/2002/04/soap/conversation/" xmlns:cw="http://www.openuri.org/2002/04/wsdl/conversation/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:jms="http://www.openuri.org/2002/04/wsdl/jms/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:s0="http://www.openuri.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xm="http://www.bea.com/2002/04/xmlmap/" targetNamespace="http://www.openuri.org/" >
  <types>
    <s:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://www.openuri.org/">
      <s:element name="addtMemberData">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="passwd" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="name" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="lastname" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="sex" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="work_address" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="ID" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="year" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="home_num" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="lane" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="village" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="moo" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="road" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="district" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="amphur" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="province" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="zip_code" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="phone1" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="phone2" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="e_mail" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="category" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="e_mail_way" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="application_way" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="addtMemberDataResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="addtMemberDataResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="boolean" type="s:boolean" />
      <s:element name="change_password">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="old_password" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="new_password" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="change_passwordResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="change_passwordResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
    </s:schema>
  </types>
  <message name="addtMemberDataSoapIn">
    <part name="parameters" element="s0:addtMemberData" />
  </message>
  <message name="addtMemberDataSoapOut">
    <part name="parameters" element="s0:addtMemberDataResponse" />
  </message>
  <message name="change_passwordSoapIn">
    <part name="parameters" element="s0:change_password" />
  </message>
  <message name="change_passwordSoapOut">
    <part name="parameters" element="s0:change_passwordResponse" />
  </message>
  <message name="addtMemberDataHttpGetIn">
    <part name="username" type="s:string" />
    <part name="passwd" type="s:string" />
    <part name="name" type="s:string" />
    <part name="lastname" type="s:string" />
    <part name="sex" type="s:string" />
    <part name="status" type="s:string" />
    <part name="work_address" type="s:string" />
    <part name="ID" type="s:string" />
    <part name="year" type="s:string" />
    <part name="home_num" type="s:string" />
    <part name="lane" type="s:string" />
    <part name="village" type="s:string" />
    <part name="moo" type="s:string" />
    <part name="road" type="s:string" />
    <part name="district" type="s:string" />
    <part name="amphur" type="s:string" />
    <part name="province" type="s:string" />
    <part name="zip_code" type="s:string" />
    <part name="phone1" type="s:string" />
    <part name="phone2" type="s:string" />
    <part name="e_mail" type="s:string" />
    <part name="category" type="s:string" />
    <part name="e_mail_way" type="s:string" />
    <part name="application_way" type="s:string" />
  </message>
  <message name="addtMemberDataHttpGetOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="change_passwordHttpGetIn">
    <part name="username" type="s:string" />
    <part name="old_password" type="s:string" />
    <part name="new_password" type="s:string" />
  </message>
  <message name="change_passwordHttpGetOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="addtMemberDataHttpPostIn">
    <part name="username" type="s:string" />
    <part name="passwd" type="s:string" />
    <part name="name" type="s:string" />
    <part name="lastname" type="s:string" />
    <part name="sex" type="s:string" />
    <part name="status" type="s:string" />
    <part name="work_address" type="s:string" />
    <part name="ID" type="s:string" />
    <part name="year" type="s:string" />
    <part name="home_num" type="s:string" />
    <part name="lane" type="s:string" />
    <part name="village" type="s:string" />
    <part name="moo" type="s:string" />
    <part name="road" type="s:string" />
    <part name="district" type="s:string" />
    <part name="amphur" type="s:string" />
    <part name="province" type="s:string" />
    <part name="zip_code" type="s:string" />
    <part name="phone1" type="s:string" />
    <part name="phone2" type="s:string" />
    <part name="e_mail" type="s:string" />
    <part name="category" type="s:string" />
    <part name="e_mail_way" type="s:string" />
    <part name="application_way" type="s:string" />
  </message>
  <message name="addtMemberDataHttpPostOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="change_passwordHttpPostIn">
    <part name="username" type="s:string" />
    <part name="old_password" type="s:string" />
    <part name="new_password" type="s:string" />
  </message>
  <message name="change_passwordHttpPostOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <portType name="registrySoap">
    <operation name="addtMemberData">
      <input message="s0:addtMemberDataSoapIn" />
      <output message="s0:addtMemberDataSoapOut" />
    </operation>
    <operation name="change_password">
      <input message="s0:change_passwordSoapIn" />
      <output message="s0:change_passwordSoapOut" />
    </operation>
  </portType>
  <portType name="registryHttpGet">
    <operation name="addtMemberData">
      <input message="s0:addtMemberDataHttpGetIn" />
      <output message="s0:addtMemberDataHttpGetOut" />
    </operation>
    <operation name="change_password">
      <input message="s0:change_passwordHttpGetIn" />
      <output message="s0:change_passwordHttpGetOut" />
    </operation>
  </portType>
  <portType name="registryHttpPost">
    <operation name="addtMemberData">
      <input message="s0:addtMemberDataHttpPostIn" />
      <output message="s0:addtMemberDataHttpPostOut" />
    </operation>
    <operation name="change_password">
      <input message="s0:change_passwordHttpPostIn" />
      <output message="s0:change_passwordHttpPostOut" />
    </operation>
  </portType>
  <binding name="registrySoap" type="s0:registrySoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
    <operation name="addtMemberData">
      <soap:operation soapAction="http://www.openuri.org/addtMemberData" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="change_password">
      <soap:operation soapAction="http://www.openuri.org/change_password" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <binding name="registryHttpGet" type="s0:registryHttpGet">
    <http:binding verb="GET" />
    <operation name="addtMemberData">
      <http:operation location="/addtMemberData" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="change_password">
      <http:operation location="/change_password" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
  </binding>
  <binding name="registryHttpPost" type="s0:registryHttpPost">
    <http:binding verb="POST" />
    <operation name="addtMemberData">
      <http:operation location="/addtMemberData" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="change_password">
      <http:operation location="/change_password" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
  </binding>
  <service name="registry">
    <port name="registrySoap" binding="s0:registrySoap">
      <soap:address location="http://aston:7001/Library/registry/registry.jws" />
    </port>
    <port name="registryHttpGet" binding="s0:registryHttpGet">
      <http:address location="http://aston:7001/Library/registry/registry.jws" />
    </port>
    <port name="registryHttpPost" binding="s0:registryHttpPost">
      <http:address location="http://aston:7001/Library/registry/registry.jws" />
    </port>
  </service>
</definitions>
