#
#Sun Apr 22 23:41:07 GMT+07:00 2001
distributors.extract1.end="
distributors.overall.start=</head>
distributors.url.old=http\://161.246.4.3/~s0010892/pager.cgi
distributors.attribute.yes=<basefont,<font,<q,<blockquote,<br,<div,<hr,<h1,<h2,<h3,<h4,<h5,<h6,<p,<span,<li,<dir,<dl,<menu,<ol,<ul,<a,<img,<map,<area,<table,<caption,<thead,<tfoot,<tbody,<colgroup,<col,<tr,<td,<th,<form,<input,<select,<option,<textarea,<button,<label,<legend,<frameset,<frame,<iframe,<applet,<param,<object,<script,
distributors.pi0.data=href\="file\:///C\:/4044ProfessionalWAP/chapter12/Cocoon/samples/wap/contact-html.xsl" type\="text/xsl"
distributors=
distributors.pi2.data=href\="file\:///C\:/4044ProfessionalWAP/chapter12/Cocoon/samples/wap/contact-phonecom.xsl" type\="text/xsl" media\="phonecom"
distributors.pi0.target=xml-stylesheet
distributors.extract4.end="
http=//www.yahoo.com/index.html
distributors.pi1.target=xml-stylesheet
distributors.extract0.name=image
distributors.extract2.name=text
distributors.extract0.end="
distributors.pi2.target=xml-stylesheet
distributors.extract4.name=email
distributors.extract.count=4
file=///d\:/nhomcake/html/hotmail.html
distributors.pi3.target=cocoon-process
distributors.extract3.end="
distributors.single.tags=<basefont,<br,<hr,<img,<area,<col,<input,<frame,<param,
distributors.pi.count=4
distributors.extract3.start=<input type\="
distributors.extract0.start=<img src\="
distributors.extract2.start=>
distributors.extract4.start=Email\: <a HREF\="mailto\:
distributors.extract1.start=<a href\="
distributors.pi1.data=href\="file\:///C\:/success/jakarta-tomcat/webapps/cocoon/samples/wap/convert2wml.xsl" type\="text/xsl" media\="wap"
distributors.result=no
distributors.pi3.data=type\="xslt"
distributors.url=http\://161.246.5.113\:8080/test/table.html
distributors.attribute.no=<b,<big,<i,<s,<strike,<small,<sub,<sup,<tt,<u,<acronym,<address,<cite,<code,<del,<dfn,<em,<ins,<kbd,<samp,<strong,<var,<center,<pre,<dt,<dd,<fieldset,<noframes,<radio,<checkbox,<marquee,
distributors.extract2.end=<
distributors.extract1.name=link
distributors.overall.end=</body>
distributors.extract3.name=inputtext
distributors.double.tags=<b,<big,<font,<i,<s,<strike,<small,<sub,<sup,<tt,<u,<acronym,<address,<cite,<code,<del,<dfn,<em,<ins,<kbd,<q,<samp,<strong,<var,<blockquote,<center,<div,<h1,<h2,<h3,<h4,<h5,<h6,<p,<pre,<span,<li,<dir,<dl,<dt,<dd,<menu,<ol,<ul,<a,<map,<table,<caption,<thead,<tfoot,<tbody,<colgroup,<tr,<td,<th,<form,<select,<option,<textarea,<button,<label,<fieldset,<legend,<frameset,<noframes,<iframe,<applet,<object,<radio,<checkbox,<script,<marquee,
distributors.interested.tags=<img,<a,>,<input,
distributors.max.items=100
