form0.action=http://www.xxx.com/cgi-bin/girl.pl
form0.method=get
form0.variable0=name
form0.value0=
form0.variable1=password
form0.value1=
form0.variable2=sex
form0.value2=
form0.variable3=hobby
form0.value3=
form0.variable4=birth
form0.value4=
form0.variable.count=5
