html.basefont.attribute0=color=
html.basefont.attribute1=face=
html.basefont.attribute2=size=
html.basefont.attributecount=3
html.basefont.attrcount=-1

html.font.attribute0=color=
html.font.attribute1=face=
html.font.attribute2=size=
html.font.attributecount=3
html.font.attrcount=-1

html.q.attribute0=cite=
html.q.attributecount=1
html.q.attrcount=-1

html.blockquote.attribute0=cite=
html.blockquote.attributecount=1
html.blockquote.attrcount=-1

html.br.attribute0=clear=
html.br.attributecount=1
html.br.attrcount=-1

html.div.attribute0=align=
html.div.attributecount=1
html.div.attrcount=-1


html.hr.attribute0=align=
html.hr.attribute1=width=
html.hr.attribute2=size=
html.hr.attributecount=3
html.hr.attr0= noshade
html.hr.attrcount=1


html.h1.attribute0=align=
html.h1.attributecount=1
html.h1.attrcount=-1

html.h2.attribute0=align=
html.h2.attributecount=1
html.h2.attrcount=-1

html.h3.attribute0=align=
html.h3.attributecount=1
html.h3.attrcount=-1

html.h4.attribute0=align=
html.h4.attributecount=1
html.h4.attrcount=-1

html.h5.attribute0=align=
html.h5.attributecount=1
html.h5.attrcount=-1

html.h6.attribute0=align=
html.h6.attributecount=1
html.h6.attrcount=-1

html.p.attribute0=align=
html.p.attributecount=1
html.p.attrcount=-1

html.span.attribute0=style=
html.span.attributecount=1
html.span.attrcount=-1

html.li.attribute0=start=
html.li.attribute1=type=
html.li.attributecount=2
html.li.attrcount=-1

html.dir.attributecount=-1
html.dir.attr0= compact
html.dir.attrcount=1

html.dl.attributecount=-1
html.dl.attr0= compact
html.dl.attrcount=1

html.menu.attributecount=-1
html.menu.attr0= compact
html.menu.attrcount=1

html.ol.attribute0=type=
html.ol.attribute1=start=
html.ol.attributecount=2
html.ol.attr0= compact
html.ol.attrcount=1

html.ul.attribute0=type=
html.ul.attributecount=1
html.ul.attr0= compact
html.ul.attrcount=1

html.a.attribute0=accesskey=
html.a.attribute1=href=
html.a.attribute2=name=
html.a.attribute3=rel=
html.a.attribute4=rev=
html.a.attribute5=tabindex=
html.a.attribute6=taget=
html.a.attributecount=7
html.a.attrcount=-1

html.img.attribute0=src=
html.img.attribute1=width=
html.img.attribute2=height=
html.img.attribute3=alt=
html.img.attribute4=border=
html.img.attribute5=align=
html.img.attribute6=hspace=
html.img.attribute7=vspace=
html.img.attribute8=ismap=
html.img.attribute9=usemap=
html.img.attributecount=10
html.img.attrcount=-1

html.map.attribute0=name=
html.map.attributecount=1
html.map.attrcount=-1

html.area.attribute0=alt=
html.area.attribute1=coords=
html.area.attribute2=href=
html.area.attribute3=shape=
html.area.attribute4=tabindex=
html.area.attribute5=target=
html.area.attributecount=6
html.area.attr0= nohref
html.area.attrcount=1


html.table.attribute0=align=
html.table.attribute1=border=
html.table.attribute2=bgcolor=
html.table.attribute3=cellpadding=
html.table.attribute4=cellspacing=
html.table.attribute5=cols=
html.table.attribute6=frame=
html.table.attribute7=rules=
html.table.attribute8=width=
html.table.attributecount=9
html.table.attrcount=-1

html.caption.attribute0=align=
html.caption.attributecount=1
html.caption.attrcount=-1

html.thead.attribute0=align=
html.thead.attribute1=valign=
html.thead.attributecount=2
html.thead.attrcount=-1

html.tfoot.attribute0=align=
html.tfoot.attribute1=valign=
html.tfoot.attributecount=2
html.tfoot.attrcount=-1

html.tbody.attribute0=align=
html.tbody.attribute1=valign=
html.tbody.attributecount=2
html.tbody.attrcount=-1

html.colgroup.attribute0=align=
html.colgroup.attribute1=valign=
html.colgroup.attribute2=span=
html.colgroup.attribute3=width=
html.colgroup.attributecount=4
html.colgroup.attrcount=-1

html.col.attribute0=align=
html.col.attribute1=valign=
html.col.attribute2=span=
html.col.attribute3=width=
html.col.attributecount=4
html.col.attrcount=-1

html.tr.attribute0=align=
html.tr.attribute1=valign=
html.tr.attribute2=bgcolor=
html.tr.attributecount=3
html.tr.attrcount=-1

html.td.attribute0=align=
html.td.attribute1=valign=
html.td.attribute2=bgcolor=
html.td.attribute3=colspan=
html.td.attribute4=rowspan=
html.td.attributecount=5
html.td.attr0= nowrap
html.td.attrcount=1


html.th.attribute0=align=
html.th.attribute1=valign=
html.th.attribute2=bgcolor=
html.th.attribute3=colspan=
html.th.attribute4=rowspan=
html.th.attributecount=5
html.th.attr0= nowrap
html.th.attrcount=1


html.form.attribute0=accept-charset=
html.form.attribute1=action=
html.form.attribute2=enctype=
html.form.attribute3=method=
html.form.attribute4=target=
html.form.attributecount=5
html.form.attrcount=-1


html.input.attribute0=name=
html.input.attribute1=value=
html.input.attribute2=type=
html.input.attribute3=onclick=
html.input.attribute4=accept=
html.input.attribute5=usemap=
html.input.attribute6=src=
html.input.attribute7=alt=
html.input.attribute8=length=
html.input.attribute9=maxlength=
html.input.attributecount=10
html.input.attr0= readonly
html.input.attr1= disabled
html.input.attr2= checked
html.input.attrcount=3


html.select.attribute0=name=
html.select.attribute1=size=
html.select.attributecount=2
html.select.attr0= disabled
html.select.attr1= multiple
html.select.attrcount=2


html.option.attribute0=value=
html.option.attributecount=1
html.option.attr0= selected
html.option.attr1= disabled
html.option.attrcount=2


html.textarea.attribute0=name=
html.textarea.attribute1=rows=
html.textarea.attribute2=cols=
html.textarea.attributecount=3
html.textarea.attr0= readonly
html.textarea.attr1= disabled
html.textarea.attrcount=2


html.button.attribute0=name=
html.button.attribute1=type=
html.button.attribute2=value=
html.button.attributecount=3
html.button.attr0= disabled
html.button.attrcount=1


html.label.attribute0=for=
html.label.attribute1=accesskey=
html.label.attributecount=2
html.label.attr0= disabled
html.label.attrcount=1


html.legend.attribute0=accesskey=
html.legend.attribute1=align=
html.legend.attributecount=2
html.legend.attrcount=-1


html.frameset.attribute0=rows=
html.frameset.attribute1=cols=
html.frameset.attributecount=2
html.frameset.attrcount=-1


html.frame.attribute0=frameborder=
html.frame.attribute1=marginheight=
html.frame.attribute2=marginwidth=
html.frame.attribute3=name=
html.frame.attribute4=scrolling=
html.frame.attribute5=src=
html.frame.attributecount=6
html.frame.attr0= noresize
html.frame.attrcount=1


html.iframe.attribute0=frameborder=
html.iframe.attribute1=src=
html.iframe.attribute2=name=
html.iframe.attribute3=align=
html.iframe.attribute4=scrolling=
html.iframe.attribute5=marginheight=
html.iframe.attribute6=marginwidth=
html.iframe.attribute7=height=
html.iframe.attribute8=width=
html.iframe.attributecount=9
html.iframe.attrcount=-1

html.applet.attribute0=align=
html.applet.attribute1=alt=
html.applet.attribute2=archive=
html.applet.attribute3=code=
html.applet.attribute4=codebase=
html.applet.attribute5=height=
html.applet.attribute6=hspace=
html.applet.attribute7=name=
html.applet.attribute8=object=
html.applet.attribute9=vspace=
html.applet.attribute10=width=
html.applet.attributecount=11
html.applet.attrcount=-1

html.param.attribute0=name=
html.param.attribute1=type=
html.param.attribute2=value=
html.param.attribute3=valuetype=
html.param.attributecount=4
html.param.attrcount=-1

html.object.attribute0=align=
html.object.attribute1=width=
html.object.attribute2=height=
html.object.attribute3=border=
html.object.attribute4=hspace=
html.object.attribute5=vspace=
html.object.attribute6=classid=
html.object.attribute7=codebase=
html.object.attribute8=codetype=
html.object.attribute9=standby=
html.object.attribute10=type=
html.object.attribute11=usemap=
html.object.attributecount=12
html.object.attrcount=-1

html.script.attribute0=language=
html.script.attributecount=1
html.script.attrcount=-1