<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://giswebservices" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://giswebservices" xmlns:intf="http://giswebservices" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.2.1
Built on Aug 08, 2005 (11:49:10 PDT)-->

   <wsdl:message name="requestNearestSVGRequest">

      <wsdl:part name="sessionKey" type="xsd:string"/>

      <wsdl:part name="xmlMapRequst" type="xsd:string"/>

      <wsdl:part name="layerID" type="xsd:int"/>

      <wsdl:part name="posX" type="xsd:double"/>

      <wsdl:part name="posY" type="xsd:double"/>

      <wsdl:part name="width" type="xsd:double"/>

      <wsdl:part name="height" type="xsd:double"/>

      <wsdl:part name="currentLadtitude" type="xsd:double"/>

      <wsdl:part name="currentLongitude" type="xsd:double"/>

      <wsdl:part name="xFill" type="xsd:string"/>

      <wsdl:part name="xStroke" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="getSvgGRequest">

      <wsdl:part name="sessionKey" type="xsd:string"/>

      <wsdl:part name="xmlMapRequst" type="xsd:string"/>

      <wsdl:part name="posX" type="xsd:double"/>

      <wsdl:part name="posY" type="xsd:double"/>

      <wsdl:part name="width" type="xsd:double"/>

      <wsdl:part name="height" type="xsd:double"/>

   </wsdl:message>

   <wsdl:message name="requestSVGRequest">

      <wsdl:part name="sessionKey" type="xsd:string"/>

      <wsdl:part name="xmlMapRequst" type="xsd:string"/>

      <wsdl:part name="posX" type="xsd:double"/>

      <wsdl:part name="posY" type="xsd:double"/>

      <wsdl:part name="width" type="xsd:double"/>

      <wsdl:part name="height" type="xsd:double"/>

   </wsdl:message>

   <wsdl:message name="getSvgGResponse">

      <wsdl:part name="getSvgGReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="requestNearbySVGRequest">

      <wsdl:part name="sessionKey" type="xsd:string"/>

      <wsdl:part name="xmlMapRequst" type="xsd:string"/>

      <wsdl:part name="layerID" type="xsd:int"/>

      <wsdl:part name="posX" type="xsd:double"/>

      <wsdl:part name="posY" type="xsd:double"/>

      <wsdl:part name="width" type="xsd:double"/>

      <wsdl:part name="height" type="xsd:double"/>

      <wsdl:part name="currentLadtitude" type="xsd:double"/>

      <wsdl:part name="currentLongitude" type="xsd:double"/>

      <wsdl:part name="radian" type="xsd:double"/>

      <wsdl:part name="xFill" type="xsd:string"/>

      <wsdl:part name="xStroke" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="requestNearbySVGResponse">

      <wsdl:part name="requestNearbySVGReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="requestNearestSVGResponse">

      <wsdl:part name="requestNearestSVGReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="requestSVGResponse">

      <wsdl:part name="requestSVGReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:portType name="Gis_GetMapServices">

      <wsdl:operation name="requestSVG" parameterOrder="sessionKey xmlMapRequst posX posY width height">

         <wsdl:input message="impl:requestSVGRequest" name="requestSVGRequest"/>

         <wsdl:output message="impl:requestSVGResponse" name="requestSVGResponse"/>

      </wsdl:operation>

      <wsdl:operation name="requestNearbySVG" parameterOrder="sessionKey xmlMapRequst layerID posX posY width height currentLadtitude currentLongitude radian xFill xStroke">

         <wsdl:input message="impl:requestNearbySVGRequest" name="requestNearbySVGRequest"/>

         <wsdl:output message="impl:requestNearbySVGResponse" name="requestNearbySVGResponse"/>

      </wsdl:operation>

      <wsdl:operation name="requestNearestSVG" parameterOrder="sessionKey xmlMapRequst layerID posX posY width height currentLadtitude currentLongitude xFill xStroke">

         <wsdl:input message="impl:requestNearestSVGRequest" name="requestNearestSVGRequest"/>

         <wsdl:output message="impl:requestNearestSVGResponse" name="requestNearestSVGResponse"/>

      </wsdl:operation>

      <wsdl:operation name="getSvgG" parameterOrder="sessionKey xmlMapRequst posX posY width height">

         <wsdl:input message="impl:getSvgGRequest" name="getSvgGRequest"/>

         <wsdl:output message="impl:getSvgGResponse" name="getSvgGResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="Gis_GetMapServicesSoapBinding" type="impl:Gis_GetMapServices">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="requestSVG">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="requestSVGRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="requestSVGResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="requestNearbySVG">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="requestNearbySVGRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="requestNearbySVGResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="requestNearestSVG">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="requestNearestSVGRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="requestNearestSVGResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="getSvgG">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getSvgGRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="getSvgGResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="Gis_GetMapServicesService">

      <wsdl:port binding="impl:Gis_GetMapServicesSoapBinding" name="Gis_GetMapServices">

         <wsdlsoap:address location="http://localhost:8080/GisServer/services/Gis_GetMapServices"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
