<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://giswebservices" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://giswebservices" xmlns:intf="http://giswebservices" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.2.1
Built on Aug 08, 2005 (11:49:10 PDT)-->

   <wsdl:message name="listMyLayerResponse">

      <wsdl:part name="listMyLayerReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="deleteLayerResponse">

      <wsdl:part name="deleteLayerReturn" type="xsd:int"/>

   </wsdl:message>

   <wsdl:message name="listMyLayerRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="insertLayerRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

      <wsdl:part name="name" type="xsd:string"/>

      <wsdl:part name="isPublic" type="xsd:boolean"/>

      <wsdl:part name="geomType" type="xsd:string"/>

      <wsdl:part name="xmlTable" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="updateLayerResponse">

      <wsdl:part name="updateLayerReturn" type="xsd:int"/>

   </wsdl:message>

   <wsdl:message name="listLayerResponse">

      <wsdl:part name="listLayerReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="publicLayerResponse">

      <wsdl:part name="publicLayerReturn" type="xsd:int"/>

   </wsdl:message>

   <wsdl:message name="searchLayerRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

      <wsdl:part name="likeName" type="xsd:string"/>

      <wsdl:part name="likeOwner" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="insertLayerResponse">

      <wsdl:part name="insertLayerReturn" type="xsd:int"/>

   </wsdl:message>

   <wsdl:message name="searchLayerResponse">

      <wsdl:part name="searchLayerReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="updateLayerRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

      <wsdl:part name="layerID" type="xsd:int"/>

      <wsdl:part name="layerName" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="publicLayerRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

      <wsdl:part name="layerID" type="xsd:int"/>

      <wsdl:part name="isPublic" type="xsd:boolean"/>

   </wsdl:message>

   <wsdl:message name="listLayerRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="deleteLayerRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

      <wsdl:part name="layerID" type="xsd:int"/>

   </wsdl:message>

   <wsdl:portType name="GIS_LayerServices">

      <wsdl:operation name="insertLayer" parameterOrder="sessionkey name isPublic geomType xmlTable">

         <wsdl:input message="impl:insertLayerRequest" name="insertLayerRequest"/>

         <wsdl:output message="impl:insertLayerResponse" name="insertLayerResponse"/>

      </wsdl:operation>

      <wsdl:operation name="listLayer" parameterOrder="sessionkey">

         <wsdl:input message="impl:listLayerRequest" name="listLayerRequest"/>

         <wsdl:output message="impl:listLayerResponse" name="listLayerResponse"/>

      </wsdl:operation>

      <wsdl:operation name="searchLayer" parameterOrder="sessionkey likeName likeOwner">

         <wsdl:input message="impl:searchLayerRequest" name="searchLayerRequest"/>

         <wsdl:output message="impl:searchLayerResponse" name="searchLayerResponse"/>

      </wsdl:operation>

      <wsdl:operation name="deleteLayer" parameterOrder="sessionkey layerID">

         <wsdl:input message="impl:deleteLayerRequest" name="deleteLayerRequest"/>

         <wsdl:output message="impl:deleteLayerResponse" name="deleteLayerResponse"/>

      </wsdl:operation>

      <wsdl:operation name="updateLayer" parameterOrder="sessionkey layerID layerName">

         <wsdl:input message="impl:updateLayerRequest" name="updateLayerRequest"/>

         <wsdl:output message="impl:updateLayerResponse" name="updateLayerResponse"/>

      </wsdl:operation>

      <wsdl:operation name="publicLayer" parameterOrder="sessionkey layerID isPublic">

         <wsdl:input message="impl:publicLayerRequest" name="publicLayerRequest"/>

         <wsdl:output message="impl:publicLayerResponse" name="publicLayerResponse"/>

      </wsdl:operation>

      <wsdl:operation name="listMyLayer" parameterOrder="sessionkey">

         <wsdl:input message="impl:listMyLayerRequest" name="listMyLayerRequest"/>

         <wsdl:output message="impl:listMyLayerResponse" name="listMyLayerResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="GIS_LayerServicesSoapBinding" type="impl:GIS_LayerServices">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="insertLayer">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="insertLayerRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="insertLayerResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="listLayer">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="listLayerRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="listLayerResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="searchLayer">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="searchLayerRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="searchLayerResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="deleteLayer">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="deleteLayerRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="deleteLayerResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="updateLayer">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="updateLayerRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="updateLayerResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="publicLayer">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="publicLayerRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="publicLayerResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="listMyLayer">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="listMyLayerRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="listMyLayerResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://giswebservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="GIS_LayerServicesService">

      <wsdl:port binding="impl:GIS_LayerServicesSoapBinding" name="GIS_LayerServices">

         <wsdlsoap:address location="http://localhost:8080/GisServer/services/GIS_LayerServices"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
