<%@ Page Language="vb" AutoEventWireup="false" Codebehind="chiangmai.aspx.vb" Inherits="WebApplicationCenter.chiangmai"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>chiangmai</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" bgColor="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma"></FONT>
			<DIV style="Z-INDEX: 101; LEFT: 47px; WIDTH: 678px; POSITION: absolute; TOP: 207px; HEIGHT: 52px" ms_positioning="FlowLayout"><STRONG><FONT face="MS Sans Serif" size="1">ผลไม้นายอิ่ม</FONT></STRONG><FONT face="MS Sans Serif" size="1">
					<BR>
					จากการที่เราดำเนินการแปรรูปผักและผลไม้มาเป็นระยะเวลากว่า 10 ปี 
					เรามีความมั่นใจที่จะส่งมอบผลิตภัณฑ์ อบแห้ง แช่อิ่ม ดอง และอื่น ๆ ที่มีคุณภาพ 
					โดยใช้วัตถุดิบในประเทศมายังท่าน<BR>
					<B>จังหวัด</B> เชียงใหม่ &nbsp; <B>ประเทศ</B> ไทย</FONT></DIV>
			<TABLE id="Table1" style="Z-INDEX: 105; LEFT: 42px; POSITION: absolute; TOP: 70px" cellSpacing="2" cellPadding="0" border="0">
				<TR>
					<TD style="WIDTH: 38px"><IMG height="45" src="picture/N.jpg" width="45" border="0"></TD>
					<TD><FONT face="MS Sans Serif, CordiaUPC" color="#000099" size="+1"><U><B>เชียงใหม่</B></U>
							<FONT style="FONT-SIZE: 8pt" face="Verdana" size="1">(Chiang Mai)</FONT></FONT></TD>
				</TR>
			</TABLE>
			<DIV style="Z-INDEX: 102; LEFT: 50px; WIDTH: 670px; POSITION: absolute; TOP: 371px; HEIGHT: 50px" ms_positioning="FlowLayout">
				<P>
					<FONT size="1"><FONT face="MS Sans Serif"><STRONG>ร้านคุณแดง</STRONG>
							<BR>
							จำหน่ายผลิตภัณฑ์ กระดาษสา งานหัตถกรรมอื่น ๆ สินค้าร่วมสมัย ของที่ระลึก เทียนเจล 
							บริการ ส่ง ของขวัญ ทางไปรษณีย์ให้กับคนที่พิเศษของคุณ เนื่องในโอกาสต่าง ๆ </FONT>
					</FONT><FONT size="1">
						<BR>
						<FONT face="MS Sans Serif"><B>จังหวัด</B> เชียงใหม่ &nbsp; <B>ประเทศ</B> ไทย</FONT></FONT></P>
			</DIV>
			<DIV style="Z-INDEX: 103; LEFT: 47px; WIDTH: 678px; POSITION: absolute; TOP: 284px; HEIGHT: 65px" ms_positioning="FlowLayout"><FONT face="MS Sans Serif" size="1">&nbsp;<FONT size="1"><FONT face="MS Sans Serif"><STRONG>ร้านคุณเขียว</STRONG></FONT></FONT></FONT><FONT size="1"><FONT face="MS Sans Serif"><BR>
						ผลิตภัณฑ์ทำจากไม้ไผ่ สืบสานภูมิปัญญาท้องถิ่น จากเชียงใหม่&nbsp; 
						ผู้ผลิตสินค้าหัตถกรรม ทำจาก ไม้ไผ่ เช่น โคมไฟไม้ไผ่ ตะกร้าไม่ไผ่ กล่องไม้ไผ่ 
						กะบุงไม้ไผ่ ภาชนะไม่ไผ่ บรรจุภัณฑ์ที่ทำจากไม้ไผ่ </FONT>
					<BR>
					<FONT face="MS Sans Serif"><B>จังหวัด</B> เชียงใหม่ &nbsp; <B>ประเทศ</B> ไทย</FONT></FONT></DIV>
			<DIV style="Z-INDEX: 104; LEFT: 43px; WIDTH: 682px; POSITION: absolute; TOP: 148px; HEIGHT: 39px" ms_positioning="FlowLayout"><FONT size="1"><FONT face="MS Sans Serif"><STRONG><a href="..\WebApplicationSeller1\index.htm" target="_blank">บ้านไม้มะม่วง</a><BR>
						</STRONG>บ้านไม้มะม่วงของเราผลิตงานไม้มะม่วงขนาดเล็กถึงปานกลาง 
						โดยขายส่งในราคาที่ถูก<BR>
						<B>จังหวัด</B> เชียงใหม่ &nbsp; <B>ประเทศ</B> ไทย</FONT></FONT></DIV>
		</form>
	</body>
</HTML>
