<%@ Page Language="vb" AutoEventWireup="false" Codebehind="khonkaen.aspx.vb" Inherits="WebApplicationCenter.khonkaen"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>khonkaen</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" bgColor="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma"></FONT>
			<DIV style="Z-INDEX: 102; LEFT: 59px; WIDTH: 652px; POSITION: absolute; TOP: 293px; HEIGHT: 39px" ms_positioning="FlowLayout">
				<P><FONT size="1"><FONT face="MS Sans Serif"><STRONG>มือไทย<BR>
							</STRONG>ร้าน มือไทย ทำ เสื้อ ,ปลอกหมอน, ผ้าปูโตะ, กระเป๋า โดยเน้น การ 
							ปักลวดลาย บนสินค้า ที่ช่วยเสริมสร้าง รายได้ให้กับ ชาวบ้านที่ว่างงาน และมีฝีมือ</FONT><BR>
					</FONT><FONT size="1"><FONT face="MS Sans Serif"><B>จังหวัด</B>&nbsp;ขอนแก่น&nbsp;&nbsp;&nbsp;
							<B>ประเทศ</B> ไทย</FONT></FONT></P>
			</DIV>
			<DIV style="Z-INDEX: 103; LEFT: 60px; WIDTH: 655px; POSITION: absolute; TOP: 143px; HEIGHT: 52px" ms_positioning="FlowLayout"><FONT size="1"><FONT face="MS Sans Serif"><STRONG><A href="..\WebApplicationSeller2\index.htm" target="_blank">เรือนเทียนหอม</A><BR>
						</STRONG>เราเป็นผู้ผลิตเทียนหอมประเภทต่างๆ เช่น เทียนลอยน้ำ, เทียนดอกไม้ก้าน, 
						เทียนแท่ง, เทียนในภาชนะแบบต่างๆ, เทียนแฟนซี และชุดเทียนของขวัญ เป็นต้น 
						และเราสามารถรับทำตามแบบต่างๆ ตามความต้องการของลูกค้า ปัจจ</FONT><FONT face="verdana">...</FONT><BR>
					<FONT face="MS Sans Serif"><B>จังหวัด</B>&nbsp;ขอนแก่น&nbsp;&nbsp; <B>ประเทศ</B> ไทย</FONT></FONT></DIV>
			<DIV style="Z-INDEX: 104; LEFT: 59px; WIDTH: 653px; POSITION: absolute; TOP: 218px; HEIGHT: 52px" ms_positioning="FlowLayout"><FONT size="1"><FONT face="MS Sans Serif"><STRONG>มดงาน<BR>
						</STRONG>ร้าน " มดงาน " เป็นร้านที่จำหน่ายงานหัตถกรรมพื้นเมือง ของชาวเหนือ เช่น 
						ผลิตภัณฑ์กระดาษสา นกรังไหม ผ้าแขวนผนังลายปักชาวเขา 
						ผ้าไหมแพรวาของจังหวัดกาฬสินธุ์ และงานถักโคเช<BR>
						<B>จังหวัด</B> ขอนแก่น&nbsp;&nbsp; <B>ประเทศ</B> ไทย</FONT></FONT></DIV>
			<TABLE id="Table1" style="Z-INDEX: 105; LEFT: 59px; POSITION: absolute; TOP: 71px" cellSpacing="2" cellPadding="0" border="0">
				<TR>
					<TD style="WIDTH: 38px"><IMG height="45" src="picture/Ne.jpg" width="45" border="0"></TD>
					<TD><FONT face="MS Sans Serif, CordiaUPC" color="#000099" size="+1"><STRONG><U>ขอนแก่น</U></STRONG>&nbsp;<FONT style="FONT-SIZE: 8pt" face="Verdana" size="1">(Khon 
								Kaen)</FONT></FONT></TD>
				</TR>
			</TABLE>
			<DIV style="Z-INDEX: 106; LEFT: 60px; WIDTH: 653px; POSITION: absolute; TOP: 370px; HEIGHT: 52px" ms_positioning="FlowLayout"><FONT size="1"><FONT face="MS Sans Serif"><STRONG>เบญจาหัตถกรรม<BR>
						</STRONG>จำหน่ายกระเป๋าจักสาร ทั้งปลีกและส่ง มีให้เลือกหลายแบบ 
						เหมาะสำหรับมอบเป็นของขวัญให้คนสำคัญในโอกาสต่าง ๆ<BR>
						<B>จังหวัด</B> ขอนแก่น&nbsp; <B>ประเทศ</B> ไทย</FONT></FONT></DIV>
		</form>
		</A>
	</body>
</HTML>
