<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormShowEast.aspx.vb" Inherits="WebApplicationCenter.WebFormShowEase"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormShowEase</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" BGCOLOR="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma">
				<TABLE id="Table1" style="Z-INDEX: 101; LEFT: 165px; POSITION: absolute; TOP: 133px" cellSpacing="0" cellPadding="0" width="750" border="0">
					<TR vAlign="top">
						<TD width="10"></TD>
						<TD width="440"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"></FONT>
							<TABLE id="Table2" cellSpacing="5" cellPadding="0" border="0">
								<TR>
									<TD><IMG height="60" alt="ตะวันออก" src="picture/E.jpg" width="100" border="0"></TD>
									<TD><FONT face="MS Sans Serif, CordiaUPC" color="#000099" size="+1">&nbsp;<U><B>ภาคตะวันออก</B></U>
											<FONT style="FONT-SIZE: 8pt" face="Verdana" size="1">(East)</FONT></FONT></TD>
								</TR>
							</TABLE>
							<TABLE id="Table3" cellSpacing="2" cellPadding="0" border="0">
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>จันทบุรี</B>
											<FONT face="Arial, Verdana">(Chanthaburi)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ชลบุรี</B>
											<FONT face="Arial, Verdana">(Chon Buri)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ตราด</B>
											<FONT face="Arial, Verdana">(Trat)</FONT></FONT></TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ระยอง</B>
											<FONT face="Arial, Verdana">(Rayong)</FONT> </FONT>
									</TD>
								</TR>
							</TABLE>
						</TD>
					</TR>
				</TABLE>
			</FONT>
		</form>
	</body>
</HTML>
