<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormThaiEncoding.aspx.vb" Inherits="WebApplicationCenter.WebFormThaiEncoding"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormThaiEncoding</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" bgColor="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="MS Sans Serif, Microsoft Sans Serif" size="2">
				<DIV style="DISPLAY: inline; Z-INDEX: 101; LEFT: 99px; WIDTH: 173px; POSITION: absolute; TOP: 111px; HEIGHT: 78px" ms_positioning="FlowLayout">ถ้าเว็บไซต์ 
					หรือ e-mail ที่ได้รับแสดงภาษาต่างดาว เกิดจาก Encoding ของ Browser 
					มิได้กำหนดเป็น Thai (Windows) แต่สามารถเลือกให้ถูกต้องได้</DIV>
				<DIV style="DISPLAY: inline; Z-INDEX: 112; LEFT: 99px; WIDTH: 429px; POSITION: absolute; TOP: 276px; HEIGHT: 53px" ms_positioning="FlowLayout">
				โปรแกรม Browser</FONT><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">หรือ 
				e-mail โดยปกติจะไม่มี icon สำหรับเปลี่ยน Encoding ดังนั้นควร Add icon Encoding 
				สามารถทำได้ทั้งโปรแกรม Browser (Internet Explorer) </FONT><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">
				และโปรแกรม e-mail (Outlook Express) โดยการคลิกขวาที่พื้นที่ว่างของเมนูบาร์ 
				แล้วให้คลิกที่ <B>Customize</B></FONT></DIV> <IMG style="Z-INDEX: 111; LEFT: 78px; WIDTH: 18px; POSITION: absolute; TOP: 760px; HEIGHT: 17px" height="17" alt="" src="picture\radio.gif" width="18"><IMG style="Z-INDEX: 110; LEFT: 78px; WIDTH: 18px; POSITION: absolute; TOP: 550px; HEIGHT: 17px" height="17" alt="" src="picture\radio.gif" width="18">
			<IMG id="pic4" style="Z-INDEX: 109; LEFT: 284px; WIDTH: 242px; POSITION: absolute; TOP: 751px; HEIGHT: 160px" height="166" alt="" src="picture\encode04.gif" width="377">
			<DIV style="DISPLAY: inline; Z-INDEX: 108; LEFT: 99px; WIDTH: 145px; POSITION: absolute; TOP: 754px; HEIGHT: 78px" ms_positioning="FlowLayout"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">เท่านี้โปรแกรม 
						Browser </FONT><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">หรือ 
						โปรแกรม e-mail จะปรากฎ icon Encoding สำหรับเปลี่ยนภาษา ให้แสดงได้ถูกต้อง</FONT><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">กับเว็บไซต์ได้</FONT></FONT>
				</B></FONT></DIV>
			<IMG id="pic3" style="Z-INDEX: 107; LEFT: 249px; WIDTH: 306px; POSITION: absolute; TOP: 539px; HEIGHT: 176px" height="166" alt="" src="picture\encode03.gif" width="377">
			<DIV style="DISPLAY: inline; Z-INDEX: 106; LEFT: 99px; WIDTH: 130px; POSITION: absolute; TOP: 540px; HEIGHT: 62px" ms_positioning="FlowLayout"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">ที่ 
						Customize Toolbar ให้เลือกที่ Encoding กด Add icon แล้วคลิกที่ close</FONT></FONT></DIV>
			<IMG style="Z-INDEX: 105; LEFT: 288px; WIDTH: 273px; POSITION: absolute; TOP: 109px; HEIGHT: 141px" height="226" alt="" src="picture\encode01.gif" width="261">
			<IMG style="Z-INDEX: 104; LEFT: 188px; WIDTH: 377px; POSITION: absolute; TOP: 344px; HEIGHT: 141px" height="166" alt="" src="picture\encode02.gif" width="377" id="pic2">
			<IMG style="Z-INDEX: 103; LEFT: 78px; WIDTH: 18px; POSITION: absolute; TOP: 278px; HEIGHT: 17px" height="17" alt="" src="picture\radio.gif" width="18">
			<IMG src="picture\radio.gif" style="Z-INDEX: 102; LEFT: 78px; WIDTH: 18px; POSITION: absolute; TOP: 112px; HEIGHT: 17px" height="17" alt="" width="18"></FONT>&nbsp;
		</form>
	</body>
</HTML>
