<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormShow.aspx.vb" Inherits="WebApplicationCenter.WebFormShow1"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormShow1</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" bgColor="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma"><IMG style="Z-INDEX: 101; LEFT: 177px; WIDTH: 110px; POSITION: absolute; TOP: 145px; HEIGHT: 80px" height="80" alt="" src="picture\N.jpg" width="110">
				<DIV style="DISPLAY: inline; Z-INDEX: 110; LEFT: 343px; WIDTH: 103px; POSITION: absolute; TOP: 531px; HEIGHT: 45px" ms_positioning="FlowLayou"><A href="webformshoweast.aspx">ภาคตะวันออก</A></DIV>
				<DIV style="DISPLAY: inline; Z-INDEX: 109; LEFT: 343px; WIDTH: 85px; POSITION: absolute; TOP: 440px; HEIGHT: 45px" ms_positioning="FlowLayout"><A href="webformshowsouth.aspx">ภาคใต้</A></DIV>
				<DIV style="DISPLAY: inline; Z-INDEX: 107; LEFT: 343px; WIDTH: 85px; POSITION: absolute; TOP: 259px; HEIGHT: 45px" ms_positioning="FlowLayout"><A href="webformshowcenter.aspx">ภาคกลาง</A></DIV>
				<IMG style="Z-INDEX: 105; LEFT: 177px; WIDTH: 110px; POSITION: absolute; TOP: 234px; HEIGHT: 80px" height="80" alt="" src="picture\C.jpg" width="110"><IMG style="Z-INDEX: 104; LEFT: 177px; WIDTH: 110px; POSITION: absolute; TOP: 323px; HEIGHT: 80px" height="80" alt="" src="picture\NE.jpg" width="110"><IMG style="Z-INDEX: 103; LEFT: 177px; WIDTH: 110px; POSITION: absolute; TOP: 411px; HEIGHT: 80px" height="80" alt="" src="picture\S.jpg" width="110"><IMG style="Z-INDEX: 102; LEFT: 177px; WIDTH: 110px; POSITION: absolute; TOP: 500px; HEIGHT: 80px" height="80" alt="" src="picture\E.jpg" width="110">
				<DIV style="DISPLAY: inline; Z-INDEX: 106; LEFT: 343px; WIDTH: 85px; POSITION: absolute; TOP: 163px; HEIGHT: 45px" ms_positioning="FlowLayout"><A href="webformshownorth.aspx">ภาคเหนือ</A></DIV>
				<DIV style="DISPLAY: inline; Z-INDEX: 108; LEFT: 343px; WIDTH: 85px; POSITION: absolute; TOP: 353px; HEIGHT: 45px" ms_positioning="FlowLayout"><A href="webformshownortheast.aspx">ภาคอีสาน</A></DIV>
				<DIV style="DISPLAY: inline; Z-INDEX: 111; LEFT: 183px; WIDTH: 300px; POSITION: absolute; TOP: 49px; HEIGHT: 39px" ms_positioning="FlowLayout"><h1>สินค้าในภาคต่างๆ</h1>
				</DIV>
			</FONT>
		</form>
		</A>
	</body>
</HTML>
