<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormShowNorth.aspx.vb" Inherits="WebApplicationCenter.WebFormShowNorth"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormShowNorth</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" BGCOLOR="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma">
				<TABLE id="Table1" style="Z-INDEX: 101; LEFT: 144px; WIDTH: 616px; POSITION: absolute; TOP: 105px; HEIGHT: 294px" cellSpacing="0" cellPadding="0" width="616" border="0">
					<TR vAlign="top">
						<TD width="10"><IMG height="1" src="/_tarad/images/tc.gif" width="10"></TD>
						<TD width="440"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"></FONT>
							<TABLE id="Table2" cellSpacing="5" cellPadding="0" border="0">
								<TR>
									<TD><IMG height="60" alt="เหนือ" src="picture\N.jpg" width="100" border="0"></TD>
									<TD><FONT face="MS Sans Serif, CordiaUPC" color="#000099" size="+1">&nbsp;<U><B>ภาคเหนือ</B></U>
											<FONT style="FONT-SIZE: 8pt" face="Verdana" size="1">(North)</FONT></FONT></TD>
								</TR>
							</TABLE>
							<TABLE id="Table3" cellSpacing="2" cellPadding="0" border="0">
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>กำแพงเพชร</B>
											<FONT face="Arial, Verdana">(Kamphaeng Phet)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>เชียงราย</B>
											<FONT face="Arial, Verdana">(Chiang Rai)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B><A href="chiangmai.aspx">เชียงใหม่</A></B>
											<FONT face="Arial, Verdana">(Chiang Mai)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ตาก</B>
											<FONT face="Arial, Verdana">(Tak)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>นครสวรรค์</B>
											<FONT face="Arial, Verdana">(Nakhon Sawan)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>น่าน</B>
											<FONT face="Arial, Verdana">(Nan)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>พะเยา</B>
											<FONT face="Arial, Verdana">(Phayao)</FONT></FONT></TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>พิจิตร</B>
											<FONT face="Arial, Verdana">(Phichit)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>พิษณุโลก</B>
											<FONT face="Arial, Verdana">(Phitsanulok)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>เพชรบูรณ์</B>
											<FONT face="Arial, Verdana">(Phetchabun)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>แพร่</B>
											<FONT face="Arial, Verdana">(Phrae)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>แม่ฮ่องสอน</B>
											<FONT face="Arial, Verdana">(Mae Hong Son)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ลำปาง</B>
											<FONT face="Arial, Verdana">(Lampang)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ลำพูน</B>
											<FONT face="Arial, Verdana">(Lamphun)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สุโขทัย</B>
											<FONT face="Arial, Verdana">(Sukhothai)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>อุตรดิตถ์</B>
											<FONT face="Arial, Verdana">(Uttaradit)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
							</TABLE>
						</TD>
					</TR>
				</TABLE>
			</FONT>
		</form>
	</body>
</HTML>
