<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormError.aspx.vb" Inherits="WebApplicationCenter.WebFormError"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormError</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma">
				<asp:Label id="Label1" style="Z-INDEX: 101; LEFT: 97px; POSITION: absolute; TOP: 107px" runat="server" Width="405px" Height="104px" ForeColor="Red" Font-Bold="True" Font-Size="X-Large">เกิดความผิดพลาดกรุณาทำรายการนั้นใหม่อีกครัง</asp:Label>
				<asp:Button id="btnOK" style="Z-INDEX: 102; LEFT: 404px; POSITION: absolute; TOP: 251px" runat="server" Width="92px" Height="31px" Text="ต่อไป"></asp:Button></FONT>
		</form>
	</body>
</HTML>
