<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormGif.aspx.vb" Inherits="WebApplicationCenter.WebFromGiftojpg"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFromGiftojpg</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" bgColor="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma">
				<DIV style="DISPLAY: inline; Z-INDEX: 101; LEFT: 103px; WIDTH: 347px; POSITION: absolute; TOP: 69px; HEIGHT: 58px" ms_positioning="FlowLayout"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">รูปสินค้าที่ต้องการ 
						จากเว็บไซต์ จะมีบางส่วนที่เป็น ไฟล์รูปนามสกุล <FONT face="Verdana, Arial, Helvetica, sans-serif">
							Graphics Interchange Format (GIF) </FONT><FONT face="MS Sans Serif">แต่</FONT>
						รูปประกอบบางอย่างจะใช้ไฟล์ นามสกุล <FONT face="Verdana, Arial, Helvetica, sans-serif">
							Jpeg (jpg)</FONT> เพื่อการย่อขยายภาพอย่างอัตโนมัต สะดวกผู้ใช้บริการ<BR>
					</FONT>
				</DIV>
				<IMG id="pic4" style="Z-INDEX: 110; LEFT: 102px; WIDTH: 425px; POSITION: absolute; TOP: 1033px; HEIGHT: 245px" height="170" alt="" src="picture\04.gif" width="259">
				<DIV style="DISPLAY: inline; Z-INDEX: 109; LEFT: 105px; WIDTH: 346px; POSITION: absolute; TOP: 968px; HEIGHT: 52px" ms_positioning="FlowLayout"><FONT face="Verdana, Arial, Helvetica, sans-serif" size="1">Save 
						for Web</FONT><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1"> จะเป็นการ
						<FONT face="Verdana, Arial, Helvetica, sans-serif">Save</FONT> ไฟล์สำหรับเว็บเพจโดยเฉพาะ 
						ในขั้นตอนการ <FONT face="Verdana, Arial, Helvetica, sans-serif">Save</FONT> ให้เลือก
						<FONT face="Verdana, Arial, Helvetica, sans-serif">Setting : JPEG Hight</FONT> ตามความเหมาะสม 
						ถ้าขนาดไฟล์เกินกว่า <FONT face="Verdana, Arial, Helvetica, sans-serif">100 Kb.</FONT>
						ให้เลือก <FONT face="Verdana, Arial, Helvetica, sans-serif">JPEG Low</FONT> ขนาดไฟล์จะน้อยลง</FONT>
				</DIV>
				<IMG id="pic5" style="Z-INDEX: 108; LEFT: 102px; WIDTH: 226px; POSITION: absolute; TOP: 1360px; HEIGHT: 205px" height="170" alt="" src="picture\05.gif" width="259">
				<DIV style="DISPLAY: inline; Z-INDEX: 107; LEFT: 105px; WIDTH: 213px; POSITION: absolute; TOP: 1293px; HEIGHT: 55px" ms_positioning="FlowLayout"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">
							<FONT face="Verdana, Arial, Helvetica, sans-serif"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">
									เมื่อทำตามขั้นตอน จะได้ไฟล์นามสกุล <FONT face="Verdana, Arial, Helvetica, sans-serif">
										.jpg</FONT> ที่สามารถนำไปใช้งานได้ตามความเหมาะสม</FONT> </FONT></FONT>
					</FONT>
				</DIV>
				<DIV style="DISPLAY: inline; Z-INDEX: 105; LEFT: 107px; WIDTH: 186px; POSITION: absolute; TOP: 646px; HEIGHT: 55px" ms_positioning="FlowLayout"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">เมื่อเปิด 
							ไฟล์รูปภาพแล้ว ให้ทำหาร <FONT face="Verdana, Arial, Helvetica, sans-serif">Save</FONT>
							ด้วยการเลือกที่ <FONT face="Verdana, Arial, Helvetica, sans-serif"><B>Files</B> &gt;&gt;
								<B>Save for Web</B><BR>
							</FONT></FONT></FONT>
				</DIV>
				<IMG id="pic2" style="Z-INDEX: 104; LEFT: 103px; WIDTH: 294px; POSITION: absolute; TOP: 423px; HEIGHT: 200px" height="170" alt="" src="picture\02.gif" width="259">
				<DIV style="DISPLAY: inline; Z-INDEX: 103; LEFT: 104px; WIDTH: 241px; POSITION: absolute; TOP: 371px; HEIGHT: 36px" ms_positioning="FlowLayout"><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1">เปิดไฟล์ 
						ด้วยโปรแกรม <FONT face="Verdana, Arial, Helvetica, sans-serif"><B>Photoshop</B></FONT>
						เนื่องจากเป็น โปรแกรมที่สะดวก ในการใช้งาน<BR>
					</FONT>
				</DIV>
				<IMG src="picture\01.gif" id="pic1" style="Z-INDEX: 102; LEFT: 103px; WIDTH: 226px; POSITION: absolute; TOP: 149px; HEIGHT: 205px" height="170" alt="" width="259"></FONT>
			<IMG id="pic3" style="Z-INDEX: 111; LEFT: 104px; WIDTH: 307px; POSITION: absolute; TOP: 715px; HEIGHT: 228px" height="228" alt="" src="picture\03.gif" width="259">
		</form>
	</body>
</HTML>
