<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormShowSouth.aspx.vb" Inherits="WebApplicationCenter.WebFormShowSouth"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormShowSouth</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" BGCOLOR="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma">
				<TABLE id="Table1" style="Z-INDEX: 101; LEFT: 134px; POSITION: absolute; TOP: 104px" cellSpacing="0" cellPadding="0" width="750" border="0">
					<TR vAlign="top">
						<TD width="10"></TD>
						<TD width="440"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"></FONT>
							<TABLE id="Table2" cellSpacing="5" cellPadding="0" border="0">
								<TR>
									<TD><IMG height="60" alt="„µÈ" src="picture/S.jpg" width="100" border="0"></TD>
									<TD><FONT face="MS Sans Serif, CordiaUPC" color="#000099" size="+1">&nbsp;<U><B>¿“§„µÈ</B></U>
											<FONT style="FONT-SIZE: 8pt" face="Verdana" size="1">(South)</FONT> </FONT>
									</TD>
								</TR>
							</TABLE>
							<TABLE id="Table3" cellSpacing="2" cellPadding="0" border="0">
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>°√–∫’Ë</B>
											<FONT face="Arial, Verdana">(Krabi)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>™ÿ¡æ√</B>
											<FONT face="Arial, Verdana">(Chumphon)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>µ√—ß</B>
											<FONT face="Arial, Verdana">(Trang)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>π§√»√’∏√√¡√“™</B>
											<FONT face="Arial, Verdana">(Nakhon Si Thammarat)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>π√“∏‘«“ </B>
											<FONT face="Arial, Verdana">(Narathiwat)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ª—µµ“π’</B>
											<FONT face="Arial, Verdana">(Pattani)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>æ—ßß“</B>
											<FONT face="Arial, Verdana">(Phangnga)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>æ—∑≈ÿß</B>
											<FONT face="Arial, Verdana">(Phatthalung)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>¿Ÿ‡°Áµ</B>
											<FONT face="Arial, Verdana">(Phuket)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>¬–≈“</B>
											<FONT face="Arial, Verdana">(Yala)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>√–πÕß</B>
											<FONT face="Arial, Verdana">(Ranong)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B> ß¢≈“</B>
											<FONT face="Arial, Verdana">(Songkhla)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B> µŸ≈</B>
											<FONT face="Arial, Verdana">(Satun)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>ï</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B> ÿ√“…Æ√Ï∏“π’</B>
											<FONT face="Arial, Verdana">(Surat Thani)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
							</TABLE>
						</TD>
					</TR>
				</TABLE>
			</FONT>
		</form>
	</body>
</HTML>
