<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormShowCrook2.aspx.vb" Inherits="WebApplicationCenter.WebFormShowCrook2"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormShowCrook2</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" bgColor="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma"></FONT>
			<DIV style="Z-INDEX: 101; LEFT: 150px; WIDTH: 373px; POSITION: absolute; TOP: 20px; HEIGHT: 3026px" ms_positioning="FlowLayout">
				<P align="center"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="navy" size="2"><B><FONT size="3">รูปแบบของการหลอกลวงทางอินเทอร์เน็ต</FONT></B></FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					</FONT><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="navy" size="2">
						<B>6. การหลอกลวงโดยใช้การตลาดหรือการขายแบบตรง (Multilevel Marketing Plans/ 
							Pyramids)</B></FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ลักษณะการหลอกลวง:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						การหลอกลวงในลักษณะนี้คล้ายคลึงกับการนำสื่อโฆษณาในการทำตลาดหรือการขายตรง 
						โดยมีการ<BR>
						ชักชวนให้บุคคลทั่วไปเข้าร่วมเป็นสมาชิกในเครือข่ายธุรกิจ 
						โดยการกล่าวอ้างว่าผู้ขายจะได้รับสิทธิในการ
						<BR>
						จำหน่ายสินค้าหลายชนิด 
						และได้รับผลประโยชน์จากการขายสินค้าหรือชักชวนบุคคลอื่นเข้ามาเป็นตัวแทน<BR>
						ขายตรงเป็นทอดๆ ทำให้ผู้ที่ได้รับประโยชน์จริงมีจำนวนน้อยราย</FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ความเสียหายที่อาจเกิดขึ้นได้:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ผู้บริโภคที่เข้าร่วมเครือข่ายจะต้องชำระค่าสมาชิกจำนวนหนึ่ง 
						แต่จะไม่มีรายได้ประจำแต่อย่างใด
						<BR>
						รายได้ของผู้บริโภคจึงไม่แน่นอนและมักจะไม่ได้รับผลประโยชน์ตามที่ผู้หลอกลวงกล่าวอ้าง 
						เพราะไม่<BR>
						สามารถขายสินค้าได้ตามเป้าหมาย </FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="green" size="2">วิธีการป้องกัน:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ผู้บริโภคควรระมัดระวังในการสมัครเป็นสมาชิกหรือตัวแทนจำหน่ายสินค้า 
						ที่ต้องหาสมาชิกรายอื่น
						<BR>
						เพิ่มขึ้นหรือต้อง จำหน่ายสินค้าที่มีราคาค่อนข้างสูงให้ได้ตามยอดจำหน่ายที่กำหนด 
						เพราะอาจถูก<BR>
						หลอกลวงได้</FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="navy" size="2"><B>7. 
							การหลอกลวงโดยเสนอให้เงินจากประเทศไนจีเรีย (Nigerian Money Offers)</B></FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ลักษณะการหลอกลวง:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ผู้ใช้อินเทอร์เน็ตจะได้รับข้อความจากจดหมายหรืออีเมล์ (e-mail) 
						จากบุคคลที่กล่าวอ้างว่ามีความ<BR>
						สำคัญในประเทศไนจีเรีย เพื่อขอช่วยเหลือในการโอนเงินจำนวนมากไปยังต่างประเทศ 
						โดยผู้บริโภคจะ<BR>
						ได้รับเงินส่วนแบ่ง จำนวนนับล้านเหรียญ ดอลลาร์สหรัฐฯ </FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ข้อความในจดหมายหรืออีเมล์มีเนื้อหาทำนองว่า ประชาชนในประเทศไนจีเรียไม่สามารถเปิด<BR>
						บัญชีเงินฝากในต่างประเทศ หรือโอนเงินออกนอกประเทศที่มีมูลค่าราว 10 
						ล้านดอลลาร์สหรัฐฯ ได้
						<BR>
						หรือรัฐบาลไนจีเรียต้องการทำธุรกิจกับชาวต่างชาติ 
						จึงต้องการความช่วยเหลือจากชาวต่างชาติในการ
						<BR>
						เปิดบัญชีเงินฝากประเภทกระแสรายวันที่เบิกด้วยเช็ค ซึ่งท่านจะได้รับค่า 
						ตอบแทนหรือค่านายหน้า
						<BR>
						ผู้บริโภคเพียงแต่แจ้งรายละเอียดของบัญชีเงินฝากของตน 
						และกรอกเอกสารพร้อมทั้งลงลายมือชื่อ
						<BR>
						ของเจ้าของบัญชีเท่านั้น </FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ความเสียหายที่อาจเกิดขึ้นได้:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						เมื่อมีการแจ้งข้อมูลบัญชีเงินฝากแล้ว 
						ผู้บริโภคจะถูกเรียกเก็บค่าธรรมเนียมหรือค่าใช้จ่ายในการ<BR>
						ดำเนินการตลอดเวลา โดยให้ผู้บริโภคโอนเงินเข้าบัญชีที่แจ้งไว้ 
						ผู้ที่หลอกลวงจึงสามารถเบิกเงินจาก<BR>
						บัญชีดังกล่าวได้ โดยอ้างเอกสารมอบอำนาจของเจ้า ของบัญชี 
						แต่การโอนเงินลักษณะนี้อาจทำไม่ได้<BR>
						ในประเทศไทย เว้นแต่จะเป็นการโอนเงินระหว่างบัญชีของธนาคารเดียวกัน 
						ทางอินเทอร์เน็ต</FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="green" size="2">วิธีการป้องกัน:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ผู้บริโภคไม่ควรหลงเชื่อบุคคลอื่นที่อ้างตัวและเสนอจะให้ผลประโยชน์จำนวนมหาศาลโดยไม่มี<BR>
						ความเสี่ยงเช่นนี้ และ ไม่ควรเปิดเผยข้อมูลบัญชีธนาคารของตนแก่ผู้อื่นด้วย</FONT>
				<P>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="navy" size="2"><B>8. 
							การหลอกลวงให้ประกอบธุรกิจที่บ้าน (Work-at-Home)</B></FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ลักษณะการหลอกลวง:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						บริษัทที่หลอกลวงจะเชิญชวนให้ผู้ต้องการประกอบธุรกิจทางอินเทอร์เน็ตหรือธุรกิจด้าน<BR>
						พาณิชย์อิเล็กทรอนิกส์ สมัครเป็นสมาชิกเพื่อทำธุรกิจ 
						โดยผู้บริโภคมีเพียงเครื่องคอมพิวเตอร์และ<BR>
						สามารถ ใช้อินเทอร์เน็ตจากที่บ้านได้ และมักอ้าง 
						ว่าธุรกิจประเภทนี้เป็นธุรกิจที่เติบโตอย่างรวดเร็ว
						<BR>
						ในขณะที่ผู้บริโภคจะไม่ได้รับคำแนะนำในการทำธุรกิจ ไม่มีข้อมูลธุรกิจ 
						ที่ชัดเจนหรือไม่ทราบว่าตน<BR>
						อาจไม่ได้รับค่าตอบแทนใดๆ 
						เลยผู้ถูกหลอกลวงจะถูกเรียกเก็บเงินค่าสมาชิกหรือซื้ออุปกรณ์ที่จำเป็น<BR>
						เพื่อเริ่มทำธุรกิจ </FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ความเสียหายที่อาจเกิดขึ้นได้:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ผู้ลงทุนจะไม่ได้รับเงินค่าตอบแทนตามที่มีการกล่าวอ้าง 
						และอาจต้องสูญเสียเงินจากการ<BR>
						ลงทุนอีกด้วย</FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="green" size="2">วิธีการป้องกัน:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ผู้ที่ต้องการลงทุนหรือต้องการเป็นเจ้าของกิจการ ควรศึกษาหรือสอบถามรายละเอียดของ<BR>
						ประเภทธุรกิจที่จะลงทุนการจ่าย เงินค่าตอบแทนที่ผู้บริโภคจะได้รับ 
						ที่มีกำหนดเวลาที่แน่นอน
						<BR>
						รวมถึงค่าใช้จ่ายทั้งหมดที่จะต้องจ่ายในการเริ่มต้นทำธุรกิจ 
						และผู้บริโภคควรระวังไม่หลงเชื่อ
						<BR>
						คำเชิญชวนของผู้ที่อ้างว่าเป็นธุรกิจที่สร้างรายได้จำนวนมากภายในระยะเวลาสั้นๆ</FONT>
				<P>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="navy" size="2"><B>9. 
							การหลอกลวงให้จดทะเบียนโดเมนเนม (domain name registration scams) </B></FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ลักษณะการหลอกลวง:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ผู้ที่ต้องการทำธุรกิจทางอินเทอร์เน็ตที่ต้องการมีเว็บไซต์และโดเมนเนมของตนเอง 
						จะได้รับ<BR>
						การเสนอแนะว่าท่านสามารถได้รับสิทธิในการจดทะเบียนโดเมนเนมในระดับบนที่เรียกว่า
						<BR>
						“Generic Top-Level Domain’ หรือ gTLD ได้แก่ .com, .org, .net, .int, .edu, .gov,
						<BR>
						.mil, .aero, .biz, .coop, .info, .museum, .name, and .pro เป็นต้น ก่อนบุคคลอื่น
						<BR>
						และถูกเรียกเก็บค่าธรรมเนียมในการจองโดเมนเนมที่ต้องการ 
						ซึ่งในความเป็นจริงไม่มีการให้บริการ
						<BR>
						ในลักษณะดังกล่าว</FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ความเสียหายที่อาจเกิดขึ้นได้:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ผู้ที่หลงเชื่ออาจได้รับความเสียหายเพราะได้ชำระเงินให้แก่ผู้ที่หลอกลวง 
						โดยไม่ได้รับสิทธิหรือ
						<BR>
						<BR>
						ประโยชน์ตามที่กล่าวอ้าง </FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="green" size="2">วิธีการป้องกัน:</FONT>
					<OL>
						<LI>
							<FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">หลีกเลี่ยงการใช้บริการการขอจดทะเบียนโดเมนเนมล่วงหน้า 
								ที่ให้การรับรองว่าจะได้รับสิทธิ
								<BR>
								ในการเลือกโดเมนเนมประเภทนี้ (gTLD) ก่อนบุคคลอื่น และไม่ควรหลงเชื่อคำโฆษณา</FONT>
						<LI>
							<FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">ควรติดตามข่าวสารเกี่ยวกับการยื่นขอจดทะเบียนจากผู้รับจดทะเบียนที่ได้รับสิทธิภายใน
								<BR>
								ประเทศหรือเว็บไซต์ของ ICANN (Internet Corporation for Assigned Names and
								<BR>
								Numbers) (www.icann.org) </FONT>
						<LI>
							<FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">ควรใช้บริการจดทะเบียนโดเมนเนมกับหน่วยงานที่น่าเชื่อถือ 
								เช่น ผู้ให้บริการอินเทอร์เน็ต,
								<BR>
								บริษัทที่ประกอบธุรกิจเกี่ยวกับพาณิชย์อิเล็กทรอนิกส์ หรือใช้บริการของ
								<BR>
								“ศูนย์สารสนเทศเครือข่ายแห่งประเทศไทย” (Thailand Network Information Center –
								<BR>
								THNIC) (www.thnic.net)</FONT>
						</LI>
					</OL>
				<P>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="navy" size="2"><B>10. 
							การหลอกลวงโฆษณาหรือขายยามหัศจรรย์ (miracle products)</B></FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ลักษณะการหลอกลวง:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						การโฆษณาหรือขายยาทางอินเทอร์เน็ตที่อ้างสรรพคุณว่าสามารถรักษาโรคหรืออาการ
						<BR>
						เจ็บป่วยด้วยโรคร้ายแรง เช่น โรคมะเร็ง, โรคภูมิคุ้มกันบกพร่อง (HIV/AIDS), 
						โรคความดัน<BR>
						โลหิตสูง ฯลฯ หรือสามารถบรรเทาความเจ็บป่วยได้ภายในระยะเวลาอันสั้น 
						และมักอ้างว่ายาเหล่านี้
						<BR>
						ได้รับการรับรองหรือการพิสูจน์ทางวิทยาศาสตร์แล้ว </FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="red" size="2">ความเสียหายที่อาจเกิดขึ้นได้:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						ผู้ป่วยที่ซื้อยาดังกล่าวโดยเชื่อว่าสามารถรักษาความเจ็บป่วยได้ 
						อาจต้องสูญเสียเงินหรือ<BR>
						โอกาสในการได้รับการรักษาอย่างถูกต้อง นอกจากนั้น 
						ยังอาจได้รับอันตรายจากการใช้ยาเหล่านั้นด้วย</FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="green" size="2">วิธีการป้องกัน:</FONT>
				<P align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
						การใช้ยารักษาโรคควรได้รับคำแนะนำจากแพทย์หรือเภสัชกรเท่านั้น </FONT>
				<P><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" color="navy" size="2"><B>แหล่งข้อมูล</B></FONT>
					<UL>
						<LI>
							<FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2">ศุนย์พัฒนาพาณิชยอิเล็กทรอนิกส์ 
								( Electronic Commerce Resource Center )<BR>
								http://www.ecommerce.or.th</FONT><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1"><BR>
							</FONT>
						</LI>
					</UL>
					<DIV align="left"><FONT face="MS Sans Serif, AngsanaUPC, CordiaUPC, EucrosiaUPC" size="2"><A href="webformshowcrook1.aspx">&lt;&lt;&lt;หน้าก่อนหน้า</A></FONT><FONT face="MS Sans Serif, Microsoft Sans Serif" size="1"></FONT></DIV>
			</DIV>
		</form>
	</body>
</HTML>
