<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormshowNorthEast.aspx.vb" Inherits="WebApplicationCenter.WebFormshowNorthEast"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormshowNorthEast</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" BGCOLOR="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma">
				<TABLE id="Table1" style="Z-INDEX: 101; LEFT: 123px; POSITION: absolute; TOP: 97px" cellSpacing="0" cellPadding="0" width="750" border="0">
					<TR vAlign="top">
						<TD width="10"></TD>
						<TD width="440"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"></FONT>
							<TABLE id="Table2" cellSpacing="5" cellPadding="0" border="0">
								<TR>
									<TD><IMG height="60" alt="ตะวันออกเฉียงเหนือ" src="picture/NE.jpg" width="100" border="0"></TD>
									<TD><FONT face="MS Sans Serif, CordiaUPC" color="#000099" size="+1">&nbsp;<U><B>ภาคตะวันออกเฉียงเหนือ</B></U>
											<FONT style="FONT-SIZE: 8pt" face="Verdana" size="1">(NorthEast)</FONT> </FONT>
									</TD>
								</TR>
							</TABLE>
							<TABLE id="Table3" cellSpacing="2" cellPadding="0" border="0">
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>กาฬสินธุ์</B>
											<FONT face="Arial, Verdana">(Kalasin)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B><A href="khonkaen.aspx">ขอนแก่น</A></B>
											<FONT face="Arial, Verdana">(Khon Kaen)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ชัยภูมิ</B>
											<FONT face="Arial, Verdana">(Chaiyaphum)</FONT></FONT></TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>นครพนม</B>
											<FONT face="Arial, Verdana">(Nakhon Phanom)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>นครราชสีมา</B>
											<FONT face="Arial, Verdana">(Nakhon Ratchasima)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>บุรีรัมย์</B>
											<FONT face="Arial, Verdana">(Buri Ram)</FONT></FONT></TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>มหาสารคาม</B>
											<FONT face="Arial, Verdana">(Maha Sarakham)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>มุกดาหาร</B>
											<FONT face="Arial, Verdana">(Mukdahan)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ยโสธร</B>
											<FONT face="Arial, Verdana">(Yasothon)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ร้อยเอ็ด</B>
											<FONT face="Arial, Verdana">(Roi Et)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>เลย</B>
											<FONT face="Arial, Verdana">(Loei)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ศรีสะเกษ</B>
											<FONT face="Arial, Verdana">(Si Sa Ket)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สกลนคร</B>
											<FONT face="Arial, Verdana">(Sakon Nakhon)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สุรินทร์</B>
											<FONT face="Arial, Verdana">(Surin)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>หนองคาย</B>
											<FONT face="Arial, Verdana">(Nong Khai)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>หนองบัวลำภู</B>
											<FONT face="Arial, Verdana">(Nong Bua Lam Phu)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>อำนาจเจริญ</B>
											<FONT face="Arial, Verdana">(Amnat Charoen)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>อุดรธานี</B>
											<FONT face="Arial, Verdana">(Udon Thani)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>อุบลราชธานี</B>
											<FONT face="Arial, Verdana">(Ubon Ratchathani)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><IMG height="1" src="/_tarad/images/tc.gif" width="1"></TD>
									<TD width="200"><IMG height="1" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
							</TABLE>
						</TD>
					</TR>
				</TABLE>
			</FONT>
		</form>
	</body>
</HTML>
