<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormShowCenter.aspx.vb" Inherits="WebApplicationCenter.WebFormShowCenter"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormShowCenter</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" BGCOLOR="#ffffcc">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma">
				<TABLE id="Table1" style="Z-INDEX: 101; LEFT: 123px; POSITION: absolute; TOP: 97px" cellSpacing="0" cellPadding="0" width="750" border="0">
					<TR vAlign="top">
						<TD width="10"></TD>
						<TD width="440">
							<TABLE id="Table2" cellSpacing="5" cellPadding="0" border="0">
								<TR>
									<TD><IMG height="60" alt="กลาง" src="picture/C.jpg" width="100" border="0"></TD>
									<TD><FONT face="MS Sans Serif, CordiaUPC" color="#000099" size="+1">&nbsp;<U><B>ภาคกลาง</B></U>
											<FONT style="FONT-SIZE: 8pt" face="Verdana" size="1">(Central)</FONT> </FONT>
									</TD>
								</TR>
							</TABLE>
							<TABLE id="Table3" cellSpacing="2" cellPadding="0" border="0">
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>กรุงเทพมหานคร</B>
											<FONT face="Arial, Verdana">(Bangkok)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>กาญจนบุรี</B>
											<FONT face="Arial, Verdana">(Kanchanaburi)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ฉะเชิงเทรา</B>
											<FONT face="Arial, Verdana">(Chachoengsao)</FONT></FONT></TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ชัยนาท</B>
											<FONT face="Arial, Verdana">(Chai Nat)</FONT></FONT></TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>นครนายก</B>
											<FONT face="Arial, Verdana">(Nakhon Nayok)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>นครปฐม</B>
											<FONT face="Arial, Verdana">(Nakhon Pathom)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>นนทบุรี</B>
											<FONT face="Arial, Verdana">(Nonthaburi)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ปทุมธานี</B>
											<FONT face="Arial, Verdana">(Pathum Thani)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ประจวบคีรีขันธ์</B>
											<FONT face="Arial, Verdana">(Prachuap Khiri Khan)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ปราจีนบุรี</B>
											<FONT face="Arial, Verdana">(Prachin Buri)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>พระนครศรีอยุธยา</B>
											<FONT face="Arial, Verdana">(Phra Nakhon Si Ayutthaya)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>เพชรบุรี</B>
											<FONT face="Arial, Verdana">(Phetchaburi)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ราชบุรี</B>
											<FONT face="Arial, Verdana">(Ratcharuri)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>ลพบุรี</B>
											<FONT face="Arial, Verdana">(Lop Buri)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สมุทรปราการ</B>
											<FONT face="Arial, Verdana">(Samut Prakan)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สมุทรสงคราม</B>
											<FONT face="Arial, Verdana">(Samut Songkhram)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สมุทรสาคร</B>
											<FONT face="Arial, Verdana">(Samut Sakhon)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สระแก้ว</B>
											<FONT face="Arial, Verdana">(Sa Kaeo)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สระบุรี</B>
											<FONT face="Arial, Verdana">(Saraburi)</FONT></FONT></TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สิงห์บุรี</B>
											<FONT face="Arial, Verdana">(Sing Buri)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>สุพรรณบุรี</B>
											<FONT face="Arial, Verdana">(Suphan Buri)</FONT> </FONT>
									</TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>อ่างทอง</B>
											<FONT face="Arial, Verdana">(Ang Thong)</FONT> </FONT>
									</TD>
								</TR>
								<TR>
									<TD colSpan="5"><IMG height="5" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
								<TR vAlign="top">
									<TD><FONT style="FONT-SIZE: 10px" face="Arial,Ms Sans Serif" color="#cccccc" size="1"><B>•</B></FONT></TD>
									<TD width="200"><FONT style="FONT-SIZE: 8pt" face="MS Sans Serif, CordiaUPC" color="#000099" size="1"><B>อุทัยธานี</B>
											<FONT face="Arial, Verdana">(Uthai Thani)</FONT></FONT></TD>
									<TD width="15"><IMG height="1" src="/_tarad/images/tc.gif" width="15"></TD>
									<TD><IMG height="1" src="/_tarad/images/tc.gif" width="1"></TD>
									<TD width="200"><IMG height="1" src="/_tarad/images/tc.gif" width="1"></TD>
								</TR>
							</TABLE>
						</TD>
					</TR>
				</TABLE>
			</FONT>
		</form>
	</body>
</HTML>
