


import  java.sql.*;                                                                        
import  oracle.jdbc.driver.*;
import  java.io.*;
import  javax.servlet.*;
import  javax.servlet.http.*;
import  java.util.*;
public class Adminaddspec extends HttpServlet
{
    public void   doGet(HttpServletRequest req, HttpServletResponse resp)
    throws ServletException, java.io.IOException
  	{
	  java.io.PrintWriter out = new java.io.PrintWriter(resp.getOutputStream());
    HttpSession session = req.getSession(true);
    String username = (String)session.getValue("username") ;
    String companyname = (String)session.getValue("companyname");
    String Str_Query ;
    int rowCount = 0;
    resp.setContentType("text/html");
out.println("   <html>");
out.println("<head>");
out.println("<title>Internet Auction : CE.KMITL</title>");
out.println("<style><!-- A:link, A:visited { text-decoration: none; color: #ffffff}  A:hover { text-decoration: none; font-weight: underline; color :  #33ccff} // --> </style>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("</head>");
out.println("<body bgcolor=\"#FFFFFF\" link=\"#FF9933\" vlink=\"#3399CC\" alink=\"#FF9966\" >");
out.println("<div align=\"center\">");
out.println("  <p>&nbsp;</p>");
out.println("  <div id=\"Layer1\" style=\"position:absolute; width:970px; height:100px; z-index:1; left: 17px; top: 22px\">");
out.println("  <table width=\"99%\" border=\"0\" height=\"400\">");
out.println("<tr>");
out.println("    <div align=\"center\"><img src=\"/picture/AuctionBanner.jpg\" width=\"970\" height=\"98\"></div>");
out.println("</tr>");
out.println("<tr>");
out.println("      <td rowspan=\"3\" height=\"137\" width=\"15%\" bgcolor=\"#4F4FD2\" valign=\"top\">");
out.println("        <div align=\"center\">");
out.println("          <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><br>");
out.println("            </font></i></font></font></p>");
out.println("          <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><font color=\"#CC0000\"><b><font size=\"3\" color=\"#FFCC00\">New");
out.println("            Users !!</font></b></font><br>");
out.println("            </font></i></font></font><br>");
out.println("          </p>");
out.println("        </div>");
out.println("        <div align=\"center\">");
out.println("          <p><font size=\"3\"><a href=\"../register.html\"><font face=\"Arial, Helvetica, sans-serif\">Register</font></a></font>");
out.println("            <br>");
out.println("              <font size=\"3\"><a href=\"../NewToAuction.html\"><font face=\"Arial, Helvetica, sans-serif\">");
out.println("              New to our Auction</font></a></font> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            <br>");
out.println("            <font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction Member</font></b></font></i></font></p>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"LoginSuccess\"><font size=\"3\" >Home<font face=\"Arial, Helvetica, sans-serif\">");
out.println("          </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i><a href=\"Changeinfo\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Change");
out.println("            Personal Information </font><font  face=\"Arial, Helvetica, sans-serif\">");
out.println("            </font></font> </a><i> </i></font> </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"></font><a href=\"Listmember\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member");
out.println("            Profile<br>");
out.println("            </font></font></a><a href=\"Listproject\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Project");
out.println("            List</font></font></a><a href=\"OfferSpec\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><br>");
out.println("            </font></font></a><a href=\"Ranking\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member Rating</font></font></a>");
out.println("            <br>");
out.println("            <br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\"><b><font color=\"#FF9900\">For");
out.println("            Buyer</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"GeneralReq\">General");
out.println("            Requirement</a></font></font><br>");
out.println("			<font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddTechReq\">Add Technical Requirement <font size=\"2\"><i>(bidding)</i></font></a></font></font><br><br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#CCCCCC\" size=\"2\"><b><font color=\"#FF9900\">For");
out.println("            Seller</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddSpecification\">Add");
out.println("            Specification</a></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"ListBiddingProject\">Bidding</a></font></font><br>");
out.println("            <br>");
out.println("            </div>");
out.println("          <div align=\"center\">");
out.println("<p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction");
out.println("              Services</font></b></font></i></font> <br>");
out.println("            </p>");
out.println("            </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i>");
out.println("            </i><a href=\"http://freeboard.adbest.com/KBoard.cgi?db=pennie23\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Auction");
out.println("            Board</font></font></a></font></div>");
out.println("        <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font>");
out.println("        <div align=\"center\">");
out.println("            <p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Mail");
out.println("              To Us</font></font></font></p>");
out.println("            <p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"Logout\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Log");
out.println("              Out </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              </i></font> </p>");
out.println("            </div>");
out.println("        <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font>");
out.println("        <div align=\"center\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("          </i></font><br>");
out.println("        </div>");
out.println("        <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font>");
out.println("<div align=\"right\">");
out.println("          <pre>&nbsp;");
out.println("</pre>");
out.println("        </div>");
out.println("        <pre>&nbsp;");
out.println("</pre>");
out.println("      </td>");
out.println("      <td width=\"63%\" rowspan=\"3\" valign=\"top\" >");
out.println("<form method=\"Post\" action=\"SendAdminSpecToDatabase\" name=\"NewMemberForm\">");
out.println("<div align=\"center\">");
out.println("  <table width=\"80%\" border=\"0\">");
out.println("    <tr bgcolor=\"#CCCCFF\"> ");
out.println("      <td colspan=\"2\" height=\"109\"> ");
out.println("        <div align=\"center\"><font size=\"5\" color=\"#FF3333\">FOR ADMIN ADD STANDARD ");
out.println("          SPECIFICATION </font></div>");
out.println("      </td>");
out.println("    </tr>");

out.println("    <tr bgcolor=\"#9999FF\"> ");
out.println("      <td colspan=\"2\"> ");
out.println("        <div align=\"center\"><font color=\"#0000FF\"><b><font size=\"4\" color=\"#99FF99\">CHOOSE ");
out.println("          SPEC TYPE</font></b></font> ");
out.println("          <select name=\"Spec_type\">");
out.println("            <option>Basic PC</option>");
out.println("            <option>Budget PC</option>");
out.println("            <option>Game PC</option>");
out.println("            <option>Professional PC</option>");
out.println("            <option>Office PC</option>");
out.println("            <option>Graphic PC</option>");
out.println("          </select>");
out.println("        </div>");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#9999FF\"> ");
out.println("      <td colspan=\"2\"> ");
out.println("        <div align=\"center\"><font color=\"#0000FF\"><b><font size=\"4\" color=\"#99FF99\">Price ");
out.println("         </font></b></font> ");
out.println("    <input type=\"text\" name=\"Price\" size=\"8\">");

out.println("        </div>");
out.println("      </td>");
out.println("    </tr>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\">");
out.println("      <td height=\"28\" width=\"49%\">");
out.println("        <div align=\"center\"><font size=\"5\"><b>TYPE DEVICE</b></font></div>");
out.println("      </td>");
out.println("      <td height=\"28\" width=\"51%\">");
out.println("        <div align=\"center\"><font size=\"5\"><b>RECOMMEND FROM SYSTEM</b></font></div>");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td height=\"28\" width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">CPU</font></div>");
out.println("      </td>");
out.println("      <td height=\"28\" width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Cpu\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td height=\"20\" width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">RAM</font></div>");
out.println("      </td>");
out.println("      <td height=\"20\" width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Ram\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">MAINBOARD</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Mainboard\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">HARDDISK</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Harddisk\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">CD-ROM DRIVE</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Cdrom\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">DISPLAY CARD</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Display\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">SOUND CARD</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Soundcard\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">MONITOR</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Monitor\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">MODEM</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Modem\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">FLOPPY DISK </font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Floppy\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">MOUSE</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Mouse\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">KEYBOARD</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Keyboard\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td width=\"49%\"> ");
out.println("        <div align=\"center\"><font size=\"5\">SPEAKER</font></div>");
out.println("      </td>");
out.println("      <td width=\"51%\"> ");
out.println("        <input type=\"text\" name=\"Speaker\" size=\"50\">");
out.println("      </td>");
out.println("    </tr>");
out.println("    <tr bgcolor=\"#FFCCCC\"> ");
out.println("      <td colspan=\"2\"> ");
out.println("        <div align=\"center\"> ");
out.println("          <input type=\"submit\" name=\"Submit\" value=\"SEND TO STANDARD SPEC DATABASE\">");
out.println("        </div>");
out.println("      </td>");
out.println("    </tr>");
out.println("  </table>");
out.println("</div>");
out.println("</form>");
out.println("      </td>");

out.println("    </tr>");
out.println("    <tr> </tr>");
out.println("    <tr> </tr>");
out.println("  </table>");
out.println("  <p>&nbsp; </p>");
out.println("</div>");
out.println("</div></body>");
out.println("</html>");


     out.flush();
    }

}


