
import oracle.sql.*;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.*;
import oracle.jdbc.driver.*;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;
public class Changeinfo extends HttpServlet implements Serializable
{
    public void   doGet(HttpServletRequest req, HttpServletResponse resp)
    throws ServletException, java.io.IOException
  	{
      java.io.PrintWriter out = new java.io.PrintWriter(resp.getOutputStream());
      Connection con = null;
      Statement stmt = null;
      ResultSet rs= null;
      resp.setContentType("text/html");
      HttpSession session = req.getSession(true);
      String username      = (String)session.getValue("username");
      if (username == null)
          resp.sendRedirect("../Pleaselogin.html");
      try
       {
      	  DriverManager.registerDriver (new oracle.jdbc.driver.OracleDriver());
	    }
	    catch (java.sql.SQLException ko){ out.println("Register error");}
      try
     {
      con = DriverManager.getConnection ("jdbc:oracle:thin:@161.246.5.182:1521:Internet","auction", "auction");
      stmt = con.createStatement();
      //////----Find Max spec_id-----///
       String Str_Query ;
       Str_Query =   "select USERNAME,PASSWORD,EMAIL,COMP_NAME,NAME,SURNAME,SEX,BIRTH_DATE,TELEPHONE,AGE,ADDRESS,REGION,PROVINCE,ZIPCODE";
       Str_Query +=  ",TELE_COMP,OCCUPATION,MOBILE,PAGER,PAGENUMBER,TYPE from member where username = '" + username + "'";
     	rs = stmt.executeQuery(Str_Query);
      rs.next();
      out.println("<html>");
out.println("<head>");
out.println("<title> Change Information: CE.KMITL</title>");
out.println("<style><!-- A:link, A:visited { text-decoration: none; color: #ffffff}  A:hover { text-decoration: none; font-weight: underline; color :  #33ccff} // --> </style>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("</head>");
out.println("");
out.println("<body bgcolor=\"#FFFFFF\">");
out.println("<div align=\"right\">");
out.println("<form method=\"Post\" action=\"ConfirmUpdateMember\" name=\"NewMemberForm\">");
out.println("    <div align=\"center\">");
out.println("      <table width=\"100%\" border=\"0\" height=\"164\" align=\"center\" cellpadding=\"4\" cellspacing=\"2\">");
out.println("        <tr>  ");
out.println("          <center>");
out.println("             <img src=\"/picture/ChangeInfo.jpg\" width=\"970\" height=\"98\">");
out.println("          </center>");
out.println("");
out.println("        <tr>");
out.println("");
out.println("        <tr> ");
out.println("          <td rowspan=\"21\" height=\"313\" width=\"20%\" bgcolor=\"#4f4fd2\"  valign=\"top\"> ");
out.println("            <div align=\"center\"><font size=3\" face=\"Arial, Helvetica, sans-serif\"><b><font color=\"#ffcc00\"><i><font size=\"3\"><br>");
out.println("              New Users !!</font></i></font></b><font color=\"#ffcc00\"><i><font size=\"3\"><br>");
out.println("              </font></i></font></font><br>");
out.println("            </div>");
out.println("            <div align=\"center\"> ");
out.println("              <p><font size=\"3\"><a href=\"../register.html\"><font face=\"Arial, Helvetica, sans-serif\">Register</font></a></font> ");
out.println("                <br>");
out.println("                <font size=\"3\"><a href=\"../NewToAuction.html\"><font face=\"Arial, Helvetica, sans-serif\"> ");
out.println("                New to our Auction</font></a></font><br>");
out.println("                <b><font face=\"Arial, Helvetica, sans-serif\" size=\"3\" color=\"#ffcc00\"><i><br>");
out.println("                <br>");
out.println("                Auction Member</i></font></b><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("                </i></font></p>");
out.println("              <p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" ><a href=\"LoginSuccess\"><font size=\"3\" >Home<font face=\"Arial, Helvetica, sans-serif\"> ");
out.println("                </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" ><i><br>");
out.println("                </i><a href=\"Changeinfo\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">C</font><font face=\"Arial, Helvetica, sans-serif\">hange ");
out.println("                Personal Information<br>");
out.println("                </font></font></a></font> <a href=\"Listmember\"><font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\">Member ");
out.println("                Profiles<br>");
out.println("                </font></font></a><a href=\"Listproject\"><font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\">Project ");
out.println("                List </font></font></a><a href=\"OfferSpec\"><font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\"><br>");
out.println("                </font></font></a><a href=\"Ranking\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member Rating ");
out.println("                </font></font></a><a href=\"OfferSpec\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"> ");
out.println("                </font></font></a><br>");
out.println("              </p>");
out.println("              <p><font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("                Buyer</font></b></font></font><br>");
out.println("                <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"GeneralReq\">General ");
out.println("                Requirement</a></font></font><br>");
out.println("                <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddTechReq\">Add ");
out.println("                Technical Requirement <font size=\"2\"><i>(bidding)</i></font></a></font></font><br>");
out.println("                <br>");
out.println("                <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#CCCCCC\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("                Seller</font></b></font></font><br>");
out.println("                <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddSpecification\">Add ");
out.println("                Specification</a></font></font><br>");
out.println("                <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"ListBiddingProject\">Bidding</a></font></font><br>");
out.println("              </p>");
out.println("            </div>");
out.println("          <div align=\"center\"> ");
out.println("            <p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction ");
out.println("              Services</font></b></font></i></font> <br>");
out.println("            </p>");
out.println("          </div>");
out.println("            <div align=\"center\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i> ");
out.println("              </i><a href=\"http://freeboard.adbest.com/KBoard.cgi?db=pennie23\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Auction ");
out.println("              Board</font></font></a></font><");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("           <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"../MailToUs.html\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Mail ");
out.println("              To Us</font></font></a><i></i></font>");
//out.println("          <div align=\"center\"> ");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"Logout\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Log ");
out.println("              Out </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              </i></font> ");
out.println("          </div>");



out.println("          </td>");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\" height=\"38\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\"><b><font size=\"2\">Username</font></b></font></td>");
out.println("          <td width=\"31%\" height=\"38\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("   <input type=hidden Name = \"username\" value = \"" + rs.getString(1) + "\">" );
out.println(             rs.getString(1));
out.println("          <td width=\"24%\" height=\"38\" bgcolor=\"#FFFFFF\"><font color=\"#FF6666\" size=\"2\" face=\"Arial, Helvetica, sans-serif\"><i> ");
out.println("            </i></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\"><b><font size=\"2\">Password</font></b></font></td>");
out.println("          <td width=\"31%\" height=\"27\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"password\" name=\"password\" value="+ rs.getString(2) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"27\" bgcolor=\"#FFD9B3\"><font color=\"#FF6666\" size=\"2\" face=\"Arial, Helvetica, sans-serif\"><i><font size=\"1\">(minimum ");
out.println("            4 characters require)</font></i></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Confirm ");
out.println("            Password </font></b></td>");
out.println("          <td width=\"31%\" height=\"33\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"password\" name=\"confirmpassword\" value="+ rs.getString(2) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"33\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\" height=\"37\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Type</font></b></td>");
out.println("          <td width=\"31%\" height=\"37\" bgcolor=\"#ffb56a\" align=\"left\"> ");
if (rs.getString(20).compareTo("Person") == 0 )
{
out.println("            <input type=\"radio\" name=\"type\" value=\"Person\" checked><font face=\"Arial, Helvetica, sans-serif\" color=\"#330033\">Person</font><font face=\"Arial, Helvetica, sans-serif\" color=\"#000000\">");
out.println("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"radio\" name=\"type\" value=\"Company\"> <font color=\"#330033\">Company *</font></font>");
}
else
{
out.println("            <input type=\"radio\" name=\"type\" value=\"Person\" checked><font face=\"Arial, Helvetica, sans-serif\" color=\"#330033\">Person</font><font face=\"Arial, Helvetica, sans-serif\" color=\"#000000\">");
out.println("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"radio\" name=\"type\" value=\"Company\" checked> <font color=\"#330033\">Company *</font></font>");
}
out.println("          </td>");
out.println("          <td width=\"24%\" height=\"37\" bgcolor=\"#ffd9b3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#333333\"><i><font size=\"1\">If ");
out.println("            you are company type.. Please enter the name and details of the employee ");
out.println("            whom we can contact with.</font></i></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Company ");
out.println("            Name </font></b></td>");
out.println("          <td width=\"31%\" height=\"33\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"companyname\" value="+ rs.getString(4) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"33\" bgcolor=\"#ffd9b3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#333333\"><i><font color=\"#FF6666\" size=\"2\" face=\"Arial, Helvetica, sans-serif\"><i><font size=\"1\">(For ");
out.println("            comapny only)</font></i></font><font size=\"1\"> </font></i></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\" height=\"40\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Company ");
out.println("            Type </font></b></td>");
out.println("          <td width=\"31%\" height=\"40\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <select name=\"select\" size=\"1\">");
out.println("              <option selected>Banking / Finance / Real estate </option>");
out.println("              <option>Comuter-related IS,MIS,DP</option>");
out.println("              <option>Computer-related Internet</option>");
out.println("              <option>Computer-related Hardware</option>");
out.println("              <option>Computer-related Software </option>");
out.println("              <option>Education / Research </option>");
out.println("              <option>Engineering / Construction</option>");
out.println("              <option>Manufacturing / Distribution </option>");
out.println("              <option>Business supplier or services </option>");
out.println("              <option>Entertainment / Media / Publishing </option>");
out.println("              <option>Hospitality-travel / Accommodations</option>");
out.println("              <option>Consumer retail / Wholesale </option>");
out.println("              <option>nonprofit / Membership organizations </option>");
out.println("              <option>Government </option>");
out.println("              <option>Legal services</option>");
out.println("            </select>");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"33\" bgcolor=\"#ffd9b3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#333333\"><i><font color=\"#FF6666\" size=\"2\" face=\"Arial, Helvetica, sans-serif\"><i><font size=\"1\">(For ");
out.println("            comapny only)</font></i></font><font size=\"1\"> </font></i></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\" height=\"35\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Name</font></b></td>");
out.println("          <td width=\"31%\" height=\"35\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"name\" value="+ rs.getString(5) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"35\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Surname</font></b></td>");
out.println("          <td width=\"31%\" height=\"34\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"surname\" value="+ rs.getString(6) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"34\" bgcolor=\"#FFFFFF\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#333333\"></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">e-mail</font></b></td>");
out.println("          <td width=\"31%\" height=\"20\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"email\" value="+ rs.getString(3) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"20\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\" height=\"39\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Gender</font></b></td>");
out.println("          <td width=\"31%\" height=\"39\" bgcolor=\"#ffb56a\" align=\"left\"> ");
if (rs.getString(7).compareTo("Male") == 0 )
{
out.println("           <input type=\"radio\" name=\"sex\" value=\"Male\" checked><font face=\"Arial, Helvetica, sans-serif\" color=\"#330033\">Male</font><font face=\"Arial, Helvetica, sans-serif\" color=\"#006666\">");
out.println("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"radio\" name=\"sex\" value=\"Female\"><font color=\"#330033\">Female  </font></font>");
}
else
{
out.println(" <input type=\"radio\" name=\"sex\" value=\"Male\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#330033\">Male</font><font face=\"Arial, Helvetica, sans-serif\" color=\"#006666\">");
out.println("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"radio\" name=\"sex\" value=\"Female\" checked><font color=\"#330033\">Female  </font></font>");
}
out.println("          </td>");
out.println("          <td width=\"24%\" height=\"39\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\" height=\"39\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Birth_date</font></b></td>");
out.println("          <td width=\"31%\" height=\"39\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <select name=\"birthdate\" size=\"1\">");
out.println("              <option selected>01</option>");
out.println("              <option>02</option>");
out.println("              <option>03</option>");
out.println("              <option>04</option>");
out.println("              <option>05</option>");
out.println("              <option>06</option>");
out.println("              <option>07</option>");
out.println("              <option>08</option>");
out.println("              <option>09</option>");
out.println("              <option>10</option>");
out.println("              <option>11</option>");
out.println("              <option>12</option>");
out.println("              <option>13</option>");
out.println("              <option>14</option>");
out.println("              <option>15</option>");
out.println("              <option>16</option>");
out.println("              <option>17</option>");
out.println("              <option>18</option>");
out.println("              <option>19</option>");
out.println("              <option>20</option>");
out.println("              <option>21</option>");
out.println("              <option>22</option>");
out.println("              <option>23</option>");
out.println("              <option>24</option>");
out.println("              <option>25</option>");
out.println("              <option>26</option>");
out.println("              <option>27</option>");
out.println("              <option>28</option>");
out.println("              <option>29</option>");
out.println("              <option>30</option>");
out.println("              <option>31</option>");
out.println("            </select>");
out.println("            / ");
out.println("            <select name=\"birthmonth\" size=\"1\">");
out.println("              <option selected>01</option>");
out.println("              <option>02</option>");
out.println("              <option>03</option>");
out.println("              <option>04</option>");
out.println("              <option>05</option>");
out.println("              <option>06</option>");
out.println("              <option>07</option>");
out.println("              <option>08</option>");
out.println("              <option>09</option>");
out.println("              <option>10</option>");
out.println("              <option>11</option>");
out.println("              <option>12</option>");
out.println("            </select>");
out.println("            / ");
out.println("            <select name=\"birthyear\" size=\"1\">");
out.println("              <option selected>1965</option>");
out.println("              <option>1966</option>");
out.println("              <option>1967</option>");
out.println("              <option>1968</option>");
out.println("              <option>1969</option>");
out.println("              <option>1970</option>");
out.println("              <option>1971</option>");
out.println("              <option>1972</option>");
out.println("              <option>1973</option>");
out.println("              <option>1974</option>");
out.println("              <option>1975</option>");
out.println("              <option>1976</option>");
out.println("              <option>1977</option>");
out.println("              <option>1978</option>");
out.println("              <option>1979</option>");
out.println("              <option>1980</option>");
out.println("              <option>1981</option>");
out.println("              <option>1982</option>");
out.println("              <option>1983</option>");
out.println("              <option>1984</option>");
out.println("              <option>1985</option>");
out.println("              <option>1986</option>");
out.println("              <option>1987</option>");
out.println("              <option>1988</option>");
out.println("              <option>1989</option>");
out.println("              <option>1990</option>");
out.println("              <option>1991</option>");
out.println("              <option>1992</option>");
out.println("              <option>1993</option>");
out.println("              <option>1994</option>");
out.println("              <option>1995</option>");
out.println("              <option>1996</option>");
out.println("              <option>1997</option>");
out.println("              <option>1998</option>");
out.println("              <option>1999</option>");
out.println("            </select>");
out.println("          </td>");
out.println("          <td width=\"24%\" height=\"39\" bgcolor=\"#ffd9b3\"><font color=\"#FF6666\" size=\"2\" face=\"Arial, Helvetica, sans-serif\"><i><font size=\"1\">(DD/MM/YYYY)</font></i></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\" height=\"34\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Age</font></b></td>");
out.println("          <td width=\"31%\" height=\"34\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <select name=\"age\" size=\"1\">");
out.println("              <option selected>Under 18</option>");
out.println("              <option>19 - 25</option>");
out.println("              <option>26 - 35</option>");
out.println("              <option>36 - 45</option>");
out.println("              <option>Upper 45</option>");
out.println("            </select>");
out.println("          </td>");
out.println("          <td width=\"24%\" height=\"34\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Address ");
out.println("            </font></b></td>");
out.println("          <td width=\"31%\" height=\"23\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"address\" value="+ rs.getString(11) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"23\" bgcolor=\"#ffd9b3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#333333\"><i><font size=\"1\">If ");
out.println("            you are company type.. Enter your company location.</font></i></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Region</font></b></td>");
out.println("          <td width=\"31%\" height=\"31\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"region\" value="+ rs.getString(12) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"31\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Province</font></b></td>");
out.println("          <td width=\"31%\" height=\"33\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <select name=\"province\" size=\"1\" value="+ rs.getString(13) + ">");
out.println("              <option selected>Bangkok </option>");
out.println("              <option>Ayuttaya </option>");
out.println("              <option>Chaing Mai </option>");
out.println("              <option>Chaing Rai</option>");
out.println("              <option>Mae Hong Sorn</option>");
out.println("              <option>Lumpang</option>");
out.println("              <option>Rayong</option>");
out.println("              <option>Ranong</option>");
out.println("              <option>Sukhothai</option>");
out.println("              <option>Ubonratchathanee</option>");
out.println("              <option>Udornthanee</option>");
out.println("              <option>Roi Edd</option>");
out.println("              <option>Nan</option>");
out.println("              <option>Prae</option>");
out.println("              <option>Trad</option>");
out.println("              <option>Tark</option>");
out.println("              <option>Rachaburi</option>");
out.println("              <option>Saraburi</option>");
out.println("              <option>Chachungsao</option>");
out.println("              <option>Kumpangped</option>");
out.println("            </select>");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"33\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Zip ");
out.println("            Code </font></b></td>");
out.println("          <td width=\"31%\" height=\"23\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"zipcode\" maxlength=\"5\" size=\"7\" value="+ rs.getString(14) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"23\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Telephone_number</font></b></td>");
out.println("          <td width=\"31%\" height=\"23\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"telephone\" value="+ rs.getString(9) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"23\" bgcolor=\"#ffd9b3\"><font color=\"#FF6666\" size=\"2\" face=\"Arial, Helvetica, sans-serif\"><i><font size=\"1\">(Please ");
out.println("            enter telephone_number that we can contact you)</font></i></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Telephone_No ");
out.println("            (company) </font></b></td>");
out.println("          <td width=\"31%\" height=\"35\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"telephonecompany\" value="+ rs.getString(15) + ">");
out.println("            <font color=\"#330033\">*</font> </td>");
out.println("          <td width=\"24%\" height=\"35\" bgcolor=\"#ffd9b3\"><font color=\"#FF6666\" size=\"2\" face=\"Arial, Helvetica, sans-serif\"><i><font size=\"1\">(For ");
out.println("            company only)</font></i></font></td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Mobile_Number ");
out.println("            </font></b></td>");
out.println("          <td width=\"31%\" height=\"23\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <input type=\"text\" name=\"mobilenumber\" value="+ rs.getString(17) + ">");
out.println("          </td>");
out.println("          <td width=\"24%\" height=\"23\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Pager</font></b></td>");
out.println("          <td width=\"31%\" height=\"25\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <select name=\"pager\" size=\"1\">");
out.println("              <option>142</option>");
out.println("              <option selected>152</option>");
out.println("              <option>162</option>");
out.println("              <option>1188</option>");
out.println("              <option>1144</option>");
out.println("              <option>1500</option>");
out.println("            </select>");
out.println("            <input type=\"text\" name=\"pagernumber\" size=\"9\" maxlength=\"7\" value=" + rs.getString(19) + ">");
out.println("          </td>");
out.println("          <td width=\"24%\" height=\"25\" bgcolor=\"#FFFFFF\">&nbsp;</td>");
out.println("        </tr>");
out.println("        <tr> ");
out.println("          <td bgcolor=\"#ffb56a\" align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" color=\"#330099\" size=\"2\">Occupation ");
out.println("            </font></b></td>");
out.println("          <td width=\"31%\" height=\"34\" bgcolor=\"#ffb56a\" align=\"left\"> ");
out.println("            <select name=\"occupation\" size=\"1\">");
out.println("              <option selected>Accounting / Finance </option>");
out.println("              <option>Computer related (Internet) </option>");
out.println("              <option>Computer related (other)</option>");
out.println("              <option>Consulting </option>");
out.println("              <option>Customer service / support </option>");
out.println("              <option>Education / Training </option>");
out.println("              <option>Engineering </option>");
out.println("              <option>Executive / Senior management </option>");
out.println("              <option>General administrative / supervisory </option>");
out.println("              <option>Government / Military </option>");
out.println("              <option>Homemaker</option>");
out.println("              <option>Manufacturing / Production / Operations </option>");
out.println("              <option>Professional (medical , legal , etc.) </option>");
out.println("              <option>Research and Development </option>");
out.println("              <option>Retired</option>");
out.println("              <option>Sales / Marketing / Advertising </option>");
out.println("              <option>Self-employed / Owner</option>");
out.println("              <option>Student</option>");
out.println("              <option>Tradesman / Craftsman</option>");
out.println("              <option>Unemployed / Between Jobs)</option>");
out.println("              <option>Other</option>");
out.println("            </select>");
out.println("          </td>");
out.println("          <td width=\"24%\" height=\"34\" bgcolor=\"#FFFFFF\"><font color=\"#FF6666\" size=\"2\" face=\"Arial, Helvetica, sans-serif\"><i></i></font></td>");
out.println("        </tr>");
out.println("      </table>");
out.println("      <img src=\"bar.gif\" width=\"550\" height=\"2\"><br>");
out.println("      <input type=\"submit\" name=\"RegisterSubmit\" value=\"Submit\">");
out.println("      <input type=\"reset\" name=\"RegisterClear\" value=\"Clear\">");
out.println("      <br>");
out.println("    </div>");
out.println("  </form>");
out.println("  <p align=\"left\">&nbsp;</p>");
out.println("</div>");
out.println("</body>");
out.println("</html>");
      }
      catch (Exception ex)
      {
      	 out.println("Exception");
	      ex.printStackTrace(out);
	    }
     finally
     {
	     try
	     { if (rs != null)  {rs.close();}
         if (stmt != null){stmt.close();}
  		   if (con != null) {con.close();}
       }
	     catch (Exception ex){}
	   }
out.flush();
    }

}


