
import oracle.sql.*;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.*;
import oracle.jdbc.driver.*;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;
public class ConfirmSellerGeneralSpec extends HttpServlet implements Serializable
{
    public synchronized void   doPost(HttpServletRequest req, HttpServletResponse resp)
    throws ServletException, java.io.IOException
  	{
      java.io.PrintWriter out = new java.io.PrintWriter(resp.getOutputStream());
      Connection con = null;
      Statement stmt = null;
      ResultSet rs= null;
      resp.setContentType("text/html");
      HttpSession session = req.getSession(true);
      Specification Seller_General_Spec = new Specification();
      Specification Standard_spec = (Specification)session.getValue("Standard_spec");
      String username = (String)session.getValue("username") ;
      String companyname = (String)session.getValue("companyname");

      String Cpu          = req.getParameter("Cpu");
      String Ram          = req.getParameter("Ram");
      String Harddisk     = req.getParameter("Harddisk");
      String Cdrom        = req.getParameter("Cdrom");
      String Mainboard    = req.getParameter("Mainboard");
      String Display_card = req.getParameter("Display_card");
      String Sound_card   = req.getParameter("Sound_card");
      String Monitor      = req.getParameter("Monitor");
      String Modem        = req.getParameter("Modem");
      String Floppy_disk  = req.getParameter("Floppy_disk");
      String Speaker      = req.getParameter("Speaker");
      String Mouse        = req.getParameter("Mouse");
      String Keyboard     = req.getParameter("Keyboard");

      String Spec_type    = req.getParameter("Spec_type");
      String Price        = req.getParameter("Seller_price");
      String Detail       = req.getParameter("Detail");


      Part   part   = new Part() ;
      Seller_General_Spec.Listpart.addElement(part);
      Seller_General_Spec.name = username ;
      Seller_General_Spec.company_name = companyname ;
      Seller_General_Spec.Maxprice   = Integer.parseInt(Price) ;
      Seller_General_Spec.GetPart(0).Partname        =  Spec_type;
      Seller_General_Spec.GetPart(0).Partdescription = "Computer Standard Spec";
      for (int row = 0 ; row < 13 ; row++)
      {
         Device device = new Device(1) ;
         Seller_General_Spec.GetPart(0).Listdevice.addElement(device);
      }
      Seller_General_Spec.GetPart(0).GetDevice(0).Data[0]  = Cpu;
      Seller_General_Spec.GetPart(0).GetDevice(1).Data[0]  = Ram;
      Seller_General_Spec.GetPart(0).GetDevice(2).Data[0]  = Mainboard ;
      Seller_General_Spec.GetPart(0).GetDevice(3).Data[0]  = Harddisk ;
      Seller_General_Spec.GetPart(0).GetDevice(4).Data[0]  = Cdrom ;
      Seller_General_Spec.GetPart(0).GetDevice(5).Data[0]  = Display_card;
      Seller_General_Spec.GetPart(0).GetDevice(6).Data[0]  = Sound_card;
      Seller_General_Spec.GetPart(0).GetDevice(7).Data[0]  = Monitor ;
      Seller_General_Spec.GetPart(0).GetDevice(8).Data[0]  = Modem ;
      Seller_General_Spec.GetPart(0).GetDevice(9).Data[0]  = Floppy_disk;
      Seller_General_Spec.GetPart(0).GetDevice(10).Data[0] = Mouse ;
      Seller_General_Spec.GetPart(0).GetDevice(11).Data[0] = Keyboard;
      Seller_General_Spec.GetPart(0).GetDevice(12).Data[0] = Speaker;

      Seller_General_Spec.GetPart(0).GetDevice(0).Type_Device  = "CPU" ;
      Seller_General_Spec.GetPart(0).GetDevice(1).Type_Device  = "RAM" ;
      Seller_General_Spec.GetPart(0).GetDevice(2).Type_Device  = "MAINBOARD" ;
      Seller_General_Spec.GetPart(0).GetDevice(3).Type_Device  = "HARDDISK" ;
      Seller_General_Spec.GetPart(0).GetDevice(4).Type_Device  = "CDROM" ;
      Seller_General_Spec.GetPart(0).GetDevice(5).Type_Device  = "DISPLAY CARD" ;
      Seller_General_Spec.GetPart(0).GetDevice(6).Type_Device  = "SOUND CARD" ;
      Seller_General_Spec.GetPart(0).GetDevice(7).Type_Device  = "MONITOR" ;
      Seller_General_Spec.GetPart(0).GetDevice(8).Type_Device  = "MODEM" ;
      Seller_General_Spec.GetPart(0).GetDevice(9).Type_Device  = "FLOPPY DISK" ;
      Seller_General_Spec.GetPart(0).GetDevice(10).Type_Device = "MOUSE" ;
      Seller_General_Spec.GetPart(0).GetDevice(11).Type_Device = "KEYBOARD" ;
      Seller_General_Spec.GetPart(0).GetDevice(12).Type_Device = "SPEAKER" ;

            out.println("<html>");
out.println("<head>");
out.println("<title>Internet Auction : CE.KMITL</title>");
out.println("<style><!-- A:link, A:visited { text-decoration: none; color: #ffffff}  A:hover { text-decoration: none; font-weight: underline; color :  #33ccff} // --> </style>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("</head>");
out.println("");
out.println("<body bgcolor=\"#FFFFFF\" link=\"#FF9933\" vlink=\"#3399CC\" alink=\"#FF9966\" >");
out.println("<div align=\"center\">");
out.println("  <p>&nbsp;</p>");
out.println("  <div id=\"Layer1\" style=\"position:absolute; width:970px; height:100px; z-index:1; left: 17px; top: 22px\"> ");
out.println("    <table width=\"100%\" border=\"0\" height=\"400\">");
out.println("      <tr> ");
out.println("        <div align=\"center\"><img src=\"/picture/AddSpecification.jpg\" width=\"970\" height=\"98\"></div>");
out.println("      </tr>");
out.println("      <tr> ");
out.println("        <td rowspan=\"3\" height=\"137\" width=\"15%\" bgcolor=\"#4F4FD2\" valign=\"top\"> ");
out.println("          <div align=\"center\"> ");
out.println("            <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><br>");
out.println("              </font></i></font></font></p>");
out.println("            <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><font color=\"#CC0000\"><b><font size=\"3\" color=\"#FFCC00\">New ");
out.println("              Users !!</font></b></font><br>");
out.println("              </font></i></font></font><br>");
out.println("            </p>");
out.println("          </div>");
out.println("          <div align=\"center\"> ");
out.println("            <p><font size=\"3\"><a href=\"../register.html\"><font face=\"Arial, Helvetica, sans-serif\">Register</font></a></font> ");
out.println("              <br>");
out.println("              <font size=\"3\"><a href=\"../NewToAuction.html\"><font face=\"Arial, Helvetica, sans-serif\"> ");
out.println("              New to our Auction</font></a></font> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              </i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              <br>");
out.println("              <font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction ");
out.println("              Member</font></b></font></i></font></p>");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"LoginSuccess\"><font size=\"3\" >Home<font face=\"Arial, Helvetica, sans-serif\"> ");
out.println("            </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i><a href=\"Changeinfo\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Change ");
out.println("            Personal Information </font><font  face=\"Arial, Helvetica, sans-serif\"> ");
out.println("            </font></font> </a><i> </i></font> </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"></font><a href=\"Listmember\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member ");
out.println("            Profile<br>");
out.println("            </font></font></a><a href=\"Listproject\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Project ");
out.println("            List</font></font></a><a href=\"OfferSpec\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><br>");
out.println("            </font></font></a><a href=\"Ranking\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member Rating</font></font></a> ");
out.println("            <br>");
out.println("            <br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("            Buyer</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"GeneralReq\">General ");
out.println("            Requirement</a></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddTechReq\">Add ");
out.println("            Technical Requirement <font size=\"2\"><i>(bidding)</i></font></a></font></font><br>");
out.println("            <br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#CCCCCC\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("            Seller</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddSpecification\">Add ");
out.println("            Specification</a></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"ListBiddingProject\">Bidding</a></font></font><br>");
out.println("            <br>");
out.println("          </div>");
out.println("          <div align=\"center\"> ");
out.println("            <p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction ");
out.println("              Services</font></b></font></i></font> <br>");
out.println("            </p>");
out.println("          </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i> ");
out.println("            </i><a href=\"http://freeboard.adbest.com/KBoard.cgi?db=pennie23\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Auction ");
out.println("            Board</font></font></a></font></div>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("          <div align=\"center\"> ");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Mail ");
out.println("              To Us</font></font></font>");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"Logout\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Log ");
out.println("              Out </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              </i></font> ");
out.println("          </div>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("          <div align=\"center\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i></font><br>");
out.println("          </div>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("          <div align=\"right\"> ");
out.println("            <pre>&nbsp;");
out.println("");
out.println("</pre>");
out.println("          </div>");
out.println("          <pre>&nbsp;");
out.println("");
out.println("");
out.println("");
out.println("</pre>");
out.println("        </td>");
out.println("<form method=\"Post\" action=\"SendSellerGeneralSpecToDatabase\" name=\"NewMemberForm\">");
out.println("        <td width=\"63%\" rowspan=\"3\" valign=\"top\"\"> ");
out.println("          <p>&nbsp;</p>");
out.println("          <p><font size=\"4\"><b><font size=\"5\"> Confirm your general specification </font> </b></font></p>");
out.println(" <input type=hidden Name = \"Spec_type\" value = \"" + Spec_type + "\">" );
out.println("          <table width=\"100%\" border=\"0\">");
out.println("            <tr bgcolor=\"#ffb56a\"> ");
out.println("              <td width=\"33%\"><font size=\"4\"><b><font size=\"5\"> <font size=\"4\">Seller ");
out.println("                name </font></font></b></font></td>");
out.println("              <td colspan=\"2\"> <font size=\"4\" color=\"#0000ff\"><b> " + Seller_General_Spec.name + " </b></font> </td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#FFCC99\"> ");
out.println("              <td width=\"33%\"><font size=\"4\"><b><font size=\"5\"> <font size=\"4\">Seller ");
out.println("                company </font></font></b></font></td>");
out.println("              <td colspan=\"2\"> <font size=\"4\" color=\"#0000ff\"> <b>" + Seller_General_Spec.company_name + " </b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#ffb56a\"> ");
out.println("              <td width=\"33%\"><font size=\"4\"><b><font size=\"5\"><font size=\"4\">Type ");
out.println("                of spec</font></font></b></font></td>");
out.println("              <td colspan=\"2\"><font size=\"4\" color=\"#0000ff\"><b>  " + Spec_type + "</b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#FFCC99\"> ");
out.println("              <td width=\"33%\"><font size=\"4\"><b><font size=\"5\"><font size=\"4\">Your ");
out.println("                price</font></font></font></td>");
out.println("              <td width=\"21%\"><br><b> ");
out.println(Price);
out.println("      </b> <font size=\"4\">     Baht  </font></td>");
out.println("              <td width=\"35%\"><font color=\"#993366\" size =\"4\"><b><i>   Recommended price = " + Seller_General_Spec.Maxprice + "</i></b></font> </td>");
out.println("            </tr>");
out.println("          </table>");
out.println("          <p>&nbsp;</p>");
out.println("          <table width=\"100%\" border=\"0\">");
out.println("            <tr> ");
out.println("              <td colspan=\"3\" height=\"28\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"><font size=\"4\"><b><font size=\"5\"><font size=\"4\" color=\"#FF0000\">Your ");
out.println("                  specification </font></font></b></font></div>");
out.println("              </td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"><font size=\"4\"><b><font size=\"5\"><font size=\"4\" color=\"#0000FF\">Device</font></font></b></font></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"><b><font size=\"4\" color=\"#0000FF\">Specification</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"><b><font size=\"4\" color=\"#0000FF\">Recommend ");
out.println("                  </font></b></div>");
out.println("              </td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">CPU</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> <b>");
out.println(Seller_General_Spec.GetPart(0).GetDevice(0).Data[0]);
out.println("</b>              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(0).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#E0F1F1\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">RAM</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#E0F1F1\"><b> ");
out.println(Seller_General_Spec.GetPart(0).GetDevice(1).Data[0]);
out.println("</b>              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#E0F1F1\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(1).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">MAINBOARD</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> <b>");
out.println(Seller_General_Spec.GetPart(0).GetDevice(2).Data[0]);
out.println("</b>              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(2).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">HARDDISK</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"> <b>");
out.println(Seller_General_Spec.GetPart(0).GetDevice(3).Data[0]);
out.println("</b>              </td>");
out.println("              <td width=\"43%\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(3).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">CDROM</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"><b> ");
out.println(Seller_General_Spec.GetPart(0).GetDevice(4).Data[0]);
out.println("</b>              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(4).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">DISPLAY CARD</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"> <b>");
out.println(Seller_General_Spec.GetPart(0).GetDevice(5).Data[0]);
out.println("  </b>            </td>");
out.println("              <td width=\"43%\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(5).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">SOUND CARD</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"><b> ");
out.println(Seller_General_Spec.GetPart(0).GetDevice(6).Data[0]);
out.println("   </b>           </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(6).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">MONITOR</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"><b> ");
out.println(Seller_General_Spec.GetPart(0).GetDevice(7).Data[0]);
out.println(" </b>             </td>");
out.println("              <td width=\"43%\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(7).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">FLOPPY DISK</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> <b>");
out.println(Seller_General_Spec.GetPart(0).GetDevice(9).Data[0]);
out.println(" </b>             </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(9).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">MODEM</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"> <b>");
out.println(Seller_General_Spec.GetPart(0).GetDevice(8).Data[0]);
out.println(" </b>             </td>");
out.println("              <td width=\"43%\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(8).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">MOUSE</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"><b> ");
out.println(Seller_General_Spec.GetPart(0).GetDevice(10).Data[0]);
out.println("  </b>            </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(10).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">KEYBOARD</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"><b> ");
out.println(Seller_General_Spec.GetPart(0).GetDevice(11).Data[0]);
out.println("</b>              </td>");
out.println("              <td width=\"43%\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(11).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">SPEAKER</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"><b> ");
out.println(Seller_General_Spec.GetPart(0).GetDevice(12).Data[0]);
out.println("</b>              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(12).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\">   <div align=\"center\"><b>More detail</b></td></div>");
out.println("              <td colspan=\"2\"> <b>");
out.println(Detail);
out.println("</b>              </td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td colspan=\"3\" height=\"24\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"></div>");
out.println("                <div align=\"center\"> ");
out.println("                  <input type=\"submit\" name=\"Submit\" value=\"SEND THIS SPEC\">");
out.println("                </div>");
out.println("              </td>");
out.println("            </tr>");
out.println("          </table>");
out.println("          <p><font size=\"4\"><b><font size=\"5\"><font size=\"4\"> </font></font></b></font></p>");
out.println("          <p>&nbsp;</p>");
out.println("        </td>");
out.println("      </tr>");
out.println("      <tr> </tr>");
out.println("      <tr> </tr>");
out.println(" <input type=hidden Name = \"Spec_type\" value = \"" + Spec_type + "\">" );
out.println(" <input type=hidden Name = \"Seller_price\" value = \"" + Price  + "\">" );
out.println(" <input type=hidden Name = \"Detial\" value = \"" + Detail + "\">" );
session.putValue("Seller_spec",Seller_General_Spec);

out.println("</form>");
out.println("    </table>");


out.println("    <p>&nbsp; </p>");
out.println("</div>");
out.println("</div></body>");
out.println("</html>");

out.flush();

    }

}
