import  java.io.*;
import  javax.servlet.*;
import  javax.servlet.http.*;
import  java.util.*;
public class GeneralReq extends HttpServlet
{
    public void   doGet(HttpServletRequest req, HttpServletResponse resp)
    throws ServletException, java.io.IOException
  	{
	  java.io.PrintWriter out = new java.io.PrintWriter(resp.getOutputStream());
    String Str_Query ;
    HttpSession session = req.getSession(true);
    String username = (String)session.getValue("username");
    resp.setContentType("text/html");
    if (username == null)
          resp.sendRedirect("../Pleaselogin.html");
    out.println("<html>");
out.println("<head>");
out.println("<title>Internet Auction : CE.KMITL</title>");
out.println("<style><!-- A:link, A:visited { text-decoration: none; color: #ffffff}  A:hover { text-decoration: none; font-weight: underline; color :  #33ccff} // --> </style>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("</head>");
out.println("");
out.println("<body bgcolor=\"#FFFFFF\" link=\"#FF9933\" vlink=\"#3399CC\" alink=\"#FF9966\" >");
out.println("<div align=\"center\">");
out.println("  <p>&nbsp;</p>");
out.println("  <div id=\"Layer1\" style=\"position:absolute; width:970px; height:100px; z-index:1; left: 17px; top: 22px\"> ");
out.println("    <table width=\"99%\" border=\"0\" height=\"400\">");
out.println("      <tr> ");
out.println("        <div align=\"center\"><img src=\"/picture/AuctionBanner.jpg\" width=\"970\" height=\"98\"></div>");
out.println("      </tr>");
out.println("      <tr> ");
out.println("        <td rowspan=\"3\" height=\"137\" width=\"15%\" bgcolor=\"#4F4FD2\" valign=\"top\"> ");
out.println("          <div align=\"center\"> ");
out.println("            <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><br>");
out.println("              </font></i></font></font></p>");
out.println("            <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><font color=\"#CC0000\"><b><font size=\"3\" color=\"#FFCC00\">New ");
out.println("              Users !!</font></b></font><br>");
out.println("              </font></i></font></font><br>");
out.println("            </p>");
out.println("          </div>");
out.println("          <div align=\"center\"> ");
out.println("            <p><font size=\"3\"><a href=\"../register.html\"><font face=\"Arial, Helvetica, sans-serif\">Register</font></a></font> ");
out.println("              <br>");
out.println("              <font size=\"3\"><a href=\"../NewToAuction.html\"><font face=\"Arial, Helvetica, sans-serif\"> ");
out.println("              New to our Auction</font></a></font> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              </i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              <br>");
out.println("              <font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction ");
out.println("              Member</font></b></font></i></font></p>");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"LoginSuccess\"><font size=\"3\" >Home<font face=\"Arial, Helvetica, sans-serif\"> ");
out.println("            </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i><a href=\"Changeinfo\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Change ");
out.println("            Personal Information </font><font  face=\"Arial, Helvetica, sans-serif\"> ");
out.println("            </font></font> </a><i> </i></font> </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"></font><a href=\"Listmember\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member ");
out.println("            Profile<br>");
out.println("            </font></font></a><a href=\"Listproject\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Project ");
out.println("            List</font></font></a><a href=\"OfferSpec\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><br>");
out.println("            </font></font></a><a href=\"Ranking\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member Rating</font></font></a> ");
out.println("            <br>");
out.println("            <br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("            Buyer</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"GeneralReq\">General ");
out.println("            Requirement</a></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddTechReq\">Add ");
out.println("            Technical Requirement <font size=\"2\"><i>(bidding)</i></font></a></font></font><br>");
out.println("            <br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#CCCCCC\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("            Seller</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddSpecification\">Add ");
out.println("            Specification</a></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"ListBiddingProject\">Bidding</a></font></font><br>");
out.println("            <br>");
out.println("          </div>");
out.println("          <div align=\"center\"> ");
out.println("            <p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction ");
out.println("              Services</font></b></font></i></font> <br>");
out.println("            </p>");
out.println("          </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i> ");
out.println("            </i><a href=\"http://freeboard.adbest.com/KBoard.cgi?db=pennie23\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Auction ");
out.println("            Board</font></font></a></font></div>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("          <div align=\"center\"> ");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"../Mailtous.html\">Mail ");
out.println("              To Us</A></font></font></font><br>");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"Logout\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Log ");
out.println("              Out </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              </i></font> ");
out.println("          </div>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("          <div align=\"center\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i></font><br>");
out.println("          </div>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("          <div align=\"right\"> ");
out.println("            <pre>&nbsp;");
out.println("");
out.println("</pre>");
out.println("          </div>");
out.println("          <pre>&nbsp;");
out.println("");
out.println("");
out.println("");
out.println("</pre>");
out.println("        </td>");
out.println("        <td width=\"63%\" rowspan=\"3\" valign=\"top\"\"> ");
out.println("          <p><font size=\"+3\">Welcome " + username + " </font></p>");
out.println("          <p><font color=\"#000000\" size=\"4\"><i><b>Choose Policy Spec that you ");
out.println("            want from table list...</b></i></font><br>");
out.println("            <font color=\"#000000\" size=\"4\"><i><b> it 'll be your requirement and ");
out.println("            we'll match seller spec which has the same policy with your spec...</b></i></font><font color=\"#000000\" size=\"4\"><i><b> ");
out.println("            </b></i></font> </p>");
out.println("          <table width=\"99%\" border=\"0\">");
out.println("            <tr bgcolor=\"#89D8D8\"> ");
out.println("              <td colspan=\"3\" height=\"40\"> ");
out.println("                <div align=\"center\"><font color=\"#000000\" size=\"4\"><i><b><font color=\"#FF3333\">Type ");
out.println("                  of computer spec Policy</font></b></i></font></div>");
out.println("              </td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#89D8D8\"> ");
out.println("              <td width=\"19%\" height=\"19\"> ");
out.println("                <div align=\"center\"><b><font color=\"#000066\">Type</font></b></div>");
out.println("              </td>");
out.println("              <td colspan=\"2\" bgcolor=\"#89D8D8\" height=\"19\"> ");
out.println("                <div align=\"center\"></div>");
out.println("                <div align=\"center\"><font color=\"#000066\"><b>Policy Detail</b></font></div>");
out.println("              </td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#C6E3E3\"> ");
out.println("              <td height=\"28\" width=\"19%\"> ");
out.println("                <div align=\"center\"><font color=\"#FF0033\"><b><font color=\"#000000\" size=\"4\">Budget ");
out.println("                  PC</font></b></font></div>");
out.println("              </td>");
out.println("              <td height=\"28\" colspan=\"2\">The computer with essential devices ");
out.println("                only and low price for general user.</td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td height=\"27\" width=\"19%\"> ");
out.println("                <div align=\"center\"><font color=\"#009900\"><b><font color=\"#000000\" size=\"4\">Basic ");
out.println("                  PC</font></b></font></div>");
out.println("              </td>");
out.println("              <td height=\"27\" colspan=\"2\">The computer with essential devices. ");
out.println("              </td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#C6E3E3\"> ");
out.println("              <td height=\"27\" width=\"19%\"> ");
out.println("                <div align=\"center\"><b><font color=\"#000000\" size=\"4\">Game PC</font></b></div>");
out.println("              </td>");
out.println("              <td height=\"27\" colspan=\"2\" bgcolor=\"#C6E3E3\">Computer specification ");
out.println("                for user who want to use for play game .</td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td height=\"26\" width=\"19%\"> ");
out.println("                <div align=\"center\"><b><font color=\"#000000\" size=\"4\">Professional ");
out.println("                  PC</font></b></div>");
out.println("              </td>");
out.println("              <td height=\"26\" colspan=\"2\">This computer specification is used ");
out.println("                for multi purpose etc,play game multimedia.</td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#C6E3E3\"> ");
out.println("              <td height=\"29\" width=\"19%\"> ");
out.println("                <div align=\"center\"><b><font color=\"#000000\" size=\"4\">Office PC</font></b></div>");
out.println("              </td>");
out.println("              <td height=\"29\" colspan=\"2\">This specification is used for working ");
out.println("                in office it doesn't have multimedia device.</td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td height=\"37\" width=\"19%\"> ");
out.println("                <div align=\"center\"><b><font color=\"#000000\" size=\"4\">Graphic ");
out.println("                  PC</font></b></div>");
out.println("              </td>");
out.println("              <td height=\"37\" colspan=\"2\">This specification is used for user ");
out.println("                who working in graphic field it have high performence display ");
out.println("                card </td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#89D8D8\"> ");
out.println("              <td colspan=\"3\" height=\"61\"> ");
out.println("                <div align=\"center\"><font size=\"4\"><b><font color=\"#000000\"><i>Please ");
out.println("                  select your spec policy requirement<br>");
out.println("                  </i></font></b></font></div>");
out.println("                <div align=\"center\"><font size=\"4\"><b> ");
out.println("<form method=\"Post\" action=\"ListGeneralSpec\" name=\"NewMemberForm\">");
out.println("                  <select name=\"Spec_type\">");
out.println("                    <option>Budget PC</option>");
out.println("                    <option>Basic PC</option>");
out.println("                    <option>Game PC</option>");
out.println("                    <option>Professional PC</option>");
out.println("                    <option>Office PC</option>");
out.println("                    <option>Graphic PC</option>");
out.println("                  </select>");
out.println("                  <input type=\"submit\" name=\"Spec_type2\" value=\"Display spec\">");
out.println("                  </b></font> </div>");
out.println("</form>");
out.println("              </td>");
out.println("            </tr>");
out.println("          </table>");
out.println("          <p>&nbsp;</p>");
out.println("        </td>");
out.println("      </tr>");
out.println("      <tr> </tr>");
out.println("      <tr> </tr>");
out.println("    </table>");
out.println("    <p>&nbsp; </p>");
out.println("</div>");
out.println("</div></body>");
out.println("</html>");


    out.flush();




    }

}
