


import  java.sql.*;
import  oracle.jdbc.driver.*;
import  java.io.*;
import  javax.servlet.*;
import  javax.servlet.http.*;
import  java.util.*;
public class LoginSuccess extends HttpServlet
{
    public void   doGet(HttpServletRequest req, HttpServletResponse resp)
    throws ServletException, java.io.IOException
  	{
	  java.io.PrintWriter out = new java.io.PrintWriter(resp.getOutputStream());
    Connection con = null;
    Statement stmt = null;
    ResultSet rs= null;
    HttpSession session = req.getSession(true);
    String username = (String)session.getValue("username") ;
    String companyname = (String)session.getValue("companyname");
    String Str_Query ;
    int rowCount = 0;
    resp.setContentType("text/html");
     if (username == null)
          resp.sendRedirect("../Pleaselogin.html");

    out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">");
out.println("<HTML><HEAD><TITLE>Internet Auction : CE.KMITL</TITLE>");
out.println("<STYLE>A:link {");
out.println("	COLOR: #ffffff; TEXT-DECORATION: none");
out.println("}");
out.println("A:visited {");
out.println("	COLOR: #ffffff; TEXT-DECORATION: none");
out.println("}");
out.println("A:hover {");
out.println("	COLOR: #33ccff; TEXT-DECORATION: none");
out.println("}");
out.println("</STYLE>");
out.println("");
out.println("<META http-equiv=Content-Type content=\"text/html; charset=iso-8859-1\">");
out.println("<META content=\"MSHTML 5.50.4522.1800\" name=GENERATOR></HEAD>");
out.println("<BODY vLink=#3399cc aLink=#ff9966 link=#ff9933 bgColor=#ffffff>");
out.println("<DIV align=center>");
out.println("<P>&nbsp;</P>");
out.println("<DIV id=Layer1 ");
out.println("style=\"Z-INDEX: 1; LEFT: 17px; WIDTH: 970px; POSITION: absolute; TOP: 22px; HEIGHT: 100px\">");
out.println("<TABLE height=400 cellSpacing=2 cellPadding=5 width=\"100%\" border=0>");
out.println("  <TBODY>");
out.println("  <TR>");
out.println("    <DIV align=center><IMG height=98 src=\"/picture/AuctionBanner.jpg\" width=970></DIV></TR>");
out.println("  <TR>");
out.println("    <TD vAlign=top width=\"18%\" bgColor=#4f4fd2 height=137 rowSpan=3>");
out.println("      <DIV align=center>");
out.println("      <P><FONT face=\"Arial, Helvetica, sans-serif\" size=3><FONT ");
out.println("      color=#ff3366><I><FONT size=2><BR></FONT></I></FONT></FONT></P>");
out.println("      <P><FONT face=\"Arial, Helvetica, sans-serif\" size=3><FONT ");
out.println("      color=#ff3366><I><FONT size=2><FONT color=#cc0000><B><FONT color=#ffcc00 ");
out.println("      size=3>New Users ");
out.println("      !!</FONT></B></FONT><BR></FONT></I></FONT></FONT><BR></P></DIV>");
out.println("      <DIV align=center>");
out.println("      <P><FONT size=3><A href=\"../register.html\"><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\">Register</FONT></A></FONT> <BR><FONT ");
out.println("      size=3><A href=\"../NewToAuction.html\"><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\">New to our Auction</FONT></A></FONT> ");
out.println("      <FONT face=\"Arial, Helvetica, sans-serif\" color=#ff3366 ");
out.println("      size=2><I><BR></I></FONT><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("      color=#ff3366 size=2><I><BR><BR><FONT color=#cc0000><B><FONT color=#ffcc00 ");
out.println("      size=3>Auction Member</FONT></B></FONT></I></FONT></P><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\" color=#ff3366 size=2><A ");
out.println("      href=\"LoginSuccess\"><FONT size=3>Home<FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\"> </FONT></FONT></A></FONT><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\" color=#ff3366 ");
out.println("      size=2><I></I></FONT><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("      color=#ff3366 size=2><I><BR></I><A href=\"Changeinfo\"><FONT ");
out.println("      size=3><FONT face=\"Arial, Helvetica, sans-serif\">Change Personal ");
out.println("      Information </FONT><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\"></FONT></FONT></A><I></I></FONT></DIV>");
out.println("      <DIV align=center><FONT face=\"Arial, Helvetica, sans-serif\" color=#ff3366 ");
out.println("      size=2></FONT><A href=\"Listmember\"><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\">Member Profile<BR></FONT></FONT></A><A ");
out.println("      href=\"Listproject\"><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\">Project List</FONT></FONT></A><A ");
out.println("      href=\"OfferSpec\"><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\"><BR></FONT></FONT></A><A ");
out.println("      href=\"Ranking\"><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\">Member Rating</FONT></FONT></A> ");
out.println("      <P><FONT size=3><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("      size=2><B><FONT color=#ff9900>For Buyer<BR></FONT></B></FONT></FONT><FONT ");
out.println("      size=3><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
out.println("      href=\"GeneralReq\">General ");
out.println("      Requirement</A></FONT></FONT><BR><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\"><A href=\"AddTechReq\">Add ");
out.println("      Technical Requirement <FONT ");
out.println("      size=2><I>(bidding)</I></FONT></A></FONT></FONT><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\" color=#cccccc size=2><B><FONT ");
out.println("      color=#ff9900>For Seller</FONT></B></FONT></FONT><BR><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\"><A ");
out.println("      href=\"AddSpecification\">Add ");
out.println("      Specification</A></FONT></FONT><BR><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\"><A ");
out.println("      href=\"ListBiddingProject\">Bidding</A></FONT></FONT><BR><BR></DIV>");
out.println("      </p><DIV align=center>");
out.println("      <P><FONT face=\"Arial, Helvetica, sans-serif\" color=#ff3366 size=2><I><FONT ");
out.println("      color=#cc0000><B><FONT color=#ffcc00 size=3>Auction ");
out.println("      Services</FONT></B></FONT></I></FONT> <BR></P></DIV>");
out.println("      <DIV align=center><FONT face=\"Arial, Helvetica, sans-serif\" color=#ff3366 ");
out.println("      size=2><I></I><A href=\"http://freeboard.adbest.com/KBoard.cgi?db=pennie23\"><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\">Auction ");
out.println("      Board</FONT></FONT></A></FONT><BR><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\" color=#ff3366 size=2><FONT ");
out.println("      size=3><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
out.println("      href=\"../MailtoUs.html\">Mail To Us</FONT></FONT></FONT><BR><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\" color=#ff3366 size=2><A ");
out.println("      href=\"Logout\"><FONT size=3><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\">Log Out ");
out.println("</FONT></FONT></A></FONT></DIV>");
out.println("      <DIV></DIV><FONT face=\"Arial, Helvetica, sans-serif\" color=#ff3366 ");
out.println("      size=2><I></I></FONT>");
out.println("      <DIV align=center><FONT face=\"Arial, Helvetica, sans-serif\" color=#ff3366 ");
out.println("      size=2><I><BR></I></FONT><BR></DIV><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\" color=#ff3366 size=2><I></I></FONT>");
out.println("      <DIV align=right><PRE>&nbsp;");
out.println("</PRE></DIV><PRE>&nbsp;");
out.println("</PRE></TD>");
out.println("    <TD vAlign=top width=\"63%\" rowSpan=3>");
out.println("      <DIV align=right>");
out.println("      <P align=right><B><FONT face=\"Arial, Helvetica, sans-serif\" color=#9999ff ");
out.println("      size=+3>");
out.println("      </FONT></B></P>");
out.println("      <P align=left><B><FONT face=\"Arial, Helvetica, sans-serif\" color=#000000 ");
out.println("      size=5><I><FONT color=#cc3333>Welcome</FONT></I></FONT><FONT ");
out.println("      face=\"Arial, Helvetica, sans-serif\" color=#000000 size=+3> ");
out.println("      </FONT></B><FONT face=\"Arial, Helvetica, sans-serif\" color=#000066 ");
out.println("      size=5>" + username  + " </FONT> ");
out.println("      <HR>");
out.println("");
out.println("      <P></P></DIV>");
out.println("<center>");
out.println("<FONT face=\"Arial, Helvetica, sans-serif\" color=#9999ff size=+3> <b> Search Device</b></font><br><BR> ");
out.println("<A href=\"SearchFromSpec\"><FONT ");
out.println("      face=\"Verdana, Arial, Helvetica, sans-serif\" color=#ff6633><B><FONT");
out.println("      color=#000099 size=3><I>From Seller Specification Database</I></FONT></B>");
out.println("      </FONT></A><BR><A href=\"ListDeviceFromDatabase\"><FONT");
out.println("      face=\"Verdana, Arial, Helvetica, sans-serif\" color=#ff6633><B><FONT");
out.println("      color=#000099 size=3><I>From System Database</I></FONT></B>");
out.println("<BR>");
out.println("</center>");
out.println("<BR>");
out.println("<BR>");
out.println("      <TABLE height=180 cellSpacing=2 cellPadding=5 width=\"100%\" border=0>");
out.println("        <TBODY>");
out.println("        <TR>");
out.println("          <TD vAlign=top width=\"50%\" bgColor=#ffffff height=30>");
out.println("            <DIV align=center>");
out.println("            <P><FONT face=\"Arial, Helvetica, sans-serif\" color=#cc3333 ");
out.println("            size=5>Buyer</FONT></P>");
out.println("            <P><A href=\"GeneralReq\"><FONT size=3><FONT ");
out.println("            face=\"Arial, Helvetica, sans-serif\" color=#ff6633><B>General ");
out.println("            Requirement</B></FONT></FONT></A>");
out.println("            <br><I><B><FONT size=2><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("            color=#333366>For Buyer who need to find computer set specification ");
out.println("            with policy requirement : Basic PC , Budget PC , Game PC , etc. ");
out.println("            Then, we'll match your requirement with seller computer set ");
out.println("            specification</FONT></FONT></B></I><BR></P></DIV></TD>");
out.println("          <TD vAlign=top width=\"50%\" bgColor=#ffffff height=100>");
out.println("            <DIV align=center>");
out.println("            <FONT face=\"Arial, Helvetica, sans-serif\" color=#cc3333 ");
out.println("            size=5>Seller</FONT></P>");
out.println("            <P><A href=\"AddSpecification\"><FONT size=3><FONT ");
out.println("            face=\"Arial, Helvetica, sans-serif\" color=#ff6633><B>Add ");
out.println("            Specification</B></FONT></FONT></A> ");
out.println("            <br><I><B><FONT size=2><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("            color=#333366>For Seller who need to offer your new computer set ");
out.println("            specification with policy : Basic PC , Budget PC , Game PC , etc. ");
out.println("            </FONT></FONT></B></I></P></DIV></TD>");
out.println("        <TR>");
out.println("          <TD vAlign=top width=\"50%\" bgColor=#ffffff height=100>");
out.println("            <P align=center><BR><A href=\"AddTechReq\"><FONT ");
out.println("            size=3><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("            color=#ff6633><B>Add Technical Requirement</B></FONT></FONT></A> ");
out.println("            <BR><I><B><FONT size=2><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("            color=#333366>For Buyer who need to offer specification to be new ");
out.println("            project for BIDDING </FONT></FONT></B></I></P></TD>");
out.println("          <TD vAlign=top width=\"50%\" bgColor=#ffffff height=100>");
out.println("            <P align=center><BR><A href=\"ListBiddingProject\"><FONT ");
out.println("            size=3><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("            color=#ff6633><B>Bidding</B></FONT></FONT></A> <BR><I><B><FONT ");
out.println("            size=2><FONT face=\"Arial, Helvetica, sans-serif\" color=#333366>For ");
out.println("            Seller who need to BIDDING in any buyer project ");
out.println("            requirement</FONT></FONT> </B></I></P>");
out.println("          </TD>");
out.println("       </TR>");
out.println("        <TR>");
out.println("          <TD vAlign=top width=\"50%\" bgColor=#ffffff height=100>");
out.println("            <P align=center><BR><A href = \"YourProjectList\"> <FONT ");
out.println("            size=3><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("            color=#ff6633><B> Your Project  </B></FONT></FONT></A> ");
out.println("            <BR><I><B><FONT size=2><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("            color=#333366>  View your project detail and remove your project history");
out.println("            </FONT></FONT></B></I></P></TD>");
out.println("            <TD vAlign=top width=\"50%\" bgColor=#ffffff height=100>");
out.println("            <P align=center><BR><A href=\"ListYourSpec\"><FONT ");
out.println("            size=3><FONT face=\"Arial, Helvetica, sans-serif\" ");
out.println("            color=#ff6633><B>Your General Specification</B></FONT></FONT></A> <BR><I><B><FONT ");
out.println("            size=2><FONT face=\"Arial, Helvetica, sans-serif\" color=#333366>");
out.println("            View your specification ");
out.println("            </FONT></FONT> </B></I></P>");
out.println("          </TD>");
out.println("       </TR>");



out.println("       </TBODY></TABLE></TD>");
out.println("    <TD vAlign=top width=\"19%\" bgColor=#ffffff rowSpan=3><BR>");
out.println("      <DIV align=center><IMG height=88 src=\"/picture/mms110_m.jpg\" width=100></DIV><BR>");
out.println("      <DIV align=center><IMG src=\"/picture/product58.jpg\"></DIV><BR>");
out.println("      <DIV align=center><IMG src=\"/picture/fd.gif\"></DIV><BR>");
out.println("      <DIV align=center><IMG src=\"/picture/ibm205.gif\"></DIV><BR>");
out.println("      <DIV align=center><IMG src=\"/picture/500a.jpg\"></DIV><BR>");
out.println("      <DIV align=center><IMG src=\"/picture/CPIII.jpg\"></DIV>");
out.println("    <TD></TD>");
out.println("  <TR></TR>");
out.println("  <TR></TR></TBODY></TABLE></DIV></DIV></BODY></HTML>");


     out.flush();
    }

}


