import  java.sql.*;
import  oracle.jdbc.driver.*;
import  java.io.*;
import  javax.servlet.*;
import  javax.servlet.http.*;
import  java.util.*;
public class SearchFromSpec extends HttpServlet
{
    public void   doGet(HttpServletRequest req, HttpServletResponse resp)
    throws ServletException, java.io.IOException
  	{
	  java.io.PrintWriter out = new java.io.PrintWriter(resp.getOutputStream());
    HttpSession session = req.getSession(true);
    resp.setContentType("text/html");
    String device = req.getParameter("device");
    out.println("<html>");
out.println("<head>");
out.println("<title>Internet Auction : CE.KMITL</title>");
out.println("<style><!-- A:link, A:visited { text-decoration: none; color: #ffffff}  A:hover { text-decoration: none; font-weight: underline; color :  #33ccff} // --></style>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("</head>");
out.println("");
out.println("<body bgcolor=\"#FFFFFF\" link=\"#FF9933\" vlink=\"#3399CC\" alink=\"#FF9966\" >");
out.println("<div align=\"center\">");
out.println("");
out.println("  <div id=\"Layer1\" style=\"position:absolute; width:970px; height:100px; z-index:1; left: 17px; top: 22px\"> ");
out.println("");
out.println("    <table width=\"99%\" border=\"0\" height=\"400\" cellpadding=\"5\" cellspacing=\"2\">");
out.println("      <tr>");
out.println("    <div align=\"center\"><img src=\"/picture/AuctionBanner.jpg\" width=\"970\" height=\"98\"></div>");
out.println("  ");
out.println("");
out.println("</tr>    ");
out.println("<tr> ");
out.println("      <td rowspan=\"3\" height=\"137\" width=\"20%\" bgcolor=\"#4F4FD2\" valign=\"top\"> ");
out.println("        <div align=\"center\">");
out.println("          <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><br>");
out.println("            </font></i></font></font></p>");
out.println("          <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><font color=\"#CC0000\"><b><font size=\"3\" color=\"#FFCC00\">New ");
out.println("            Users !!</font></b></font><br>");
out.println("            </font></i></font></font><br>");
out.println("          </p>");
out.println("        </div>");
out.println("        <div align=\"center\">");
out.println("          <p><font size=\"3\"><a href=\"../register.html\"><font face=\"Arial, Helvetica, sans-serif\">Register</font></a></font>");
out.println("            <br>");
out.println("              <font size=\"3\"><a href=\"../NewToAuction.html\"><font face=\"Arial, Helvetica, sans-serif\">");
out.println("              New to our Auction</font></a></font> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            <br>");
out.println("            <font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction Member</font></b></font></i></font></p>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"LoginSuccess\"><font size=\"3\" >Home<font face=\"Arial, Helvetica, sans-serif\">");
out.println("          </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i><a href=\"Changeinfo\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Change ");
out.println("            Personal Information </font><font  face=\"Arial, Helvetica, sans-serif\"> ");
out.println("            </font></font> </a><i> </i></font> </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"></font><a href=\"Listmember\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member");
out.println("            Profiles<br>");
out.println("            </font></font></a><a href=\"Listproject\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Project");
out.println("            List</font></font></a><a href=\"OfferSpec\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><br>");
out.println("            </font></font></a><a href=\"Ranking\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member Rating</font></font></a>");
out.println("            <br>");
out.println("            <br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\"><b><font color=\"#FF9900\">For");
out.println("            Buyer</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"GeneralReq\">General");
out.println("            Requirement</a></font></font><br>");
out.println("			<font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddTechReq\">Add Technical Requirement <font size=\"2\"><i>(bidding)</i></font></a></font></font><br><br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#CCCCCC\" size=\"2\"><b><font color=\"#FF9900\">For");
out.println("            Seller</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddSpecification\">Add");
out.println("            Specification</a></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"ListBiddingProject\">Bidding</a></font></font><br>");
out.println("            <br>");
out.println("");
out.println("");
out.println("            </div>");
out.println("          <div align=\"center\">");
out.println("<p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction ");
out.println("              Services</font></b></font></i></font> <br>");
out.println("            </p>");
out.println("            </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i> ");
out.println("            </i><a href=\"http://freeboard.adbest.com/KBoard.cgi?db=pennie23\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Auction ");
out.println("            Board</font></font></a></font><br>");
out.println("   ");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"../MailToUs.html\">Mail ");
out.println("              To Us</a></font></font></font><br>");
out.println("          <!-- <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"Logout\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Log ");
out.println("              Out </font></font></a>--> <p></p>");
out.println("            </div>");
out.println("        <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font>");
out.println("        <div align=\"center\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("          </i></font><br>");
out.println("        </div>");
out.println("        <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font>");
out.println("<div align=\"right\">");
out.println("          <pre>&nbsp;");
out.println("");
out.println("</pre>");
out.println("        </div>");
out.println("        <pre>&nbsp;");
out.println("");
out.println("");
out.println("");
out.println("</pre>");
out.println("      </td>");
out.println("      <td width=\"63%\" rowspan=\"3\" valign=\"top\">");
out.println("          <div align=\"right\"> ");
out.println("            <p align=\"right\"><b><font face=\"Arial, Helvetica, sans-serif\" size=\"+3\" color=\"#9999FF\"> ");
/*
out.println("              <script language=Javascript1.2>");
out.println("<!--");
out.println("");
out.println("//var tags_before_clock = \"<font face='geneva, arial, helvetica, sans-seif' size='4' color='#0000FF'>It is now \"");
out.println("//var tags_middle_clock = \"on\"");
out.println("//var tags_after_clock  = \"</font>\"");
out.println("");
out.println("");
out.println("if(navigator.appName == \"Netscape\") {");
out.println("document.write('<layer id=\"clock\"></layer><br>');");
out.println("}");
out.println("");
out.println("if (navigator.appVersion.indexOf(\"MSIE\") != -1){");
out.println("document.write('<span id=\"clock\"></span>');");
out.println("}");
out.println("");
out.println("DaysofWeek = new Array()");
out.println("  DaysofWeek[0]=\"SUN\"");
out.println("  DaysofWeek[1]=\"MON\"");
out.println("  DaysofWeek[2]=\"TUE\"");
out.println("  DaysofWeek[3]=\"WED\"");
out.println("  DaysofWeek[4]=\"THU\"");
out.println("  DaysofWeek[5]=\"FRI\"");
out.println("  DaysofWeek[6]=\"SAT\"");
out.println("");
out.println("Months = new Array()");
out.println("  Months[0]=\"JAN\"");
out.println("  Months[1]=\"FEB\"");
out.println("  Months[2]=\"MAR\"");
out.println("  Months[3]=\"APR\"");
out.println("  Months[4]=\"MAY\"");
out.println("  Months[5]=\"JUN\"");
out.println("  Months[6]=\"JUL\"");
out.println("  Months[7]=\"AUG\"");
out.println("  Months[8]=\"SEP\"");
out.println("  Months[9]=\"OCT\"");
out.println("  Months[10]=\"NOV\"");
out.println("  Months[11]=\"DEC\"");
out.println("");
out.println("function upclock(){");
out.println("var dte = new Date();");
out.println("var hrs = dte.getHours();");
out.println("var min = dte.getMinutes();");
out.println("var sec = dte.getSeconds();");
out.println("var day = DaysofWeek[dte.getDay()]");
out.println("var date = dte.getDate()");
out.println("var month = Months[dte.getMonth()]");
out.println("var year = dte.getFullYear()");
out.println("");
out.println("var col = \":\";");
out.println("var spc = \" \";");
out.println("var com = \",\";");
out.println("var apm;");
out.println("");
out.println("//if (date == 1 || date == 21 || date == 31)");
out.println("//  {ender = \"<sup>st</sup>\"}");
out.println("//else");
out.println("//if (date == 2 || date == 22)");
out.println("//  {ender = \"<sup>nd</sup>\"}");
out.println("//else");
out.println("//if (date == 3 || date == 23)");
out.println("//  {ender = \"<sup>rd</sup>\"}");
out.println("");
out.println("//else");
out.println("//  {ender = \"<sup>th</sup>\"}");
out.println("");
out.println("if (12 < hrs) {");
out.println("apm=\"<font size='-1'>PM</font>\";");
out.println("hrs-=12;");
out.println("}");
out.println("");
out.println("else {");
out.println("apm=\"<font size='-1'>AM</font>\";");
out.println("}");
out.println("");
out.println("if (hrs == 0) hrs=12;");
out.println("if (hrs<=9) hrs=\"0\"+hrs;");
out.println("if (min<=9) min=\"0\"+min;");
out.println("if (sec<=9) sec=\"0\"+sec;");
out.println("");
out.println("if(navigator.appName == \"Netscape\") {");
out.println("document.clock.document.write(\"<font face=\\"efArial, Helvetica, sans-serif\\" size=\\"2\\" color=\\"#000000\\">\"+hrs+col+min+col+sec+spc+apm+spc+com+spc+day+spc+date+spc+month+spc+year+\"</font>\");");
out.println("document.clock.document.close();");
out.println("}");
out.println("");
out.println("if (navigator.appVersion.indexOf(\"MSIE\") != -1){");
out.println("clock.innerHTML = \"<font face=\\"Arial, Helvetica, sans-serif\\" size=\\"2\\" color=\\"#000000\\">\"+hrs+col+min+col+sec+spc+apm+spc+com+spc+day+spc+date+spc+month+spc+year+\"</font>\";");
out.println("}");
out.println("}");
out.println("");
out.println("setInterval(\"upclock()\",1000);");
out.println("//-->");
out.println("</script>");
*/
out.println("<!--------------------------------------------------------------------------------------------------------- -->");
out.println("			");
out.println("              </font></b></p>");
out.println("<form method = \"Get\" action = \"SearchFromSpec\">");
out.println("            <br><div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">Search ");
out.println("              Computer Device</font></b> </font>");
out.println("			  <select name=\"device\" size=\"1\">");
out.println("                <option selected>CPU </option>");
out.println("                <option>RAM</option>");
out.println("                <option>MAINBOARD</option>");
out.println("				<option>HARDDISK</option>");
out.println("                <option>CD-ROM</option>");

out.println("                <option>DISPLAY CARD</option>");
out.println("                <option>SOUND CARD</option>");
out.println("                <option>MONITOR</option>");
out.println("                <option>MODEM</option>");
//out.println("                <option>FLOPPY DISK</option>");
//out.println("				<option>MOUSE</option>");
//out.println("				<option>KEYBOARD</option>");
out.println("				<option>SPEAKER</option>");
out.println("				</select>");
out.println("				<br><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\" size=\"3\">(From Seller Specification)");
out.println("			  <br><br>");
out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Choose device\">");
out.println("			</form>");
out.println("			<hr>");
out.println("");
GenerateSearchSpec Gen = new GenerateSearchSpec() ;
if (device != null)
{
   if (device.compareTo("CPU") == 0)
   {
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/cpusearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_cpu\">");
   Gen.query_select_spec(out,"CPU","Brand_cpu");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Type cpu</td>");
   out.println("                  <td width=\"58%\"><select name=\"Type_cpu\">");
   Gen.query_select_spec(out,"CPU","Type_cpu");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Speed</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Speed_cpu\">");
   Gen.query_select_spec(out,"CPU","Speed_cpu");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr>");
   out.println("                  <td width=\"42%\">Slot  Type ");
   out.println("                 </td>");
   out.println("				   <td width=\"58%\"><select name=\"Slot_type\">");
   Gen.query_select_spec(out,"CPU","Slot_type");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
   if (device.compareTo("RAM") == 0)
   {
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/ramsearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand ram</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_ram\">");
   Gen.query_select_spec(out,"RAM","Brand_ram");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Model ram</td>");
   out.println("                  <td width=\"58%\"><select name=\"Model_ram\">");
   Gen.query_select_spec(out,"RAM","Model_ram");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Size ram</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Size_ram\">");
   Gen.query_select_spec(out,"RAM","Size_ram");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
   if (device.compareTo("MAINBOARD") == 0)
   {
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/mainboardsearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_mb\">");
   Gen.query_select_spec(out,"MAINBOARD","Brand_mb");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              <tr> ");
   out.println("                  <td width=\"42%\">Model</td>");
   out.println("                  <td width=\"58%\"><select name=\"Model_mb\">");
   Gen.query_select_spec(out,"MAINBOARD","Model_mb");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Chip set</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Chip_set\">");
   Gen.query_select_spec(out,"MAINBOARD","Chip_set");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr>");
   out.println("                  <td width=\"42%\">Type cpu");
   out.println("                 </td>");
   out.println("				   <td width=\"58%\"><select name=\"Type_cpu\">");
   Gen.query_select_spec(out,"MAINBOARD","Type_cpu");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
   if (device.compareTo("HARDDISK") == 0)
   {
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/harddisksearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_harddisk\">");
   Gen.query_select_spec(out,"HARDDISK","Brand_harddisk");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Model</td>");
   out.println("                  <td width=\"58%\"><select name=\"Model_harddisk\">");
   Gen.query_select_spec(out,"HARDDISK","Model_harddisk");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Capacity</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Capacity\">");
   Gen.query_select_spec(out,"HARDDISK","Capacity");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr>");
   out.println("                  <td width=\"42%\">Speed");
   out.println("                 </td>");
   out.println("				   <td width=\"58%\"><select name=\"Speed\">");
   Gen.query_select_spec(out,"HARDDISK","Speed");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
 if (device.compareTo("CD-ROM") == 0)
   {
   device = "CD_ROM" ;
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/cdromsearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_cdrom\">");
   Gen.query_select_spec(out,"CD_ROM","Brand_cdrom");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">speed(x)</td>");
   out.println("                  <td width=\"58%\"><select name=\"x\">");
   Gen.query_select_spec(out,"CD_ROM","x");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Interface</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Interface\">");
   Gen.query_select_spec(out,"CD_ROM","Interface");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
   if (device.compareTo("DISPLAY CARD") == 0)
   {
   device = "DISPLAY_CARD" ;
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/displaysearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_display\">");
   Gen.query_select_spec(out,"DISPLAY_CARD","Brand_display");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">TYPE</td>");
   out.println("                  <td width=\"58%\"><select name=\"Type_display\">");
   Gen.query_select_spec(out,"DISPLAY_CARD","Type_display");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Chip set</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Chip\">");
   Gen.query_select_spec(out,"DISPLAY_CARD","Chip");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr>");
   out.println("                  <td width=\"42%\">Memory");
   out.println("                 </td>");
   out.println("				   <td width=\"58%\"><select name=\"Memory\">");
   Gen.query_select_spec(out,"DISPLAY_CARD","Memory");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
   if (device.compareTo("SOUND CARD") == 0)
   {
   device = "SOUNDCARD" ;
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/soundcardsearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_sound\">");
   Gen.query_select_spec(out,"SOUNDCARD","Brand_sound");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Model</td>");
   out.println("                  <td width=\"58%\"><select name=\"Model_sound\">");
   Gen.query_select_spec(out,"SOUNDCARD","Model_sound");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Sound system</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Sound_system\">");
   Gen.query_select_spec(out,"SOUNDCARD","Sound_system");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr>");
   out.println("                  <td width=\"42%\">Interface");
   out.println("                 </td>");
   out.println("				   <td width=\"58%\"><select name=\"Interface\">");
   Gen.query_select_spec(out,"SOUNDCARD","Interface");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
   if (device.compareTo("MONITOR") == 0)
   {
   device = "MONITOR" ;
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/monitorsearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_monitor\">");
   Gen.query_select_spec(out,"MONITOR","Brand_monitor");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Type</td>");
   out.println("                  <td width=\"58%\"><select name=\"Type_monitor\">");
   Gen.query_select_spec(out,"MONITOR","Type_monitor");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Size</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Size_monitor\">");
   Gen.query_select_spec(out,"MONITOR","Size_monitor");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr>");
   out.println("                  <td width=\"42%\">Dot pitch");
   out.println("                 </td>");
   out.println("				   <td width=\"58%\"><select name=\"Dot_pitch\">");
   Gen.query_select_spec(out,"MONITOR","Dot_pitch");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
    if (device.compareTo("MODEM") == 0)
   {
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/modemsearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_modem\">");
   Gen.query_select_spec(out,"MODEM","Brand_modem");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Type</td>");
   out.println("                  <td width=\"58%\"><select name=\"Type_modem\">");
   Gen.query_select_spec(out,"MODEM","Type_modem");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Interface</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Interface\">");
   Gen.query_select_spec(out,"MODEM","Interface");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr>");
   out.println("                  <td width=\"42%\">Speed");
   out.println("                 </td>");
   out.println("				   <td width=\"58%\"><select name=\"Speed_modem\">");
   Gen.query_select_spec(out,"MODEM","Speed_modem");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
     if (device.compareTo("SPEAKER") == 0)
   {
   out.println("<form method = \"Post\" action = \"DisplaySpecSearch\">");
   out.println(" <input type=hidden Name = \"device\" value = \"" + device + "\">" );
   out.println("            <div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("				<img src=\"/picture/speakersearch.jpg\" width=\"590\" height=\"118\"><br>");
   out.println("		<font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6633\"><b><font color=\"#000099\" size=\"3\">");
   out.println("		<table width=\"70%\" border=\"0\" cellspacing=\"2\" cellpadding=\"4\">");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Brand</td>");
   out.println("                  <td width=\"58%\"><select name=\"Brand_speaker\">");
   Gen.query_select_spec(out,"SPEAKER","Brand_speaker");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Type</td>");
   out.println("                  <td width=\"58%\"><select name=\"Type_speaker\">");
   Gen.query_select_spec(out,"SPEAKER","Type_speaker");
   out.println("                </select></td>");
   out.println("                </tr> ");
   out.println("                <tr> ");
   out.println("                  <td width=\"42%\">Number speaker</td> ");
   out.println("                  <td width=\"58%\"><select name=\"Number_speaker\">");
   Gen.query_select_spec(out,"SPEAKER","Number_speaker");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("                <tr>");
   out.println("                  <td width=\"42%\">Watt");
   out.println("                 </td>");
   out.println("				   <td width=\"58%\"><select name=\"Watt\">");
   Gen.query_select_spec(out,"SPEAKER","Watt");
   out.println("                </select></td>");
   out.println("                </tr>");
   out.println("              </table></font></b></font>");
   out.println("			  <br>");
   out.println("			  <br>");
   out.println("			  <input type=\"Submit\" name=\"submit\" value=\"Search\">");
   out.println("			  </div>");
   out.println("			</form>");
   out.println("            </div>");
   }
}
out.println("      </td>");
out.println("");
out.println("<!------------------------------------------- column 3 [right] --------------------------------------------->");
out.println("");
out.println("      <td width=\"17%\" rowspan=\"3\" valign=\"top\" bgcolor=\"#ffb56a\"> ");
out.println("        <div align=\"center\"> ");
out.println("          <div align=\"left\"> ");
out.println("            <form method=\"post\" action=\"servlet/Logined\">");
out.println("              <div align=\"center\"> <br><br>");
out.println("			  <font face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FF6600\"><b><font color=\"#330033\" size=\"2\">");
out.println("");
out.println("			  <SCRIPT LANGUAGE=\"JavaScript1.2\">");
out.println("");
out.println("<!-- This script and many more are available free online at -->");
out.println("<!-- The JavaScript Source!! http://javascript.internet.com -->");
out.println("");
out.println("<!-- Begin");
out.println("function initArray() {");
out.println("this.length = initArray.arguments.length;");
out.println("for (var i = 0; i < this.length; i++) {");
out.println("this[i] = initArray.arguments[i];");
out.println("   }");
out.println("}");
out.println("");
out.println("var ctext = \"Choose computer device which you need .. <br><br> We will search from Seller Computer Specification Database\" ;");
out.println("var speed = 1000;");
out.println("var x = 0;");
out.println("var color = new initArray(");
out.println("\"#003399\", ");
out.println("\"#003399\", ");
out.println("\"#003399\", ");
out.println("\"#FF9999\", ");
out.println("\"#FF6666\",");
out.println("\"#FF3333\"");
out.println("");
out.println(");");
out.println("if(navigator.appName == \"Netscape\") {");
out.println("document.write('<layer id=\"c\"><center>'+ctext+'</center></layer><br>');");
out.println("}");
out.println("if (navigator.appVersion.indexOf(\"MSIE\") != -1){");
out.println("document.write('<div id=\"c\"><center>'+ctext+'</center></div>');");
out.println("}");
out.println("function chcolor(){ ");
out.println("if(navigator.appName == \"Netscape\") {");
out.println("document.c.document.write('<center><font color=\"'+color[x]);");
out.println("document.c.document.write('\">'+ctext+'</font></center>');");
out.println("document.c.document.close();");
out.println("}");
out.println("else if (navigator.appVersion.indexOf(\"MSIE\") != -1){");
out.println("document.all.c.style.color = color[x];");
out.println("}");
out.println("(x < color.length-1) ? x++ : x = 0;");
out.println("}");
out.println("setInterval(\"chcolor()\",1000);");
out.println("// End -->");
out.println("</script>");
out.println("			");
out.println("");
out.println("               <!-- <div align=\"right\">");
out.println("                  <div align=\"center\">");
out.println("                    <div align=\"left\">");
out.println("                      <pre><img src=\"../login.jpg\" width=\"170\" height=\"35\">");
out.println("</pre>");
out.println("                    </div>");
out.println("                  </div>");
out.println("                </div>");
out.println("                <table width=\"29%\" border=\"0\" align=\"center\" vspace=\"2\" hspace=\"2\" cellpadding=\"3\" cellspacing=\"2\" bgcolor=\"#ffb56a\">");
out.println("                  <tr bgcolor=\"#ffb56a\"> ");
out.println("                    <td width=\"49%\" height=\"31\" align=\"center\"><font face=\"Arial, Helvetica, sans-serif\" size=\"3\"><b><font color=\"#000099\" size=\"2\">Username</font></b></font></td>");
out.println("                    <td width=\"51%\" height=\"31\" align=\"center\" valign=\"middle\"> ");
out.println("                      <font color=\"#FFFFFF\"> ");
out.println("                      <input type=\"text\" name=\"username\" size=\"10\" maxlength=\"15\">");
out.println("                      </font></td>");
out.println("                  </tr>");
out.println("                  <tr bgcolor=\"#ffb56a\"> ");
out.println("                    <td width=\"49%\" height=\"40\" align=\"center\"><font face=\"Arial, Helvetica, sans-serif\" size=\"3\" color=\"#006666\"><b><font size=\"2\" color=\"#000099\">Password</font></b></font></td>");
out.println("                    <td width=\"51%\" height=\"40\" align=\"center\" valign=\"middle\"> ");
out.println("                      <font color=\"#FFFFFF\"> ");
out.println("                      <input type=\"password\" name=\"password\" size=\"10\" maxlength=\"15\">");
out.println("                      </font></td>");
out.println("                  </tr>");
out.println("                </table>");
out.println("                  <pre><i><font face=\"Arial, Helvetica, sans-serif\" size=\"3\" color=\"#FF9999\"><font color=\"#990033\" size=\"2\"><input type=\"submit\" name=\"Submit2\" value=\"Login\">");
out.println("");
out.println("Forget Password ??? ... ");
out.println("    Enter your e-mail here !!  </font><font color=\"#FF6666\" size=\"2\">");
out.println(" ");
out.println("</font><b><font color=\"#FF6666\"><input type=\"text\" name=\"email\">");
out.println("");
out.println("<input type=\"submit\" name=\"Submit\" value=\"Submit\">  </font></b></font></i></pre>");
out.println("                  <pre>&nbsp;</pre>");
out.println("                <pre>&nbsp;</pre>");
out.println("                <pre>&nbsp;");
out.println("                </pre>");
out.println("              </div>");
out.println("            </form>");
out.println("            <pre>&nbsp;</pre>");
out.println("            <form method=\"post\" action=\"servlet/testsession\" name=\"test\">");
out.println("                <input type=\"submit\" name=\"test\" value=\"Delete_session\">");
out.println("            </form>");
out.println("          </div>");
out.println("        </div>");
out.println("      </td>");
out.println("    </tr> -->");
out.println("");
out.println("  </table>");
out.println("</div>");
out.println("</div></body>");
out.println("</html>");
out.flush();
    }

}


