
import oracle.sql.*;
import  java.sql.*;
import  oracle.jdbc.driver.*;
import  java.io.*;
import  javax.servlet.*;
import  javax.servlet.http.*;
import  java.util.*;
public class SellerAddSpecification extends HttpServlet
{
    public void   doPost(HttpServletRequest req, HttpServletResponse resp)
    throws ServletException, java.io.IOException
  	{
	  java.io.PrintWriter out = new java.io.PrintWriter(resp.getOutputStream());
    HttpSession session = req.getSession(true);
    String username = (String)session.getValue("username") ;
    String companyname = (String)session.getValue("companyname");
    String Str_Query ;
    resp.setContentType("text/html");
    String Spec_type    = req.getParameter("Spec_type");
    String Standard_price = "0";
    GenerateSelectSpec Gen = new GenerateSelectSpec() ;
    if (username == null)
         resp.sendRedirect("../Pleaselogin.html");
    Specification Standard_spec  = new Specification();
    Connection Standard_con = null;
    Statement Standard_stmt = null;
    ResultSet Standard_rs= null;
    try
    {
     	  DriverManager.registerDriver (new oracle.jdbc.driver.OracleDriver());
    }
    catch (java.sql.SQLException ko){ out.println("Register error");}
     try
      {
        Standard_con = DriverManager.getConnection ("jdbc:oracle:thin:@161.246.5.182:1521:Internet","auction", "auction");
        Standard_con.setAutoCommit(false);
        Standard_stmt = Standard_con.createStatement();
        String select_standard = new String("select standard_spec,standard_price from standard_spec where spec_type = '" + Spec_type + "'");
        Standard_rs = Standard_stmt.executeQuery(select_standard);
    	  Standard_rs.next();
        BLOB blob;
        ///------------Unserialize object------------///
        blob = ((OracleResultSet)Standard_rs).getBLOB(1);
        Standard_price = Standard_rs.getString(2);
        InputStream instream = blob.getBinaryStream();
    	  ObjectInputStream iis = new ObjectInputStream(instream);
        ///------------Read Object------------------//
        Standard_spec = (Specification)iis.readObject();
     }
     catch (Exception ex)
     {
    	 out.println("Exception");
	     ex.printStackTrace(out);
	   }
     finally
     {
	     try
	     { if (Standard_rs != null)  {Standard_rs.close();}
         if (Standard_stmt != null){Standard_stmt.close();}
  		   if (Standard_con != null) {Standard_con.close();}
       }
	     catch (Exception ex){}
	   }
        out.println("<html>");
out.println("<head>");
out.println("<title>Internet Auction : CE.KMITL</title>");
out.println("<style><!-- A:link, A:visited { text-decoration: none; color: #ffffff}  A:hover { text-decoration: none; font-weight: underline; color :  #33ccff} // --> </style>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("</head>");
out.println("");
out.println("<body bgcolor=\"#FFFFFF\" link=\"#FF9933\" vlink=\"#3399CC\" alink=\"#FF9966\" >");
out.println("<div align=\"center\">");
out.println("  <p>&nbsp;</p>");
out.println("  <div id=\"Layer1\" style=\"position:absolute; width:970px; height:100px; z-index:1; left: 17px; top: 22px\"> ");
out.println("    <table width=\"100%\" border=\"0\" height=\"400\">");
out.println("      <tr> ");
out.println("        <div align=\"center\"><img src=\"/picture/AddSpecification.jpg\" width=\"970\" height=\"98\"></div>");
out.println("      </tr>");
out.println("      <tr> ");
out.println("        <td rowspan=\"3\" height=\"137\" width=\"15%\" bgcolor=\"#4F4FD2\" valign=\"top\"> ");
out.println("          <div align=\"center\"> ");
out.println("            <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><br>");
out.println("              </font></i></font></font></p>");
out.println("            <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><font color=\"#CC0000\"><b><font size=\"3\" color=\"#FFCC00\">New ");
out.println("              Users !!</font></b></font><br>");
out.println("              </font></i></font></font><br>");
out.println("            </p>");
out.println("          </div>");
out.println("          <div align=\"center\"> ");
out.println("            <p><font size=\"3\"><a href=\"../register.html\"><font face=\"Arial, Helvetica, sans-serif\">Register</font></a></font> ");
out.println("              <br>");
out.println("              <font size=\"3\"><a href=\"../NewToAuction.html\"><font face=\"Arial, Helvetica, sans-serif\"> ");
out.println("              New to our Auction</font></a></font> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              </i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              <br>");
out.println("              <font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction ");
out.println("              Member</font></b></font></i></font></p>");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"LoginSuccess\"><font size=\"3\" >Home<font face=\"Arial, Helvetica, sans-serif\"> ");
out.println("            </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i><a href=\"Changeinfo\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Change ");
out.println("            Personal Information </font><font  face=\"Arial, Helvetica, sans-serif\"> ");
out.println("            </font></font> </a><i> </i></font> </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"></font><a href=\"Listmember\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member ");
out.println("            Profile<br>");
out.println("            </font></font></a><a href=\"Listproject\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Project ");
out.println("            List</font></font></a><a href=\"OfferSpec\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><br>");
out.println("            </font></font></a><a href=\"Ranking\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member Rating</font></font></a> ");
out.println("            <br>");
out.println("            <br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("            Buyer</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"GeneralReq\">General ");
out.println("            Requirement</a></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddTechReq\">Add ");
out.println("            Technical Requirement <font size=\"2\"><i>(bidding)</i></font></a></font></font><br>");
out.println("            <br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#CCCCCC\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("            Seller</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"AddSpec\">Add ");
out.println("            Specification</a></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"ListBiddingProject\">Bidding</a></font></font><br>");
out.println("            <br>");
out.println("          </div>");
out.println("          <div align=\"center\"> ");
out.println("            <p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction ");
out.println("              Services</font></b></font></i></font> <br>");
out.println("            </p>");
out.println("          </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i> ");
out.println("            </i><a href=\"http://freeboard.adbest.com/KBoard.cgi?db=pennie23\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Auction ");
out.println("            Board</font></font></a></font></div>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("          <div align=\"center\"> ");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Mail ");
out.println("              To Us</font></font></font>");
out.println("            <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"Logout\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Log ");
out.println("              Out </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              </i></font> ");
out.println("          </div>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("          <div align=\"center\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i></font><br>");
out.println("          </div>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font> ");
out.println("          <div align=\"right\"> ");
out.println("            <pre>&nbsp;");
out.println("");
out.println("</pre>");
out.println("          </div>");
out.println("          <pre>&nbsp;");
out.println("");
out.println("");
out.println("");
out.println("</pre>");
out.println("        </td>");
out.println("<form method=\"Post\" action=\"ConfirmSellerGeneralSpec\" name=\"NewMemberForm\">");
out.println("        <td width=\"63%\" rowspan=\"3\" valign=\"top\"\"> ");
out.println("          <p>&nbsp;</p>");
out.println("          <p><font size=\"4\"><b><font size=\"5\">You choosed " + Spec_type +" </font> </b></font></p>");
out.println(" <input type=hidden Name = \"Spec_type\" value = \"" + Spec_type + "\">" );

out.println("          <table width=\"100%\" border=\"0\">");
out.println("            <tr bgcolor=\"#ffb56a\"> ");
out.println("              <td width=\"33%\"><font size=\"4\"><b><font size=\"5\"> <font size=\"4\">Seller ");
out.println("                name </font></font></b></font></td>");
out.println("              <td colspan=\"2\"> <font size=\"4\" color=\"#0000ff\"><b> " + username + " </b></font> </td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#FFCC99\"> ");
out.println("              <td width=\"33%\"><font size=\"4\"><b><font size=\"5\"> <font size=\"4\">Seller ");
out.println("                company </font></font></b></font></td>");
out.println("              <td colspan=\"2\"> <font size=\"4\" color=\"#0000ff\"> <b>" + companyname + " </b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#ffb56a\"> ");
out.println("              <td width=\"33%\"><font size=\"4\"><b><font size=\"5\"><font size=\"4\">Type ");
out.println("                of spec</font></font></b></font></td>");
out.println("              <td colspan=\"2\"><font size=\"4\" color=\"#0000ff\"><b>  " + Spec_type + "</b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#FFCC99\"> ");
out.println("              <td width=\"33%\"><font size=\"4\"><b><font size=\"5\"><font size=\"4\">Your ");
out.println("                price</font></font></b></font></td>");
out.println("              <td width=\"21%\"> ");
out.println("                <input type=\"text\" name=\"Seller_price\" size=\"10\" maxlength=\"10\">");
out.println("       <font size=\"4\">     Baht  </font></td>");
out.println("              <td width=\"35%\"><font color=\"#993366\" size =\"4\"><b><i>   Recommended price = " + Standard_price + "</i></b></font> </td>");
out.println("            </tr>");

out.println("          </table>");
out.println("          <p>&nbsp;</p>");
out.println("          <table width=\"100%\" border=\"0\">");
out.println("            <tr> ");
out.println("              <td colspan=\"3\" height=\"28\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"><font size=\"4\"><b><font size=\"5\"><font size=\"4\" color=\"#FF0000\">Your ");
out.println("                  specification </font></font></b></font></div>");
out.println("              </td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"><font size=\"4\"><b><font size=\"5\"><font size=\"4\" color=\"#0000FF\">Device</font></font></b></font></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"><b><font size=\"4\" color=\"#0000FF\">Specification</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"><b><font size=\"4\" color=\"#0000FF\">Recommend ");
out.println("                  </font></b></div>");
out.println("              </td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">CPU</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <select name=\"Cpu\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"CPU");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(0).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#E0F1F1\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">RAM</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#E0F1F1\"> ");
out.println("                <select name=\"Ram\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"RAM");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#E0F1F1\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(1).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">MAINBOARD</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <select name=\"Mainboard\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"MAINBOARD");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(2).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">HARDDISK</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"> ");
out.println("                <select name=\"Harddisk\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"HARDDISK");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(3).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">CDROM</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <select name=\"Cdrom\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"CDROM");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(4).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">DISPLAY CARD</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"> ");
out.println("                <select name=\"Display_card\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"DISPLAY CARD");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(5).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">SOUND CARD</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <select name=\"Sound_card\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"SOUND CARD");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(6).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">MONITOR</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"> ");
out.println("                <select name=\"Monitor\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"MONITOR");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(7).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">FLOPPY DISK</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <select name=\"Floppy_disk\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"FLOPPY DISK");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(9).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">MODEM</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"> ");
out.println("                <select name=\"Modem\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"MODEM");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\">  <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(8).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">MOUSE</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <select name=\"Mouse\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"MOUSE");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(10).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">KEYBOARD</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\"> ");
out.println("                <select name=\"Keyboard\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"KEYBOARD");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(11).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td width=\"20%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <div align=\"center\"><b><font size=\"2\">SPEAKER</font></b></div>");
out.println("              </td>");
out.println("              <td width=\"37%\" bgcolor=\"#C6E3E3\"> ");
out.println("                <select name=\"Speaker\">");
out.println("<option> Not Specific</option>");
out.println("<option> ------------------------</option>");
Gen.query_select_spec(out,"SPEAKER");
out.println("                </select>");
out.println("              </td>");
out.println("              <td width=\"43%\" bgcolor=\"#C6E3E3\"> <font color=\"#993366\"><b><i>");
out.println(Standard_spec.GetPart(0).GetDevice(12).Data[0] + "</i></b></font></td>");
out.println("            </tr>");
out.println("            <tr bgcolor=\"#E0F1F1\"> ");
out.println("              <td width=\"20%\"><b>More detail</b></td>");
out.println("              <td colspan=\"2\"> ");
out.println("                <textarea name=\"Detail\" cols=\"50\"></textarea>");
out.println("              </td>");
out.println("            </tr>");
out.println("            <tr> ");
out.println("              <td colspan=\"3\" height=\"24\" bgcolor=\"#89D8D8\"> ");
out.println("                <div align=\"center\"></div>");
out.println("                <div align=\"center\"> ");
out.println("                  <input type=\"submit\" name=\"Submit\" value=\"SEND THIS SPEC\">");
out.println("                </div>");
out.println("              </td>");
out.println("            </tr>");
out.println("          </table>");
out.println("          <p><font size=\"4\"><b><font size=\"5\"><font size=\"4\"> </font></font></b></font></p>");
out.println("          <p>&nbsp;</p>");
out.println("        </td>");
out.println("      </tr>");
out.println("      <tr> </tr>");
out.println("      <tr> </tr>");
out.println("</form>");
out.println("    </table>");
out.println("    <p>&nbsp; </p>");
out.println("</div>");
out.println("</div></body>");
out.println("</html>");
out.flush();
session.putValue("Standard_spec",Standard_spec);
    }

}
