
import oracle.sql.*;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.*;
import oracle.jdbc.driver.*;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;
public class Userhavebidproject extends HttpServlet implements Serializable
{
    public void   doGet(HttpServletRequest req, HttpServletResponse resp)
    throws ServletException, java.io.IOException
  	{
      java.io.PrintWriter out = new java.io.PrintWriter(resp.getOutputStream());
      Connection con = null;
      Statement stmt = null;
      ResultSet rs= null;
      resp.setContentType("text/html");
      HttpSession session = req.getSession(true);
      out.println("<html>");
out.println("<head>");
out.println("<title>Internet Auction : CE.KMITL</title>");
out.println("<style><!-- A:link, A:visited { text-decoration: none; color: #ffffff}  A:hover { text-decoration: none; font-weight: underline; color :  #33ccff} // --> </style>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("</head>");
out.println("");
out.println("<body bgcolor=\"#FFFFFF\" link=\"#FF9933\" vlink=\"#3399CC\" alink=\"#FF9966\" >");
out.println("<div align=\"center\">");
out.println("  <p>&nbsp;</p>");
out.println("  <div id=\"Layer1\" style=\"position:absolute; width:970px; height:100px; z-index:1; left: 17px; top: 22px\"> ");
out.println("");
out.println("  <table width=\"99%\" border=\"0\" height=\"400\">");
out.println("<tr>");
out.println("    <div align=\"center\"><img src=\"/picture/bidding.jpg\" width=\"970\" height=\"98\"></div>");
out.println("  ");
out.println("");
out.println("</tr>    ");
out.println("<tr> ");
out.println("      <td rowspan=\"3\" height=\"137\" width=\"15%\" bgcolor=\"#4F4FD2\" valign=\"top\"> ");
out.println("        <div align=\"center\">");
out.println("          <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><br>");
out.println("            </font></i></font></font></p>");
out.println("          <p><font size=\"3\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#FF3366\"><i><font size=\"2\"><font color=\"#CC0000\"><b><font size=\"3\" color=\"#FFCC00\">New ");
out.println("            Users !!</font></b></font><br>");
out.println("            </font></i></font></font><br>");
out.println("          </p>");
out.println("        </div>");
out.println("        <div align=\"center\">");
out.println("          <p><font size=\"3\"><a href=\"register.html\"><font face=\"Arial, Helvetica, sans-serif\">Register</font></a></font>");
out.println("            <br>");
out.println("              <font size=\"3\"><a href=\"NewToAuction.html\"><font face=\"Arial, Helvetica, sans-serif\"> ");
out.println("              New to our Auction</font></a></font> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            <br>");
out.println("            <font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction Member</font></b></font></i></font></p>");
out.println("          <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"LoginSuccess\"><font size=\"3\" >Home<font face=\"Arial, Helvetica, sans-serif\">");
out.println("          </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("            </i><a href=\"servlet/Changeinfo\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Change ");
out.println("            Personal Information </font><font  face=\"Arial, Helvetica, sans-serif\"> ");
out.println("            </font></font> </a><i> </i></font> </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"></font><a href=\"servlet/Listmember\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member");
out.println("            Profile<br>");
out.println("            </font></font></a><a href=\"servlet/Listproject\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Project ");
out.println("            List</font></font></a><a href=\"servlet/OfferSpec\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><br>");
out.println("            </font></font></a><a href=\"servlet/Ranking\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Member Rating</font></font></a> ");
out.println("            <br>");
out.println("            <br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("            Buyer</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"servlet/GeneralReq\">General ");
out.println("            Requirement</a></font></font><br>");
out.println("			<font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"servlet/AddTechReq\">Add Technical Requirement <font size=\"2\"><i>(bidding)</i></font></a></font></font><br><br>");
out.println("            <font size=\"3\"><font face=\"Arial, Helvetica, sans-serif\" color=\"#CCCCCC\" size=\"2\"><b><font color=\"#FF9900\">For ");
out.println("            Seller</font></b></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"servlet/AddSpecification\">Add ");
out.println("            Specification</a></font></font><br>");
out.println("            <font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\"><a href=\"servlet/ListBiddingProject\">Bidding</a></font></font><br>");
out.println("            <br>");
out.println("");
out.println("");
out.println("            </div>");
out.println("          <div align=\"center\">");
out.println("<p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><font color=\"#cc0000\"><b><font size=\"3\" color=\"#ffcc00\">Auction ");
out.println("              Services</font></b></font></i></font> <br>");
out.println("            </p>");
out.println("            </div>");
out.println("          <div align=\"center\"> <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i> ");
out.println("            </i><a href=\"http://freeboard.adbest.com/KBoard.cgi?db=pennie23\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Auction ");
out.println("            Board</font></font></a></font></div>");
out.println("        <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font>");
out.println("        <div align=\"center\">");
out.println("            <p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Mail ");
out.println("              To Us</font></font></font></p>");
out.println("            <p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><a href=\"servlet/Logout\"><font size=\"3\"><font  face=\"Arial, Helvetica, sans-serif\">Log ");
out.println("              Out </font></font></a></font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("              </i></font> </p>");
out.println("            </div>");
out.println("        <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font>");
out.println("        <div align=\"center\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i><br>");
out.println("          </i></font><br>");
out.println("        </div>");
out.println("        <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#FF3366\"><i></i></font>");
out.println("<div align=\"right\">");
out.println("          <pre>&nbsp;");
out.println("");
out.println("</pre>");
out.println("        </div>");
out.println("        <pre>&nbsp;");
out.println("");
out.println("");
out.println("");
out.println("</pre>");
out.println("      </td>");
out.println("      <td width=\"63%\" rowspan=\"3\" valign=\"top\" background=\"picture/indexpic2.jpg\">");
out.println("          <div align=\"right\"> ");
out.println("            <p align=\"left\"><b><font face=\"Arial, Helvetica, sans-serif\" size=\"+3\" color=\"#9999FF\"> ");
out.println("         </font></b></p>");
out.println("         <div align = \"left\">");
out.println("   <font size=\"5\" color=\"#ff0000\">    Sorry,you have already bid this project</font>");
out.println("			<br>");
out.println("			  <font size=\"3\"> <font face=\"Arial, Helvetica, sans-serif\" color =\"0000ff\"> ");
out.println(" <a href=\"ListBiddingProject\"> Please bidding other project </a>");
out.println("  </font></font>");
out.println("       </div>");
out.println("");
out.println("</div>");
out.println("      </td>");
out.println("");
out.println("");
out.println("    </tr>");
out.println("    <tr> </tr>");
out.println("    <tr> </tr>");
out.println("  </table>");
out.println("  <p>&nbsp; </p>");
out.println("</div>");
out.println("</div></body>");
out.println("</html>");
       out.flush();
    }

}


