'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace skyhighSeat
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SeatSoap", [Namespace]:="http://tempuri.org/skyhighWS/Service1")>  _
    Public Class Seat
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/skyhighWS/UpdateSeat.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/skyhighWS/Service1/UpdateSeat", RequestNamespace:="http://tempuri.org/skyhighWS/Service1", ResponseNamespace:="http://tempuri.org/skyhighWS/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateSeat(ByVal UpdateSeatSet As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("UpdateSeat", New Object() {UpdateSeatSet})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateSeat(ByVal UpdateSeatSet As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateSeat", New Object() {UpdateSeatSet}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateSeat(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
