[COREGEN.VHDL Component Instantiation.datamem]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component datamem"
text005="    port ("
text006="    din: IN std_logic_VECTOR(7 downto 0);"
text007="    rd_clk: IN std_logic;"
text008="    rd_en: IN std_logic;"
text009="    rst: IN std_logic;"
text010="    wr_clk: IN std_logic;"
text011="    wr_en: IN std_logic;"
text012="    almost_empty: OUT std_logic;"
text013="    almost_full: OUT std_logic;"
text014="    dout: OUT std_logic_VECTOR(7 downto 0);"
text015="    empty: OUT std_logic;"
text016="    full: OUT std_logic);"
text017="end component;"
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : datamem"
text026="        port map ("
text027="            din => din,"
text028="            rd_clk => rd_clk,"
text029="            rd_en => rd_en,"
text030="            rst => rst,"
text031="            wr_clk => wr_clk,"
text032="            wr_en => wr_en,"
text033="            almost_empty => almost_empty,"
text034="            almost_full => almost_full,"
text035="            dout => dout,"
text036="            empty => empty,"
text037="            full => full);"
text038=" "
type=template
[COREGEN.VHDL Component Instantiation.fifo1bit]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component fifo1bit"
text005="    port ("
text006="    din: IN std_logic_VECTOR(0 downto 0);"
text007="    rd_clk: IN std_logic;"
text008="    rd_en: IN std_logic;"
text009="    rst: IN std_logic;"
text010="    wr_clk: IN std_logic;"
text011="    wr_en: IN std_logic;"
text012="    almost_empty: OUT std_logic;"
text013="    almost_full: OUT std_logic;"
text014="    dout: OUT std_logic_VECTOR(0 downto 0);"
text015="    empty: OUT std_logic;"
text016="    full: OUT std_logic);"
text017="end component;"
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : fifo1bit"
text026="        port map ("
text027="            din => din,"
text028="            rd_clk => rd_clk,"
text029="            rd_en => rd_en,"
text030="            rst => rst,"
text031="            wr_clk => wr_clk,"
text032="            wr_en => wr_en,"
text033="            almost_empty => almost_empty,"
text034="            almost_full => almost_full,"
text035="            dout => dout,"
text036="            empty => empty,"
text037="            full => full);"
text038=" "
type=template
[COREGEN.VHDL Component Instantiation.tdque2]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component tdque2"
text005="    port ("
text006="    clk: IN std_logic;"
text007="    din: IN std_logic_VECTOR(15 downto 0);"
text008="    rd_en: IN std_logic;"
text009="    rst: IN std_logic;"
text010="    wr_en: IN std_logic;"
text011="    almost_empty: OUT std_logic;"
text012="    almost_full: OUT std_logic;"
text013="    dout: OUT std_logic_VECTOR(15 downto 0);"
text014="    empty: OUT std_logic;"
text015="    full: OUT std_logic);"
text016="end component;"
text017=""
text018=" "
text019="-------------------------------------------------------------"
text020=" "
text021="-- The following code must appear in the VHDL architecture body."
text022="-- Substitute your own instance name and net names."
text023=" "
text024="your_instance_name : tdque2"
text025="        port map ("
text026="            clk => clk,"
text027="            din => din,"
text028="            rd_en => rd_en,"
text029="            rst => rst,"
text030="            wr_en => wr_en,"
text031="            almost_empty => almost_empty,"
text032="            almost_full => almost_full,"
text033="            dout => dout,"
text034="            empty => empty,"
text035="            full => full);"
text036=" "
type=template
