package Sagent2;
import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.net.*;
import oracle.sql.*;
import java.lang.*;
import oracle.jdbc.driver.*;
import javax.servlet.http.HttpSession;
import org.jdom.*;
import org.jdom.output.XMLOutputter;
import org.jdom.Element;
import org.jdom.Document;
import org.jdom.input.DOMBuilder;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

public class Display extends HttpServlet{
  DriverManager driver;
  Connection conn;
  Statement stmt = null;
  ResultSet rst = null;
  String username,number,type,password;
  List property;
  List tags[];
  int count;
  public void doGet(HttpServletRequest req, HttpServletResponse res)
        throws ServletException, IOException
  {
    PrintWriter writer = res.getWriter();
    res.setContentType("text/html");
    HttpSession session = req.getSession(true);
    if (session.isNew()){res.sendRedirect("http://161.246.5.185:8080/Sagent/sendlogin.html");}
      else {
      username = (String)session.getValue("user.username");
      password = (String)session.getValue("user.password");
      if((username.length()==0)&&(password.length()==0)){
        res.sendRedirect("http://161.246.5.185:8080/Sagent/login.html");
      }else
      {
         DOMBuilder builder= new DOMBuilder();
         try{
            URL url =  new URL("http://161.246.5.185:8080/profile/"+username+".xml");
            Document doc = builder.build(url);
            Element root = doc.getRootElement();
            String Strtmp = root.getAttributeValue("count");
            Integer intTemp = new Integer(Strtmp);
            count = intTemp.intValue();
            if(count!=0){
              tags = new List[count];
              property = root.getChildren();
          	  writer.println("<html>");
          	  writer.println("<!-- #BeginTemplate \"/Templates/main.dwt\" --> ");
    	        writer.println("<head>");
          	  writer.println("<!-- #BeginEditable \"doctitle\" --> ");
          	  writer.println("<title>RealAgent...Your total solution</title>");
          	  writer.println("<!-- #EndEditable --> ");
          	  writer.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-874\">");
          	  writer.println("<style>");
          	  writer.println("a {text-decoration:none;font-size:14pt;font-family:Cordia New}");
              writer.println("table{font-size:14pt;font-family:Cordia New}");
              writer.println("div{font-size:14pt;font-family:Cordia New}");
              writer.println("font{font-size:14pt;font-family:Cordia New");
          	  writer.println("</style>");
          	  writer.println("<script language=\"JavaScript\">");
          	  writer.println("<!--");
              URL url2 = new URL("http://161.246.5.185:8080/display_head.txt");
              InputStream in = url2.openStream();
              InputStreamReader reader = new InputStreamReader(in,"latin1");
              BufferedReader bufferedReader = new BufferedReader(reader);
              String line;
              while((line = bufferedReader.readLine())!=null) {
              writer.println(MTThai.UnicodeToMS874(line));  }
          	  writer.println("function MM_displayStatusMsg(msgStr) { //v1.0");
          	  writer.println("  status=msgStr;");
          	  writer.println("  document.MM_returnValue = true;");
          	  writer.println("}");
          	  writer.println("");
          	  writer.println("function MM_swapImgRestore() { //v3.0");
          	  writer.println("  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;");
          	  writer.println("}");
          	  writer.println("");
          	  writer.println("function MM_preloadImages() { //v3.0");
          	  writer.println("  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();");
              writer.println("    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)");
          	  writer.println("    if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}");
          	  writer.println("}");
          	  writer.println("");
          	  writer.println("function MM_findObj(n, d) { //v4.0");
          	  writer.println("  var p,i,x;  if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {");
          	  writer.println("    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}");
          	  writer.println("  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];");
          	  writer.println("  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);");
          	  writer.println("  if(!x && document.getElementById) x=document.getElementById(n); return x;");
          	  writer.println("}");
          	  writer.println("");
          	  writer.println("function MM_swapImage() { //v3.0");
          	  writer.println("  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)");
          	  writer.println("   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}");
          	  writer.println("}");
          	  writer.println("//-->");
          	  writer.println("</script>");
          	  writer.println("<script language=\"JavaScript\">");
          	  writer.println("<!--");
          	  writer.println("function MM_reloadPage(init) {  //reloads the window if Nav4 resized");
          	  writer.println("  if (init==true) with (navigator) {if ((appName==\"Netscape\")&&(parseInt(appVersion)==4)) {");
          	  writer.println("    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}");
          	  writer.println("  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();");
          	  writer.println("}");
          	  writer.println("MM_reloadPage(true);");
          	  writer.println("// -->");
          	  writer.println("</script>");
          	  writer.println("</head>");
          	  writer.println("<body background=\"http://161.246.5.185:8080/Sagent/images/mycolloseum.jpg\" bgproperties=\"fixed\" bgcolor=\"#FFFFFF\" text=\"#000000\"  topmargin=\"0\" marginheight=\"0\" leftmargin=\"0\" marginwidth=\"0\" link=\"#0099FF\" onLoad=\"MM_preloadImages('../images/ed_profiley.jpg','../images/searchy.jpg','../images/posty.jpg','../images/logouty.jpg','../images/mainy.jpg')\" vlink=\"#0099FF\" alink=\"#FF9933\">");
          	  writer.println("<table width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
          	  writer.println("  <tr> ");
          	  writer.println("    <td><img src=\"../images/blackline.GIF\" width=\"640\" height=\"2\"></td>");
          	  writer.println("  </tr>");
          	  writer.println("</table>");
          	  writer.println("<table width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
          	  writer.println("  <tr> ");
          	  writer.println("    <td bgcolor=\"#003399\" width=\"235\"><img src=\"../images/logo2.GIF\" width=\"160\" height=\"44\"></td>");
          	  writer.println("    <td bgcolor=\"#003399\" width=\"404\"> ");
          	  writer.println("      <table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#000000\">");
          	  writer.println("        <tr> ");
          	  writer.println("          <td width=\"19%\"><img src=\"../images/building3.jpg\" width=\"74\" height=\"70\"></td>");
          	  writer.println("          <td width=\"81%\"><img src=\"../images/banner.gif\" width=\"330\" height=\"70\"></td>");
          	  writer.println("        </tr>");
          	  writer.println("      </table>");
          	  writer.println("    </td>");
          	  writer.println("  </tr>");
          	  writer.println("</table>");
        	    writer.println("<table width=\"160\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
          	  writer.println("  <tr> ");
          	  writer.println("    <td><img src=\"../images/line.GIF\" width=\"640\" height=\"2\"></td>");
          	  writer.println("  </tr>");
          	  writer.println("</table>");
          	  writer.println("<table width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"5\">");
          	  writer.println("  <tr> ");
          	  writer.println("    <td background=\"../images/gradient.jpg\" > ");
          	  writer.println("      <div align=\"center\"></div>");
          	  writer.println("      <div align=\"center\"><font color=\"#FFFFFF\"><b> ");
          	  writer.println("        <script>");
        	    writer.println("			  var mont= new Array('January','February','March','April','May','June','July','August','September','October','November','December');");
          	  writer.println("			  currentdate=new Date();");
          	  writer.println("			  document.write(mont[currentdate.getMonth()]+' '+currentdate.getDate()+', '+currentdate.getYear());");
          	  writer.println("			  </script>");
          	  writer.println("        </b></font></div>");
          	  writer.println("    </td>");
          	  writer.println("  </tr>");
          	  writer.println("</table>");
          	  writer.println("<table width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"0\">");
          	  writer.println("  <tr> ");
          	  writer.println("    <td><img src=\"../images/blackline.GIF\" width=\"640\" height=\"2\"></td>");
          	  writer.println("  </tr>");
          	  writer.println("</table>");
          	  writer.println("<table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#003399\">");
              writer.println("  <tr> ");
          	  writer.println("    <td width=\"160\" bgcolor=\"#003399\" background=\"../images/building5.jpg\" valign=\"top\"> ");
          	  writer.println("      <div align=\"center\"><!-- #BeginEditable \"menubar\" --> <br>");
          	  writer.println("        <table width=\"154\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">");
          	  writer.println("          <tr> ");
          	  writer.println("            <td><a href=\"Templates/index.html\" onMouseOver=\"MM_displayStatusMsg('Home');return document.MM_returnValue\" onMouseOut=\"MM_displayStatusMsg('');return document.MM_returnValue\"></a><a href=\"../main.html\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('homex','','../images/mainy.jpg',1);MM_displayStatusMsg('Main');return document.MM_returnValue\"><img src=\"../images/mainx.jpg\" width=\"150\" height=\"30\" border=\"0\" name=\"homex\" onLoad=\"\"></a></td>");
          	  writer.println("          </tr>");
          	  writer.println("          <tr> ");
          	  writer.println("            <td><a href=\"Templates/login.html\" onMouseOver=\"MM_displayStatusMsg('Member Login');return document.MM_returnValue\" onMouseOut=\"MM_displayStatusMsg('');return document.MM_returnValue\"></a><a href=\"../profile.html\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('Image1','','../images/ed_profiley.jpg',1);MM_displayStatusMsg('Edit Profile');return document.MM_returnValue\"><img src=\"../images/ed_profilex.jpg\" width=\"150\" height=\"30\" border=\"0\" name=\"Image1\"></a></td>");
          	  writer.println("          </tr>");
          	  writer.println("          <tr> ");
          	  writer.println("            <td><a href=\"Templates/register.html\" onMouseOver=\"MM_displayStatusMsg('Register');return document.MM_returnValue\" onMouseOut=\"MM_displayStatusMsg('');return document.MM_returnValue\"></a><a href=\"../search.html\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('Image2','','../images/searchy.jpg',1);MM_displayStatusMsg('Search');return document.MM_returnValue\"><img src=\"../images/searchx.JPG\" width=\"150\" height=\"30\" border=\"0\" name=\"Image2\"></a></td>");
          	  writer.println("          </tr>");
          	  writer.println("          <tr> ");
          	  writer.println("            <td><a href=\"Templates/services.html\" onMouseOver=\"MM_displayStatusMsg('Services');return document.MM_returnValue\" onMouseOut=\"MM_displayStatusMsg('');return document.MM_returnValue\"></a><a href=\"../post.html\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('Image3','','../images/posty.jpg',1);MM_displayStatusMsg('Post');return document.MM_returnValue\"><img src=\"../images/postx.jpg\" width=\"150\" height=\"30\" border=\"0\" name=\"Image3\"></a></td>");
          	  writer.println("          </tr>");
          	  writer.println("          <tr> ");
          	  writer.println("            <td><a href=\"http://161.246.5.185:8080/Sagent/servlet/Sagent2.Logout\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('Image4','','../images/logouty.jpg',1);MM_displayStatusMsg('Logout');return document.MM_returnValue\"><img src=\"../images/logoutx.jpg\" width=\"150\" height=\"30\" border=\"0\" name=\"Image4\"></a></td>");
          	  writer.println("          </tr>");
          	  writer.println("        </table>");
          	  writer.println("        <p>&nbsp;</p>");
          	  writer.println("        <!-- #EndEditable --><br>");
          	  writer.println("        <br>");
          	  writer.println("        <br>");
          	  writer.println("        <br>");
          	  writer.println("        <br>");
          	  writer.println("        <br>");
          	  writer.println("        <br>");
        	    writer.println("        <br>");
          	  writer.println("        <br>");
        	    writer.println("        <br>");
          	  writer.println("        <br>");
          	  writer.println("        <br>");
          	  writer.println("        <br>");
          	  writer.println("      </div>");
              writer.println("    </td>");
          	  writer.println("    <td width=\"100%\" valign=\"top\" bgcolor=\"#FFFFFF\"> ");
          	  writer.println("      <div align=\"right\"> ");
          	  writer.println("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"10\">");
          	  writer.println("          <tr> ");
          	  writer.println("            <td> <!-- #BeginEditable \"content\" --><br>");
          	  writer.println("              <img src=\"../images/your_spec.GIF\" width=\"268\" height=\"20\"><br>");
          	  writer.println("              <img src=\"../images/line.GIF\" width=\"100%\" height=\"2\"> <br>");
          	  writer.println("              <div id=\"Layer1\" style=\"position:relative; width:100%; height:500px; z-index:1; overflow: scroll\"> ");
          	  writer.println("                <table border=\"1\" height=\"20\" width=\"100%\" cellpadding=\"2\" bordercolor=\"#000000\">");
          	  writer.println("                  <tr> ");
              writer.println("                    <td height=\"20\" width=\"30\" bgcolor=\"#FF9933\"> ");
              writer.println("                      <table border=\"1\" cellspacing=\"0\" cellpadding=\"2\" bordercolor=\"#000000\"><tr>");
          	  writer.println("                         <td><div align=\"center\"><font face=\"Courier New, Courier, mono\" >number</font></div></td>");
              writer.println("                      </tr>");
              writer.println("                      <tr>");
              writer.println("                        <td><div align=\"center\"><font face=\"Courier New, Courier, mono\" >found</font></div></td>");
              writer.println("                      </tr></table>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"45\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >type</font></div>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"15\" bgcolor=\"#FF9933\"> ");
              writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >need ");
          	  writer.println("                        to </font></div>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"25\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >size</font></div>");
          	  writer.println("                    </td>");
              writer.println("                    <td height=\"20\" width=\"20\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >price</font></div>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"35\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >bedroom</font></div>");
          	  writer.println("                    </td>");
              writer.println("                    <td height=\"20\" width=\"35\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >bathroom</font></div>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"35\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >kitchen</font></div>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"35\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >laundry</font></div>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"45\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >furnished</font></div>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"45\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >swimming ");
          	  writer.println("                        pool </font></div>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"35\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >fitness</font></div>");
          	  writer.println("                    </td>");
          	  writer.println("                    <td height=\"20\" width=\"50\" bgcolor=\"#FF9933\"> ");
          	  writer.println("                      <div align=\"center\"><font face=\"Courier New, Courier, mono\" >location</font></div>");
          	  writer.println("                    </td>");
              /*writer.println("    <td height=\"20\" width=\"71\">");
              writer.println("      <div align=\"center\">");
              writer.println("        <form name=\"form1\" method=\"post\" action=\"http://161.246.5.185:8080/Sagent/servlet/Sagent2.SendRedirect\">");
              writer.println("          <input type=\"hidden\" name=\"url\" value=\"http://161.246.5.185:8080/Sagent/search.html\">");
              writer.println("          <input type=\"submit\" name=\"Submit\" value=\"New Search\">");
              writer.println("        </form>");
              writer.println("        <font face=\"Courier New, Courier, mono\"><font face=\"Courier New, Courier, mono\"><font face=\"Courier New, Courier, mono\"><font ><font><font ><font ></font></font></font></font></font></font></font></div>");
              writer.println("    </td>");*/
              writer.println("    <td height=\"20\" width=\"40\">");
              writer.println("      <div align=\"center\"><font face=\"Courier New, Courier, mono\"><font face=\"Courier New, Courier, mono\"><font face=\"Courier New, Courier, mono\"><font ><font ><font ><font ></font></font></font></font></font></font></font></div>");
              writer.println("    </td>");
              writer.println("    <td height=\"20\" width=\"71\">");
              writer.println("      <div align=\"center\"><font face=\"Courier New, Courier, mono\"><font face=\"Courier New, Courier, mono\"><font face=\"Courier New, Courier, mono\"><font ><font ><font><font ></font></font></font></font></font></font></font></div>");
              writer.println("    </td>");
              writer.println("  </tr>");
              for(int i=0;i<count;i++){
                Element temp1 = (Element)property.get(i);
                tags[i] = temp1.getChildren();
                Element temp2;
                writer.println("<tr>");
                writer.println("<td height=\"20\" width=\"30\" bgcolor=\"#CCCCCC\">");
                writer.println("  <center><table border=\"1\" cellspacing=\"0\" cellpadding=\"2\" bordercolor=\"#000000\"><tr>");
                writer.println("    <tr><td><div align=\"center\"><font face=\"Courier New, Courier, mono\" >"+temp1.getAttributeValue("number")+"</font></div></td></tr>");
                writer.println("    <tr><td><div align=\"center\"><font face=\"Courier New, Courier, mono\" >"+temp1.getAttributeValue("found")+"</font></div></td></tr>");
                writer.println("</table></center></td>");
                writer.println("<td height=\"20\" width=\"45\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" >"+temp1.getAttributeValue("type")+"</font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(0);
                writer.println("<td height=\"20\" width=\"15\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" >"+temp2.getText()+"</font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(1);
                writer.println("<td height=\"20\" width=\"25\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" ><script language=\"JavaScript\">document.write(sizelabel["+temp2.getText()+"]);</script></font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(2);
                writer.println("<td height=\"20\" width=\"40\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" ><script language=\"JavaScript\">document.write(priceArray["+temp2.getText()+"]);</script></font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(3);
                writer.println("<td height=\"20\" width=\"35\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" ><script language=\"JavaScript\">document.write(bedroom["+temp2.getText()+"]);</script></font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(4);
                writer.println("<td height=\"20\" width=\"35\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" ><script language=\"JavaScript\">document.write(bathroom["+temp2.getText()+"]);</script></font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(5);
                writer.println("<td height=\"20\" width=\"35\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" >"+temp2.getText()+"</font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(6);
                writer.println("<td height=\"20\" width=\"35\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" >"+temp2.getText()+"</font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(7);
                writer.println("<td height=\"20\" width=\"45\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" >"+temp2.getText()+"</font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(8);
                writer.println("<td height=\"20\" width=\"45\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" >"+temp2.getText()+"</font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(9);
                writer.println("<td height=\"20\" width=\"35\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" >"+temp2.getText()+"</font></div>");
                writer.println("</td>");
                temp2 = (Element)tags[i].get(10);
                java.util.List address = temp2.getChildren();
                Element temp4 = (Element)address.get(0);
                Element temp3 = (Element)address.get(1);
                writer.println("<td height=\"20\" width=\"50\" bgcolor=\"#CCCCCC\">");
                writer.println("  <div align=\"center\"><font face=\"Courier New, Courier, mono\" >"/*<script language=\"JavaScript\">document.write(provinceArray["*/+MTThai.UnicodeToMS874(temp3.getText())/*"]);"</script>"*/);
                writer.println("  in  "/*<script language=\"JavaScript\">"/*document.write(areaArray["+temp4.getText()+"]["*/+MTThai.UnicodeToMS874(temp4.getText())+/*"]);</script>*/"</font></div>");
                writer.println("</td>");
/*                writer.println("<td height=\"20\" width=\"71\" bgcolor=\"#CCCCCC\"> <font > </font>");
                writer.println("  <form name=\"form2\" method=\"post\" action=\"http://161.246.5.185:8080/Sagent/servlet/Sagent2.EditSpec\">");
                writer.println("    <font >");
                writer.println("    <input type=\"hidden\" name=\"number\" value=\""+temp1.getAttributeValue("number")+"\">");
                writer.println("    <input type=\"submit\" name=\"Submit\" value=\"Edit\">");
                writer.println("    </font>");
                writer.println("  </form>");
                writer.println("  <font > </font></td>"); */
                writer.println("<td height=\"20\" width=\"40\" bgcolor=\"#CCCCCC\"> <font > </font>");
                writer.println("  <form name=\"form3\" method=\"post\" action=\"http://161.246.5.185:8080/Sagent/servlet/Sagent2.Remove\">");
                writer.println("    <font >");
                writer.println("    <input type=\"hidden\" name=\"number\" value=\""+temp1.getAttributeValue("number")+"\">");
                writer.println("    <input type=\"submit\" name=\"Submit\" value=\"remove\">");
                writer.println("    </font>");
                writer.println("  </form>");
                writer.println("  <font > </font></td>");
                writer.println("<td height=\"20\" width=\"71\" bgcolor=\"#CCCCCC\"> <font > </font>");
                writer.println("  <form name=\"form4\" method=\"post\" action=\"http://161.246.5.185:8080/Sagent/servlet/Sagent2.Search\">");
                writer.println("    <font >");
                writer.println("    <input type=\"hidden\" name=\"number\" value=\""+temp1.getAttributeValue("number")+"\">");
                writer.println("    <input type=\"submit\" name=\"Submit\" value=\"Search\">");
                writer.println("    </font>");
                writer.println("  </form>");
                writer.println("  <font > </font></td>");
                writer.println("</tr>");
              }
          writer.println("</table>");
          writer.println("</body>");
          writer.println("</html>");
          writer.close();
        }else
        {
      	  res.sendRedirect("http://161.246.5.185:8080/Sagent/havenospecs.html");
        }
      }catch(Exception e){
        writer.println(e.getMessage());
        e.printStackTrace(writer);
      }
    }
    }
  }
}