package Sagent2;
import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.net.*;
import oracle.sql.*;
import java.lang.*;
import oracle.jdbc.driver.*;
import javax.servlet.http.HttpSession;
public class EditInfo extends HttpServlet {
  DriverManager driver;
  Connection conn;
  Statement stmt = null;
  ResultSet rst = null;
  String username,password,name,lastname,tel,age,sex,mobile,fax,beeper,email,address;
  public void doGet(HttpServletRequest req, HttpServletResponse res)
        throws ServletException, IOException
  {
    PrintWriter writer = res.getWriter();
    res.setContentType("text/html");
    HttpSession session = req.getSession(true);
    if (session.isNew()){res.sendRedirect("http://161.246.5.185:8080/Sagent/sendlogin.html");}
    else{
    username = (String)session.getValue("user.username");
    if(username.length()==0){

    }else
    {
      password  = (String)session.getValue("user.password");
      try{
         driver.registerDriver(new OracleDriver());
         conn = driver.getConnection("jdbc:oracle:thin:@161.246.5.185:1521:Sagent","scott","tiger");
         stmt = conn.createStatement();
         rst = stmt.executeQuery("select * from member_attribute where username = '"+username+"'");
         rst.next();
         name = rst.getString(3);
         lastname = rst.getString(4);
         sex = rst.getString(5);
         age = rst.getString(6);
         tel = rst.getString(7);
         fax = rst.getString(8);
         mobile = rst.getString(9);
         beeper = rst.getString(10);
         address = rst.getString(11);
         email = rst.getString(12);
         writer.println("<html><!-- #BeginTemplate \"/Templates/main.dwt\" -->");
	  writer.println("<head>");
	  writer.println("<!-- #BeginEditable \"doctitle\" --> ");
	  writer.println("<title>RealAgent...Your total solution</title>");
	  writer.println("<!-- #EndEditable --> ");
	  writer.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-874\">");
	  writer.println("<style>");
 	  writer.println("a {text-decoration:none;font-size:14pt;font-family:Cordia New}");
    writer.println("table{font-size:14pt;font-family:Cordia New}");
    writer.println("div{font-size:14pt;font-family:Cordia New}");
	  writer.println("</style>");
	  writer.println("<script language=\"JavaScript\">");
	  writer.println("<!--");
	  writer.println("function MM_displayStatusMsg(msgStr) { //v1.0");
	  writer.println("  status=msgStr;");
	  writer.println("  document.MM_returnValue = true;");
	  writer.println("}");
	  writer.println("");
	  writer.println("function MM_swapImgRestore() { //v3.0");
	  writer.println("  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;");
	  writer.println("}");
	  writer.println("");
	  writer.println("function MM_preloadImages() { //v3.0");
	  writer.println("  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();");
	  writer.println("    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)");
	  writer.println("    if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}");
	  writer.println("}");
	  writer.println("");
	  writer.println("function MM_findObj(n, d) { //v4.0");
	  writer.println("  var p,i,x;  if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {");
	  writer.println("    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}");
	  writer.println("  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];");
	  writer.println("  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);");
	  writer.println("  if(!x && document.getElementById) x=document.getElementById(n); return x;");
	  writer.println("}");
	  writer.println("");
	  writer.println("function MM_swapImage() { //v3.0");
	  writer.println("  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)");
	  writer.println("   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}");
	  writer.println("}");
	  writer.println("");
	  writer.println("function MM_validateForm() { //v4.0");
	  writer.println("  var i,p,q,nm,test,num,min,max,errors='',args=MM_validateForm.arguments;");
	  writer.println("  for (i=0; i<(args.length-2); i+=3) { test=args[i+2]; val=MM_findObj(args[i]);");
	  writer.println("    if (val) { nm=val.name; if ((val=val.value)!=\"\") {");
	  writer.println("      if (test.indexOf('isEmail')!=-1) { p=val.indexOf('@');");
	  writer.println("        if (p<1 || p==(val.length-1)) errors+='- '+nm+' must contain an e-mail address.\n';");
	  writer.println("      } else if (test!='R') {");
	  writer.println("        if (isNaN(val)) errors+='- '+nm+' must contain a number.\n';");
	  writer.println("        if (test.indexOf('inRange') != -1) { p=test.indexOf(':');");
	  writer.println("          min=test.substring(8,p); max=test.substring(p+1);");
	  writer.println("          if (val<min || max<val) errors+='- '+nm+' must contain a number between '+min+' and '+max+'.\n';");
	  writer.println("    } } } else if (test.charAt(0) == 'R') errors += '- '+nm+' is required.\n'; }");
	  writer.println("  } if(document.editprofile_form.newpassword.value!=document.editprofile_form.repassword.value)");
	  writer.println("     errors+='- New password confirmation doesn\'t match.\n';");
	  writer.println("    if (errors) alert('The following error(s) occurred:\n'+errors);");
	  writer.println("  document.MM_returnValue = (errors == '');");
	  writer.println("}");
	  writer.println("//-->");
	  writer.println("</script>");
	  writer.println("<script language=\"JavaScript\">");
	  writer.println("<!--");
	  writer.println("function MM_reloadPage(init) {  //reloads the window if Nav4 resized");
	  writer.println("  if (init==true) with (navigator) {if ((appName==\"Netscape\")&&(parseInt(appVersion)==4)) {");
	  writer.println("    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}");
	  writer.println("  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();");
	  writer.println("}");
	  writer.println("MM_reloadPage(true);");
	  writer.println("// -->");
	  writer.println("</script>");
	  writer.println("</head>");
	  writer.println("");
	  writer.println("<body background=\"http://161.246.5.185:8080/Sagent/images/mycolloseum.jpg\" bgproperties=\"fixed\"  bgcolor=\"#FFFFFF\" text=\"#000000\"  topmargin=\"0\" marginheight=\"0\" leftmargin=\"0\" marginwidth=\"0\" link=\"#0099FF\" onLoad=\"MM_preloadImages('../images/ed_profiley.jpg','../images/searchy.jpg','../images/posty.jpg','../images/logouty.jpg','../images/mainy.jpg')\" vlink=\"#0099FF\" alink=\"#FF9933\">");
	  writer.println("<table width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
	  writer.println("  <tr>");
	  writer.println("    <td><img src=\"../images/blackline.GIF\" width=\"640\" height=\"2\"></td>");
	  writer.println("  </tr>");
	  writer.println("</table>");
	  writer.println("<table width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
	  writer.println("  <tr> ");
	  writer.println("    <td bgcolor=\"#003399\" width=\"235\"><img src=\"../images/logo2.GIF\" width=\"160\" height=\"44\"></td>");
	  writer.println("    <td bgcolor=\"#003399\" width=\"404\">");
	  writer.println("      <table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#000000\">");
	  writer.println("        <tr> ");
	  writer.println("          <td width=\"19%\"><img src=\"../images/building3.jpg\" width=\"74\" height=\"70\"></td>");
	  writer.println("          <td width=\"81%\"><img src=\"../images/banner.gif\" width=\"330\" height=\"70\"></td>");
	  writer.println("        </tr>");
	  writer.println("      </table>");
	  writer.println("    </td>");
	  writer.println("  </tr>");
	  writer.println("</table>");
	  writer.println("<table width=\"160\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
	  writer.println("  <tr>");
	  writer.println("    <td><img src=\"../images/line.GIF\" width=\"640\" height=\"2\"></td>");
	  writer.println("  </tr>");
	  writer.println("</table>");
	  writer.println("<table width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"5\">");
	  writer.println("  <tr> ");
	  writer.println("    <td background=\"../images/gradient.jpg\" > ");
	  writer.println("      <div align=\"center\"></div>");
	  writer.println("      <div align=\"center\"><font color=\"#FFFFFF\"><b> <script>");
	  writer.println("			  var mont= new Array('January','February','March','April','May','June','July','August','September','October','November','December');");
	  writer.println("			  currentdate=new Date();");
	  writer.println("			  document.write(mont[currentdate.getMonth()]+' '+currentdate.getDate()+', '+currentdate.getYear());");
	  writer.println("			  </script></b></font></div>");
	  writer.println("    </td>");
	  writer.println("  </tr>");
	  writer.println("</table>");
	  writer.println("<table width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"0\">");
	  writer.println("  <tr>");
	  writer.println("    <td><img src=\"../images/blackline.GIF\" width=\"640\" height=\"2\"></td>");
	  writer.println("  </tr>");
	  writer.println("</table>");
	  writer.println("<table width=\"640\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#003399\">");
	  writer.println("  <tr> ");
	  writer.println("    <td width=\"160\" bgcolor=\"#003399\" background=\"../images/building5.jpg\" valign=\"top\"> ");
	  writer.println("      <div align=\"center\"><!-- #BeginEditable \"menubar\" --> <br>");
	  writer.println("        <table width=\"154\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">");
	  writer.println("          <tr> ");
	  writer.println("            <td><a href=\"Templates/index.html\" onMouseOver=\"MM_displayStatusMsg('Home');return document.MM_returnValue\" onMouseOut=\"MM_displayStatusMsg('');return document.MM_returnValue\"></a><a href=\"../main.html\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('homex','','../images/mainy.jpg',1);MM_displayStatusMsg('Main');return document.MM_returnValue\"><img src=\"../images/mainx.jpg\" width=\"150\" height=\"30\" border=\"0\" name=\"homex\" onLoad=\"\"></a></td>");
	  writer.println("          </tr>");
	  writer.println("          <tr> ");
	  writer.println("            <td><a href=\"Templates/login.html\" onMouseOver=\"MM_displayStatusMsg('Member Login');return document.MM_returnValue\" onMouseOut=\"MM_displayStatusMsg('');return document.MM_returnValue\"></a><a href=\"../profile.html\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('Image1','','../images/ed_profiley.jpg',1);MM_displayStatusMsg('Edit Profile');return document.MM_returnValue\"><img src=\"../images/ed_profilex.jpg\" width=\"150\" height=\"30\" border=\"0\" name=\"Image1\"></a></td>");
	  writer.println("          </tr>");
	  writer.println("          <tr> ");
	  writer.println("            <td><a href=\"Templates/register.html\" onMouseOver=\"MM_displayStatusMsg('Register');return document.MM_returnValue\" onMouseOut=\"MM_displayStatusMsg('');return document.MM_returnValue\"></a><a href=\"../search.html\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('Image2','','../images/searchy.jpg',1);MM_displayStatusMsg('Search');return document.MM_returnValue\"><img src=\"../images/searchx.JPG\" width=\"150\" height=\"30\" border=\"0\" name=\"Image2\"></a></td>");
	  writer.println("          </tr>");
	  writer.println("          <tr> ");
	  writer.println("            <td><a href=\"Templates/services.html\" onMouseOver=\"MM_displayStatusMsg('Services');return document.MM_returnValue\" onMouseOut=\"MM_displayStatusMsg('');return document.MM_returnValue\"></a><a href=\"../post.html\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('Image3','','../images/posty.jpg',1);MM_displayStatusMsg('Post');return document.MM_returnValue\"><img src=\"../images/postx.jpg\" width=\"150\" height=\"30\" border=\"0\" name=\"Image3\"></a></td>");
	  writer.println("          </tr>");
	  writer.println("          <tr> ");
	  writer.println("            <td><a href=\"http://161.246.5.185:8080/Sagent/servlet/Sagent2.Logout\" onMouseOut=\"MM_swapImgRestore();MM_displayStatusMsg('');return document.MM_returnValue\" onMouseOver=\"MM_swapImage('Image4','','../images/logouty.jpg',1);MM_displayStatusMsg('Logout');return document.MM_returnValue\"><img src=\"../images/logoutx.jpg\" width=\"150\" height=\"30\" border=\"0\" name=\"Image4\"></a></td>");
	  writer.println("          </tr>");
	  writer.println("        </table>");
	  writer.println("        <p>&nbsp;</p>");
	  writer.println("        <!-- #EndEditable --><br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("        <br>");
	  writer.println("      </div>");
	  writer.println("    </td>");
	  writer.println("    <td width=\"480\" valign=\"top\" bgcolor=\"#FFFFFF\"> ");
	  writer.println("      <div align=\"right\">");
	  writer.println("        <table width=\"435\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
	  writer.println("          <tr>");
	  writer.println("            <td> <!-- #BeginEditable \"content\" --><br>");
	  writer.println("              <img src=\"../images/ed_profile.GIF\" width=\"170\" height=\"20\"><br>");
	  writer.println("              <br>");
	  writer.println("			  <form name=\"editprofile_form\" method=\"post\" action=\"http://161.246.5.185:8080/Sagent/servlet/Sagent2.Update\">");
	  writer.println("                <div id=\"Layer1\" style=\"position:relative; width:400px; height:475px; z-index:1; overflow: auto\">");
	  writer.println("				                 ");
	  writer.println("                  <table width=\"400\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Old Password </font></b></td>");
	  writer.println("                      <td width=\"250\"> ");
	  writer.println("                        <p><b><font color=\"#003399\"> ");
	  writer.println("                          <input type=\"password\" name=\"password\" size=\"12\" maxlength=\"8\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\">");
	  writer.println("                          <b><font color=\"#FF0000\">* </font></b></font></b></p>");
	  writer.println("                      </td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">New Password</font></b></td>");
	  writer.println("                      <td width=\"250\"> ");
	  writer.println("                        <input type=\"password\" name=\"newpassword\" size=\"12\" maxlength=\"8\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\">");
	  writer.println("                        <b><font color=\"#003399\"><b><font color=\"#0000FF\">*</font></b></font> ");
	  writer.println("                        </b></td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Confirm Password ");
	  writer.println("                        </font></b></td>");
	  writer.println("                      <td width=\"250\"><b><font color=\"#003399\"> ");
	  writer.println("                        <input type=\"password\" name=\"repassword\" size=\"12\" maxlength=\"8\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\">");
	  writer.println("                        <b><font color=\"#0000FF\">*</font></b></font></b></td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Name </font></b></td>");
	  writer.println("                      <td width=\"250\"><b><font color=\"#003399\"> ");
	  writer.println("                        <input type=\"text\" name=\"name\" size=\"12\" maxlength=\"30\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\" value=\""+MTThai.UnicodeToMS874(name)+"\">");
	  writer.println("                        <b><font color=\"#FF0000\">*</font></b></font> </b></td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Lastname </font></b></td>");
	  writer.println("                      <td width=\"250\"><b><font color=\"#003399\"> ");
	  writer.println("                        <input type=\"text\" name=\"lastname\" size=\"12\" maxlength=\"30\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\" value=\""+MTThai.UnicodeToMS874(lastname)+"\">");
	  writer.println("                        <b><font color=\"#FF0000\">*</font></b></font> </b></td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Age </font></b></td>");
	  writer.println("                      <td width=\"250\"><b><font color=\"#003399\"> ");
	  writer.println("                        <input type=\"text\" name=\"age\" size=\"3\" maxlength=\"3\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\" value=\""+age+"\">");
	  writer.println("                        <b><font color=\"#FF0000\">*</font></b></font></b></td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Sex</font></b></td>");
	  writer.println("                      <td width=\"250\"> <b><font color=\"#003399\"> ");
	  writer.println("                        <select name=\"sex\">");
	  writer.println("                          <option value=\"male\">male</option>");
	  writer.println("                          <option value=\"female\">female</option>");
	  writer.println("                        </select>");
	  writer.println("                        </font></b></td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Address </font></b></td>");
	  writer.println("                      <td width=\"250\"><b><font color=\"#003399\"> ");
	  writer.println("                        <input type=\"text\" name=\"address\" size=\"35\" maxlength=\"255\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\" value=\""+MTThai.UnicodeToMS874(address)+"\">");
	  writer.println("                        <b><font color=\"#FF0000\">*</font></b></font> </b></td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Email </font></b></td>");
	  writer.println("                      <td width=\"250\"><b><font color=\"#003399\"> ");
	  writer.println("                        <input type=\"text\" name=\"email\" size=\"12\" maxlength=\"30\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\" value=\""+email+"\">");
	  writer.println("                        <b><font color=\"#FF0000\">*</font></b></font> </b></td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Phone </font></b></td>");
	  writer.println("                      <td width=\"250\"> ");
	  writer.println("                        <input type=\"text\" name=\"tel\" size=\"12\" maxlength=\"12\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\" value=\""+tel+"\">");
	  writer.println("                        <font color=\"#003399\"><b><font color=\"#FF0000\">*</font></b></font> ");
	  writer.println("                      </td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Fax </font></b></td>");
	  writer.println("                      <td width=\"250\"> ");
  if (fax==null){ 	  writer.println("                        <input type=\"text\" name=\"fax\" size=\"12\" maxlength=\"12\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\">");}
else{ writer.println("                        <input type=\"text\" name=\"fax\" size=\"12\" maxlength=\"12\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\" value=\""+fax+"\">");}
	  writer.println("                      </td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Mobile</font></b></td>");
	  writer.println("                      <td width=\"250\"> ");
  if (mobile==null){	  writer.println("                        <input type=\"text\" name=\"mobile\" size=\"12\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\">");}
else{	  writer.println("                        <input type=\"text\" name=\"mobile\" size=\"12\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\" value=\""+mobile+"\">");}
	  writer.println("                      </td>");
	  writer.println("                    </tr>");
	  writer.println("                    <tr> ");
	  writer.println("                      <td width=\"150\"><b><font color=\"#003399\">Beeper</font></b></td>");
	  writer.println("                      <td width=\"250\"> ");
  if (beeper==null){writer.println("                        <input type=\"text\" name=\"beeper\" size=\"12\" maxlength=\"12\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\">");}
else{    writer.println("                        <input type=\"text\" name=\"beeper\" size=\"12\" maxlength=\"12\" style=\"border-width= 1pt;border-color: '#000000';background-color:white;color:'#666666'\" value=\""+beeper+"\">");}
	  writer.println("                      </td>");
	  writer.println("                    </tr>");
	  writer.println("                  </table>");
	  writer.println("			    <input type=\"submit\" name=\"Submit\" value=\"Submit\" onClick=\"MM_validateForm('name','','R','lastname','','R','age','','RisNum','address','','R','email','','RisEmail','tel','','RisNum','fax','','NisNum','mobile','','NisNum','beeper','','NisNum','password','','R');return document.MM_returnValue\">");
	  writer.println("                <br>");
	  writer.println("                <b><font color=\"#003399\"> <b><font color=\"#0000FF\">*</font></b></font></b> ");
	  writer.println("                <font color=\"#0000FF\" size=\"-1\">leave blank if you don't want ");
	  writer.println("                to change </font><br>");
	  writer.println("");
	  writer.println("				</div>");
	  writer.println("              </form>");
	  writer.println("              <!-- #EndEditable --></td>");
	  writer.println("          </tr>");
	  writer.println("        </table>");
	  writer.println("      </div>");
	  writer.println("    </td>");
	  writer.println("  </tr>");
	  writer.println("</table>");
	  writer.println("<div align=\"center\"><br>");
	  writer.println("  &copy; Hitman and Zatan Co.,Ltd 2001 All Rights Reserved</div>");
	  writer.println("</body>");
	  writer.println("<!-- #EndTemplate --></html>");
         writer.close();
      }catch(Exception e){}
    }
    }
  }
}