# libcsuCommon2.a uses csuSubspaceCVEigen.h
#that's not MIT license but openCV license so stop to use temporary

noinst_LIBRARIES = libcsuCommon.a
#libcsuCommon2.a

libcsuCommon_a_SOURCES = csuCommonMatrix.c csuCommonFile.c csuCommonUtil.c csuCommonSubspace.c  csuCommonCommandLine.c csuCommonImage.c csuEBGMUtil.c csuEBGMSimilarity.c

#libcsuCommon2_a_SOURCES = $(libcsuCommon_a_SOURCES) csuSubspaceEigen.c csuSubspaceFisher.c csuSubspaceCVEigen.c csuSubspaceEigen.h csuSubspaceFisher.h csuSubspaceCVEigen.h

noinst_HEADERS =  csuCommonMatrix.h csuCommonFile.h csuCommonUtil.h csuCommonSubspace.h  csuCommonCommandLine.h csuCommonImage.h csuEBGMUtil.h csuEBGMSimilarity.h 




