#lksjdl;fjs;adflj;sdjf;sdajd;fl
#dlsj;alfkjsdlkfjsldkjfl;ksdajfl;jsa

user_name: "ids"

passwd: "audit_detail"

server_address: "127.0.0.1"
server_port: 3000
buffer_size: 256


#tkjfl ;jl;ajsd;lfjsda;lfj;saldjkf;lsdakjf;lkjsda;dlkfjasd;ild
seq_length: 6  #dasl;fjasdd;lfkj;sdalkjf;l

#ldksjd;lfkjls;dkjf;lksjad;kfljsa;ldkjf;lkasjd;f
max_diff_sc: 500  #adsfalsd;jl;fkjsa;ldkjfl

#lkdsajf;lksjd;lfkjsd;alkjf;lksajd;flkjsda;lkfj;alsd
add_to_db: 0  #lkdjsa;ldfkj;lsdakjf;lksdajl;fj0

#lkdjsa;flkjsd;lkfj;lsdkajf;kljsad;lkfj;alskdjf;l
hmd_on: 1 #dasfl;askdjf;lksdj;flk

#dklsajf;lkjasd;lfjl;askjdf;lkasddj;flkjasd;lkfj;asdl
report_anomall_seq: 1

#jlkj;lkj;lkj;lksdjf;lkasdjf;lksdja;lfkjsd;alkfj;sdlkfj
report_all: 1

keep_seq_file: 1

print_result_to_screen: 1

num_anomall_seq_alert: 1

#lkdsjaf;lksjd;flkasdj;flkjasd;lkfjsad;lkfj;asddlkjf;lasddkjf
DetectProcessName: "ls,ps,cat,netstat,ping"


