//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dict.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DICT_FORM                   101
#define IDP_FAILED_OPEN_DATABASE        103
#define IDR_MAINFRAME                   128
#define IDR_DICTTYPE                    129
#define IDD_ADD_DIALOG                  131
#define IDD_UPDATE_DIALOG               132
#define IDD_DELETE_DIALOG               133
#define IDD_SEARCHONLINE                135
#define IDD_UPDATE_VOCAB                136
#define IDR_POPUP_MENU                  137
#define ID_POPUP_MENU                   142
#define IDR_MONKEY                      144
#define IDD_GIF_DIALOG                  145
#define IDI_ICON1                       147
#define IDI_ICON2                       150
#define IDD_GAME_DIALOG                 151
#define IDR_APE                         152
#define IDD_RESULT_DIALOG               153
#define IDR_HANG00                      154
#define IDR_HANG01                      155
#define IDR_HANG02                      156
#define IDR_HANG03                      157
#define IDR_HANG04                      158
#define IDR_HANG05                      159
#define IDR_HANG06                      160
#define IDR_HANG07                      161
#define IDR_HANG08                      162
#define IDR_HANG09                      163
#define IDR_LOSE                        164
#define IDR_RESULT                      165
#define IDR_WIN                         168
#define IDC_OVERGIF                     174
#define IDC_MEANING                     1002
#define IDC_THAI_MEANING                1002
#define IDC_Search                      1003
#define IDC_CVOCAB                      1005
#define IDC_TAB2                        1020
#define IDC_ADDVOCAB                    1021
#define IDC_ADDNOUN                     1022
#define IDC_ADDENOUN                    1022
#define IDADDOK                         1023
#define IDOnlineOK                      1024
#define IDOnlineCANCEL                  1025
#define IDC_ADDVERB                     1026
#define IDC_ADDEVERB                    1026
#define IDC_ADDADJ                      1027
#define IDC_ADDEADJ                     1027
#define IDC_ADDADV                      1028
#define IDC_ADDEADV                     1028
#define IDC_ADDPRON                     1029
#define IDC_ADDEPREP                    1029
#define IDC_ADDCONJ                     1030
#define IDC_ADDPREP                     1031
#define IDC_UPVOCAB                     1032
#define IDC_UPNOUN                      1033
#define IDC_UPENOUN                     1033
#define IDC_UPVERB                      1034
#define IDC_UPEVERB                     1034
#define IDC_UPADJ                       1035
#define IDC_UPEADJ                      1035
#define IDC_UPADV                       1036
#define IDC_UPEADV                      1036
#define IDC_UPPRON                      1037
#define IDC_UPEPREP                     1037
#define IDC_UPCONJ                      1038
#define IDC_UPPREP                      1039
#define IDC_DELVOCAB                    1040
#define IDC_EDIT_VOCAB                  1041
#define IDC_Point                       1043
#define IDC_ENABLE                      1044
#define IDC_ADDTNOUN                    1045
#define IDC_ADDTVERB                    1046
#define IDC_ADDTADJ                     1047
#define IDC_ADDTADV                     1048
#define IDC_ADDTPREP                    1049
#define IDC_UPTNOUN                     1050
#define IDC_UPTVERB                     1051
#define IDC_UPTADJ                      1052
#define IDC_UPTADV                      1053
#define IDC_UPTPREP                     1054
#define IDC_ENG_MEANING                 1055
#define IDC_ADDEPRON                    1056
#define IDC_ADDECONJ                    1057
#define IDC_ADDEINT                     1058
#define IDC_ADDTPRON                    1059
#define IDC_ADDTCONJ                    1060
#define IDC_ADDTINT                     1061
#define IDC_UPEPRON                     1062
#define IDC_UPECONJ                     1063
#define IDC_UPEINT                      1064
#define IDC_UPTPRON                     1065
#define IDC_UPTCONJ                     1067
#define IDC_UPTINT                      1068
#define IDC_GIF                         1069
#define IDC_HOTKEY1                     1070
#define IDC_PICT                        1073
#define IDC_VOCAB                       1074
#define IDC_TIMES                       1075
#define IDC_SYN                         1076
#define IDC_MEAN                        1077
#define IDC_ALL                         1078
#define IDC_WIN                         1079
#define IDC_LOSE                        1080
#define ID_ADDVOCAB                     32773
#define ID_UPDATEVOCAB                  32774
#define ID_DELETEVOCAB                  32775
#define IDC_SHOW_ICON                   32776
#define IDC_HIDE_ICON                   32777
#define ID_DEMO_MAXIMISE                32778
#define ID_DEMO_MINIMISE                32779
#define ID_FLOAT                        32780
#define ID_ABOUTVOCABULARY              32781
#define ID_DEMO_GIF                     32783
#define ID_MENU_FLOAT                   32786
#define ID_EN_ONLINE                    32787
#define ID_DIS_ONLINE                   32788
#define ID_EN_GAME                      32789
#define ID_DIS_GAME                     32790
#define ID_BUTTON32791                  32791
#define ID_HANGMAN                      32792
#define ID_POP_ONLINE                   32793
#define ID_POP_GAME                     32794
#define ID_PDIS_ONLINE                  32795
#define ID_PDIS_GAME                    32796
#define ID_PEN_ONLINE                   32797
#define ID_PEN_GAME                     32798
#define ID_POPUP_ABOUTFLOATING          32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        177
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
