<?xml version="1.0" encoding="windows-874"?>

<!ELEMENT PO (POHead+, ProductList+)>

<!ELEMENT POHead (POID, PODate, POStatus, POTotalPrice, 
VendorName, VendorAddress, VendorPhone, VendorFax, SaleName, SaleMail,
BuyerName, BuyerAddress, BuyerPhone, BuyerFax, BuyerMail)>

<!ELEMENT POID (#PCDATA)>
<!ELEMENT PODate (#PCDATA)>
<!ELEMENT POStatus (#PCDATA)>
<!ELEMENT POTotalPrice (#PCDATA)>
<!ELEMENT VendorName (#PCDATA)>
<!ELEMENT VendorAddress (#PCDATA)>
<!ELEMENT VendorPhone (#PCDATA)>
<!ELEMENT VendorFax (#PCDATA)>
<!ELEMENT SaleName (#PCDATA)>
<!ELEMENT SaleMail (#PCDATA)>
<!ELEMENT BuyerName (#PCDATA)>
<!ELEMENT BuyerAddress (#PCDATA)>
<!ELEMENT BuyerPhone (#PCDATA)>
<!ELEMENT BuyerFax (#PCDATA)>
<!ELEMENT BuyerMail (#PCDATA)>

<!ELEMENT ProductList (POLine+, ProductName+, ProductPrice+, ProductUnit+, ProductQTY+, RequiredDate+, ProductLineStatus*)>

<!ELEMENT POLine (#PCDATA)>
<!ELEMENT ProductName (#PCDATA)>
<!ELEMENT ProductPrice (#PCDATA)>
<!ELEMENT ProductQTY (#PCDATA)>
<!ELEMENT RequiredDate (#PCDATA)>
<!ELEMENT ProductLineStatus (#PCDATA)>