unit Unit4;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Db, DBTables, jpeg, Qrctrls, QuickRpt, ExtCtrls, StdCtrls;

type
  TForm4 = class(TForm)
    QuickRep1: TQuickRep;
    Query1: TQuery;
    Query2: TQuery;
    QRSysData3: TQRSysData;
    PageHeaderBand1: TQRBand;
    QRImage1: TQRImage;
    QRLabel7: TQRLabel;
    QRLabel6: TQRLabel;
    TitleBand1: TQRBand;
    QRLabel12: TQRLabel;
    QRLabel11: TQRLabel;
    DetailBand1: TQRBand;
    QRLabel5: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel1: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    Label6: TLabel;
    QRLabel10: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRLabel15: TQRLabel;
    QRLabel16: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRLabel23: TQRLabel;
    QRLabel24: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel26: TQRLabel;

  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form4: TForm4;

implementation

uses car_tracking;

{$R *.DFM}




end.
