//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace HealthyService {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class RegisterDataset : DataSet {
        
        private UCS_HEALTHYDataTable tableUCS_HEALTHY;
        
        public RegisterDataset() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected RegisterDataset(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["UCS_HEALTHY"] != null)) {
                    this.Tables.Add(new UCS_HEALTHYDataTable(ds.Tables["UCS_HEALTHY"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public UCS_HEALTHYDataTable UCS_HEALTHY {
            get {
                return this.tableUCS_HEALTHY;
            }
        }
        
        public override DataSet Clone() {
            RegisterDataset cln = ((RegisterDataset)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["UCS_HEALTHY"] != null)) {
                this.Tables.Add(new UCS_HEALTHYDataTable(ds.Tables["UCS_HEALTHY"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableUCS_HEALTHY = ((UCS_HEALTHYDataTable)(this.Tables["UCS_HEALTHY"]));
            if ((this.tableUCS_HEALTHY != null)) {
                this.tableUCS_HEALTHY.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "RegisterDataset";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/RegisterDataset.xsd";
            this.Locale = new System.Globalization.CultureInfo("th-TH");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableUCS_HEALTHY = new UCS_HEALTHYDataTable();
            this.Tables.Add(this.tableUCS_HEALTHY);
        }
        
        private bool ShouldSerializeUCS_HEALTHY() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void UCS_HEALTHYRowChangeEventHandler(object sender, UCS_HEALTHYRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UCS_HEALTHYDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnPID;
            
            private DataColumn columnPROCODE;
            
            private DataColumn columnRESULT;
            
            private DataColumn columnTITLE;
            
            private DataColumn columnFNAME;
            
            private DataColumn columnLNAME;
            
            private DataColumn columnBDATE;
            
            private DataColumn columnCARDID;
            
            private DataColumn columnINSCL;
            
            private DataColumn columnHOSPMAIN;
            
            private DataColumn columnHOSPSUB;
            
            private DataColumn columnIDATE;
            
            private DataColumn columnEDATE;
            
            private DataColumn columnSEX;
            
            private DataColumn columnNATION;
            
            private DataColumn columnOCCUPA;
            
            private DataColumn columnADDRESS;
            
            private DataColumn columnMOO;
            
            private DataColumn columnTAMBON;
            
            private DataColumn columnAMPHUR;
            
            private DataColumn columnPROVINCE;
            
            private DataColumn columnSTATUS;
            
            internal UCS_HEALTHYDataTable() : 
                    base("UCS_HEALTHY") {
                this.InitClass();
            }
            
            internal UCS_HEALTHYDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn PIDColumn {
                get {
                    return this.columnPID;
                }
            }
            
            internal DataColumn PROCODEColumn {
                get {
                    return this.columnPROCODE;
                }
            }
            
            internal DataColumn RESULTColumn {
                get {
                    return this.columnRESULT;
                }
            }
            
            internal DataColumn TITLEColumn {
                get {
                    return this.columnTITLE;
                }
            }
            
            internal DataColumn FNAMEColumn {
                get {
                    return this.columnFNAME;
                }
            }
            
            internal DataColumn LNAMEColumn {
                get {
                    return this.columnLNAME;
                }
            }
            
            internal DataColumn BDATEColumn {
                get {
                    return this.columnBDATE;
                }
            }
            
            internal DataColumn CARDIDColumn {
                get {
                    return this.columnCARDID;
                }
            }
            
            internal DataColumn INSCLColumn {
                get {
                    return this.columnINSCL;
                }
            }
            
            internal DataColumn HOSPMAINColumn {
                get {
                    return this.columnHOSPMAIN;
                }
            }
            
            internal DataColumn HOSPSUBColumn {
                get {
                    return this.columnHOSPSUB;
                }
            }
            
            internal DataColumn IDATEColumn {
                get {
                    return this.columnIDATE;
                }
            }
            
            internal DataColumn EDATEColumn {
                get {
                    return this.columnEDATE;
                }
            }
            
            internal DataColumn SEXColumn {
                get {
                    return this.columnSEX;
                }
            }
            
            internal DataColumn NATIONColumn {
                get {
                    return this.columnNATION;
                }
            }
            
            internal DataColumn OCCUPAColumn {
                get {
                    return this.columnOCCUPA;
                }
            }
            
            internal DataColumn ADDRESSColumn {
                get {
                    return this.columnADDRESS;
                }
            }
            
            internal DataColumn MOOColumn {
                get {
                    return this.columnMOO;
                }
            }
            
            internal DataColumn TAMBONColumn {
                get {
                    return this.columnTAMBON;
                }
            }
            
            internal DataColumn AMPHURColumn {
                get {
                    return this.columnAMPHUR;
                }
            }
            
            internal DataColumn PROVINCEColumn {
                get {
                    return this.columnPROVINCE;
                }
            }
            
            internal DataColumn STATUSColumn {
                get {
                    return this.columnSTATUS;
                }
            }
            
            public UCS_HEALTHYRow this[int index] {
                get {
                    return ((UCS_HEALTHYRow)(this.Rows[index]));
                }
            }
            
            public event UCS_HEALTHYRowChangeEventHandler UCS_HEALTHYRowChanged;
            
            public event UCS_HEALTHYRowChangeEventHandler UCS_HEALTHYRowChanging;
            
            public event UCS_HEALTHYRowChangeEventHandler UCS_HEALTHYRowDeleted;
            
            public event UCS_HEALTHYRowChangeEventHandler UCS_HEALTHYRowDeleting;
            
            public void AddUCS_HEALTHYRow(UCS_HEALTHYRow row) {
                this.Rows.Add(row);
            }
            
            public UCS_HEALTHYRow AddUCS_HEALTHYRow(
                        string PID, 
                        string PROCODE, 
                        string RESULT, 
                        string TITLE, 
                        string FNAME, 
                        string LNAME, 
                        string BDATE, 
                        string CARDID, 
                        string INSCL, 
                        string HOSPMAIN, 
                        string HOSPSUB, 
                        string IDATE, 
                        string EDATE, 
                        string SEX, 
                        string NATION, 
                        string OCCUPA, 
                        string ADDRESS, 
                        string MOO, 
                        string TAMBON, 
                        string AMPHUR, 
                        string PROVINCE, 
                        string STATUS) {
                UCS_HEALTHYRow rowUCS_HEALTHYRow = ((UCS_HEALTHYRow)(this.NewRow()));
                rowUCS_HEALTHYRow.ItemArray = new object[] {
                        PID,
                        PROCODE,
                        RESULT,
                        TITLE,
                        FNAME,
                        LNAME,
                        BDATE,
                        CARDID,
                        INSCL,
                        HOSPMAIN,
                        HOSPSUB,
                        IDATE,
                        EDATE,
                        SEX,
                        NATION,
                        OCCUPA,
                        ADDRESS,
                        MOO,
                        TAMBON,
                        AMPHUR,
                        PROVINCE,
                        STATUS};
                this.Rows.Add(rowUCS_HEALTHYRow);
                return rowUCS_HEALTHYRow;
            }
            
            public UCS_HEALTHYRow FindByPID(string PID) {
                return ((UCS_HEALTHYRow)(this.Rows.Find(new object[] {
                            PID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                UCS_HEALTHYDataTable cln = ((UCS_HEALTHYDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new UCS_HEALTHYDataTable();
            }
            
            internal void InitVars() {
                this.columnPID = this.Columns["PID"];
                this.columnPROCODE = this.Columns["PROCODE"];
                this.columnRESULT = this.Columns["RESULT"];
                this.columnTITLE = this.Columns["TITLE"];
                this.columnFNAME = this.Columns["FNAME"];
                this.columnLNAME = this.Columns["LNAME"];
                this.columnBDATE = this.Columns["BDATE"];
                this.columnCARDID = this.Columns["CARDID"];
                this.columnINSCL = this.Columns["INSCL"];
                this.columnHOSPMAIN = this.Columns["HOSPMAIN"];
                this.columnHOSPSUB = this.Columns["HOSPSUB"];
                this.columnIDATE = this.Columns["IDATE"];
                this.columnEDATE = this.Columns["EDATE"];
                this.columnSEX = this.Columns["SEX"];
                this.columnNATION = this.Columns["NATION"];
                this.columnOCCUPA = this.Columns["OCCUPA"];
                this.columnADDRESS = this.Columns["ADDRESS"];
                this.columnMOO = this.Columns["MOO"];
                this.columnTAMBON = this.Columns["TAMBON"];
                this.columnAMPHUR = this.Columns["AMPHUR"];
                this.columnPROVINCE = this.Columns["PROVINCE"];
                this.columnSTATUS = this.Columns["STATUS"];
            }
            
            private void InitClass() {
                this.columnPID = new DataColumn("PID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPID);
                this.columnPROCODE = new DataColumn("PROCODE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPROCODE);
                this.columnRESULT = new DataColumn("RESULT", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRESULT);
                this.columnTITLE = new DataColumn("TITLE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTITLE);
                this.columnFNAME = new DataColumn("FNAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFNAME);
                this.columnLNAME = new DataColumn("LNAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLNAME);
                this.columnBDATE = new DataColumn("BDATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBDATE);
                this.columnCARDID = new DataColumn("CARDID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCARDID);
                this.columnINSCL = new DataColumn("INSCL", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnINSCL);
                this.columnHOSPMAIN = new DataColumn("HOSPMAIN", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHOSPMAIN);
                this.columnHOSPSUB = new DataColumn("HOSPSUB", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHOSPSUB);
                this.columnIDATE = new DataColumn("IDATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIDATE);
                this.columnEDATE = new DataColumn("EDATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEDATE);
                this.columnSEX = new DataColumn("SEX", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSEX);
                this.columnNATION = new DataColumn("NATION", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNATION);
                this.columnOCCUPA = new DataColumn("OCCUPA", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOCCUPA);
                this.columnADDRESS = new DataColumn("ADDRESS", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnADDRESS);
                this.columnMOO = new DataColumn("MOO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMOO);
                this.columnTAMBON = new DataColumn("TAMBON", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTAMBON);
                this.columnAMPHUR = new DataColumn("AMPHUR", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAMPHUR);
                this.columnPROVINCE = new DataColumn("PROVINCE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPROVINCE);
                this.columnSTATUS = new DataColumn("STATUS", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSTATUS);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnPID}, true));
                this.columnPID.AllowDBNull = false;
                this.columnPID.Unique = true;
            }
            
            public UCS_HEALTHYRow NewUCS_HEALTHYRow() {
                return ((UCS_HEALTHYRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new UCS_HEALTHYRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(UCS_HEALTHYRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.UCS_HEALTHYRowChanged != null)) {
                    this.UCS_HEALTHYRowChanged(this, new UCS_HEALTHYRowChangeEvent(((UCS_HEALTHYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.UCS_HEALTHYRowChanging != null)) {
                    this.UCS_HEALTHYRowChanging(this, new UCS_HEALTHYRowChangeEvent(((UCS_HEALTHYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.UCS_HEALTHYRowDeleted != null)) {
                    this.UCS_HEALTHYRowDeleted(this, new UCS_HEALTHYRowChangeEvent(((UCS_HEALTHYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.UCS_HEALTHYRowDeleting != null)) {
                    this.UCS_HEALTHYRowDeleting(this, new UCS_HEALTHYRowChangeEvent(((UCS_HEALTHYRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveUCS_HEALTHYRow(UCS_HEALTHYRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UCS_HEALTHYRow : DataRow {
            
            private UCS_HEALTHYDataTable tableUCS_HEALTHY;
            
            internal UCS_HEALTHYRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableUCS_HEALTHY = ((UCS_HEALTHYDataTable)(this.Table));
            }
            
            public string PID {
                get {
                    return ((string)(this[this.tableUCS_HEALTHY.PIDColumn]));
                }
                set {
                    this[this.tableUCS_HEALTHY.PIDColumn] = value;
                }
            }
            
            public string PROCODE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.PROCODEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.PROCODEColumn] = value;
                }
            }
            
            public string RESULT {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.RESULTColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.RESULTColumn] = value;
                }
            }
            
            public string TITLE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.TITLEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.TITLEColumn] = value;
                }
            }
            
            public string FNAME {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.FNAMEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.FNAMEColumn] = value;
                }
            }
            
            public string LNAME {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.LNAMEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.LNAMEColumn] = value;
                }
            }
            
            public string BDATE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.BDATEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.BDATEColumn] = value;
                }
            }
            
            public string CARDID {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.CARDIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.CARDIDColumn] = value;
                }
            }
            
            public string INSCL {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.INSCLColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.INSCLColumn] = value;
                }
            }
            
            public string HOSPMAIN {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.HOSPMAINColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.HOSPMAINColumn] = value;
                }
            }
            
            public string HOSPSUB {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.HOSPSUBColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.HOSPSUBColumn] = value;
                }
            }
            
            public string IDATE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.IDATEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.IDATEColumn] = value;
                }
            }
            
            public string EDATE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.EDATEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.EDATEColumn] = value;
                }
            }
            
            public string SEX {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.SEXColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.SEXColumn] = value;
                }
            }
            
            public string NATION {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.NATIONColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.NATIONColumn] = value;
                }
            }
            
            public string OCCUPA {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.OCCUPAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.OCCUPAColumn] = value;
                }
            }
            
            public string ADDRESS {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.ADDRESSColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.ADDRESSColumn] = value;
                }
            }
            
            public string MOO {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.MOOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.MOOColumn] = value;
                }
            }
            
            public string TAMBON {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.TAMBONColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.TAMBONColumn] = value;
                }
            }
            
            public string AMPHUR {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.AMPHURColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.AMPHURColumn] = value;
                }
            }
            
            public string PROVINCE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.PROVINCEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.PROVINCEColumn] = value;
                }
            }
            
            public string STATUS {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.STATUSColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.STATUSColumn] = value;
                }
            }
            
            public bool IsPROCODENull() {
                return this.IsNull(this.tableUCS_HEALTHY.PROCODEColumn);
            }
            
            public void SetPROCODENull() {
                this[this.tableUCS_HEALTHY.PROCODEColumn] = System.Convert.DBNull;
            }
            
            public bool IsRESULTNull() {
                return this.IsNull(this.tableUCS_HEALTHY.RESULTColumn);
            }
            
            public void SetRESULTNull() {
                this[this.tableUCS_HEALTHY.RESULTColumn] = System.Convert.DBNull;
            }
            
            public bool IsTITLENull() {
                return this.IsNull(this.tableUCS_HEALTHY.TITLEColumn);
            }
            
            public void SetTITLENull() {
                this[this.tableUCS_HEALTHY.TITLEColumn] = System.Convert.DBNull;
            }
            
            public bool IsFNAMENull() {
                return this.IsNull(this.tableUCS_HEALTHY.FNAMEColumn);
            }
            
            public void SetFNAMENull() {
                this[this.tableUCS_HEALTHY.FNAMEColumn] = System.Convert.DBNull;
            }
            
            public bool IsLNAMENull() {
                return this.IsNull(this.tableUCS_HEALTHY.LNAMEColumn);
            }
            
            public void SetLNAMENull() {
                this[this.tableUCS_HEALTHY.LNAMEColumn] = System.Convert.DBNull;
            }
            
            public bool IsBDATENull() {
                return this.IsNull(this.tableUCS_HEALTHY.BDATEColumn);
            }
            
            public void SetBDATENull() {
                this[this.tableUCS_HEALTHY.BDATEColumn] = System.Convert.DBNull;
            }
            
            public bool IsCARDIDNull() {
                return this.IsNull(this.tableUCS_HEALTHY.CARDIDColumn);
            }
            
            public void SetCARDIDNull() {
                this[this.tableUCS_HEALTHY.CARDIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsINSCLNull() {
                return this.IsNull(this.tableUCS_HEALTHY.INSCLColumn);
            }
            
            public void SetINSCLNull() {
                this[this.tableUCS_HEALTHY.INSCLColumn] = System.Convert.DBNull;
            }
            
            public bool IsHOSPMAINNull() {
                return this.IsNull(this.tableUCS_HEALTHY.HOSPMAINColumn);
            }
            
            public void SetHOSPMAINNull() {
                this[this.tableUCS_HEALTHY.HOSPMAINColumn] = System.Convert.DBNull;
            }
            
            public bool IsHOSPSUBNull() {
                return this.IsNull(this.tableUCS_HEALTHY.HOSPSUBColumn);
            }
            
            public void SetHOSPSUBNull() {
                this[this.tableUCS_HEALTHY.HOSPSUBColumn] = System.Convert.DBNull;
            }
            
            public bool IsIDATENull() {
                return this.IsNull(this.tableUCS_HEALTHY.IDATEColumn);
            }
            
            public void SetIDATENull() {
                this[this.tableUCS_HEALTHY.IDATEColumn] = System.Convert.DBNull;
            }
            
            public bool IsEDATENull() {
                return this.IsNull(this.tableUCS_HEALTHY.EDATEColumn);
            }
            
            public void SetEDATENull() {
                this[this.tableUCS_HEALTHY.EDATEColumn] = System.Convert.DBNull;
            }
            
            public bool IsSEXNull() {
                return this.IsNull(this.tableUCS_HEALTHY.SEXColumn);
            }
            
            public void SetSEXNull() {
                this[this.tableUCS_HEALTHY.SEXColumn] = System.Convert.DBNull;
            }
            
            public bool IsNATIONNull() {
                return this.IsNull(this.tableUCS_HEALTHY.NATIONColumn);
            }
            
            public void SetNATIONNull() {
                this[this.tableUCS_HEALTHY.NATIONColumn] = System.Convert.DBNull;
            }
            
            public bool IsOCCUPANull() {
                return this.IsNull(this.tableUCS_HEALTHY.OCCUPAColumn);
            }
            
            public void SetOCCUPANull() {
                this[this.tableUCS_HEALTHY.OCCUPAColumn] = System.Convert.DBNull;
            }
            
            public bool IsADDRESSNull() {
                return this.IsNull(this.tableUCS_HEALTHY.ADDRESSColumn);
            }
            
            public void SetADDRESSNull() {
                this[this.tableUCS_HEALTHY.ADDRESSColumn] = System.Convert.DBNull;
            }
            
            public bool IsMOONull() {
                return this.IsNull(this.tableUCS_HEALTHY.MOOColumn);
            }
            
            public void SetMOONull() {
                this[this.tableUCS_HEALTHY.MOOColumn] = System.Convert.DBNull;
            }
            
            public bool IsTAMBONNull() {
                return this.IsNull(this.tableUCS_HEALTHY.TAMBONColumn);
            }
            
            public void SetTAMBONNull() {
                this[this.tableUCS_HEALTHY.TAMBONColumn] = System.Convert.DBNull;
            }
            
            public bool IsAMPHURNull() {
                return this.IsNull(this.tableUCS_HEALTHY.AMPHURColumn);
            }
            
            public void SetAMPHURNull() {
                this[this.tableUCS_HEALTHY.AMPHURColumn] = System.Convert.DBNull;
            }
            
            public bool IsPROVINCENull() {
                return this.IsNull(this.tableUCS_HEALTHY.PROVINCEColumn);
            }
            
            public void SetPROVINCENull() {
                this[this.tableUCS_HEALTHY.PROVINCEColumn] = System.Convert.DBNull;
            }
            
            public bool IsSTATUSNull() {
                return this.IsNull(this.tableUCS_HEALTHY.STATUSColumn);
            }
            
            public void SetSTATUSNull() {
                this[this.tableUCS_HEALTHY.STATUSColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UCS_HEALTHYRowChangeEvent : EventArgs {
            
            private UCS_HEALTHYRow eventRow;
            
            private DataRowAction eventAction;
            
            public UCS_HEALTHYRowChangeEvent(UCS_HEALTHYRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public UCS_HEALTHYRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
