import java.io.*;
import java.sql.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;

import  com.oreilly.servlet.MultipartRequest;

public class ForH2hForm extends HttpServlet implements SingleThreadModel {

private Connection conn = null;
public void init( ServletConfig config ) throws ServletException {
  super.init(config);
  try {
   Class.forName ("oracle.jdbc.driver.OracleDriver");
   conn = DriverManager.getConnection("jdbc:oracle:thin:@jim:1521:PROJECT","scott","tiger");
  } catch ( SQLException e ) {
  System.err.println("Could not establish connection.");
  } catch ( ClassNotFoundException e ) {
  System.err.println("Could not load database driver.");
  }
} // init

  public void doPost(HttpServletRequest req, HttpServletResponse res)
                                throws ServletException, IOException {
    String nameRent="";
    String TypeRent="";
    String HomeNumber="";
    String Select_Province="";
    String Select_Location="";
    String area = "";
    String floor = "";
    String bedroom = "";
    String bathroom = "";
    String kitchen = "";
    String price = "";
    String Vfirstname = "";
    String Vlastname = "";
    String address = "";
    String telephone = "";
    String name = "";
    String filename = "";
    String temp = "";
    int N_Row = 0;
    int projectID =101;
    int HomeID = 501;
    int indeximage = 100001;
    int vendorID =0;
    String[] value = new String[17];
    ToUnicode t = new ToUnicode();
    res.setContentType("text/html;charset=windows-874");
    PrintWriter out = res.getWriter();

    try {
          //---- Create a Statement ----
          Statement stmt = conn.createStatement ();
          ResultSet rset;
          // Blindly take it on faith this is a multipart/form-data request
          // Construct a MultipartRequest to help read the information.
          // Pass in the request, a directory to saves files to, and the
          // maximum POST size we should attempt to handle.
          // Here we (rudely) write to the server root and impose 5 Meg limit.
          MultipartRequest multi = new MultipartRequest(req,"E:/HomeProject/www/image/homeImages", 5 * 1024 * 1024);
          int i = 0;
          Enumeration params = multi.getParameterNames();
          while (params.hasMoreElements()) {
             name = (String)params.nextElement();
             value[i] = multi.getParameter(name);
             i++;
          }
          rset = stmt.executeQuery("SELECT count(*) FROM project");
          rset.next();
          N_Row = rset.getInt(1);
          projectID = projectID+N_Row;
          indeximage = indeximage+N_Row;
          nameRent = t.toUnicode(value[12]);
          stmt.executeUpdate("INSERT INTO project(projectid,projectname) VALUES ("+"'"+projectID+"','"+nameRent+"')");
          rset = stmt.executeQuery("SELECT count(*) FROM home");
	        rset.next();
          N_Row = rset.getInt(1);
          HomeID = HomeID + N_Row;
          rset = stmt.executeQuery("SELECT count(*) FROM vendor");
	        rset.next();
          N_Row = rset.getInt(1);
          vendorID = N_Row+1;
          //out.println(value[11]);
          if(value[11].equals("hide"))
          {
           // out.println("hide");
            Select_Location = "-";
            bedroom = t.toUnicode(value[13]);
            Vfirstname = t.toUnicode(value[14]);
            area = t.toUnicode(value[15]);
          }
          else {
                // out.println("nohide");
                 if (value[13].equals("0")) Select_Location = "-";
                 else Select_Location = t.toUnicode(value[13]);
                 bedroom = t.toUnicode(value[14]);
                 Vfirstname = t.toUnicode(value[15]);
                 area = t.toUnicode(value[16]);
               }
          if(value[6].equals("01")) Select_Province = "กรุงเทพฯ";
          else Select_Province = t.toUnicode(value[6]);
          HomeNumber = t.toUnicode(value[4]);
          floor = t.toUnicode(value[0]);
          kitchen = t.toUnicode(value[10]);
          bathroom = t.toUnicode(value[8]);
          price = t.toUnicode(value[3]);
          TypeRent = t.toUnicode(value[2]);
          String statusReserv = "ว่าง";
          String groupHome = "s";
          Enumeration files = multi.getFileNames();
          while (files.hasMoreElements()) {
             name = (String)files.nextElement();
             filename = multi.getFilesystemName(name);
          }
          int dot = filename.indexOf('.');
          filename = filename.substring(0,dot);
          stmt.executeUpdate("INSERT INTO home(homeid,homenumber,hamphur,hprovince,area,floor,bedroom,kitchenroom,bathroom,price,statusreserv,hometype,grouphome,homeimage,projectid,indeximage,vendorid) VALUES ("+"'"+HomeID+"','"+HomeNumber+"','"+Select_Location+"','"+Select_Province+"','"+area+"','"+floor+"','"+bedroom+"','"+kitchen+"','"+bathroom+"','"+price+"','"+statusReserv+"','"+TypeRent+"','"+groupHome+"','"+filename+"','"+projectID+"','"+indeximage+"','"+vendorID+"')");
          Vlastname = t.toUnicode(value[7]);
          address = t.toUnicode(value[1]);
          telephone = t.toUnicode(value[9]);
          stmt.executeUpdate("INSERT INTO vendor VALUES ("+"'"+vendorID+"','"+Vfirstname+"','"+Vlastname+"','"+address+"','"+telephone+"')");
          stmt.executeUpdate("INSERT INTO hometypedetail(projectid,indeximage,homeimage) VALUES ("+"'"+projectID+"','"+indeximage+"','"+filename+"')");

out.println("<html>                                                                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("<head>                                                                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("<title>Un title page</title>                                                                                                                                                                                                                                                                                                                                                                                                                    ");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-874\">                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("<style type=\"text/css\">                                                                                                                                                                                                                                                                                                                                                                                                                       ");
out.println("<!--                                                                                                                                                                                                                                                                                                                                                                                                                                            ");
out.println("body {  margin: 0px  0px; padding: 0px  0px}                                                                                                                                                                                                                                                                                                                                                                                                    ");
out.println("a:link { color: #005CA2; text-decoration: none}                                                                                                                                                                                                                                                                                                                                                                                                 ");
out.println("a:visited { color: #005CA2; text-decoration: none}                                                                                                                                                                                                                                                                                                                                                                                              ");
out.println("a:active { color: #0099FF; text-decoration: underline}                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("a:hover { color: #0099FF; text-decoration: underline}                                                                                                                                                                                                                                                                                                                                                                                           ");
out.println("-->                                                                                                                                                                                                                                                                                                                                                                                                                                             ");
out.println("</style>                                                                                                                                                                                                                                                                                                                                                                                                                                        ");
out.println("<script language=\"JavaScript\">                                                                                                                                                                                                                                                                                                                                                                                                                ");
out.println("<!--                                                                                                                                                                                                                                                                                                                                                                                                                                            ");
out.println("<!--                                                                                                                                                                                                                                                                                                                                                                                                                                            ");
out.println("function MM_reloadPage(init) {  //reloads the window if Nav4 resized                                                                                                                                                                                                                                                                                                                                                                            ");
out.println("  if (init==true) with (navigator) {if ((appName==\"Netscape\")&&(parseInt(appVersion)==4)) {                                                                                                                                                                                                                                                                                                                                                   ");
out.println("    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}                                                                                                                                                                                                                                                                                                                                                         ");
out.println("  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();                                                                                                                                                                                                                                                                                                                                                      ");
out.println("}                                                                                                                                                                                                                                                                                                                                                                                                                                               ");
out.println("MM_reloadPage(true);                                                                                                                                                                                                                                                                                                                                                                                                                            ");
out.println("// -->                                                                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("                                                                                                                                                                                                                                                                                                                                                                                                                                                ");
out.println("function MM_swapImgRestore() { //v3.0                                                                                                                                                                                                                                                                                                                                                                                                           ");
out.println("  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;                                                                                                                                                                                                                                                                                                                                                          ");
out.println("}                                                                                                                                                                                                                                                                                                                                                                                                                                               ");
out.println("                                                                                                                                                                                                                                                                                                                                                                                                                                                ");
out.println("function MM_preloadImages() { //v3.0                                                                                                                                                                                                                                                                                                                                                                                                            ");
out.println("  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();                                                                                                                                                                                                                                                                                                                                                                                 ");
out.println("    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)                                                                                                                                                                                                                                                                                                                                                               ");
out.println("    if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("}                                                                                                                                                                                                                                                                                                                                                                                                                                               ");
out.println("                                                                                                                                                                                                                                                                                                                                                                                                                                                ");
out.println("function MM_findObj(n, d) { //v4.0                                                                                                                                                                                                                                                                                                                                                                                                              ");
out.println("  var p,i,x;  if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {                                                                                                                                                                                                                                                                                                                                                             ");
out.println("    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}                                                                                                                                                                                                                                                                                                                                                                            ");
out.println("  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];                                                                                                                                                                                                                                                                                                                                                          ");
out.println("  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);                                                                                                                                                                                                                                                                                                                                                            ");
out.println("  if(!x && document.getElementById) x=document.getElementById(n); return x;                                                                                                                                                                                                                                                                                                                                                                     ");
out.println("}                                                                                                                                                                                                                                                                                                                                                                                                                                               ");
out.println("                                                                                                                                                                                                                                                                                                                                                                                                                                                ");
out.println("function MM_swapImage() { //v3.0                                                                                                                                                                                                                                                                                                                                                                                                                ");
out.println("  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)                                                                                                                                                                                                                                                                                                                                                  ");
out.println("   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}                                                                                                                                                                                                                                                                                                                                              ");
out.println("}                                                                                                                                                                                                                                                                                                                                                                                                                                               ");
out.println("//-->                                                                                                                                                                                                                                                                                                                                                                                                                                           ");
out.println("</script>                                                                                                                                                                                                                                                                                                                                                                                                                                       ");
out.println("</head>                                                                                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("                                                                                                                                                                                                                                                                                                                                                                                                                                                ");
out.println("<body bgcolor=\"#FFFFFF\" onLoad=\"MM_preloadImages('http://kling/html/image/registorF.gif','http://kling/html/image/NewHomesF.gif','http://kling/html/image/homeRentF.gif','http://kling/html/image/HsecondF.gif')\" background=\"http://kling/html/image/backgnd.gif\">                                                                                                                        ");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\" \" cellpadding=\" \">                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("  <tr valign=\"top\">                                                                                                                                                                                                                                                                                                                                                                                                                           ");
out.println("    <td width=\"61%\"> <img src=\"http://kling/html/image/etest2.GIF\" width=\"616\" height=\"113\"></td>                                                                                                                                                                                                                                                                                                                              ");
out.println("    <td width=\"39%\" align=\"left\"><img src=\"http://kling/html/image/lineB.gif\" width=\"359\" height=\"113\"></td>                                                                                                                                                                                                                                                                                                               ");
out.println("  </tr>                                                                                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("</table>                                                                                                                                                                                                                                                                                                                                                                                                                                        ");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\" \" cellpadding=\" \" height=\"754\">                                                                                                                                                                                                                                                                                                                                                          ");
out.println("  <tr>                                                                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("    <td width=\"19%\" height=\"786\" valign=\"top\"><img src=\"http://kling/html/image/Bg1.gif\" width=\"179\" height=\"784\"></td>                                                                                                                                                                                                                                                                                                  ");
out.println("    <td width=\"77%\" valign=\"top\" height=\"371\" rowspan=\"2\">                                                                                                                                                                                                                                                                                                                                                                              ");
out.println("      <table width=\"100%\" border=\"0\" cellspacing=\" \" cellpadding=\" \">                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("        <tr>                                                                                                                                                                                                                                                                                                                                                                                                                                    ");
out.println("          <td>                                                                                                                                                                                                                                                                                                                                                                                                                                  ");
out.println("            <div id=\"Layer3\" style=\"position:absolute; left:4px; top:99px; width:184px; height:214px; z-index:3\"><img src=\"http://kling/html/image/Bg11.gif\" width=\"166\" height=\"206\"></div>                                                                                                                                                                                                                               ");
out.println("            <div id=\"Layer3\" style=\"position:absolute; left:21px; top:182px; width:92px; height:10px; z-index:3\"><a href=\"http://kling/html/SearchHome.html\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image7','','file:///E|/HomeProject/jimHomePage/searchF.gif',1)\"><img name=\"Image7\" border=\"0\" src=\"file:///E|/HomeProject/jimHomePage/searchB.gif\" width=\"83\" height=\"19\"></a></div>      ");
out.println("            <div id=\"Layer4\" style=\"position:absolute; left:19px; top:206px; width:109px; height:14px; z-index:4\">                                                                                                                                                                                                                                                                                                                          ");
out.println("              <p><a href=\"http://kling/test/ShowTopicFirstS\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image8','','http://kling/html/image/talkhomeF.gif',1)\" target=\"_blank\"><img name=\"Image8\" border=\"0\" src=\"file:///E|/HomeProject/jimHomePage/talkhomeB.gif\" width=\"97\" height=\"23\"></a></p>                                                                                               ");
out.println("            </div>                                                                                                                                                                                                                                                                                                                                                                                                                              ");
out.println("            <div id=\"Layer5\" style=\"position:absolute; left:20px; top:235px; width:109px; height:9px; z-index:5\"><a href=\"http://kling/html/aboutus_th.html\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image9','','http://kling/html/image/aboutF.gif',1)\"><img name=\"Image9\" border=\"0\" src=\"http://kling/html/image/aboutB.gif\" width=\"84\" height=\"14\"></a></div>        ");
out.println("            <div id=\"Layer2\" style=\"position:absolute; left:20px; top:156px; width:126px; height:22px; z-index:12\"><a href=\"http://kling/html/Forget.html\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image6','','http://kling/html/image/forgotF.gif',1)\"><img name=\"Image6\" border=\"0\" src=\"http://kling/html/image/forgotB.gif\" width=\"94\" height=\"19\"></a></div>        ");
out.println("            <div id=\"Layer6\" style=\"position:absolute; left:21px; top:257px; width:112px; height:7px; z-index:6\"><a href=\"mailto:kling_sup@hotmail.com\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image10','','http://kling/html/image/contactF.gif',1)\"><img name=\"Image10\" border=\"0\" src=\"http://kling/html/image/contactB.gif\" width=\"102\" height=\"15\"></a></div>               ");
out.println("            <div id=\"Layer7\" style=\"position:absolute; left:838px; top:18px; width:138px; height:54px; z-index:7\"><img src=\"http://kling/html/image/SellingYrHome.gif\" width=\"136\" height=\"54\"></div>                                                                                                                                                                                                                        ");
out.println("            <div id=\"Layer8\" style=\"position:absolute; left:659px; top:85px; width:325px; height:37px; z-index:8\">                                                                                                                                                                                                                                                                                                                          ");
out.println("              <form name=\"form1\" method=\"post\" action=\"http://kling/test/LoginNew1\">                                                                                                                                                                                                                                                                                                                                                      ");
out.println("                <b><font color=\"#000066\">Username </font></b> <font color=\"#000066\">                                                                                                                                                                                                                                                                                                                                                        ");
out.println("                <input type=\"text\" name=\"username\" size=\"10\">                                                                                                                                                                                                                                                                                                                                                                             ");
out.println("                <b>Password </b> </font>                                                                                                                                                                                                                                                                                                                                                                                                        ");
out.println("                <input type=\"password\" name=\"password\" size=\"10\">                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("                <input type=\"image\" border=\"0\" name=\"imageField3\" src=\"http://kling/html/image/go1.gif\" width=\"28\" height=\"20\" align=\"bottom\">                                                                                                                                                                                                                                                                           ");
out.println("              </form>                                                                                                                                                                                                                                                                                                                                                                                                                           ");
out.println("            </div>                                                                                                                                                                                                                                                                                                                                                                                                                              ");
out.println("            <div id=\"Layer1\" style=\"position:absolute; left:18px; top:128px; width:141px; height:24px; z-index:11\"><a href=\"http://kling/html/register2.html\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image5','','http://kling/html/image/registorF.gif',1)\"><img name=\"Image5\" border=\"0\" src=\"http://kling/html/image/registorB.gif\" width=\"132\" height=\"19\"></a></div>");
out.println("            <div id=\"Layer3\" style=\"position:absolute; left:135px; top:296px; width:56px; height:263px; z-index:3\"><img src=\"http://kling/html/image/homeproject.gif\" width=\"59\" height=\"296\"></div>                                                                                                                                                                                                                         ");
out.println("          </td>                                                                                                                                                                                                                                                                                                                                                                                                                                 ");
out.println("        </tr>                                                                                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("      </table>                                                                                                                                                                                                                                                                                                                                                                                                                                  ");
out.println("                                                                                                                                                                                                                                                                                                                                                                                                                                                ");
out.println("      <table width=\"100%\" border=\"0\" cellspacing=\"10\" cellpadding=\" \">                                                                                                                                                                                                                                                                                                                                                                  ");
out.println("        <tr>                                                                                                                                                                                                                                                                                                                                                                                                                                    ");
out.println("          <td width=\"8%\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("          <td width=\"83%\"><img src=\"http://kling/html/image/ResultH2h.gif\" width=\"443\" height=\"114\"></td>                                                                                                                                                                                                                                                                                                           ");
out.println("          <td width=\"9%\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("        </tr>                                                                                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("      </table>                                                                                                                                                                                                                                                                                                                                                                                                                                  ");
out.println("      <table width=\"100%\" border=\"0\" cellspacing=\"20\" cellpadding=\"10\">                                                                                                                                                                                                                                                                                                                                                                 ");
out.println("        <tr>                                                                                                                                                                                                                                                                                                                                                                                                                                    ");
out.println("          <td width=\"17%\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("          <td width=\"76%\"><font color=\"#FF9999\" size=\"2\" face=\"MS Sans Serif, Microsoft Sans Serif\">การประกาศขายบ้านมือสองของท่านเสร็จเรียบร้อย</font><font color=\"#0099FF\" size=\"1\" face=\"MS Sans Serif, Microsoft Sans Serif\"></font></td>                                                                                                                                                                                        ");
out.println("          <td width=\"7%\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("        </tr>                                                                                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("      </table>                                                                                                                                                                                                                                                                                                                                                                                                                                  ");
out.println("      <table width=\"100%\" border=\"0\" cellspacing=\" \" cellpadding=\" \">                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("        <tr>                                                                                                                                                                                                                                                                                                                                                                                                                                    ");
out.println("          <td width=\"15%\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("          <td width=\"56%\">                                                                                                                                                                                                                                                                                                                                                                                                                    ");
out.println("            <div align=\"center\"><font color=\"#0099FF\" size=\"2\" face=\"MS Sans Serif, Microsoft Sans Serif\">บ้านมือสองที่ต้องการประกาศขายนั้นจะปรากฎบนหน้า</font><font color=\"#0099FF\" size=\"1\" face=\"MS Sans Serif, Microsoft Sans Serif\"><br>                                                                                                                                                                                       ");
out.println("              <font size=\"2\">web page ได้นั้นต้องได้ผ่านการตรวจสอบข้อความ</font><br>                                                                                                                                                                                                                                                                                                                                                          ");
out.println("              <font color=\"#0099FF\" size=\"1\" face=\"MS Sans Serif, Microsoft Sans Serif\"><font size=\"2\">ประกาศ</font></font><font size=\"2\">และภาพถ่ายจากทีมงานก่อนและการประกาศ</font><br>                                                                                                                                                                                                                                              ");
out.println("              <font color=\"#0099FF\" size=\"1\" face=\"MS Sans Serif, Microsoft Sans Serif\"><font size=\"2\">เช่าจะมีระยะ</font></font><font size=\"2\">เวลาในการประกาศภายใน                                                                                                                                                                                                                                                                  ");
out.println("              30 วันเท่านั้น</font></font></div>                                                                                                                                                                                                                                                                                                                                                                                                ");
out.println("          </td>                                                                                                                                                                                                                                                                                                                                                                                                                                 ");
out.println("          <td width=\"29%\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("        </tr>                                                                                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("      </table>                                                                                                                                                                                                                                                                                                                                                                                                                                  ");
out.println("      <table width=\"100%\" border=\"0\" cellspacing=\"10\" cellpadding=\"0\">                                                                                                                                                                                                                                                                                                                                                                  ");
out.println("        <tr>                                                                                                                                                                                                                                                                                                                                                                                                                                    ");
out.println("          <td width=\"57%\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("          <td width=\"34%\"><a href=\"http://kling/html/mainPage3.html\"><img src=\"http://kling/html/image/backHome.gif\" width=\"85\" height=\"36\" border=\"0\"></a></td>                                                                                                                                                                                                                                                           ");
out.println("          <td width=\"9%\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("        </tr>                                                                                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("      </table>                                                                                                                                                                                                                                                                                                                                                                                                                                  ");
out.println("      <p>&nbsp;</p>                                                                                                                                                                                                                                                                                                                                                                                                                             ");
out.println("      </td>                                                                                                                                                                                                                                                                                                                                                                                                                                     ");
out.println("    <td width=\"4%\" height=\"371\" rowspan=\"2\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                                                   ");
out.println("  </tr>                                                                                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("  <tr>                                                                                                                                                                                                                                                                                                                                                                                                                                          ");
out.println("    <td width=\"19%\" height=\"120\" valign=\"top\" bgcolor=\"#FFFFFF\">&nbsp;</td>                                                                                                                                                                                                                                                                                                                                                             ");
out.println("  </tr>                                                                                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("</table>                                                                                                                                                                                                                                                                                                                                                                                                                                        ");
out.println("</body>                                                                                                                                                                                                                                                                                                                                                                                                                                         ");
out.println("</html>																																																						");

    }
    catch (Exception e) {
      out.println("<PRE>");
      e.printStackTrace(out);
      out.println("</PRE>");
    }



  }
  public void destroy() {
  try {
  // close the database connection
  if ( conn != null) conn.close();
  } catch (SQLException e) {
     System.err.println("Error closing database connection.");
  }
 } // destroy
}
