/*
 * AcessMonitor.java
 *
 * Created on 17 มกราคม 2549, 15:07 น.
 */

/**
 *
 * @author  IBM
 */
import javax.media.*;
import javax.media.protocol.DataSource;
import javax.media.format.*;
import javax.media.protocol.*;
import javax.media.control.*;
import java.util.Vector;
import java.awt.*;
import java.awt.event.*;        
public class AcessMonitor extends javax.swing.JFrame{
    
    String rootpath = "E:\\\\BackupAMS\\";
    /** Creates new form AcessMonitor */
    static Processor p;
    statusmotion smotion;
    EditUser edituser;
    AddUser adduser;
    SearchFrame Search;
    MotionDetectionEffect mde;
    Setippath setip;
    Checkbox checkVideo = new Checkbox();
    JVidCap captureapi,mdeapi;
    public AcessMonitor() {
    //super("Acess Monitor");
        checkVideo.setState(true);
        checkVideo.setEnabled(false);
        checkVideo.setVisible(false);
        initComponents();
        smsalert.setVisible(false);
        jcomboEncoding.setVisible(false);
        jcomboFileType.setVisible(false);
        jcomboSize.setVisible(false);
        mde = new MotionDetectionEffect(this);
        captureapi = new JVidCap(this);
        variableCode.flagStartProcessor = 1;
        captureapi.startMonitoring(null);
        smotion = new statusmotion(this);
        edituser = new EditUser();
        adduser =new AddUser();
        Search =new SearchFrame();
        setip = new Setippath(this);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jcomboFileType = new javax.swing.JComboBox();
        jcomboEncoding = new javax.swing.JComboBox();
        jcomboSize = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        emailalert = new javax.swing.JCheckBox();
        smsalert = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ckbxServerActiveBasic = new javax.swing.JCheckBox();
        timemail = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jalertmoiton = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtotalarea = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acess Monitoring System");
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(10);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(5);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 400, -1));

        jSlider2.setMajorTickSpacing(1);
        jSlider2.setMaximum(5);
        jSlider2.setMinimum(1);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);
        jSlider2.setValue(1);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        getContentPane().add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 400, -1));

        jButton1.setText("Start Capture");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 140, -1));

        jButton2.setText("Add User");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 140, -1));

        jButton3.setText("Stop Capture");
        jButton3.setEnabled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 140, -1));

        jButton4.setText("Edit/Delete User");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 140, -1));

        jButton5.setText("Status Motion");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 140, -1));

        jButton6.setText("Set IP/Path File");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 140, -1));

        jButton7.setText("Search File");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 140, -1));

        jButton8.setText("Exit");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 140, -1));

        jcomboFileType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AVI" }));
        jcomboFileType.setEnabled(false);
        getContentPane().add(jcomboFileType, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 50, 20));

        jcomboEncoding.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RGB" }));
        jcomboEncoding.setEnabled(false);
        getContentPane().add(jcomboEncoding, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 50, 20));

        jcomboSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "320x240" }));
        jcomboSize.setEnabled(false);
        jcomboSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboSizeItemStateChanged(evt);
            }
        });

        getContentPane().add(jcomboSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 80, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("File Format :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 90, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Level Detection");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Sensitive");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 60, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setBorder(new javax.swing.border.TitledBorder(null, "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 300, 250));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 320, 240));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setBorder(new javax.swing.border.TitledBorder(null, "Motion and Alert Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 300, 110));

        emailalert.setSelected(true);
        emailalert.setText("E-mail Alert");
        getContentPane().add(emailalert, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, -1, 20));

        smsalert.setSelected(true);
        smsalert.setText("Sms Alert");
        getContentPane().add(smsalert, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, -1, -1));

        jScrollPane1.setAutoscrolls(true);
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 260, 200));

        ckbxServerActiveBasic.setSelected(true);
        ckbxServerActiveBasic.setText("Motion Detection");
        getContentPane().add(ckbxServerActiveBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        timemail.setEditable(true);
        timemail.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        timemail.setSelectedIndex(1);
        timemail.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                timemailItemStateChanged(evt);
            }
        });

        getContentPane().add(timemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 40, 20));

        jLabel6.setText("Second");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, -1, 20));

        jLabel7.setBorder(new javax.swing.border.TitledBorder(""));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 300, 40));

        jLabel8.setBorder(new javax.swing.border.TitledBorder(null, "Monitor Screen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 400, 330));

        jTextField1.setEditable(false);
        jTextField1.setText("AVI");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 30, -1));

        jTextField2.setEditable(false);
        jTextField2.setText("RGB");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 40, -1));

        jTextField3.setEditable(false);
        jTextField3.setText("320x240");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 60, -1));

        jLabel9.setText("Alert Motion :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, 20));

        jalertmoiton.setEditable(false);
        jalertmoiton.setText("0");
        getContentPane().add(jalertmoiton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 40, 20));

        jLabel10.setText("From :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, 20));

        jtotalarea.setEditable(false);
        jtotalarea.setText("3072");
        getContentPane().add(jtotalarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 40, 20));

        jLabel11.setText("Areas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 40, 20));

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
// TODO add your handling code here:
        setip.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
// TODO add your handling code here:
        //smotion = new statusmotion(this);
            smotion.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void timemailItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_timemailItemStateChanged
// TODO add your handling code here:
        int emailtime = Integer.parseInt(timemail.getSelectedItem().toString())*1000;
               mde.updateemail(emailtime);
    }//GEN-LAST:event_timemailItemStateChanged

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
// TODO add your handling code here:
            //EditUser edituser = new EditUser();
            edituser.dispose();
            edituser = new EditUser();
            edituser.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
// TODO add your handling code here:
        //AddUser adduser =new AddUser();
       adduser.dispose();
            adduser = new AddUser();
        adduser.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
// TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
// TODO add your handling code here:
            captureapi.stopCapture(null,null);
            ckbxServerActiveBasic.setEnabled(true);
            variableCode.ismanual = 0;
            variableCode.flagimage = 0;
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
// TODO add your handling code here:
        if(jButton1.getText().equals("Start Capture")){
            variableCode.ismanual = 1;
            ckbxServerActiveBasic.setEnabled(false);
            captureapi.startCapture(mde.getDateTime());
        }
        else if(jButton1.getText().equals("Pause")){
            captureapi.pauseCapture();
        }
        else if(jButton1.getText().equals("Resume")){
            //System.out.println("getText return Resume");
            captureapi.resumeCapture();
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void jcomboSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboSizeItemStateChanged
// TODO add your handling code here:
        variableCode.flagStartProcessor = 1;
	captureapi.startMonitoring(null);
        //mde = new MotionDetectionEffect(this);
    }//GEN-LAST:event_jcomboSizeItemStateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
// TODO add your handling code here:
        System.out.println ("SensitiveSlider : "+jSlider2.getValue());
        mde.updateLevel(jSlider2.getValue());
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
// TODO add your handling code here:
        System.out.println ("LevelSlider : : "+jSlider1.getValue());
       	mde.updateSen(jSlider1.getValue());
        
    }//GEN-LAST:event_jSlider1StateChanged

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
// TODO add your handling code here:
       //SearchFrame Search =new SearchFrame();
       Search.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked
    public AcessMonitor getGUI(){
        return this;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               AcessMonitor ams = new AcessMonitor();
              ams.setVisible(true);
              //ams.pack();
               //p.start();
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox ckbxServerActiveBasic;
    protected javax.swing.JCheckBox emailalert;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    public javax.swing.JSlider jSlider2;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jalertmoiton;
    public javax.swing.JComboBox jcomboEncoding;
    public javax.swing.JComboBox jcomboFileType;
    public javax.swing.JComboBox jcomboSize;
    public javax.swing.JTextField jtotalarea;
    protected javax.swing.JCheckBox smsalert;
    protected javax.swing.JComboBox timemail;
    // End of variables declaration//GEN-END:variables
    
}

