/*
 * EditUser.java
 *
 * Created on 28 มกราคม 2549, 21:41 น.
 */

/**
 *
 * @author  IBM
 */
import java.sql.*;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.*;
public class EditUser extends javax.swing.JFrame {
       private Vector d = new Vector();
       private Vector h = new Vector();
       private DefaultTableModel dmodel;
    /** Creates new form EditUser */
    public EditUser() {
       
        String querystring;
        Statement s;
        Connection c;
        //String username = "root";
        //String password = "komate";
        String username = variableCode.userDB;
        String password = variableCode.passDB;
        String url = "jdbc:mysql://localhost/ams";
        String driver = "com.mysql.jdbc.Driver";
        //String driver = "org.gjt.mm.mysql.Drive";
        querystring = "SELECT username,password,email,tel FROM mobileaccount";
        try{
        Class.forName(driver);
        c = DriverManager.getConnection(url,username,password);
        s = c.createStatement();
        ResultSet r =s.executeQuery(querystring);
        ResultSetMetaData rm = r.getMetaData();

        while(r.next()){
           Vector v = new Vector();
           for(int i = 1;i <=rm.getColumnCount();i++)
             v.addElement(r.getObject(i));    
           d.addElement(v);
            
            
        }
        s.close();
        c.close();
        }
        catch(ClassNotFoundException cnfe){
        System.err.println("Failed to Connect Database");
        System.exit(1);
        }
        catch(SQLException se){
            System.err.println("Unable to connect");
            se.printStackTrace();
        }
        

        h.addElement("Username");
        h.addElement("Password");
        h.addElement("Email");
        h.addElement("Tel");
        //System.out.println(d.elementAt(1));
        dmodel = new DefaultTableModel(d,h);
        initComponents();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(dmodel);
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jpassword = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jtel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit/Delete User");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 300));

        Update.setText("Update");
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });

        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        Delete.setText("Delete");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });

        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 20));

        jusername.setEditable(false);
        getContentPane().add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 170, 20));

        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 170, -1));

        getContentPane().add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 170, -1));

        getContentPane().add(jtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("E-mail");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Tel.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, 20));

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
// TODO add your handling code here:
      if(jTable1.getSelectedRow()!=-1){    
        String querystring;
        Statement s;
        Connection c;
        //String username = "root";
        //String password = "komate";
        String username = variableCode.userDB;
        String password = variableCode.passDB;
        String url = "jdbc:mysql://localhost/ams";
        String driver = "com.mysql.jdbc.Driver";
        String user = jusername.getText();
        querystring = "DELETE FROM mobileaccount WHERE username='"+user+"'";
        //System.out.println(querystring);
        try{
        Class.forName(driver);
        c = DriverManager.getConnection(url,username,password);
        s = c.createStatement();
        s.executeUpdate(querystring);            
        
        s.close();
        c.close();
        }
        catch(ClassNotFoundException cnfe){
        System.err.println("Failed to Connect Database");
        System.exit(1);
        }
        catch(SQLException se){
            System.err.println("Unable to connect");
            se.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"User has been Delete","User Delete Complete",JOptionPane.WARNING_MESSAGE);    
        dmodel.removeRow(jTable1.getSelectedRow());
        jusername.setText("");
        jpassword.setText("");
        jemail.setText("");
        jtel.setText("");
      }
    }//GEN-LAST:event_DeleteMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
// TODO add your handling code here:
      if(jTable1.getSelectedRow()!=-1){  
        String querystring;
        Statement s;
        Connection c;
        //String username = "root";
        //String password = "komate";
        String username = variableCode.userDB;
        String password = variableCode.passDB;
        String url = "jdbc:mysql://localhost/ams";
        String driver = "com.mysql.jdbc.Driver";
        //String driver = "org.gjt.mm.mysql.Drive";
        String user = jusername.getText();
        String pass = jpassword.getText();
        String email = jemail.getText();
        String tel = jtel.getText();
        querystring = "UPDATE mobileaccount SET password='"+pass+"',email='"+email+"',tel='"+tel+"' WHERE username='"+user+"'";
        //System.out.println(querystring);
        try{
        Class.forName(driver);
        c = DriverManager.getConnection(url,username,password);
        s = c.createStatement();
        s.executeUpdate(querystring);            
        
        s.close();
        c.close();
        }
        catch(ClassNotFoundException cnfe){
        System.err.println("Failed to Connect Database");
        System.exit(1);
        }
        catch(SQLException se){
            System.err.println("Unable to connect");
            se.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"User has been Update","User Update Complete",JOptionPane.PLAIN_MESSAGE);
        Vector e = new Vector();
        e.addElement(jusername.getText());
        e.addElement(jpassword.getText());
        e.addElement(jemail.getText());
        e.addElement(jtel.getText());
        
        TableModel model=jTable1.getModel();
        for(int i = 0;i<=jTable1.getColumnCount()-1;i++)
            model.setValueAt(e.elementAt(i),jTable1.getSelectedRow(),i);

      }
    }//GEN-LAST:event_UpdateMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// TODO add your handling code here:
        Vector e = new Vector();
        if(jTable1.getSelectedRow()!=-1){
            
            for(int i = 0;i<=jTable1.getColumnCount()-1;i++){
                e.addElement(jTable1.getValueAt(jTable1.getSelectedRow(),i));    
            }
            jusername.setText(e.elementAt(0).toString());
            jpassword.setText(e.elementAt(1).toString());
            jemail.setText(e.elementAt(2).toString());
            jtel.setText(e.elementAt(3).toString());
        }
        
        
        
        
        
        //System.out.println(e);
        //System.out.println(jTable1.getSelectedColumn());
    }//GEN-LAST:event_jTable1MouseClicked
    private void refresh(){
        TableModel model=jTable1.getModel();
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jpassword;
    private javax.swing.JTextField jtel;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
    
}
