/*
 * SearchFrame.java
 *
 * Created on 20 มกราคม 2549, 23:30 น.
 */

/**
 *
 * @author  IBM
 */
import javax.swing.table.*;
import javax.swing.*;
import java.awt.event.*;
import java.util.*;
import java.sql.*;
public class SearchFrame extends javax.swing.JFrame {
    private DefaultTableModel model;
    private MovieScreen movieScreen;
    private Viewer viewimage = new Viewer();
    
    /** Creates new form SearchFrame */
    public SearchFrame() {
  
        Vector Header = new Vector();
        Vector d = new Vector();
        Header.addElement("Date");
        Header.addElement("Time");
        Header.addElement("Filename");
        Header.addElement("Path");
        model = new DefaultTableModel(d,Header);
        initComponents();
        jMotionCheckBox.setVisible(false);
         //addWindowListener(new WindowAdapter(){
           //public void windowClosing(WindowEvent e){
               // GUI.jCheckBoxMenuItem2.setSelected(false);
           //}
    //});
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSearchButton = new javax.swing.JButton();
        jDayTextField = new javax.swing.JTextField();
        jDateCheckbox = new javax.swing.JCheckBox();
        jTimeCheckBox = new javax.swing.JCheckBox();
        jMotionCheckBox = new javax.swing.JCheckBox();
        jTimeTextField = new javax.swing.JTextField();
        jMonthCheckBox = new javax.swing.JCheckBox();
        jYearCheckBox = new javax.swing.JCheckBox();
        jMonthTextField = new javax.swing.JTextField();
        jYearTextField = new javax.swing.JTextField();
        jOpenButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable(model);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Video = new javax.swing.JRadioButton();
        Image = new javax.swing.JRadioButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Video File");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSearchButton.setText("Search");
        jSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchButtonMouseClicked(evt);
            }
        });

        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 80, -1));

        jDayTextField.setEnabled(false);
        getContentPane().add(jDayTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 40, 20));

        jDateCheckbox.setText("Day");
        jDateCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jDateCheckboxItemStateChanged(evt);
            }
        });

        getContentPane().add(jDateCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        jTimeCheckBox.setText("Time");
        jTimeCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jTimeCheckBoxItemStateChanged(evt);
            }
        });

        getContentPane().add(jTimeCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jMotionCheckBox.setText("Motion Detection Alert");
        getContentPane().add(jMotionCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTimeTextField.setEnabled(false);
        getContentPane().add(jTimeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 40, 20));

        jMonthCheckBox.setText("Month");
        jMonthCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMonthCheckBoxItemStateChanged(evt);
            }
        });

        getContentPane().add(jMonthCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 20));

        jYearCheckBox.setText("Year");
        jYearCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jYearCheckBoxItemStateChanged(evt);
            }
        });

        getContentPane().add(jYearCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 20));

        jMonthTextField.setEnabled(false);
        getContentPane().add(jMonthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 40, 20));

        jYearTextField.setEnabled(false);
        getContentPane().add(jYearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 40, 20));

        jOpenButton.setText("Open File");
        jOpenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOpenButtonMouseClicked(evt);
            }
        });

        getContentPane().add(jOpenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 90, -1));

        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 510, 300));

        jLabel1.setText("Hours");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 20));

        jLabel2.setText("Search for :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        Video.setSelected(true);
        Video.setText("Video");
        Video.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VideoItemStateChanged(evt);
            }
        });

        getContentPane().add(Video, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        Image.setText("Image");
        Image.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ImageItemStateChanged(evt);
            }
        });

        getContentPane().add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 30));

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void ImageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ImageItemStateChanged
// TODO add your handling code here:
        if(Image.isSelected()){
            Video.setSelected(false);
            Image.setSelected(true);
        }
        else{
            Video.setSelected(true);
            Image.setSelected(false);
        }
    }//GEN-LAST:event_ImageItemStateChanged

    private void VideoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VideoItemStateChanged
// TODO add your handling code here:
        if(Video.isSelected()){
            Video.setSelected(true);
            Image.setSelected(false);
        }
        else{
            Video.setSelected(false);
            Image.setSelected(true);
        }
    }//GEN-LAST:event_VideoItemStateChanged

    private void jOpenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOpenButtonMouseClicked
// TODO add your handling code here:
        String pathfile;
        pathfile = model.getValueAt(jTable2.getSelectedRow(),3).toString();
        if(Video.isSelected())
            loadMovie("file:///"+pathfile);
        else{
            //pathfile.trim();
            viewimage.setFileName(pathfile);
            viewimage.showImage();
        }
    }//GEN-LAST:event_jOpenButtonMouseClicked

    private void jTimeCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jTimeCheckBoxItemStateChanged
// TODO add your handling code here:
        if (jTimeCheckBox.isSelected())
            jTimeTextField.setEnabled(true);
        else
            jTimeTextField.setEnabled(false);     
    }//GEN-LAST:event_jTimeCheckBoxItemStateChanged

    private void jYearCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jYearCheckBoxItemStateChanged
// TODO add your handling code here:
        if (jYearCheckBox.isSelected())
            jYearTextField.setEnabled(true);
        else
            jYearTextField.setEnabled(false);
    }//GEN-LAST:event_jYearCheckBoxItemStateChanged

    private void jMonthCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMonthCheckBoxItemStateChanged
// TODO add your handling code here:
        if (jMonthCheckBox.isSelected())
            jMonthTextField.setEnabled(true);
        else
            jMonthTextField.setEnabled(false);
    }//GEN-LAST:event_jMonthCheckBoxItemStateChanged

    private void jDateCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jDateCheckboxItemStateChanged
// TODO add your handling code here:
        if (jDateCheckbox.isSelected())
            jDayTextField.setEnabled(true);
        else
            jDayTextField.setEnabled(false);
    }//GEN-LAST:event_jDateCheckboxItemStateChanged

    private void jSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchButtonMouseClicked
// TODO add your handling code here:
        String day,month,year,time;
    
        if(jDateCheckbox.isSelected())
            day = jDayTextField.getText();
        else
            day = "%";
        if(jMonthCheckBox.isSelected())
            month = jMonthTextField.getText();
        else
            month = "%";
        if(jYearCheckBox.isSelected())
            year = jYearTextField.getText();
        else
            year = "%";
        if(jTimeCheckBox.isSelected())
            time = jTimeTextField.getText();
        else
            time = "%";
        if (day.length()==0)
            day = "%";
        if (month.length()==0)
            month = "%";
        if (year.length()==0)
            year = "%";
        if (time.length()==0)
            time = "%";
       
        //System.out.println(day+month+year+time);       
        search(day, month, year,time);
    }//GEN-LAST:event_jSearchButtonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
      //  java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
          //      new SearchFrame().setVisible(true);
            //}
        //});
    //}
    private void search(String Day,String Month,String Year,String Time){
        Vector Header = new Vector();
        Vector d = new Vector();
        Header.addElement("Date");
        Header.addElement("Time");
        Header.addElement("Filename");
        Header.addElement("Path");
        String querystring;
        Statement s;
        Connection c;
        //String username = "root";
        //String password = "komate";
        String username = variableCode.userDB;
        String password = variableCode.passDB;
        String url = "jdbc:mysql://localhost/ams";
        String driver = "com.mysql.jdbc.Driver";
        //String driver = "org.gjt.mm.mysql.Drive";
        if(Day.length()==1 && jDateCheckbox.isSelected() && Day != "%")
            Day = "0"+Day;
        if(Month.length()==1 && jMonthCheckBox.isSelected() && Month != "%")
            Month = "0"+Month;
         if(Time.length()==1 && jTimeCheckBox.isSelected() && Time != "%")
            Time = "0"+Time;
       
        if(Video.isSelected())    
            querystring = "SELECT Datestart,Timestart,Filename,Path FROM videofile WHERE " +
                "Datestart LIKE '%"+Year+"-"+Month+"-"+Day+"' AND Timestart LIKE '"+Time+":%'" ;
        else
            querystring = "SELECT Date,Time,Filename,Path FROM imagefile WHERE " +
                "Date LIKE '%"+Year+"-"+Month+"-"+Day+"' AND Time LIKE '"+Time+":%'" ;
        //System.out.println(querystring);
        try{
        Class.forName(driver);
        c = DriverManager.getConnection(url,username,password);
        s = c.createStatement();
        ResultSet r =s.executeQuery(querystring);
        ResultSetMetaData rm = r.getMetaData();

        while(r.next()){
           Vector v = new Vector();
           for(int i = 1;i <=rm.getColumnCount();i++)
             v.addElement(r.getObject(i));    
           d.addElement(v);
            
            
        }
        s.close();
        c.close();
        }
        catch(ClassNotFoundException cnfe){
        System.err.println("Failed to Connect Database");
        System.exit(1);
        }
        catch(SQLException se){
            System.err.println("Unable to connect");
            se.printStackTrace();
        }
        model.setDataVector(d, Header);
    }
    
   public void loadMovie(String location)
    {
		// Check if a movie is alredy playing. If so, remove it.
		if(movieScreen != null)
	    	closeMovieScreen();

		// Create a new window for the movie.
		movieScreen = new MovieScreen(location);
		//movieScreen.debug = debug;

		// See if we are able to load the movie. If not, discarde the newly created window. 
		//printDebug("Trying to load movie");
		if(movieScreen.loadMovie() != 0){
	    	System.out.println("Unable to load movie");	    
	    	closeMovieScreen();
	    	return;
		}
	
		movieScreen.setLoop(false);
		// Start the movie.
      	movieScreen.start();
    }

 public void closeMovieScreen(){
       	//if(movieScreen != null){
	    //movieScreen.destroy();
	//}
	//movieScreen = null;
	
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Image;
    private javax.swing.JRadioButton Video;
    private javax.swing.JCheckBox jDateCheckbox;
    private javax.swing.JTextField jDayTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox jMonthCheckBox;
    private javax.swing.JTextField jMonthTextField;
    private javax.swing.JCheckBox jMotionCheckBox;
    private javax.swing.JButton jOpenButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTable jTable2;
    private javax.swing.JCheckBox jTimeCheckBox;
    private javax.swing.JTextField jTimeTextField;
    private javax.swing.JCheckBox jYearCheckBox;
    private javax.swing.JTextField jYearTextField;
    // End of variables declaration//GEN-END:variables
    
}
