/* File: INC\NAPT.H */

/*lint -e534 -e713 -e732 -e785 -e737 */

/*lint -elib(????) */
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <memory.h>
#include <malloc.h>
#include <dos.h>
#include <bios.h>
#include <process.h>
#include "c:\multi-c\mtc.h"

/*lint +elib(????) */
#include "inc\defines.h"
#include "inc\typedefs.h"
#include "inc\function.h"
#include "inc\globals.h"
