//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FirewallAgent.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_FIREWATYPE                  129
#define IDI_LOCK                        131
#define IDI_UNLOCK                      132
#define IDI_TRAY                        138
#define IDD_LOG                         139
#define IDC_LOGLIST                     1009
#define ID_START_FILTER                 32771
#define ID_STOP_FILTER                  32772
#define ID_TEST_FILTER                  32773
#define ID_GO_ONLINE                    32775
#define ID_SHOW_LOG                     32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
