//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FirewallServer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FIREWALLSERVER_DIALOG       102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDI_OFFLINE                     129
#define IDI_ONLINE                      130
#define IDD_CLIENTINFO                  131
#define IDD_DBPART_DIALOG               132
#define IDD_GROUPRECORD                 133
#define IDD_NEWCLIENT                   134
#define IDD_RULERECORD                  135
#define IDD_RULESETTAB                  136
#define IDD_RULETAB                     138
#define IDC_SENDRULE                    1000
#define IDC_STOPFILTER                  1001
#define IDC_GROUPTAB                    1002
#define IDC_CANCEL                      1002
#define IDC_RULETAB                     1003
#define IDC_CLIENTLIST                  1004
#define IDC_NEWCLIENT                   1005
#define IDC_REMOVECLIENT                1006
#define IDC_IPADDR                      1007
#define IDC_GET_LOG                     1007
#define IDC_GROUP                       1008
#define IDC_RULELIST                    1009
#define IDC_RULE                        1010
#define IDC_SRCADDR                     1011
#define IDC_SRCMASK                     1012
#define IDC_SRCPORT                     1013
#define IDC_SPRANGE                     1014
#define IDC_DSTADDR                     1015
#define IDC_DSTMASK                     1016
#define IDC_DSTPORT                     1017
#define IDC_DPRANGE                     1018
#define IDC_PTCOL                       1019
#define IDC_NEW                         1020
#define IDC_ADD                         1021
#define IDC_UPDATE                      1022
#define IDC_DELETE                      1023
#define IDC_OK                          1024
#define IDC_LISTGP                      1030
#define IDC_DETAIL                      1033
#define IDC_LISTRE                      1034
#define IDC_GPNAME                      1036
#define IDC_NEWGROUP                    1038

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
