#if !defined(AFX_MSCHART_H__A6E16CAC_4D01_4855_AF56_60B1F143D75B__INCLUDED_)
#define AFX_MSCHART_H__A6E16CAC_4D01_4855_AF56_60B1F143D75B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcTitle;
class CVcFootnote;
class CVcBackdrop;
class CVcLegend;
class CVcDataGrid;
class CVcPlot;

/////////////////////////////////////////////////////////////////////////////
// CMSChart wrapper class

//##ModelId=3E9ABEEF01D8
class CMSChart : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMSChart)
public:
	//##ModelId=3E9ABEEF0284
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x3a2b370c, 0xba0a, 0x11d1, { 0xb1, 0x37, 0x0, 0x0, 0xf8, 0x75, 0x3f, 0x5d } };
		return clsid;
	}
	//##ModelId=3E9ABEEF0273
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

	//##ModelId=3E9ABEEF027B
    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEEF0272
	BOOL GetAutoIncrement();
	//##ModelId=3E9ABEEF0270
	void SetAutoIncrement(BOOL bNewValue);
	//##ModelId=3E9ABEEF026F
	BOOL GetRandomFill();
	//##ModelId=3E9ABEEF026D
	void SetRandomFill(BOOL bNewValue);
	//##ModelId=3E9ABEEF026C
	long GetChartType();
	//##ModelId=3E9ABEEF026A
	void SetChartType(long nNewValue);
	//##ModelId=3E9ABEEF0269
	short GetColumn();
	//##ModelId=3E9ABEEF0267
	void SetColumn(short nNewValue);
	//##ModelId=3E9ABEEF0266
	short GetColumnCount();
	//##ModelId=3E9ABEEF0264
	void SetColumnCount(short nNewValue);
	//##ModelId=3E9ABEEF0263
	CString GetColumnLabel();
	//##ModelId=3E9ABEEF0261
	void SetColumnLabel(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEEF0260
	short GetColumnLabelCount();
	//##ModelId=3E9ABEEF025E
	void SetColumnLabelCount(short nNewValue);
	//##ModelId=3E9ABEEF025D
	short GetColumnLabelIndex();
	//##ModelId=3E9ABEEF025B
	void SetColumnLabelIndex(short nNewValue);
	//##ModelId=3E9ABEEF025A
	CString GetData();
	//##ModelId=3E9ABEEF0258
	void SetData(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEEF0257
	CString GetFootnoteText();
	//##ModelId=3E9ABEEF0255
	void SetFootnoteText(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEEF0254
	BOOL GetRepaint();
	//##ModelId=3E9ABEEF0252
	void SetRepaint(BOOL bNewValue);
	//##ModelId=3E9ABEEF0251
	short GetRow();
	//##ModelId=3E9ABEEF024F
	void SetRow(short nNewValue);
	//##ModelId=3E9ABEEF024E
	short GetRowCount();
	//##ModelId=3E9ABEEF024C
	void SetRowCount(short nNewValue);
	//##ModelId=3E9ABEEF024B
	CString GetRowLabel();
	//##ModelId=3E9ABEEF0249
	void SetRowLabel(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEEF0248
	short GetRowLabelCount();
	//##ModelId=3E9ABEEF0246
	void SetRowLabelCount(short nNewValue);
	//##ModelId=3E9ABEEF0245
	short GetRowLabelIndex();
	//##ModelId=3E9ABEEF0243
	void SetRowLabelIndex(short nNewValue);
	//##ModelId=3E9ABEEF0242
	short GetSeriesColumn();
	//##ModelId=3E9ABEEF0240
	void SetSeriesColumn(short nNewValue);
	//##ModelId=3E9ABEEF023F
	long GetSeriesType();
	//##ModelId=3E9ABEEF023D
	void SetSeriesType(long nNewValue);
	//##ModelId=3E9ABEEF023C
	BOOL GetShowLegend();
	//##ModelId=3E9ABEEF023A
	void SetShowLegend(BOOL bNewValue);
	//##ModelId=3E9ABEEF0239
	long GetDrawMode();
	//##ModelId=3E9ABEEF0237
	void SetDrawMode(long nNewValue);
	//##ModelId=3E9ABEEF0236
	long GetBorderStyle();
	//##ModelId=3E9ABEEF0234
	void SetBorderStyle(long nNewValue);
	//##ModelId=3E9ABEEF0233
	BOOL GetEnabled();
	//##ModelId=3E9ABEEF0231
	void SetEnabled(BOOL bNewValue);
	//##ModelId=3E9ABEEF0230
	long GetHWnd();
	//##ModelId=3E9ABEEF022F
	CVcTitle GetTitle();
	//##ModelId=3E9ABEEF022E
	CVcFootnote GetFootnote();
	//##ModelId=3E9ABEEF022D
	CString GetTitleText();
	//##ModelId=3E9ABEEF022B
	void SetTitleText(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEEF022A
	BOOL GetStacking();
	//##ModelId=3E9ABEEF0228
	void SetStacking(BOOL bNewValue);
	//##ModelId=3E9ABEEF0227
	long GetTextLengthType();
	//##ModelId=3E9ABEEF0225
	void SetTextLengthType(long nNewValue);
	//##ModelId=3E9ABEEF0224
	BOOL GetAllowSelections();
	//##ModelId=3E9ABEEF0222
	void SetAllowSelections(BOOL bNewValue);
	//##ModelId=3E9ABEEF0221
	BOOL GetAllowSeriesSelection();
	//##ModelId=3E9ABEEF021F
	void SetAllowSeriesSelection(BOOL bNewValue);
	//##ModelId=3E9ABEEF021E
	BOOL GetAllowDynamicRotation();
	//##ModelId=3E9ABEEF021C
	void SetAllowDynamicRotation(BOOL bNewValue);
	//##ModelId=3E9ABEEF021B
	short GetActiveSeriesCount();
	//##ModelId=3E9ABEEF021A
	CVcBackdrop GetBackdrop();
	//##ModelId=3E9ABEEF0219
	CVcLegend GetLegend();
	//##ModelId=3E9ABEEF0218
	CVcDataGrid GetDataGrid();
	//##ModelId=3E9ABEEF0217
	CVcPlot GetPlot();
	//##ModelId=3E9ABEEF0216
	BOOL GetAllowDithering();
	//##ModelId=3E9ABEEF0214
	void SetAllowDithering(BOOL bNewValue);
	//##ModelId=3E9ABEEF0213
	BOOL GetDoSetCursor();
	//##ModelId=3E9ABEEF0211
	void SetDoSetCursor(BOOL bNewValue);
	//##ModelId=3E9ABEEF0210
	BOOL GetChart3d();
	//##ModelId=3E9ABEEF020F
	VARIANT GetChartData();
	//##ModelId=3E9ABEEF020D
	void SetChartData(const VARIANT& newValue);
	//##ModelId=3E9ABEEF020C
	long GetMousePointer();
	//##ModelId=3E9ABEEF020A
	void SetMousePointer(long nNewValue);
	//##ModelId=3E9ABEEF0209
	void Refresh();
	//##ModelId=3E9ABEEF0208
	void EditPaste();
	//##ModelId=3E9ABEEF0207
	void EditCopy();
	//##ModelId=3E9ABEEF0206
	void Layout();
	//##ModelId=3E9ABEEF0205
	void ToDefaults();
	//##ModelId=3E9ABEEF01FF
	void SelectPart(short part, short index1, short index2, short index3, short index4);
	//##ModelId=3E9ABEEF01F9
	void GetSelectedPart(short* part, short* index1, short* index2, short* index3, short* index4);
	//##ModelId=3E9ABEEF01F1
	void TwipsToChartPart(long xVal, long yVal, short* part, short* index1, short* index2, short* index3, short* index4);
	//##ModelId=3E9ABEEF01F0
	long GetOLEDragMode();
	//##ModelId=3E9ABEEF01EE
	void SetOLEDragMode(long nNewValue);
	//##ModelId=3E9ABEEF01ED
	long GetOLEDropMode();
	//##ModelId=3E9ABEEF01EA
	void SetOLEDropMode(long nNewValue);
	//##ModelId=3E9ABEEF01E9
	void OLEDrag();
	//##ModelId=3E9ABEEF01E8
	LPUNKNOWN GetDataSource();
	//##ModelId=3E9ABEEF01E6
	void SetRefDataSource(LPUNKNOWN newValue);
	//##ModelId=3E9ABEEF01E5
	CString GetDataMember();
	//##ModelId=3E9ABEEF01E3
	void SetDataMember(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MSCHART_H__A6E16CAC_4D01_4855_AF56_60B1F143D75B__INCLUDED_)
