#if !defined(AFX_VCAXISSCALE_H__92BE485B_2763_42DB_A764_81AB7BB64DED__INCLUDED_)
#define AFX_VCAXISSCALE_H__92BE485B_2763_42DB_A764_81AB7BB64DED__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcAxisScale wrapper class

//##ModelId=3E9ABEEA01DB
class CVcAxisScale : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEEA01F1
	CVcAxisScale() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEEA01F2
	CVcAxisScale(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEEA01F4
	CVcAxisScale(const CVcAxisScale& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEEA01F0
	BOOL GetHide();
	//##ModelId=3E9ABEEA01EE
	void SetHide(BOOL bNewValue);
	//##ModelId=3E9ABEEA01ED
	long GetType();
	//##ModelId=3E9ABEEA01EB
	void SetType(long nNewValue);
	//##ModelId=3E9ABEEA01EA
	short GetLogBase();
	//##ModelId=3E9ABEEA01E8
	void SetLogBase(short nNewValue);
	//##ModelId=3E9ABEEA01E7
	long GetPercentBasis();
	//##ModelId=3E9ABEEA01E5
	void SetPercentBasis(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCAXISSCALE_H__92BE485B_2763_42DB_A764_81AB7BB64DED__INCLUDED_)
