#if !defined(AFX_VCAXIS_H__871E6FE4_76E6_4306_B025_6EE64D0F0A6B__INCLUDED_)
#define AFX_VCAXIS_H__871E6FE4_76E6_4306_B025_6EE64D0F0A6B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcPen;
class CVcCategoryScale;
class CVcAxisGrid;
class CVcIntersection;
class CVcTick;
class CVcAxisScale;
class CVcValueScale;
class CVcAxisTitle;
class CVcLabels;

/////////////////////////////////////////////////////////////////////////////
// CVcAxis wrapper class

//##ModelId=3E9ABEE702A9
class CVcAxis : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEE702BD
	CVcAxis() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEE702BE
	CVcAxis(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEE702C0
	CVcAxis(const CVcAxis& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEE702BA
	CVcPen GetPen();
	//##ModelId=3E9ABEE702B9
	short GetLabelLevelCount();
	//##ModelId=3E9ABEE702B8
	CVcCategoryScale GetCategoryScale();
	//##ModelId=3E9ABEE702B7
	CVcAxisGrid GetAxisGrid();
	//##ModelId=3E9ABEE702B6
	CVcIntersection GetIntersection();
	//##ModelId=3E9ABEE702B5
	CVcTick GetTick();
	//##ModelId=3E9ABEE702B4
	CVcAxisScale GetAxisScale();
	//##ModelId=3E9ABEE702B3
	CVcValueScale GetValueScale();
	//##ModelId=3E9ABEE702AC
	CVcAxisTitle GetAxisTitle();
	//##ModelId=3E9ABEE702AB
	CVcLabels GetLabels();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCAXIS_H__871E6FE4_76E6_4306_B025_6EE64D0F0A6B__INCLUDED_)
