#if !defined(AFX_VCAXISTITLE_H__E629BDCE_9EF5_4BB4_A06D_8B08B8B39E88__INCLUDED_)
#define AFX_VCAXISTITLE_H__E629BDCE_9EF5_4BB4_A06D_8B08B8B39E88__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcBackdrop;
class CVcFont;
class CVcTextLayout;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CVcAxisTitle wrapper class

//##ModelId=3E9ABEE800FB
class CVcAxisTitle : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEE80112
	CVcAxisTitle() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEE80113
	CVcAxisTitle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEE80115
	CVcAxisTitle(const CVcAxisTitle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEE80111
	CString GetText();
	//##ModelId=3E9ABEE8010F
	void SetText(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEE8010D
	CVcBackdrop GetBackdrop();
	//##ModelId=3E9ABEE8010C
	CVcFont GetVtFont();
	//##ModelId=3E9ABEE8010B
	BOOL GetVisible();
	//##ModelId=3E9ABEE80109
	void SetVisible(BOOL bNewValue);
	//##ModelId=3E9ABEE80108
	CVcTextLayout GetTextLayout();
	//##ModelId=3E9ABEE80107
	short GetTextLength();
	//##ModelId=3E9ABEE80105
	void SetRefFont(LPDISPATCH newValue);
	//##ModelId=3E9ABEE800FD
	COleFont GetFont();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCAXISTITLE_H__E629BDCE_9EF5_4BB4_A06D_8B08B8B39E88__INCLUDED_)
