#if !defined(AFX_VCBACKDROP_H__DEC315E1_2D12_41B6_AC44_FBEF7D4FAFE6__INCLUDED_)
#define AFX_VCBACKDROP_H__DEC315E1_2D12_41B6_AC44_FBEF7D4FAFE6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcShadow;
class CVcFrame;
class CVcFill;

/////////////////////////////////////////////////////////////////////////////
// CVcBackdrop wrapper class

//##ModelId=3E9ABEE601D5
class CVcBackdrop : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEE601E2
	CVcBackdrop() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEE601E3
	CVcBackdrop(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEE601E5
	CVcBackdrop(const CVcBackdrop& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEE601E1
	CVcShadow GetShadow();
	//##ModelId=3E9ABEE601E0
	CVcFrame GetFrame();
	//##ModelId=3E9ABEE601DF
	CVcFill GetFill();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCBACKDROP_H__DEC315E1_2D12_41B6_AC44_FBEF7D4FAFE6__INCLUDED_)
