#if !defined(AFX_VCCOOR_H__D9DEFC6B_2F43_4E61_B9C6_220F9CD20009__INCLUDED_)
#define AFX_VCCOOR_H__D9DEFC6B_2F43_4E61_B9C6_220F9CD20009__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcCoor wrapper class

//##ModelId=3E9ABEE6038D
class CVcCoor : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEE6039C
	CVcCoor() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEE6039D
	CVcCoor(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEE6039F
	CVcCoor(const CVcCoor& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEE6039B
	float GetX();
	//##ModelId=3E9ABEE60399
	void SetX(float newValue);
	//##ModelId=3E9ABEE60398
	float GetY();
	//##ModelId=3E9ABEE60392
	void SetY(float newValue);
	//##ModelId=3E9ABEE6038F
	void Set(float X, float Y);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCCOOR_H__D9DEFC6B_2F43_4E61_B9C6_220F9CD20009__INCLUDED_)
