#if !defined(AFX_VCDATAPOINTLABEL_H__ED11EA57_9B84_4EC8_B993_217C5E510A20__INCLUDED_)
#define AFX_VCDATAPOINTLABEL_H__ED11EA57_9B84_4EC8_B993_217C5E510A20__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcBackdrop;
class CVcFont;
class CVcLCoor;
class CVcTextLayout;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CVcDataPointLabel wrapper class

//##ModelId=3E9ABEEA03CF
class CVcDataPointLabel : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEEB0012
	CVcDataPointLabel() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEEB0013
	CVcDataPointLabel(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEEB0015
	CVcDataPointLabel(const CVcDataPointLabel& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEEB0011
	CString GetText();
	//##ModelId=3E9ABEEB000F
	void SetText(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEEB000D
	CVcBackdrop GetBackdrop();
	//##ModelId=3E9ABEEB000C
	CVcFont GetVtFont();
	//##ModelId=3E9ABEEB000B
	CVcLCoor GetOffset();
	//##ModelId=3E9ABEEB000A
	CVcTextLayout GetTextLayout();
	//##ModelId=3E9ABEEB0009
	long GetLocationType();
	//##ModelId=3E9ABEEB0007
	void SetLocationType(long nNewValue);
	//##ModelId=3E9ABEEB0006
	BOOL GetCustom();
	//##ModelId=3E9ABEEA03ED
	void SetCustom(BOOL bNewValue);
	//##ModelId=3E9ABEEA03EC
	short GetComponent();
	//##ModelId=3E9ABEEA03EA
	void SetComponent(short nNewValue);
	//##ModelId=3E9ABEEA03E9
	long GetLineStyle();
	//##ModelId=3E9ABEEA03E7
	void SetLineStyle(long nNewValue);
	//##ModelId=3E9ABEEA03E6
	CString GetValueFormat();
	//##ModelId=3E9ABEEA03E4
	void SetValueFormat(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEEA03E3
	CString GetPercentFormat();
	//##ModelId=3E9ABEEA03E0
	void SetPercentFormat(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEEA03DF
	short GetTextLength();
	//##ModelId=3E9ABEEA03DD
	void SetRefFont(LPDISPATCH newValue);
	//##ModelId=3E9ABEEA03DC
	COleFont GetFont();
	//##ModelId=3E9ABEEA03DB
	void ResetCustomLabel();
	//##ModelId=3E9ABEEA03DA
	void Select();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCDATAPOINTLABEL_H__ED11EA57_9B84_4EC8_B993_217C5E510A20__INCLUDED_)
