#if !defined(AFX_VCFONT_H__8E32ECC1_943B_4D89_BA0F_BDD39182C4E4__INCLUDED_)
#define AFX_VCFONT_H__8E32ECC1_943B_4D89_BA0F_BDD39182C4E4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcColor;

/////////////////////////////////////////////////////////////////////////////
// CVcFont wrapper class

//##ModelId=3E9ABEE7003C
class CVcFont : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEE70050
	CVcFont() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEE70051
	CVcFont(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEE70053
	CVcFont(const CVcFont& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEE7004F
	CString GetName();
	//##ModelId=3E9ABEE7004D
	void SetName(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEE7004C
	float GetSize();
	//##ModelId=3E9ABEE7004A
	void SetSize(float newValue);
	//##ModelId=3E9ABEE70049
	short GetStyle();
	//##ModelId=3E9ABEE70047
	void SetStyle(short nNewValue);
	//##ModelId=3E9ABEE70046
	short GetEffect();
	//##ModelId=3E9ABEE7003F
	void SetEffect(short nNewValue);
	//##ModelId=3E9ABEE7003E
	CVcColor GetVtColor();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCFONT_H__8E32ECC1_943B_4D89_BA0F_BDD39182C4E4__INCLUDED_)
