#if !defined(AFX_VCFOOTNOTE_H__50E4E7BC_2204_4A6F_AC23_6D31861D0F83__INCLUDED_)
#define AFX_VCFOOTNOTE_H__50E4E7BC_2204_4A6F_AC23_6D31861D0F83__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcTextLayout;
class CVcLocation;
class CVcBackdrop;
class CVcFont;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CVcFootnote wrapper class

//##ModelId=3E9ABEE70385
class CVcFootnote : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEE7039D
	CVcFootnote() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEE7039E
	CVcFootnote(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEE703A0
	CVcFootnote(const CVcFootnote& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEE7039C
	CVcTextLayout GetTextLayout();
	//##ModelId=3E9ABEE7039B
	CVcLocation GetLocation();
	//##ModelId=3E9ABEE7039A
	CVcBackdrop GetBackdrop();
	//##ModelId=3E9ABEE70399
	CVcFont GetVtFont();
	//##ModelId=3E9ABEE70397
	CString GetText();
	//##ModelId=3E9ABEE70395
	void SetText(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEE70394
	short GetTextLength();
	//##ModelId=3E9ABEE70392
	void SetRefFont(LPDISPATCH newValue);
	//##ModelId=3E9ABEE70391
	COleFont GetFont();
	//##ModelId=3E9ABEE70390
	void Select();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCFOOTNOTE_H__50E4E7BC_2204_4A6F_AC23_6D31861D0F83__INCLUDED_)
