#if !defined(AFX_VCLABEL_H__5EBFA17A_BA8D_4100_97EC_DF69E1E316A2__INCLUDED_)
#define AFX_VCLABEL_H__5EBFA17A_BA8D_4100_97EC_DF69E1E316A2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcBackdrop;
class CVcFont;
class CVcTextLayout;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CVcLabel wrapper class

//##ModelId=3E9ABEEB010A
class CVcLabel : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEEB0121
	CVcLabel() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEEB0122
	CVcLabel(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEEB0124
	CVcLabel(const CVcLabel& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEEB0120
	CVcBackdrop GetBackdrop();
	//##ModelId=3E9ABEEB011F
	CString GetFormat();
	//##ModelId=3E9ABEEB011C
	void SetFormat(LPCTSTR lpszNewValue);
	//##ModelId=3E9ABEEB011B
	CVcFont GetVtFont();
	//##ModelId=3E9ABEEB011A
	BOOL GetAuto();
	//##ModelId=3E9ABEEB0118
	void SetAuto(BOOL bNewValue);
	//##ModelId=3E9ABEEB0117
	BOOL GetStanding();
	//##ModelId=3E9ABEEB0115
	void SetStanding(BOOL bNewValue);
	//##ModelId=3E9ABEEB0114
	CVcTextLayout GetTextLayout();
	//##ModelId=3E9ABEEB010F
	short GetFormatLength();
	//##ModelId=3E9ABEEB010D
	void SetRefFont(LPDISPATCH newValue);
	//##ModelId=3E9ABEEB010C
	COleFont GetFont();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCLABEL_H__5EBFA17A_BA8D_4100_97EC_DF69E1E316A2__INCLUDED_)
