#if !defined(AFX_VCPLOTBASE_H__132D5908_FF75_4FC3_8EBA_29AF43021F3E__INCLUDED_)
#define AFX_VCPLOTBASE_H__132D5908_FF75_4FC3_8EBA_29AF43021F3E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcBrush;
class CVcPen;

/////////////////////////////////////////////////////////////////////////////
// CVcPlotBase wrapper class

//##ModelId=3E9ABEEB02C2
class CVcPlotBase : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEEB02D2
	CVcPlotBase() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEEB02D6
	CVcPlotBase(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEEB02D8
	CVcPlotBase(const CVcPlotBase& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEEB02D1
	float GetBaseHeight();
	//##ModelId=3E9ABEEB02CF
	void SetBaseHeight(float newValue);
	//##ModelId=3E9ABEEB02CE
	CVcBrush GetBrush();
	//##ModelId=3E9ABEEB02CD
	CVcPen GetPen();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCPLOTBASE_H__132D5908_FF75_4FC3_8EBA_29AF43021F3E__INCLUDED_)
