#if !defined(AFX_VCRECT_H__A747B384_C92D_4BDF_B9DF_79F6391CB34C__INCLUDED_)
#define AFX_VCRECT_H__A747B384_C92D_4BDF_B9DF_79F6391CB34C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcCoor;

/////////////////////////////////////////////////////////////////////////////
// CVcRect wrapper class

//##ModelId=3E9ABEEB0308
class CVcRect : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEEB0312
	CVcRect() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEEB0313
	CVcRect(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEEB0315
	CVcRect(const CVcRect& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEEB030B
	CVcCoor GetMin();
	//##ModelId=3E9ABEEB030A
	CVcCoor GetMax();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCRECT_H__A747B384_C92D_4BDF_B9DF_79F6391CB34C__INCLUDED_)
