#if !defined(AFX_VCSERIESMARKER_H__3FDBE7A7_F90F_4F3E_88FA_63980F0F046E__INCLUDED_)
#define AFX_VCSERIESMARKER_H__3FDBE7A7_F90F_4F3E_88FA_63980F0F046E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcSeriesMarker wrapper class

//##ModelId=3E9ABEE60026
class CVcSeriesMarker : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEE60033
	CVcSeriesMarker() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEE60034
	CVcSeriesMarker(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEE60036
	CVcSeriesMarker(const CVcSeriesMarker& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEE60032
	BOOL GetAuto();
	//##ModelId=3E9ABEE60030
	void SetAuto(BOOL bNewValue);
	//##ModelId=3E9ABEE6002A
	BOOL GetShow();
	//##ModelId=3E9ABEE60028
	void SetShow(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCSERIESMARKER_H__3FDBE7A7_F90F_4F3E_88FA_63980F0F046E__INCLUDED_)
