#if !defined(AFX_VCSERIESPOSITION_H__62C8F784_FA1F_49A0_A251_775CC59762E6__INCLUDED_)
#define AFX_VCSERIESPOSITION_H__62C8F784_FA1F_49A0_A251_775CC59762E6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcSeriesPosition wrapper class

//##ModelId=3E9ABEEA00E0
class CVcSeriesPosition : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEEA00FA
	CVcSeriesPosition() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEEA00FB
	CVcSeriesPosition(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEEA00FD
	CVcSeriesPosition(const CVcSeriesPosition& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEEA00F9
	BOOL GetExcluded();
	//##ModelId=3E9ABEEA00F7
	void SetExcluded(BOOL bNewValue);
	//##ModelId=3E9ABEEA00F6
	BOOL GetHidden();
	//##ModelId=3E9ABEEA00F4
	void SetHidden(BOOL bNewValue);
	//##ModelId=3E9ABEEA00F0
	short GetOrder();
	//##ModelId=3E9ABEEA00EE
	void SetOrder(short nNewValue);
	//##ModelId=3E9ABEEA00ED
	short GetStackOrder();
	//##ModelId=3E9ABEEA00EB
	void SetStackOrder(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCSERIESPOSITION_H__62C8F784_FA1F_49A0_A251_775CC59762E6__INCLUDED_)
