#if !defined(AFX_VCTEXTLAYOUT_H__C08F3F5E_65C1_46FD_B829_AC3F667D02E2__INCLUDED_)
#define AFX_VCTEXTLAYOUT_H__C08F3F5E_65C1_46FD_B829_AC3F667D02E2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcTextLayout wrapper class

//##ModelId=3E9ABEF10040
class CVcTextLayout : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEF10057
	CVcTextLayout() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEF10058
	CVcTextLayout(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEF1005A
	CVcTextLayout(const CVcTextLayout& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEF10056
	long GetHorzAlignment();
	//##ModelId=3E9ABEF10054
	void SetHorzAlignment(long nNewValue);
	//##ModelId=3E9ABEF10053
	long GetVertAlignment();
	//##ModelId=3E9ABEF10051
	void SetVertAlignment(long nNewValue);
	//##ModelId=3E9ABEF10050
	long GetOrientation();
	//##ModelId=3E9ABEF1004E
	void SetOrientation(long nNewValue);
	//##ModelId=3E9ABEF1004D
	BOOL GetWordWrap();
	//##ModelId=3E9ABEF1004B
	void SetWordWrap(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCTEXTLAYOUT_H__C08F3F5E_65C1_46FD_B829_AC3F667D02E2__INCLUDED_)
