#if !defined(AFX_VCTICK_H__9FA07D9F_E91C_4F74_B089_5C0F3A0D30E1__INCLUDED_)
#define AFX_VCTICK_H__9FA07D9F_E91C_4F74_B089_5C0F3A0D30E1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcTick wrapper class

//##ModelId=3E9ABEE60293
class CVcTick : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEE6029E
	CVcTick() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEE6029F
	CVcTick(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEE602A1
	CVcTick(const CVcTick& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEE6029D
	float GetLength();
	//##ModelId=3E9ABEE60298
	void SetLength(float newValue);
	//##ModelId=3E9ABEE60297
	long GetStyle();
	//##ModelId=3E9ABEE60295
	void SetStyle(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCTICK_H__9FA07D9F_E91C_4F74_B089_5C0F3A0D30E1__INCLUDED_)
