#if !defined(AFX_VCVALUESCALE_H__53AFC64D_1036_47ED_88A9_40BFE44D67DD__INCLUDED_)
#define AFX_VCVALUESCALE_H__53AFC64D_1036_47ED_88A9_40BFE44D67DD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcValueScale wrapper class

//##ModelId=3E9ABEEF039A
class CVcValueScale : public COleDispatchDriver
{
public:
	//##ModelId=3E9ABEEF03B1
	CVcValueScale() {}		// Calls COleDispatchDriver default constructor
	//##ModelId=3E9ABEEF03B2
	CVcValueScale(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	//##ModelId=3E9ABEEF03B4
	CVcValueScale(const CVcValueScale& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	//##ModelId=3E9ABEEF03B0
	BOOL GetAuto();
	//##ModelId=3E9ABEEF03AE
	void SetAuto(BOOL bNewValue);
	//##ModelId=3E9ABEEF03AD
	double GetMinimum();
	//##ModelId=3E9ABEEF03AB
	void SetMinimum(double newValue);
	//##ModelId=3E9ABEEF03AA
	double GetMaximum();
	//##ModelId=3E9ABEEF03A8
	void SetMaximum(double newValue);
	//##ModelId=3E9ABEEF03A7
	short GetMajorDivision();
	//##ModelId=3E9ABEEF03A5
	void SetMajorDivision(short nNewValue);
	//##ModelId=3E9ABEEF03A4
	short GetMinorDivision();
	//##ModelId=3E9ABEEF039C
	void SetMinorDivision(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCVALUESCALE_H__53AFC64D_1036_47ED_88A9_40BFE44D67DD__INCLUDED_)
