//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace App2.LinuxBaseService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Gis_GetMapServicesSoapBinding", Namespace="http://giswebservices")]
    public partial class Gis_GetMapServicesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback requestSVGOperationCompleted;
        
        private System.Threading.SendOrPostCallback requestNearbySVGOperationCompleted;
        
        private System.Threading.SendOrPostCallback requestNearestSVGOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSvgGOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Gis_GetMapServicesService() {
            this.Url = global::App2.Properties.Settings.Default.App2_LinuxBaseService_Gis_GetMapServicesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event requestSVGCompletedEventHandler requestSVGCompleted;
        
        /// <remarks/>
        public event requestNearbySVGCompletedEventHandler requestNearbySVGCompleted;
        
        /// <remarks/>
        public event requestNearestSVGCompletedEventHandler requestNearestSVGCompleted;
        
        /// <remarks/>
        public event getSvgGCompletedEventHandler getSvgGCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://giswebservices", ResponseNamespace="http://giswebservices")]
        [return: System.Xml.Serialization.SoapElementAttribute("requestSVGReturn")]
        public string requestSVG(string sessionKey, string xmlMapRequst, double posX, double posY, double width, double height) {
            object[] results = this.Invoke("requestSVG", new object[] {
                        sessionKey,
                        xmlMapRequst,
                        posX,
                        posY,
                        width,
                        height});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void requestSVGAsync(string sessionKey, string xmlMapRequst, double posX, double posY, double width, double height) {
            this.requestSVGAsync(sessionKey, xmlMapRequst, posX, posY, width, height, null);
        }
        
        /// <remarks/>
        public void requestSVGAsync(string sessionKey, string xmlMapRequst, double posX, double posY, double width, double height, object userState) {
            if ((this.requestSVGOperationCompleted == null)) {
                this.requestSVGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestSVGOperationCompleted);
            }
            this.InvokeAsync("requestSVG", new object[] {
                        sessionKey,
                        xmlMapRequst,
                        posX,
                        posY,
                        width,
                        height}, this.requestSVGOperationCompleted, userState);
        }
        
        private void OnrequestSVGOperationCompleted(object arg) {
            if ((this.requestSVGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.requestSVGCompleted(this, new requestSVGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://giswebservices", ResponseNamespace="http://giswebservices")]
        [return: System.Xml.Serialization.SoapElementAttribute("requestNearbySVGReturn")]
        public string requestNearbySVG(string sessionKey, string xmlMapRequst, int layerID, double posX, double posY, double width, double height, double currentLadtitude, double currentLongitude, double radian, string xFill, string xStroke) {
            object[] results = this.Invoke("requestNearbySVG", new object[] {
                        sessionKey,
                        xmlMapRequst,
                        layerID,
                        posX,
                        posY,
                        width,
                        height,
                        currentLadtitude,
                        currentLongitude,
                        radian,
                        xFill,
                        xStroke});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void requestNearbySVGAsync(string sessionKey, string xmlMapRequst, int layerID, double posX, double posY, double width, double height, double currentLadtitude, double currentLongitude, double radian, string xFill, string xStroke) {
            this.requestNearbySVGAsync(sessionKey, xmlMapRequst, layerID, posX, posY, width, height, currentLadtitude, currentLongitude, radian, xFill, xStroke, null);
        }
        
        /// <remarks/>
        public void requestNearbySVGAsync(string sessionKey, string xmlMapRequst, int layerID, double posX, double posY, double width, double height, double currentLadtitude, double currentLongitude, double radian, string xFill, string xStroke, object userState) {
            if ((this.requestNearbySVGOperationCompleted == null)) {
                this.requestNearbySVGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestNearbySVGOperationCompleted);
            }
            this.InvokeAsync("requestNearbySVG", new object[] {
                        sessionKey,
                        xmlMapRequst,
                        layerID,
                        posX,
                        posY,
                        width,
                        height,
                        currentLadtitude,
                        currentLongitude,
                        radian,
                        xFill,
                        xStroke}, this.requestNearbySVGOperationCompleted, userState);
        }
        
        private void OnrequestNearbySVGOperationCompleted(object arg) {
            if ((this.requestNearbySVGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.requestNearbySVGCompleted(this, new requestNearbySVGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://giswebservices", ResponseNamespace="http://giswebservices")]
        [return: System.Xml.Serialization.SoapElementAttribute("requestNearestSVGReturn")]
        public string requestNearestSVG(string sessionKey, string xmlMapRequst, int layerID, double posX, double posY, double width, double height, double currentLadtitude, double currentLongitude, string xFill, string xStroke) {
            object[] results = this.Invoke("requestNearestSVG", new object[] {
                        sessionKey,
                        xmlMapRequst,
                        layerID,
                        posX,
                        posY,
                        width,
                        height,
                        currentLadtitude,
                        currentLongitude,
                        xFill,
                        xStroke});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void requestNearestSVGAsync(string sessionKey, string xmlMapRequst, int layerID, double posX, double posY, double width, double height, double currentLadtitude, double currentLongitude, string xFill, string xStroke) {
            this.requestNearestSVGAsync(sessionKey, xmlMapRequst, layerID, posX, posY, width, height, currentLadtitude, currentLongitude, xFill, xStroke, null);
        }
        
        /// <remarks/>
        public void requestNearestSVGAsync(string sessionKey, string xmlMapRequst, int layerID, double posX, double posY, double width, double height, double currentLadtitude, double currentLongitude, string xFill, string xStroke, object userState) {
            if ((this.requestNearestSVGOperationCompleted == null)) {
                this.requestNearestSVGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestNearestSVGOperationCompleted);
            }
            this.InvokeAsync("requestNearestSVG", new object[] {
                        sessionKey,
                        xmlMapRequst,
                        layerID,
                        posX,
                        posY,
                        width,
                        height,
                        currentLadtitude,
                        currentLongitude,
                        xFill,
                        xStroke}, this.requestNearestSVGOperationCompleted, userState);
        }
        
        private void OnrequestNearestSVGOperationCompleted(object arg) {
            if ((this.requestNearestSVGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.requestNearestSVGCompleted(this, new requestNearestSVGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://giswebservices", ResponseNamespace="http://giswebservices")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSvgGReturn")]
        public string getSvgG(string sessionKey, string xmlMapRequst, double posX, double posY, double width, double height) {
            object[] results = this.Invoke("getSvgG", new object[] {
                        sessionKey,
                        xmlMapRequst,
                        posX,
                        posY,
                        width,
                        height});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSvgGAsync(string sessionKey, string xmlMapRequst, double posX, double posY, double width, double height) {
            this.getSvgGAsync(sessionKey, xmlMapRequst, posX, posY, width, height, null);
        }
        
        /// <remarks/>
        public void getSvgGAsync(string sessionKey, string xmlMapRequst, double posX, double posY, double width, double height, object userState) {
            if ((this.getSvgGOperationCompleted == null)) {
                this.getSvgGOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSvgGOperationCompleted);
            }
            this.InvokeAsync("getSvgG", new object[] {
                        sessionKey,
                        xmlMapRequst,
                        posX,
                        posY,
                        width,
                        height}, this.getSvgGOperationCompleted, userState);
        }
        
        private void OngetSvgGOperationCompleted(object arg) {
            if ((this.getSvgGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSvgGCompleted(this, new getSvgGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void requestSVGCompletedEventHandler(object sender, requestSVGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class requestSVGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal requestSVGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void requestNearbySVGCompletedEventHandler(object sender, requestNearbySVGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class requestNearbySVGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal requestNearbySVGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void requestNearestSVGCompletedEventHandler(object sender, requestNearestSVGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class requestNearestSVGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal requestNearestSVGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getSvgGCompletedEventHandler(object sender, getSvgGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSvgGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSvgGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591