//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace socialService {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet1 : DataSet {
        
        private SSSDataTable tableSSS;
        
        public DataSet1() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet1(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["SSS"] != null)) {
                    this.Tables.Add(new SSSDataTable(ds.Tables["SSS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SSSDataTable SSS {
            get {
                return this.tableSSS;
            }
        }
        
        public override DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["SSS"] != null)) {
                this.Tables.Add(new SSSDataTable(ds.Tables["SSS"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableSSS = ((SSSDataTable)(this.Tables["SSS"]));
            if ((this.tableSSS != null)) {
                this.tableSSS.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet1.xsd";
            this.Locale = new System.Globalization.CultureInfo("th-TH");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableSSS = new SSSDataTable();
            this.Tables.Add(this.tableSSS);
        }
        
        private bool ShouldSerializeSSS() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void SSSRowChangeEventHandler(object sender, SSSRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SSSDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnPID;
            
            private DataColumn columnFNAME;
            
            private DataColumn columnLNAME;
            
            private DataColumn columnCC;
            
            private DataColumn columnBRANCH;
            
            private DataColumn columnHMAIN;
            
            private DataColumn columnHNAME;
            
            private DataColumn columnSTARTDATE;
            
            private DataColumn columnEXPDATE;
            
            internal SSSDataTable() : 
                    base("SSS") {
                this.InitClass();
            }
            
            internal SSSDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn PIDColumn {
                get {
                    return this.columnPID;
                }
            }
            
            internal DataColumn FNAMEColumn {
                get {
                    return this.columnFNAME;
                }
            }
            
            internal DataColumn LNAMEColumn {
                get {
                    return this.columnLNAME;
                }
            }
            
            internal DataColumn CCColumn {
                get {
                    return this.columnCC;
                }
            }
            
            internal DataColumn BRANCHColumn {
                get {
                    return this.columnBRANCH;
                }
            }
            
            internal DataColumn HMAINColumn {
                get {
                    return this.columnHMAIN;
                }
            }
            
            internal DataColumn HNAMEColumn {
                get {
                    return this.columnHNAME;
                }
            }
            
            internal DataColumn STARTDATEColumn {
                get {
                    return this.columnSTARTDATE;
                }
            }
            
            internal DataColumn EXPDATEColumn {
                get {
                    return this.columnEXPDATE;
                }
            }
            
            public SSSRow this[int index] {
                get {
                    return ((SSSRow)(this.Rows[index]));
                }
            }
            
            public event SSSRowChangeEventHandler SSSRowChanged;
            
            public event SSSRowChangeEventHandler SSSRowChanging;
            
            public event SSSRowChangeEventHandler SSSRowDeleted;
            
            public event SSSRowChangeEventHandler SSSRowDeleting;
            
            public void AddSSSRow(SSSRow row) {
                this.Rows.Add(row);
            }
            
            public SSSRow AddSSSRow(string PID, string FNAME, string LNAME, string CC, string BRANCH, string HMAIN, string HNAME, string STARTDATE, string EXPDATE) {
                SSSRow rowSSSRow = ((SSSRow)(this.NewRow()));
                rowSSSRow.ItemArray = new object[] {
                        PID,
                        FNAME,
                        LNAME,
                        CC,
                        BRANCH,
                        HMAIN,
                        HNAME,
                        STARTDATE,
                        EXPDATE};
                this.Rows.Add(rowSSSRow);
                return rowSSSRow;
            }
            
            public SSSRow FindByPID(string PID) {
                return ((SSSRow)(this.Rows.Find(new object[] {
                            PID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                SSSDataTable cln = ((SSSDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new SSSDataTable();
            }
            
            internal void InitVars() {
                this.columnPID = this.Columns["PID"];
                this.columnFNAME = this.Columns["FNAME"];
                this.columnLNAME = this.Columns["LNAME"];
                this.columnCC = this.Columns["CC"];
                this.columnBRANCH = this.Columns["BRANCH"];
                this.columnHMAIN = this.Columns["HMAIN"];
                this.columnHNAME = this.Columns["HNAME"];
                this.columnSTARTDATE = this.Columns["STARTDATE"];
                this.columnEXPDATE = this.Columns["EXPDATE"];
            }
            
            private void InitClass() {
                this.columnPID = new DataColumn("PID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPID);
                this.columnFNAME = new DataColumn("FNAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFNAME);
                this.columnLNAME = new DataColumn("LNAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLNAME);
                this.columnCC = new DataColumn("CC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCC);
                this.columnBRANCH = new DataColumn("BRANCH", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBRANCH);
                this.columnHMAIN = new DataColumn("HMAIN", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHMAIN);
                this.columnHNAME = new DataColumn("HNAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHNAME);
                this.columnSTARTDATE = new DataColumn("STARTDATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSTARTDATE);
                this.columnEXPDATE = new DataColumn("EXPDATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEXPDATE);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnPID}, true));
                this.columnPID.AllowDBNull = false;
                this.columnPID.Unique = true;
            }
            
            public SSSRow NewSSSRow() {
                return ((SSSRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new SSSRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(SSSRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SSSRowChanged != null)) {
                    this.SSSRowChanged(this, new SSSRowChangeEvent(((SSSRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SSSRowChanging != null)) {
                    this.SSSRowChanging(this, new SSSRowChangeEvent(((SSSRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SSSRowDeleted != null)) {
                    this.SSSRowDeleted(this, new SSSRowChangeEvent(((SSSRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SSSRowDeleting != null)) {
                    this.SSSRowDeleting(this, new SSSRowChangeEvent(((SSSRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveSSSRow(SSSRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SSSRow : DataRow {
            
            private SSSDataTable tableSSS;
            
            internal SSSRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableSSS = ((SSSDataTable)(this.Table));
            }
            
            public string PID {
                get {
                    return ((string)(this[this.tableSSS.PIDColumn]));
                }
                set {
                    this[this.tableSSS.PIDColumn] = value;
                }
            }
            
            public string FNAME {
                get {
                    try {
                        return ((string)(this[this.tableSSS.FNAMEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSSS.FNAMEColumn] = value;
                }
            }
            
            public string LNAME {
                get {
                    try {
                        return ((string)(this[this.tableSSS.LNAMEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSSS.LNAMEColumn] = value;
                }
            }
            
            public string CC {
                get {
                    try {
                        return ((string)(this[this.tableSSS.CCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSSS.CCColumn] = value;
                }
            }
            
            public string BRANCH {
                get {
                    try {
                        return ((string)(this[this.tableSSS.BRANCHColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSSS.BRANCHColumn] = value;
                }
            }
            
            public string HMAIN {
                get {
                    try {
                        return ((string)(this[this.tableSSS.HMAINColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSSS.HMAINColumn] = value;
                }
            }
            
            public string HNAME {
                get {
                    try {
                        return ((string)(this[this.tableSSS.HNAMEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSSS.HNAMEColumn] = value;
                }
            }
            
            public string STARTDATE {
                get {
                    try {
                        return ((string)(this[this.tableSSS.STARTDATEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSSS.STARTDATEColumn] = value;
                }
            }
            
            public string EXPDATE {
                get {
                    try {
                        return ((string)(this[this.tableSSS.EXPDATEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSSS.EXPDATEColumn] = value;
                }
            }
            
            public bool IsFNAMENull() {
                return this.IsNull(this.tableSSS.FNAMEColumn);
            }
            
            public void SetFNAMENull() {
                this[this.tableSSS.FNAMEColumn] = System.Convert.DBNull;
            }
            
            public bool IsLNAMENull() {
                return this.IsNull(this.tableSSS.LNAMEColumn);
            }
            
            public void SetLNAMENull() {
                this[this.tableSSS.LNAMEColumn] = System.Convert.DBNull;
            }
            
            public bool IsCCNull() {
                return this.IsNull(this.tableSSS.CCColumn);
            }
            
            public void SetCCNull() {
                this[this.tableSSS.CCColumn] = System.Convert.DBNull;
            }
            
            public bool IsBRANCHNull() {
                return this.IsNull(this.tableSSS.BRANCHColumn);
            }
            
            public void SetBRANCHNull() {
                this[this.tableSSS.BRANCHColumn] = System.Convert.DBNull;
            }
            
            public bool IsHMAINNull() {
                return this.IsNull(this.tableSSS.HMAINColumn);
            }
            
            public void SetHMAINNull() {
                this[this.tableSSS.HMAINColumn] = System.Convert.DBNull;
            }
            
            public bool IsHNAMENull() {
                return this.IsNull(this.tableSSS.HNAMEColumn);
            }
            
            public void SetHNAMENull() {
                this[this.tableSSS.HNAMEColumn] = System.Convert.DBNull;
            }
            
            public bool IsSTARTDATENull() {
                return this.IsNull(this.tableSSS.STARTDATEColumn);
            }
            
            public void SetSTARTDATENull() {
                this[this.tableSSS.STARTDATEColumn] = System.Convert.DBNull;
            }
            
            public bool IsEXPDATENull() {
                return this.IsNull(this.tableSSS.EXPDATEColumn);
            }
            
            public void SetEXPDATENull() {
                this[this.tableSSS.EXPDATEColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SSSRowChangeEvent : EventArgs {
            
            private SSSRow eventRow;
            
            private DataRowAction eventAction;
            
            public SSSRowChangeEvent(SSSRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public SSSRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
