<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:s0="http://tempuri.org/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" targetNamespace="http://tempuri.org/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:element name="SearchProductByID">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="StrIDProduct" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="StrIDSeller" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SearchProductByIDResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="SearchProductByIDResult" type="s0:ReturnInfoProduct" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ReturnInfoProduct">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="ID" type="s:int" />
          <s:element minOccurs="0" maxOccurs="1" name="Name" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Detail" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Unit" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Price" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Picture" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="IDSeller" type="s:int" />
        </s:sequence>
      </s:complexType>
      <s:element name="SearchProductByName">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="NameProduct" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Detail" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="PriceStr" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SearchProductByNameResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="SearchProductByNameResult" type="s0:ArrayOfReturnInfoProduct" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfReturnInfoProduct">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="ReturnInfoProduct" type="s0:ReturnInfoProduct" />
        </s:sequence>
      </s:complexType>
      <s:element name="PutInBasket">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IP" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="StrIDProduct" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="StrQuantity" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="StrIDSeller" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="PutInBasketResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="PutInBasketResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetInBasket">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IP" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetInBasketResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetInBasketResult" type="s0:ArrayOfReturnInfoBasket" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfReturnInfoBasket">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="ReturnInfoBasket" type="s0:ReturnInfoBasket" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ReturnInfoBasket">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="IDProduct" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="Quantity" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="IDSeller" type="s:int" />
        </s:sequence>
      </s:complexType>
      <s:element name="DeleteInbasket">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IP" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="StrIDProduct" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="StrIDSell" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DeleteInbasketResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="DeleteInbasketResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpdateQuantityInbasket">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IP" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="StrIDProduct" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="StrQuantity" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="StrIDSell" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpdateQuantityInbasketResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="UpdateQuantityInbasketResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CheckOut">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IP" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="IDCradit" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="PasswordCradit" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Name" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Address" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Province" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Zipcode" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="WayPay" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Email" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CheckOutResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="CheckOutResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SumBasket">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IP" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SumBasketResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="SumBasketResult" type="s:decimal" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CheckStrIsNumAll">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Str" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CheckStrIsNumAllResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="CheckStrIsNumAllResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CheckStrIsTextAll">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Str" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CheckStrIsTextAllResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="CheckStrIsTextAllResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetWayPay">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Name" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetWayPayResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetWayPayResult" type="s0:ArrayOfReturnInfoPay" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfReturnInfoPay">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="ReturnInfoPay" type="s0:ReturnInfoPay" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ReturnInfoPay">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Name" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Detail" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="SendMail">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Frommail" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Tomail" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="message" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SendMailResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="SendMailResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CheckStatusSelled">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IP" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CheckStatusSelledResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="CheckStatusSelledResult" type="s0:ArrayOfReturnOrder" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfReturnOrder">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="ReturnOrder" type="s0:ReturnOrder" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ReturnOrder">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="DateOrder" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="NameProduct" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Quantity" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Price" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Waypay" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="Send" type="s:boolean" />
          <s:element minOccurs="1" maxOccurs="1" name="GetMoney" type="s:boolean" />
        </s:sequence>
      </s:complexType>
      <s:element name="ReturnInfoProduct" type="s0:ReturnInfoProduct" />
      <s:element name="ArrayOfReturnInfoProduct" nillable="true" type="s0:ArrayOfReturnInfoProduct" />
      <s:element name="boolean" type="s:boolean" />
      <s:element name="ArrayOfReturnInfoBasket" nillable="true" type="s0:ArrayOfReturnInfoBasket" />
      <s:element name="decimal" type="s:decimal" />
      <s:element name="ArrayOfReturnInfoPay" nillable="true" type="s0:ArrayOfReturnInfoPay" />
      <s:element name="ArrayOfReturnOrder" nillable="true" type="s0:ArrayOfReturnOrder" />
    </s:schema>
  </types>
  <message name="SearchProductByIDSoapIn">
    <part name="parameters" element="s0:SearchProductByID" />
  </message>
  <message name="SearchProductByIDSoapOut">
    <part name="parameters" element="s0:SearchProductByIDResponse" />
  </message>
  <message name="SearchProductByNameSoapIn">
    <part name="parameters" element="s0:SearchProductByName" />
  </message>
  <message name="SearchProductByNameSoapOut">
    <part name="parameters" element="s0:SearchProductByNameResponse" />
  </message>
  <message name="PutInBasketSoapIn">
    <part name="parameters" element="s0:PutInBasket" />
  </message>
  <message name="PutInBasketSoapOut">
    <part name="parameters" element="s0:PutInBasketResponse" />
  </message>
  <message name="GetInBasketSoapIn">
    <part name="parameters" element="s0:GetInBasket" />
  </message>
  <message name="GetInBasketSoapOut">
    <part name="parameters" element="s0:GetInBasketResponse" />
  </message>
  <message name="DeleteInbasketSoapIn">
    <part name="parameters" element="s0:DeleteInbasket" />
  </message>
  <message name="DeleteInbasketSoapOut">
    <part name="parameters" element="s0:DeleteInbasketResponse" />
  </message>
  <message name="UpdateQuantityInbasketSoapIn">
    <part name="parameters" element="s0:UpdateQuantityInbasket" />
  </message>
  <message name="UpdateQuantityInbasketSoapOut">
    <part name="parameters" element="s0:UpdateQuantityInbasketResponse" />
  </message>
  <message name="CheckOutSoapIn">
    <part name="parameters" element="s0:CheckOut" />
  </message>
  <message name="CheckOutSoapOut">
    <part name="parameters" element="s0:CheckOutResponse" />
  </message>
  <message name="SumBasketSoapIn">
    <part name="parameters" element="s0:SumBasket" />
  </message>
  <message name="SumBasketSoapOut">
    <part name="parameters" element="s0:SumBasketResponse" />
  </message>
  <message name="CheckStrIsNumAllSoapIn">
    <part name="parameters" element="s0:CheckStrIsNumAll" />
  </message>
  <message name="CheckStrIsNumAllSoapOut">
    <part name="parameters" element="s0:CheckStrIsNumAllResponse" />
  </message>
  <message name="CheckStrIsTextAllSoapIn">
    <part name="parameters" element="s0:CheckStrIsTextAll" />
  </message>
  <message name="CheckStrIsTextAllSoapOut">
    <part name="parameters" element="s0:CheckStrIsTextAllResponse" />
  </message>
  <message name="GetWayPaySoapIn">
    <part name="parameters" element="s0:GetWayPay" />
  </message>
  <message name="GetWayPaySoapOut">
    <part name="parameters" element="s0:GetWayPayResponse" />
  </message>
  <message name="SendMailSoapIn">
    <part name="parameters" element="s0:SendMail" />
  </message>
  <message name="SendMailSoapOut">
    <part name="parameters" element="s0:SendMailResponse" />
  </message>
  <message name="CheckStatusSelledSoapIn">
    <part name="parameters" element="s0:CheckStatusSelled" />
  </message>
  <message name="CheckStatusSelledSoapOut">
    <part name="parameters" element="s0:CheckStatusSelledResponse" />
  </message>
  <message name="SearchProductByIDHttpGetIn">
    <part name="StrIDProduct" type="s:string" />
    <part name="StrIDSeller" type="s:string" />
  </message>
  <message name="SearchProductByIDHttpGetOut">
    <part name="Body" element="s0:ReturnInfoProduct" />
  </message>
  <message name="SearchProductByNameHttpGetIn">
    <part name="NameProduct" type="s:string" />
    <part name="Detail" type="s:string" />
    <part name="PriceStr" type="s:string" />
  </message>
  <message name="SearchProductByNameHttpGetOut">
    <part name="Body" element="s0:ArrayOfReturnInfoProduct" />
  </message>
  <message name="PutInBasketHttpGetIn">
    <part name="IP" type="s:string" />
    <part name="StrIDProduct" type="s:string" />
    <part name="StrQuantity" type="s:string" />
    <part name="StrIDSeller" type="s:string" />
  </message>
  <message name="PutInBasketHttpGetOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="GetInBasketHttpGetIn">
    <part name="IP" type="s:string" />
  </message>
  <message name="GetInBasketHttpGetOut">
    <part name="Body" element="s0:ArrayOfReturnInfoBasket" />
  </message>
  <message name="DeleteInbasketHttpGetIn">
    <part name="IP" type="s:string" />
    <part name="StrIDProduct" type="s:string" />
    <part name="StrIDSell" type="s:string" />
  </message>
  <message name="DeleteInbasketHttpGetOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="UpdateQuantityInbasketHttpGetIn">
    <part name="IP" type="s:string" />
    <part name="StrIDProduct" type="s:string" />
    <part name="StrQuantity" type="s:string" />
    <part name="StrIDSell" type="s:string" />
  </message>
  <message name="UpdateQuantityInbasketHttpGetOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="CheckOutHttpGetIn">
    <part name="IP" type="s:string" />
    <part name="IDCradit" type="s:string" />
    <part name="PasswordCradit" type="s:string" />
    <part name="Name" type="s:string" />
    <part name="Address" type="s:string" />
    <part name="Province" type="s:string" />
    <part name="Zipcode" type="s:string" />
    <part name="WayPay" type="s:string" />
    <part name="Email" type="s:string" />
  </message>
  <message name="CheckOutHttpGetOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="SumBasketHttpGetIn">
    <part name="IP" type="s:string" />
  </message>
  <message name="SumBasketHttpGetOut">
    <part name="Body" element="s0:decimal" />
  </message>
  <message name="CheckStrIsNumAllHttpGetIn">
    <part name="Str" type="s:string" />
  </message>
  <message name="CheckStrIsNumAllHttpGetOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="CheckStrIsTextAllHttpGetIn">
    <part name="Str" type="s:string" />
  </message>
  <message name="CheckStrIsTextAllHttpGetOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="GetWayPayHttpGetIn">
    <part name="Name" type="s:string" />
  </message>
  <message name="GetWayPayHttpGetOut">
    <part name="Body" element="s0:ArrayOfReturnInfoPay" />
  </message>
  <message name="SendMailHttpGetIn">
    <part name="Frommail" type="s:string" />
    <part name="Tomail" type="s:string" />
    <part name="message" type="s:string" />
  </message>
  <message name="SendMailHttpGetOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="CheckStatusSelledHttpGetIn">
    <part name="IP" type="s:string" />
  </message>
  <message name="CheckStatusSelledHttpGetOut">
    <part name="Body" element="s0:ArrayOfReturnOrder" />
  </message>
  <message name="SearchProductByIDHttpPostIn">
    <part name="StrIDProduct" type="s:string" />
    <part name="StrIDSeller" type="s:string" />
  </message>
  <message name="SearchProductByIDHttpPostOut">
    <part name="Body" element="s0:ReturnInfoProduct" />
  </message>
  <message name="SearchProductByNameHttpPostIn">
    <part name="NameProduct" type="s:string" />
    <part name="Detail" type="s:string" />
    <part name="PriceStr" type="s:string" />
  </message>
  <message name="SearchProductByNameHttpPostOut">
    <part name="Body" element="s0:ArrayOfReturnInfoProduct" />
  </message>
  <message name="PutInBasketHttpPostIn">
    <part name="IP" type="s:string" />
    <part name="StrIDProduct" type="s:string" />
    <part name="StrQuantity" type="s:string" />
    <part name="StrIDSeller" type="s:string" />
  </message>
  <message name="PutInBasketHttpPostOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="GetInBasketHttpPostIn">
    <part name="IP" type="s:string" />
  </message>
  <message name="GetInBasketHttpPostOut">
    <part name="Body" element="s0:ArrayOfReturnInfoBasket" />
  </message>
  <message name="DeleteInbasketHttpPostIn">
    <part name="IP" type="s:string" />
    <part name="StrIDProduct" type="s:string" />
    <part name="StrIDSell" type="s:string" />
  </message>
  <message name="DeleteInbasketHttpPostOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="UpdateQuantityInbasketHttpPostIn">
    <part name="IP" type="s:string" />
    <part name="StrIDProduct" type="s:string" />
    <part name="StrQuantity" type="s:string" />
    <part name="StrIDSell" type="s:string" />
  </message>
  <message name="UpdateQuantityInbasketHttpPostOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="CheckOutHttpPostIn">
    <part name="IP" type="s:string" />
    <part name="IDCradit" type="s:string" />
    <part name="PasswordCradit" type="s:string" />
    <part name="Name" type="s:string" />
    <part name="Address" type="s:string" />
    <part name="Province" type="s:string" />
    <part name="Zipcode" type="s:string" />
    <part name="WayPay" type="s:string" />
    <part name="Email" type="s:string" />
  </message>
  <message name="CheckOutHttpPostOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="SumBasketHttpPostIn">
    <part name="IP" type="s:string" />
  </message>
  <message name="SumBasketHttpPostOut">
    <part name="Body" element="s0:decimal" />
  </message>
  <message name="CheckStrIsNumAllHttpPostIn">
    <part name="Str" type="s:string" />
  </message>
  <message name="CheckStrIsNumAllHttpPostOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="CheckStrIsTextAllHttpPostIn">
    <part name="Str" type="s:string" />
  </message>
  <message name="CheckStrIsTextAllHttpPostOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="GetWayPayHttpPostIn">
    <part name="Name" type="s:string" />
  </message>
  <message name="GetWayPayHttpPostOut">
    <part name="Body" element="s0:ArrayOfReturnInfoPay" />
  </message>
  <message name="SendMailHttpPostIn">
    <part name="Frommail" type="s:string" />
    <part name="Tomail" type="s:string" />
    <part name="message" type="s:string" />
  </message>
  <message name="SendMailHttpPostOut">
    <part name="Body" element="s0:boolean" />
  </message>
  <message name="CheckStatusSelledHttpPostIn">
    <part name="IP" type="s:string" />
  </message>
  <message name="CheckStatusSelledHttpPostOut">
    <part name="Body" element="s0:ArrayOfReturnOrder" />
  </message>
  <portType name="ServiceSellSoap">
    <operation name="SearchProductByID">
      <documentation>ใช้สำหรับค้นหาสินค้าโดยใช้ IDProduct และ IDSell จากร้านค้า</documentation>
      <input message="s0:SearchProductByIDSoapIn" />
      <output message="s0:SearchProductByIDSoapOut" />
    </operation>
    <operation name="SearchProductByName">
      <documentation>ใช้สำหรับค้นหาสินค้าโดยใช้ NameProduct จากร้านค้าทุกร้าน</documentation>
      <input message="s0:SearchProductByNameSoapIn" />
      <output message="s0:SearchProductByNameSoapOut" />
    </operation>
    <operation name="PutInBasket">
      <documentation>ใช้สำหรับหยิบของใส่ตระกล้า</documentation>
      <input message="s0:PutInBasketSoapIn" />
      <output message="s0:PutInBasketSoapOut" />
    </operation>
    <operation name="GetInBasket">
      <documentation>ใช้สำหรับ ดึงข้อมูลสินค้าออกจาก รถเข็น ยังไม่ได้ทำ</documentation>
      <input message="s0:GetInBasketSoapIn" />
      <output message="s0:GetInBasketSoapOut" />
    </operation>
    <operation name="DeleteInbasket">
      <documentation>ใช้สำหรับ ลบข้อมูลสินค้าออกจาก รถเข็น ยังไม่ได้ทำ</documentation>
      <input message="s0:DeleteInbasketSoapIn" />
      <output message="s0:DeleteInbasketSoapOut" />
    </operation>
    <operation name="UpdateQuantityInbasket">
      <documentation>ใช้สำหรับ เปลี่ยนแปลงข้อมูลจำนวนของสินค้าใน รถเข็น</documentation>
      <input message="s0:UpdateQuantityInbasketSoapIn" />
      <output message="s0:UpdateQuantityInbasketSoapOut" />
    </operation>
    <operation name="CheckOut">
      <documentation>ใช้สำหรับขายสินค้าใน รถเข็น</documentation>
      <input message="s0:CheckOutSoapIn" />
      <output message="s0:CheckOutSoapOut" />
    </operation>
    <operation name="SumBasket">
      <documentation>ใช้สำหรับรวมเงินของสินค้าใน รถเข็น</documentation>
      <input message="s0:SumBasketSoapIn" />
      <output message="s0:SumBasketSoapOut" />
    </operation>
    <operation name="CheckStrIsNumAll">
      <documentation>ใช้สำหรับตรวจสอบว่าstringนั้นเป็นตัวเลขทั้งหมดหรือไม่</documentation>
      <input message="s0:CheckStrIsNumAllSoapIn" />
      <output message="s0:CheckStrIsNumAllSoapOut" />
    </operation>
    <operation name="CheckStrIsTextAll">
      <documentation>ใช้สำหรับตรวจสอบว่าstringนั้นเป็นตัวหนังสือทั้งหมดหรือไม่</documentation>
      <input message="s0:CheckStrIsTextAllSoapIn" />
      <output message="s0:CheckStrIsTextAllSoapOut" />
    </operation>
    <operation name="GetWayPay">
      <documentation>ใช้สำหรับตรวจสอบว่าstringนั้นเป็นตัวหนังสือทั้งหมดหรือไม่</documentation>
      <input message="s0:GetWayPaySoapIn" />
      <output message="s0:GetWayPaySoapOut" />
    </operation>
    <operation name="SendMail">
      <documentation>ใช้สำหรับส่งจดหมาย</documentation>
      <input message="s0:SendMailSoapIn" />
      <output message="s0:SendMailSoapOut" />
    </operation>
    <operation name="CheckStatusSelled">
      <documentation>ดูสินค้าที่ซื้อไปแล้ว</documentation>
      <input message="s0:CheckStatusSelledSoapIn" />
      <output message="s0:CheckStatusSelledSoapOut" />
    </operation>
  </portType>
  <portType name="ServiceSellHttpGet">
    <operation name="SearchProductByID">
      <documentation>ใช้สำหรับค้นหาสินค้าโดยใช้ IDProduct และ IDSell จากร้านค้า</documentation>
      <input message="s0:SearchProductByIDHttpGetIn" />
      <output message="s0:SearchProductByIDHttpGetOut" />
    </operation>
    <operation name="SearchProductByName">
      <documentation>ใช้สำหรับค้นหาสินค้าโดยใช้ NameProduct จากร้านค้าทุกร้าน</documentation>
      <input message="s0:SearchProductByNameHttpGetIn" />
      <output message="s0:SearchProductByNameHttpGetOut" />
    </operation>
    <operation name="PutInBasket">
      <documentation>ใช้สำหรับหยิบของใส่ตระกล้า</documentation>
      <input message="s0:PutInBasketHttpGetIn" />
      <output message="s0:PutInBasketHttpGetOut" />
    </operation>
    <operation name="GetInBasket">
      <documentation>ใช้สำหรับ ดึงข้อมูลสินค้าออกจาก รถเข็น ยังไม่ได้ทำ</documentation>
      <input message="s0:GetInBasketHttpGetIn" />
      <output message="s0:GetInBasketHttpGetOut" />
    </operation>
    <operation name="DeleteInbasket">
      <documentation>ใช้สำหรับ ลบข้อมูลสินค้าออกจาก รถเข็น ยังไม่ได้ทำ</documentation>
      <input message="s0:DeleteInbasketHttpGetIn" />
      <output message="s0:DeleteInbasketHttpGetOut" />
    </operation>
    <operation name="UpdateQuantityInbasket">
      <documentation>ใช้สำหรับ เปลี่ยนแปลงข้อมูลจำนวนของสินค้าใน รถเข็น</documentation>
      <input message="s0:UpdateQuantityInbasketHttpGetIn" />
      <output message="s0:UpdateQuantityInbasketHttpGetOut" />
    </operation>
    <operation name="CheckOut">
      <documentation>ใช้สำหรับขายสินค้าใน รถเข็น</documentation>
      <input message="s0:CheckOutHttpGetIn" />
      <output message="s0:CheckOutHttpGetOut" />
    </operation>
    <operation name="SumBasket">
      <documentation>ใช้สำหรับรวมเงินของสินค้าใน รถเข็น</documentation>
      <input message="s0:SumBasketHttpGetIn" />
      <output message="s0:SumBasketHttpGetOut" />
    </operation>
    <operation name="CheckStrIsNumAll">
      <documentation>ใช้สำหรับตรวจสอบว่าstringนั้นเป็นตัวเลขทั้งหมดหรือไม่</documentation>
      <input message="s0:CheckStrIsNumAllHttpGetIn" />
      <output message="s0:CheckStrIsNumAllHttpGetOut" />
    </operation>
    <operation name="CheckStrIsTextAll">
      <documentation>ใช้สำหรับตรวจสอบว่าstringนั้นเป็นตัวหนังสือทั้งหมดหรือไม่</documentation>
      <input message="s0:CheckStrIsTextAllHttpGetIn" />
      <output message="s0:CheckStrIsTextAllHttpGetOut" />
    </operation>
    <operation name="GetWayPay">
      <documentation>ใช้สำหรับตรวจสอบว่าstringนั้นเป็นตัวหนังสือทั้งหมดหรือไม่</documentation>
      <input message="s0:GetWayPayHttpGetIn" />
      <output message="s0:GetWayPayHttpGetOut" />
    </operation>
    <operation name="SendMail">
      <documentation>ใช้สำหรับส่งจดหมาย</documentation>
      <input message="s0:SendMailHttpGetIn" />
      <output message="s0:SendMailHttpGetOut" />
    </operation>
    <operation name="CheckStatusSelled">
      <documentation>ดูสินค้าที่ซื้อไปแล้ว</documentation>
      <input message="s0:CheckStatusSelledHttpGetIn" />
      <output message="s0:CheckStatusSelledHttpGetOut" />
    </operation>
  </portType>
  <portType name="ServiceSellHttpPost">
    <operation name="SearchProductByID">
      <documentation>ใช้สำหรับค้นหาสินค้าโดยใช้ IDProduct และ IDSell จากร้านค้า</documentation>
      <input message="s0:SearchProductByIDHttpPostIn" />
      <output message="s0:SearchProductByIDHttpPostOut" />
    </operation>
    <operation name="SearchProductByName">
      <documentation>ใช้สำหรับค้นหาสินค้าโดยใช้ NameProduct จากร้านค้าทุกร้าน</documentation>
      <input message="s0:SearchProductByNameHttpPostIn" />
      <output message="s0:SearchProductByNameHttpPostOut" />
    </operation>
    <operation name="PutInBasket">
      <documentation>ใช้สำหรับหยิบของใส่ตระกล้า</documentation>
      <input message="s0:PutInBasketHttpPostIn" />
      <output message="s0:PutInBasketHttpPostOut" />
    </operation>
    <operation name="GetInBasket">
      <documentation>ใช้สำหรับ ดึงข้อมูลสินค้าออกจาก รถเข็น ยังไม่ได้ทำ</documentation>
      <input message="s0:GetInBasketHttpPostIn" />
      <output message="s0:GetInBasketHttpPostOut" />
    </operation>
    <operation name="DeleteInbasket">
      <documentation>ใช้สำหรับ ลบข้อมูลสินค้าออกจาก รถเข็น ยังไม่ได้ทำ</documentation>
      <input message="s0:DeleteInbasketHttpPostIn" />
      <output message="s0:DeleteInbasketHttpPostOut" />
    </operation>
    <operation name="UpdateQuantityInbasket">
      <documentation>ใช้สำหรับ เปลี่ยนแปลงข้อมูลจำนวนของสินค้าใน รถเข็น</documentation>
      <input message="s0:UpdateQuantityInbasketHttpPostIn" />
      <output message="s0:UpdateQuantityInbasketHttpPostOut" />
    </operation>
    <operation name="CheckOut">
      <documentation>ใช้สำหรับขายสินค้าใน รถเข็น</documentation>
      <input message="s0:CheckOutHttpPostIn" />
      <output message="s0:CheckOutHttpPostOut" />
    </operation>
    <operation name="SumBasket">
      <documentation>ใช้สำหรับรวมเงินของสินค้าใน รถเข็น</documentation>
      <input message="s0:SumBasketHttpPostIn" />
      <output message="s0:SumBasketHttpPostOut" />
    </operation>
    <operation name="CheckStrIsNumAll">
      <documentation>ใช้สำหรับตรวจสอบว่าstringนั้นเป็นตัวเลขทั้งหมดหรือไม่</documentation>
      <input message="s0:CheckStrIsNumAllHttpPostIn" />
      <output message="s0:CheckStrIsNumAllHttpPostOut" />
    </operation>
    <operation name="CheckStrIsTextAll">
      <documentation>ใช้สำหรับตรวจสอบว่าstringนั้นเป็นตัวหนังสือทั้งหมดหรือไม่</documentation>
      <input message="s0:CheckStrIsTextAllHttpPostIn" />
      <output message="s0:CheckStrIsTextAllHttpPostOut" />
    </operation>
    <operation name="GetWayPay">
      <documentation>ใช้สำหรับตรวจสอบว่าstringนั้นเป็นตัวหนังสือทั้งหมดหรือไม่</documentation>
      <input message="s0:GetWayPayHttpPostIn" />
      <output message="s0:GetWayPayHttpPostOut" />
    </operation>
    <operation name="SendMail">
      <documentation>ใช้สำหรับส่งจดหมาย</documentation>
      <input message="s0:SendMailHttpPostIn" />
      <output message="s0:SendMailHttpPostOut" />
    </operation>
    <operation name="CheckStatusSelled">
      <documentation>ดูสินค้าที่ซื้อไปแล้ว</documentation>
      <input message="s0:CheckStatusSelledHttpPostIn" />
      <output message="s0:CheckStatusSelledHttpPostOut" />
    </operation>
  </portType>
  <binding name="ServiceSellSoap" type="s0:ServiceSellSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
    <operation name="SearchProductByID">
      <soap:operation soapAction="http://tempuri.org/SearchProductByID" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="SearchProductByName">
      <soap:operation soapAction="http://tempuri.org/SearchProductByName" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="PutInBasket">
      <soap:operation soapAction="http://tempuri.org/PutInBasket" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="GetInBasket">
      <soap:operation soapAction="http://tempuri.org/GetInBasket" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="DeleteInbasket">
      <soap:operation soapAction="http://tempuri.org/DeleteInbasket" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="UpdateQuantityInbasket">
      <soap:operation soapAction="http://tempuri.org/UpdateQuantityInbasket" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="CheckOut">
      <soap:operation soapAction="http://tempuri.org/CheckOut" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="SumBasket">
      <soap:operation soapAction="http://tempuri.org/SumBasket" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="CheckStrIsNumAll">
      <soap:operation soapAction="http://tempuri.org/CheckStrIsNumAll" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="CheckStrIsTextAll">
      <soap:operation soapAction="http://tempuri.org/CheckStrIsTextAll" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="GetWayPay">
      <soap:operation soapAction="http://tempuri.org/GetWayPay" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="SendMail">
      <soap:operation soapAction="http://tempuri.org/SendMail" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="CheckStatusSelled">
      <soap:operation soapAction="http://tempuri.org/CheckStatusSelled" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <binding name="ServiceSellHttpGet" type="s0:ServiceSellHttpGet">
    <http:binding verb="GET" />
    <operation name="SearchProductByID">
      <http:operation location="/SearchProductByID" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="SearchProductByName">
      <http:operation location="/SearchProductByName" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="PutInBasket">
      <http:operation location="/PutInBasket" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="GetInBasket">
      <http:operation location="/GetInBasket" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="DeleteInbasket">
      <http:operation location="/DeleteInbasket" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="UpdateQuantityInbasket">
      <http:operation location="/UpdateQuantityInbasket" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="CheckOut">
      <http:operation location="/CheckOut" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="SumBasket">
      <http:operation location="/SumBasket" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="CheckStrIsNumAll">
      <http:operation location="/CheckStrIsNumAll" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="CheckStrIsTextAll">
      <http:operation location="/CheckStrIsTextAll" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="GetWayPay">
      <http:operation location="/GetWayPay" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="SendMail">
      <http:operation location="/SendMail" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="CheckStatusSelled">
      <http:operation location="/CheckStatusSelled" />
      <input>
        <http:urlEncoded />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
  </binding>
  <binding name="ServiceSellHttpPost" type="s0:ServiceSellHttpPost">
    <http:binding verb="POST" />
    <operation name="SearchProductByID">
      <http:operation location="/SearchProductByID" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="SearchProductByName">
      <http:operation location="/SearchProductByName" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="PutInBasket">
      <http:operation location="/PutInBasket" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="GetInBasket">
      <http:operation location="/GetInBasket" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="DeleteInbasket">
      <http:operation location="/DeleteInbasket" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="UpdateQuantityInbasket">
      <http:operation location="/UpdateQuantityInbasket" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="CheckOut">
      <http:operation location="/CheckOut" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="SumBasket">
      <http:operation location="/SumBasket" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="CheckStrIsNumAll">
      <http:operation location="/CheckStrIsNumAll" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="CheckStrIsTextAll">
      <http:operation location="/CheckStrIsTextAll" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="GetWayPay">
      <http:operation location="/GetWayPay" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="SendMail">
      <http:operation location="/SendMail" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
    <operation name="CheckStatusSelled">
      <http:operation location="/CheckStatusSelled" />
      <input>
        <mime:content type="application/x-www-form-urlencoded" />
      </input>
      <output>
        <mime:mimeXml part="Body" />
      </output>
    </operation>
  </binding>
  <service name="ServiceSell">
    <port name="ServiceSellSoap" binding="s0:ServiceSellSoap">
      <soap:address location="http://161.246.6.4/projecttumbolthai/center/Webservice/Servicesell.asmx" />
    </port>
    <port name="ServiceSellHttpGet" binding="s0:ServiceSellHttpGet">
      <http:address location="http://161.246.6.4/projecttumbolthai/center/Webservice/Servicesell.asmx" />
    </port>
    <port name="ServiceSellHttpPost" binding="s0:ServiceSellHttpPost">
      <http:address location="http://161.246.6.4/projecttumbolthai/center/Webservice/Servicesell.asmx" />
    </port>
  </service>
</definitions>