/*
//============================================================================
//
//    FILE NAME : _G729DEC.h
//
//    BLOCK NAME: G729DEC
//
//    GROUP NAME: Default Group
//
//    PURPOSE   : Provides the real-time block's DSP header file.
//
//    Component Wizard for eXpressDSP Version 1.31.00 Auto-Generated Block
//
//    Number of Inputs : 0
//    Number of Outputs: 1
//
//    Creation Date: Mon - 15 November 2004
//    Creation Time: 10:42 PM
//
//==========================================================================
*/

/***********************************************************************/
/*                              DEFINITIONS                            */
/***********************************************************************/
/* boolean macros */
typedef  unsigned int  BOOL;
#define  FALSE   0
#define  TRUE    1

#include <std.h>
#include "g729dec.h"
#include "g729dec_kmitl.h"


/***********************************************************************/
/* Data Pointers / Parameter Structure                                 */
/*                                                                     */
/* NOTE: This structure was auto-generated by Hypersignal              */
/*       Block Wizard application.  DO NOT MODIFY THIS STRUCTURE!      */
/***********************************************************************/

typedef struct
{
  /*********************************************************************/
  /*                  Synchronization Addresses                        */
  /*********************************************************************/
  unsigned int *SyncIn;                  /* ptr to input sync value  */
  unsigned int *SyncOut;                 /* ptr to output sync value */

  /*********************************************************************/
  /*                  Output Data Pointers / Framesize                 */
  /*********************************************************************/
  float        *PtrOut0;                 /* output 0 data pointer */
  unsigned int FramesizeOut0;            /* output 0 framesize */


  /*********************************************************************/
  /*                       xDAIS Parameters                            */
  /*********************************************************************/
  int          Changed; /* Please Don't Move or Remove !!  */
  G729DEC_Handle  handle;

  /*********************************************************************/
  /*                   Internal Persistent Variables                   */
  /*********************************************************************/
  /* NOTE: If your block requires persistent variables, then they must */
  /*       be put here.  DO NOT USE global variables or statics in the */
  /*       C source file unless you really want them to be shared by   */
  /*       all instances of this block.                                */
  /*********************************************************************/

} PARAMS;


/***********************************************************************/
/*                           FUNCTION PROTOTYPES                       */
/***********************************************************************/

void G729DEC_INT  (PARAMS *pPtr);        /* optional block interrupt routine */

void G729DEC_INIT (PARAMS *pPtr);        /* optional block initialization routine */

void G729DEC_STOP (PARAMS *pPtr);        /* optional block stop routine */

void G729DEC_RESTART (PARAMS *pPtr);     /* optional block restart routine */

void G729DEC(PARAMS *pPtr);              /* main block routine */

