// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package routersim;

public final class ClientCallbackImpl_Stub
    extends java.rmi.server.RemoteStub
    implements routersim.ClientCallbackInt
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_callShowStatus_0;
    
    static {
	try {
	    $method_callShowStatus_0 = routersim.ClientCallbackInt.class.getMethod("callShowStatus", new java.lang.Class[] {javax.swing.JPanel.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ClientCallbackImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of callShowStatus(JPanel)
    public void callShowStatus(javax.swing.JPanel $param_JPanel_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_callShowStatus_0, new java.lang.Object[] {$param_JPanel_1}, 325410761901393290L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
