// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package routersim;

public final class NewRouterImpl_Stub
    extends java.rmi.server.RemoteStub
    implements routersim.NewRouterInt, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_DelRouter_0;
    private static java.lang.reflect.Method $method_NewFrameR_1;
    private static java.lang.reflect.Method $method_checkVhello_2;
    private static java.lang.reflect.Method $method_constructor_3;
    private static java.lang.reflect.Method $method_deleteAllVector_4;
    private static java.lang.reflect.Method $method_deleteInt_5;
    private static java.lang.reflect.Method $method_getCost_6;
    private static java.lang.reflect.Method $method_getInt_7;
    private static java.lang.reflect.Method $method_getIntName_8;
    private static java.lang.reflect.Method $method_getMaxr_9;
    private static java.lang.reflect.Method $method_getName_10;
    private static java.lang.reflect.Method $method_getRouter_11;
    private static java.lang.reflect.Method $method_getrname_12;
    private static java.lang.reflect.Method $method_gettype_13;
    private static java.lang.reflect.Method $method_getvModel_14;
    private static java.lang.reflect.Method $method_getvName_15;
    private static java.lang.reflect.Method $method_getvRouter_16;
    private static java.lang.reflect.Method $method_getvStatus_17;
    private static java.lang.reflect.Method $method_nextstep_18;
    private static java.lang.reflect.Method $method_normalmode_19;
    private static java.lang.reflect.Method $method_setCost_20;
    private static java.lang.reflect.Method $method_setCostOfWire_21;
    private static java.lang.reflect.Method $method_setIntName_22;
    private static java.lang.reflect.Method $method_setMaxr_23;
    private static java.lang.reflect.Method $method_setsingleMode_24;
    private static java.lang.reflect.Method $method_setvFrame_25;
    private static java.lang.reflect.Method $method_setvModel_26;
    private static java.lang.reflect.Method $method_setvRouter_27;
    private static java.lang.reflect.Method $method_showFrame_28;
    private static java.lang.reflect.Method $method_showStatus_29;
    private static java.lang.reflect.Method $method_singlemode_30;
    private static java.lang.reflect.Method $method_wireDelete_31;
    
    static {
	try {
	    $method_DelRouter_0 = routersim.NewRouterInt.class.getMethod("DelRouter", new java.lang.Class[] {int.class});
	    $method_NewFrameR_1 = routersim.NewRouterInt.class.getMethod("NewFrameR", new java.lang.Class[] {java.lang.String.class, int.class});
	    $method_checkVhello_2 = routersim.NewRouterInt.class.getMethod("checkVhello", new java.lang.Class[] {routersim.Router.class, routersim.Router.class});
	    $method_constructor_3 = routersim.NewRouterInt.class.getMethod("constructor", new java.lang.Class[] {int.class});
	    $method_deleteAllVector_4 = routersim.NewRouterInt.class.getMethod("deleteAllVector", new java.lang.Class[] {});
	    $method_deleteInt_5 = routersim.NewRouterInt.class.getMethod("deleteInt", new java.lang.Class[] {int.class, java.lang.String.class});
	    $method_getCost_6 = routersim.NewRouterInt.class.getMethod("getCost", new java.lang.Class[] {});
	    $method_getInt_7 = routersim.NewRouterInt.class.getMethod("getInt", new java.lang.Class[] {});
	    $method_getIntName_8 = routersim.NewRouterInt.class.getMethod("getIntName", new java.lang.Class[] {});
	    $method_getMaxr_9 = routersim.NewRouterInt.class.getMethod("getMaxr", new java.lang.Class[] {});
	    $method_getName_10 = routersim.NewRouterInt.class.getMethod("getName", new java.lang.Class[] {});
	    $method_getRouter_11 = routersim.NewRouterInt.class.getMethod("getRouter", new java.lang.Class[] {});
	    $method_getrname_12 = routersim.NewRouterInt.class.getMethod("getrname", new java.lang.Class[] {});
	    $method_gettype_13 = routersim.NewRouterInt.class.getMethod("gettype", new java.lang.Class[] {});
	    $method_getvModel_14 = routersim.NewRouterInt.class.getMethod("getvModel", new java.lang.Class[] {});
	    $method_getvName_15 = routersim.NewRouterInt.class.getMethod("getvName", new java.lang.Class[] {});
	    $method_getvRouter_16 = routersim.NewRouterInt.class.getMethod("getvRouter", new java.lang.Class[] {});
	    $method_getvStatus_17 = routersim.NewRouterInt.class.getMethod("getvStatus", new java.lang.Class[] {});
	    $method_nextstep_18 = routersim.NewRouterInt.class.getMethod("nextstep", new java.lang.Class[] {});
	    $method_normalmode_19 = routersim.NewRouterInt.class.getMethod("normalmode", new java.lang.Class[] {});
	    $method_setCost_20 = routersim.NewRouterInt.class.getMethod("setCost", new java.lang.Class[] {int.class, int.class, int.class});
	    $method_setCostOfWire_21 = routersim.NewRouterInt.class.getMethod("setCostOfWire", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, int.class});
	    $method_setIntName_22 = routersim.NewRouterInt.class.getMethod("setIntName", new java.lang.Class[] {});
	    $method_setMaxr_23 = routersim.NewRouterInt.class.getMethod("setMaxr", new java.lang.Class[] {routersim.Router.class});
	    $method_setsingleMode_24 = routersim.NewRouterInt.class.getMethod("setsingleMode", new java.lang.Class[] {boolean.class});
	    $method_setvFrame_25 = routersim.NewRouterInt.class.getMethod("setvFrame", new java.lang.Class[] {int.class});
	    $method_setvModel_26 = routersim.NewRouterInt.class.getMethod("setvModel", new java.lang.Class[] {});
	    $method_setvRouter_27 = routersim.NewRouterInt.class.getMethod("setvRouter", new java.lang.Class[] {});
	    $method_showFrame_28 = routersim.NewRouterInt.class.getMethod("showFrame", new java.lang.Class[] {int.class});
	    $method_showStatus_29 = routersim.NewRouterInt.class.getMethod("showStatus", new java.lang.Class[] {int.class});
	    $method_singlemode_30 = routersim.NewRouterInt.class.getMethod("singlemode", new java.lang.Class[] {});
	    $method_wireDelete_31 = routersim.NewRouterInt.class.getMethod("wireDelete", new java.lang.Class[] {int.class, int.class, java.lang.String.class, java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public NewRouterImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of DelRouter(int)
    public void DelRouter(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_DelRouter_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 6443934886613575871L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of NewFrameR(String, int)
    public void NewFrameR(java.lang.String $param_String_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_NewFrameR_1, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2)}, 1531737294512476948L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of checkVhello(Router, Router)
    public void checkVhello(routersim.Router $param_Router_1, routersim.Router $param_Router_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_checkVhello_2, new java.lang.Object[] {$param_Router_1, $param_Router_2}, -8682640122228461571L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of constructor(int)
    public void constructor(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_constructor_3, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 1575520569653386134L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteAllVector()
    public void deleteAllVector()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteAllVector_4, null, 6970632421532591079L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteInt(int, String)
    public void deleteInt(int $param_int_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteInt_5, new java.lang.Object[] {new java.lang.Integer($param_int_1), $param_String_2}, 5810427790279734237L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getCost()
    public int getCost()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getCost_6, null, 6425782963340199567L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getInt()
    public java.util.Vector getInt()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getInt_7, null, -6423228787845683878L);
	    return ((java.util.Vector) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getIntName()
    public java.util.Vector getIntName()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getIntName_8, null, 7970882387395986140L);
	    return ((java.util.Vector) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getMaxr()
    public int getMaxr()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getMaxr_9, null, 4394367553885430704L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getName()
    public java.util.Vector getName()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getName_10, null, 8531218095116463478L);
	    return ((java.util.Vector) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getRouter()
    public routersim.Router getRouter()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getRouter_11, null, -3098331489627132451L);
	    return ((routersim.Router) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getrname()
    public java.lang.String getrname()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getrname_12, null, -302588667315287206L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of gettype()
    public int gettype()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_gettype_13, null, 6539808755787337602L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getvModel()
    public java.util.Vector getvModel()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getvModel_14, null, 7969332590027196487L);
	    return ((java.util.Vector) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getvName()
    public java.util.Vector getvName()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getvName_15, null, -932402851981358112L);
	    return ((java.util.Vector) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getvRouter()
    public java.util.Vector getvRouter()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getvRouter_16, null, 2298791114190557744L);
	    return ((java.util.Vector) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getvStatus()
    public java.util.Vector getvStatus()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getvStatus_17, null, -1524267698401589125L);
	    return ((java.util.Vector) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of nextstep()
    public void nextstep()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_nextstep_18, null, -6468341407248974656L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of normalmode()
    public void normalmode()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_normalmode_19, null, -3285140124262559807L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setCost(int, int, int)
    public void setCost(int $param_int_1, int $param_int_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setCost_20, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2), new java.lang.Integer($param_int_3)}, -1878275863106460309L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setCostOfWire(String, String, int)
    public void setCostOfWire(java.lang.String $param_String_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setCostOfWire_21, new java.lang.Object[] {$param_String_1, $param_String_2, new java.lang.Integer($param_int_3)}, 4039477440688948890L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setIntName()
    public void setIntName()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setIntName_22, null, -5407825364861928247L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setMaxr(Router)
    public void setMaxr(routersim.Router $param_Router_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setMaxr_23, new java.lang.Object[] {$param_Router_1}, -940132969637983472L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setsingleMode(boolean)
    public void setsingleMode(boolean $param_boolean_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setsingleMode_24, new java.lang.Object[] {new java.lang.Boolean($param_boolean_1)}, 8632671761955009131L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setvFrame(int)
    public void setvFrame(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setvFrame_25, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 6163406699369162562L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setvModel()
    public void setvModel()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setvModel_26, null, -5930192029507588487L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setvRouter()
    public void setvRouter()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setvRouter_27, null, -2602912129977772774L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of showFrame(int)
    public void showFrame(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_showFrame_28, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -8134393715317832503L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of showStatus(int)
    public void showStatus(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_showStatus_29, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 278973615045450553L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of singlemode()
    public void singlemode()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_singlemode_30, null, 2117294122614259157L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of wireDelete(int, int, String, String, String)
    public void wireDelete(int $param_int_1, int $param_int_2, java.lang.String $param_String_3, java.lang.String $param_String_4, java.lang.String $param_String_5)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_wireDelete_31, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2), $param_String_3, $param_String_4, $param_String_5}, 3281637613167599209L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
