// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package routersim;

public final class PassengerImpl_Stub
    extends java.rmi.server.RemoteStub
    implements routersim.PassengerInt, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_Generatekey_0;
    private static java.lang.reflect.Method $method_ReceivePublicKey_1;
    private static java.lang.reflect.Method $method_SendCiphertext_2;
    private static java.lang.reflect.Method $method_SendPublicKey_3;
    private static java.lang.reflect.Method $method_VerifiePassword_4;
    
    static {
	try {
	    $method_Generatekey_0 = routersim.PassengerInt.class.getMethod("Generatekey", new java.lang.Class[] {});
	    $method_ReceivePublicKey_1 = routersim.PassengerInt.class.getMethod("ReceivePublicKey", new java.lang.Class[] {java.lang.String.class});
	    $method_SendCiphertext_2 = routersim.PassengerInt.class.getMethod("SendCiphertext", new java.lang.Class[] {java.lang.String.class});
	    $method_SendPublicKey_3 = routersim.PassengerInt.class.getMethod("SendPublicKey", new java.lang.Class[] {java.security.PublicKey.class});
	    $method_VerifiePassword_4 = routersim.PassengerInt.class.getMethod("VerifiePassword", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public PassengerImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of Generatekey()
    public void Generatekey()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_Generatekey_0, null, 2861529155657877707L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of ReceivePublicKey(String)
    public java.security.PublicKey ReceivePublicKey(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_ReceivePublicKey_1, new java.lang.Object[] {$param_String_1}, -7558102677193895133L);
	    return ((java.security.PublicKey) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of SendCiphertext(String)
    public void SendCiphertext(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_SendCiphertext_2, new java.lang.Object[] {$param_String_1}, -2067748183066789161L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of SendPublicKey(PublicKey)
    public void SendPublicKey(java.security.PublicKey $param_PublicKey_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_SendPublicKey_3, new java.lang.Object[] {$param_PublicKey_1}, -4706830503277403068L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of VerifiePassword(String)
    public boolean VerifiePassword(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_VerifiePassword_4, new java.lang.Object[] {$param_String_1}, -5803777307600887513L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
