// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package routersim;

public final class Scrollpane2Impl_Stub
    extends java.rmi.server.RemoteStub
    implements routersim.Scrollpane2Int, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_constructor_0;
    private static java.lang.reflect.Method $method_setScrollpane_1;
    
    static {
	try {
	    $method_constructor_0 = routersim.Scrollpane2Int.class.getMethod("constructor", new java.lang.Class[] {});
	    $method_setScrollpane_1 = routersim.Scrollpane2Int.class.getMethod("setScrollpane", new java.lang.Class[] {routersim.Frame3.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Scrollpane2Impl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of constructor()
    public void constructor()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_constructor_0, null, -9000235719137383690L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setScrollpane(Frame3)
    public void setScrollpane(routersim.Frame3 $param_Frame3_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setScrollpane_1, new java.lang.Object[] {$param_Frame3_1}, 4472313497374036630L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
