// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package routersim;

public final class StatusImpl_Stub
    extends java.rmi.server.RemoteStub
    implements routersim.StatusInt, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_constructor_0;
    private static java.lang.reflect.Method $method_getRname_1;
    private static java.lang.reflect.Method $method_getS_2;
    private static java.lang.reflect.Method $method_getS1_3;
    private static java.lang.reflect.Method $method_setS1_4;
    
    static {
	try {
	    $method_constructor_0 = routersim.StatusInt.class.getMethod("constructor", new java.lang.Class[] {java.lang.String.class});
	    $method_getRname_1 = routersim.StatusInt.class.getMethod("getRname", new java.lang.Class[] {});
	    $method_getS_2 = routersim.StatusInt.class.getMethod("getS", new java.lang.Class[] {});
	    $method_getS1_3 = routersim.StatusInt.class.getMethod("getS1", new java.lang.Class[] {});
	    $method_setS1_4 = routersim.StatusInt.class.getMethod("setS1", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public StatusImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of constructor(String)
    public void constructor(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_constructor_0, new java.lang.Object[] {$param_String_1}, -1902516435535675811L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getRname()
    public java.lang.String getRname()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getRname_1, null, 8576915859681263679L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getS()
    public java.lang.String getS()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getS_2, null, 5276426077715000677L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getS1()
    public java.lang.String getS1()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getS1_3, null, -5459104004394163912L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setS1(String)
    public void setS1(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setS1_4, new java.lang.Object[] {$param_String_1}, 4301739439658589009L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
