#
# ----- CUT HERE  --- Server config --- CUT HERE -----
#
options {
  port 5000;		# Listen on this port.

  # Path to various programs
  ppp 		/usr/sbin/pppd;            
  ifconfig 	/sbin/ifconfig;
  route 	/sbin/route;
  firewall 	/sbin/ipchains;
}

# Default session options 
default {
  compress no;		# Compression is off by default
  speed 0;		# By default maximum speed, NO shaping
}

# TUN example. Session 'cobra'.
cobra {
  pass  Ma&^TU;		# Password
  type  tun;		# IP tunnel 
  proto udp;   		# UDP protocol
  comp  lzo:9;		# LZO compression level 9
  encr  yes;		# Encryption
  keepalive yes;	# Keep connection alive

  up {
	# Connection is Up 

	# 10.3.0.1 - local, 10.3.0.2 - remote 
	ifconfig "%% 10.3.0.1 pointopoint 10.3.0.2 mtu 1450";
  };
}

# Ethernet example. Session 'lion'.
lion {
  pass  Ma&^TU;		# Password
  type  ether; 		# Ethernet tunnel
  device tap0; 		# Device tap0 
  proto udp;   		# UDP protocol
  comp  lzo:1;		# LZO compression level 1 
  encr  yes;		# Encryption
  stat  yes;   		# Log connection statistic 
  keepalive yes;	# Keep connection alive

  up {	
	# Connection is Up 

	# Assign IP address 
	ifconfig "%% 10.1.0.1 netmask 255.255.255.0";
		
	# Add route to net 10.2.0.0/24  
	route "add -net 10.2.0.0 netmask 255.255.255.0 gw 10.1.0.2";

	# Enable masquerading for net 10.2.0.0.0/24 
	firewall "-A forward -s 10.2.0.0/24 -d 0.0.0.0/0 -j MASQ";
  };

  down {
	# Connection is Down

	# Shutdown tap device. 
	ifconfig "%% down"; 

	# Disable masquerading for net 10.2.0.0.0/24 
	firewall "-D forward -s 10.2.0.0/24 -d 0.0.0.0/0 -j MASQ";
  };
}

# PPP example. Session 'viper'.
viper {	
  pass  TTT$bio;	# Password
  comp  yes; 		# ZLIB compression level 1 
  encr  yes;		# Encryption
  up {
	# Connection is Up (established)

        # Assign IP addresses 10.0.0.1 - local, 10.0.0.2 - remote
	ppp "10.0.0.1:10.0.0.2 proxyarp";
  };
}

# Pipe example. Session 'backup'.
backup {
  passwd OnlyME;	# Password
  type pipe;		# Pipe tunnel
  speed 256:128;	# Shaping speed 256K IN and 128K OUT.
  encrypt yes;		# Encryption
  up {
	# Connection is Up 

	# Start shell and tar '/etc' directory to 
	# the stdout (pipe tunnel). 
	prog /bin/sh "-c 'tar cf - /etc/*'";
  };
}

# TTY example. Session 'sz'.
# Silly example to show that VTun can tunnel ALMOST
# anything :-). 
sz {
  pass  OnlyME;		# Password
  type  tty;		# TTY tunnel
  speed 64;		# Shaping speed 64K IN/OUT
  encr  yes;		# Encryption
  up {
	# Connection is Up 

        # Send '/etc/profile' via ZMODEM to the
	# stdout(tty tunnel).
	prog /bin/sh "-c 'sz /etc/termcap'";
  };
}
#
# ----- CUT HERE  -------- End -------- CUT HERE -----
#
