function ShowPoint

% if nargin<1,
%     action='start';
% end;
% if ~strcmp(action,'start'),
%     %         handles=get(gcf,'UserData');
%     hPlot = handles(1);
%     hnext = handles(1);
%     hprevious = handles(2);
% end;
conn = database('store','','');
curs = exec(conn,'select points from point ORDER BY `points`');
curs = fetch(curs);
dataans = curs.data;
close(conn);
numrows = rows(curs);

score_min = dataans{1};
score_max = dataans{numrows};
score_average = 0;
for i = 1:numrows
    score_average =score_average+dataans{i};
end
score_average = score_average/numrows;

str_score = strcat('แสดงผลคะแนนทั้งหมด   ','   คะแนนน้อยสุด=',num2str(score_min),'  คะแนนมากสุด=',num2str(score_max),'   คะแนนเฉลี่ย=',num2str(score_average));

bgcolor = 'black';
fgcolor = 'white';

scrsz = get(0,'ScreenSize');
figure('Position',[5 65 scrsz(3)*4/5 scrsz(4)-105])
set(gcf, ...
    'NumberTitle','off', ...
    'Name',str_score, ...
    'backingstore','off',...
    'Units','normalized',...
    'Color',fgcolor);

conn = database('store','','');
curs = exec(conn,'select * from point order by std_id');
curs = fetch(curs);
datatest = curs.data;
numrows = rows(curs);
numcols = cols(curs);

count = 0;
top = 0.90;
left = 0.05;
width = 0.6;
hight = 0.03;

top2 = 0.90;
left2 = 0.25;
top3 = 0.90;
left3 = 0.45;
m = numrows;
          
for i = 1:m
    if i <= 30 
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left-0.03 .95 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String','รหัสนักศึกษา');  
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left+0.07 .95 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String','คะแนน');
        datainfo = datatest(i,1);
        datainfo = num2str(datainfo{1});
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left-0.03 top width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String',datainfo);   
        %datainfo = char(datatest(i,2));  
        datainfo = datatest(i,2);
        datainfo = num2str(datainfo{1});
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left+0.08 top width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String',datainfo);    
        top = top - 0.03;
    elseif i <= 60
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left2-0.03 .95 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String','รหัสนักศึกษา');  
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left2+0.07 .95 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String','คะแนน');
        %datainfo = char(datatest(i,1));
        datainfo = datatest(i,1);
        datainfo = num2str(datainfo{1});
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left2-0.03 top2 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String',datainfo);   
        %datainfo = char(datatest(i,2));     
        datainfo = datatest(i,2);
        datainfo = num2str(datainfo{1});
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left2+0.08 top2 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String',datainfo);    
        top2 = top2 - 0.03;
    else
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left3-0.03 .95 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String','รหัสนักศึกษา');  
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left3+0.07 .95 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String','คะแนน');
%         datainfo = char(datatest(i,1));
        datainfo = datatest(i,1);
        datainfo = num2str(datainfo{1});
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left3-0.03 top3 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String',datainfo);   
        %datainfo = char(datatest(i,2));        
        datainfo = datatest(i,2);
        datainfo = num2str(datainfo{1});
        uicontrol(...
            'Style','text',...
            'Units','normalized',...
            'Position',[left3+0.08 top3 width hight],...
            'BackgroundColor',fgcolor,...
            'ForegroundColor','Black',...
            'HorizontalAlignment','left',...
            'FontSize',10.0,...
            'String',datainfo);    
        top3 = top3 - 0.03;
    end    
end        