#
# ----- CUT HERE  --- Client config --- CUT HERE -----
#
options {
  port 5000;		# Connect to this port.
  timeout 60;		# General timeout

  # Path to various programs
  ppp		/usr/sbin/pppd;            
  ifconfig	/sbin/ifconfig;
  route		/sbin/route;
  firewall	/sbin/ipchains;
}

# TUN example. Session 'cobra'. 
cobra {
  pass  Ma&^TU;		# Password
  device tun1; 		# Device tun1 
  persist yes;		# Persist mode 
  up {
	# Connection is Up 

	# Assign IP addresses. 
	ifconfig "%% 10.3.0.2 pointopoint 10.3.0.1 mtu 1450";
  };
}

# Ethernet example. Session 'lion'. 
lion {
  pass  Ma&^TU;		# Password
  type  ether;		# Ethernet tunnel
  device tap1; 		# Device tap1 
  up {
	# Connection is Up 

	# Assign IP address and netmask. 
	ifconfig "%% 10.1.0.2 netmask 255.255.255.0";
  };
  down {
	# Connection is Down 

	# Shutdown tap device
	ifconfig "%% down";
  };
}

# PPP example. Session 'viper'. 
viper {
  pass  TTT$bio; 	# Password
  up {
	# Connection is Up 

	# IP address will be assigned by the server 
	ppp "noipdefault";
  };
}

# Pipe example. Session 'backup'.
backup {
  passwd OnlyME;	# Password
  up {
	# Connection is Up 

	# Start shell and untar files from
	# stdin(pipe tunnel). 
	prog /bin/sh "-c 'cd /tmp; tar xf -";
  };
}

# TTY example. Session 'sz'.
# Silly example to show that VTun can tunnel ALMOST
# anything :-).
sz {
  pass  OnlyME;		# Password
  up {
	# Receive file via ZMODEM from the
	# stdin(tty tunnel).
	prog  /bin/sh "-c 'cd /tmp; rz'";
  };
}
