<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Book (DC, Kmitl)>
<!ELEMENT DC (DC_Title, DC_Creator, DC_Subject, DC_Desscription, DC_Contributor, DC_Publisher, DC_Date, DC_Format, DC_Identifier, DC_Source, DC_Language, DC_Relation?, DC_Coverage?, DC_Rights, DC_Thesis)>
<!ELEMENT DC_Title (Title_Title, Title_Alternative)>
<!ELEMENT Title_Title (#PCDATA)>
<!ELEMENT Title_Alternative (#PCDATA)>
<!ELEMENT DC_Creator (Creator_Name+, Creator_Org_Name, Creator_E-Mail*)>
<!ELEMENT Creator_Name (#PCDATA)>
<!ELEMENT Creator_Org_Name (#PCDATA)>
<!ELEMENT Creator_E-Mail (#PCDATA)>
<!ELEMENT DC_Subject (Subject_ThaSH)>
<!ELEMENT Subject_ThaSH (#PCDATA)>
<!ELEMENT DC_Desscription (Desscription_Abstract)>
<!ELEMENT Desscription_Abstract (#PCDATA)>
<!ELEMENT DC_Contributor (Contributor_Name+, Contributor_Roles, Contributor_E-mail*)>
<!ELEMENT Contributor_Name (#PCDATA)>
<!ELEMENT Contributor_Roles (#PCDATA)>
<!ELEMENT Contributor_E-mail (#PCDATA)>
<!ELEMENT DC_Publisher (Publisher_Name, Publisher_Place, Publisher_E-mail*)>
<!ELEMENT Publisher_Name (#PCDATA)>
<!ELEMENT Publisher_Place (#PCDATA)>
<!ELEMENT Publisher_E-mail (#PCDATA)>
<!ELEMENT DC_Date (Date_Created, Date_Issued, Date_Modified)>
<!ELEMENT Date_Created (#PCDATA)>
<!ELEMENT Date_Issued (#PCDATA)>
<!ELEMENT Date_Modified (#PCDATA)>
<!ELEMENT DC_Format (#PCDATA)>
<!ELEMENT DC_Identifier (Identifier_Url, Identifier_Isbn?, Identifier_Issn?, Identifier_BibliographyCitation?)>
<!ELEMENT Identifier_Url (#PCDATA)>
<!ELEMENT Identifier_Isbn (#PCDATA)>
<!ELEMENT Identifier_Issn (#PCDATA)>
<!ELEMENT Identifier_BibliographyCitation (#PCDATA)>
<!ELEMENT DC_Source (Source_Call_Number)>
<!ELEMENT Source_Call_Number (#PCDATA)>
<!ELEMENT DC_Language (#PCDATA)>
<!ELEMENT DC_Relation (#PCDATA)>
<!ELEMENT DC_Coverage (#PCDATA)>
<!ELEMENT DC_Rights (Rights_Rights, Rights_Rights_Accress)>
<!ELEMENT Rights_Rights (#PCDATA)>
<!ELEMENT Rights_Rights_Accress (#PCDATA)>
<!ELEMENT DC_Thesis (Thesis_Degree_Name, Thesis_Degree_Level, Thesis_Degree_Descipline, Thesis_Degree_Grantor)>
<!ELEMENT Thesis_Degree_Name (#PCDATA)>
<!ELEMENT Thesis_Degree_Level (#PCDATA)>
<!ELEMENT Thesis_Degree_Descipline (#PCDATA)>
<!ELEMENT Thesis_Degree_Grantor (#PCDATA)>
<!ELEMENT Kmitl ( Creator_English+, Adviser_English+, Faculty, Department_English, Year_English, Abstract_English, Contents?, Illustrative?, Chapter, Bibliography?, Appendix?, Keyword?)>
<!ELEMENT Creator_English (#PCDATA)>
<!ELEMENT Adviser_English (#PCDATA)>
<!ELEMENT Faculty (Faculty_Thai, Faculty_English)>
<!ELEMENT Faculty_Thai (#PCDATA)>
<!ELEMENT Faculty_English (#PCDATA)>
<!ELEMENT Department_English (#PCDATA)>
<!ELEMENT Year_English (#PCDATA)>
<!ELEMENT Abstract_English (#PCDATA)>
<!ELEMENT Contents (#PCDATA)>
<!ELEMENT Illustrative (#PCDATA)>
<!ELEMENT Chapter (Chapter1?,Chapter2?,Chapter3?,Chapter4?,Chapter5?,Chapter6?,Chapter7?,Chapter8?,Chapter9?,Chapter10?,Chapter11?,Chapter12?,Chapter13?,Chapter14?,Chapter15?)>
<!ELEMENT Chapter1 (#PCDATA)>
<!ELEMENT Chapter2 (#PCDATA)>
<!ELEMENT Chapter3 (#PCDATA)>
<!ELEMENT Chapter4 (#PCDATA)>
<!ELEMENT Chapter5 (#PCDATA)>
<!ELEMENT Chapter6 (#PCDATA)>
<!ELEMENT Chapter7 (#PCDATA)>
<!ELEMENT Chapter8 (#PCDATA)>
<!ELEMENT Chapter9 (#PCDATA)>
<!ELEMENT Chapter10 (#PCDATA)>
<!ELEMENT Chapter11 (#PCDATA)>
<!ELEMENT Chapter12 (#PCDATA)>
<!ELEMENT Chapter13 (#PCDATA)>
<!ELEMENT Chapter14 (#PCDATA)>
<!ELEMENT Chapter15 (#PCDATA)>
<!ELEMENT Bibliography (#PCDATA)>
<!ELEMENT Appendix (#PCDATA)>
<!ELEMENT Keyword (#PCDATA)> 

