//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Restaurant.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://localhost/WebserviceRestaurant/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/hello", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string hello() {
            object[] results = this.Invoke("hello", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginhello(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("hello", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string Endhello(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkReserv", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int checkReserv(
                    string useTime, 
                    string reservTime, 
                    string endTime, 
                    int covers, 
                    string cardID, 
                    string name, 
                    string lastname, 
                    int age, 
                    bool sex, 
                    string address, 
                    string province, 
                    string postcode, 
                    string telephone, 
                    string email, 
                    int shopID, 
                    string shopName) {
            object[] results = this.Invoke("checkReserv", new object[] {
                        useTime,
                        reservTime,
                        endTime,
                        covers,
                        cardID,
                        name,
                        lastname,
                        age,
                        sex,
                        address,
                        province,
                        postcode,
                        telephone,
                        email,
                        shopID,
                        shopName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckReserv(
                    string useTime, 
                    string reservTime, 
                    string endTime, 
                    int covers, 
                    string cardID, 
                    string name, 
                    string lastname, 
                    int age, 
                    bool sex, 
                    string address, 
                    string province, 
                    string postcode, 
                    string telephone, 
                    string email, 
                    int shopID, 
                    string shopName, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return this.BeginInvoke("checkReserv", new object[] {
                        useTime,
                        reservTime,
                        endTime,
                        covers,
                        cardID,
                        name,
                        lastname,
                        age,
                        sex,
                        address,
                        province,
                        postcode,
                        telephone,
                        email,
                        shopID,
                        shopName}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndcheckReserv(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public menu test() {
            object[] results = this.Invoke("test", new object[0]);
            return ((menu)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begintest(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("test", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public menu Endtest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((menu)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateMenu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public menu[] updateMenu() {
            object[] results = this.Invoke("updateMenu", new object[0]);
            return ((menu[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateMenu(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateMenu", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public menu[] EndupdateMenu(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((menu[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateMenuAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] updateMenuAll() {
            object[] results = this.Invoke("updateMenuAll", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateMenuAll(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateMenuAll", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndupdateMenuAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updatePromotion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public promotion[] updatePromotion() {
            object[] results = this.Invoke("updatePromotion", new object[0]);
            return ((promotion[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdatePromotion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updatePromotion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public promotion[] EndupdatePromotion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((promotion[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updatePromotionAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] updatePromotionAll() {
            object[] results = this.Invoke("updatePromotionAll", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdatePromotionAll(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updatePromotionAll", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndupdatePromotionAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cancelReserv", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cancelReserv(int tableID, string reservTime, string endTime) {
            object[] results = this.Invoke("cancelReserv", new object[] {
                        tableID,
                        reservTime,
                        endTime});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelReserv(int tableID, string reservTime, string endTime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelReserv", new object[] {
                        tableID,
                        reservTime,
                        endTime}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndcancelReserv(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class menu {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class promotion {
    }
}
