<%@ Page Language="vb" AutoEventWireup="false" Codebehind="in_wood.aspx.vb" Inherits="WebApplicationSeller1.in_candle"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>in_candle</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" background="pic\snows.gif">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma"><a href="webformbag1.aspx"><IMG style="Z-INDEX: 101; LEFT: 182px; WIDTH: 308px; POSITION: absolute; TOP: 154px; HEIGHT: 296px" height="296" alt="" src="pic\information.jpg" width="308" id="IMG1" runat="server"></a>
				<DIV style="DISPLAY: inline; Z-INDEX: 102; LEFT: 529px; WIDTH: 311px; POSITION: absolute; TOP: 177px; HEIGHT: 294px" ms_positioning="FlowLayout">แจกัน 
					ชาม และสินค้าส่วนใหญ่ เป็นผลิตภัณฑ์ผลิตจากไม้มะม่วง 
					ซึ่งผ่านขบวนการในการผลิตหลายขั้นตอน 
					โดยการคัดเลือกไม้ที่ได้ขนาดเหมาะสมกับชิ้นงานแต่ละประเภท 
					นำไปผ่านขบวนการอบไม้ให้แห้ง 
					เพื่อลดความชื้นในเนื้อไม้ซึ่งเป็นสาเหตุทำให้เกิดเชื้อรา นำไปกลึง และ คว้าน 
					ไม้ตามรูปแบบของชิ้นงานที่ต้องการ จากนั้นนำไปขัดผิว ทำสี 
					แล้วในขั้นตอนที่สำคัญสุดท้ายคือการ แกะสลักลวดลายต่างๆ 
					ลงบนเนื้อไม้ที่ได้ผ่านขบวนการข้างต้นมาโดยสมบูรณ์แล้ว ด้วยความชำนาญ 
					และตกแต่งด้วยเชือกถัก หรือ ร้อยหวายตามแต่ประเภทของผลิตภัณฑ์
				</DIV>
				<DIV style="DISPLAY: inline; Z-INDEX: 103; LEFT: 435px; WIDTH: 216px; POSITION: absolute; TOP: 65px; HEIGHT: 56px" ms_positioning="FlowLayout"><h1>บ้านไม้มะม่วง</h1>
				</DIV>
			</FONT>
		</form>
	</body>
</HTML>
