<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormBag1.aspx.vb" Inherits="WebApplicationSeller1.WebForm1"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebForm1</title>
		<meta content="Microsoft Visual Studio.NET 7.0" name="GENERATOR">
		<meta content="Visual Basic 7.0" name="CODE_LANGUAGE">
		<meta content="JavaScript" name="vs_defaultClientScript">
		<meta content="http://schemas.microsoft.com/intellisense/ie5" name="vs_targetSchema">
	</HEAD>
	<body background="pic/snows.gif" MS_POSITIONING="GridLayout">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma"><IMG style="Z-INDEX: 101; LEFT: 493px; WIDTH: 165px; POSITION: absolute; TOP: 158px; HEIGHT: 129px" height="129" alt="" src="pic\033.jpg" width="165">
				<DIV id="lblRegis" style="DISPLAY: inline; Z-INDEX: 117; LEFT: 290px; WIDTH: 86px; POSITION: absolute; TOP: 58px; HEIGHT: 19px" ms_positioning="FlowLayout"><A href="WebFormRegis.aspx">สมัครสมาชิก</A></ACRONYM></DIV>
				<DIV style="DISPLAY: inline; Z-INDEX: 116; LEFT: 389px; WIDTH: 107px; POSITION: absolute; TOP: 58px; HEIGHT: 19px" ms_positioning="FlowLayout"><A href="WebFormInbasket.aspx">ดูสินค้าในตะกร้า</A></DIV>
				<DIV style="DISPLAY: inline; Z-INDEX: 113; LEFT: 662px; WIDTH: 41px; POSITION: absolute; TOP: 57px; HEIGHT: 21px" ms_positioning="FlowLayout"><A href="in_wood.aspx">Home</A></DIV>
				<DIV style="Z-INDEX: 112; LEFT: 672px; WIDTH: 211px; POSITION: absolute; TOP: 519px; HEIGHT: 124px" ms_positioning="FlowLayout">
					<P>ชามแกะลาย<BR>
						500&nbsp;g.
						<BR>
						ผ่านศูนย์กลาง 12 inch<BR>
						สูง 6 inch<BR>
						วัสดุ ไม้มะม่วง<BR>
						ราคา 280บาท <INPUT id="Button6" style="WIDTH: 83px; HEIGHT: 21px" type="button" value="หยิบใส่ตะกร้า" name="Button6" runat="server"></P>
				</DIV>
				<DIV style="Z-INDEX: 111; LEFT: 676px; WIDTH: 211px; POSITION: absolute; TOP: 166px; HEIGHT: 124px" ms_positioning="FlowLayout">
					<P>ถาดแกะลาย<BR>
						400&nbsp;g.
						<BR>
						ผ่านศูนย์กลาง 12 inch<BR>
						สูง 6 inch<BR>
						วัสดุ ไม้มะม่วง<BR>
						ราคา 335บาท <INPUT id="Button3" style="WIDTH: 83px; HEIGHT: 21px" type="button" value="หยิบใส่ตะกร้า" name="Button3" runat="server"></P>
				</DIV>
				<DIV style="Z-INDEX: 110; LEFT: 676px; WIDTH: 211px; POSITION: absolute; TOP: 334px; HEIGHT: 124px" ms_positioning="FlowLayout">
					<P>ชามแกะลาย<BR>
						500&nbsp;g.
						<BR>
						ผ่านศูนย์กลาง 12 inch<BR>
						สูง 6 inch<BR>
						วัสดุ ไม้มะม่วง<BR>
						ราคา 300บาท <INPUT id="Button5" style="WIDTH: 83px; HEIGHT: 21px" type="button" value="หยิบใส่ตะกร้า" name="Button5" runat="server"></P>
				</DIV>
				<DIV style="Z-INDEX: 108; LEFT: 252px; WIDTH: 211px; POSITION: absolute; TOP: 335px; HEIGHT: 124px" ms_positioning="FlowLayout">
					<P>ชามแกะลาย<BR>
						500&nbsp;g.
						<BR>
						ผ่านศูนย์กลาง 12 inch<BR>
						สูง 6 inch<BR>
						วัสดุ ไม้มะม่วง<BR>
						ราคา 320บาท <INPUT id="Button2" style="WIDTH: 83px; HEIGHT: 21px" type="button" value="หยิบใส่ตะกร้า" name="Button2" runat="server"></P>
				</DIV>
				<IMG style="Z-INDEX: 106; LEFT: 69px; WIDTH: 165px; POSITION: absolute; TOP: 336px; HEIGHT: 129px" height="129" alt="" src="pic\026.jpg" width="165"><IMG style="Z-INDEX: 105; LEFT: 492px; WIDTH: 165px; POSITION: absolute; TOP: 331px; HEIGHT: 129px" height="129" alt="" src="pic\038.jpg" width="165"><IMG style="Z-INDEX: 104; LEFT: 64px; WIDTH: 165px; POSITION: absolute; TOP: 518px; HEIGHT: 129px" height="129" alt="" src="pic\030.jpg" width="165"><IMG style="Z-INDEX: 103; LEFT: 492px; WIDTH: 165px; POSITION: absolute; TOP: 518px; HEIGHT: 129px" height="129" alt="" src="pic\039.jpg" width="165"><IMG style="Z-INDEX: 102; LEFT: 76px; WIDTH: 165px; POSITION: absolute; TOP: 152px; HEIGHT: 136px" height="136" alt="" src="pic\018.jpg" width="165"></FONT>
			<DIV style="Z-INDEX: 107; LEFT: 255px; WIDTH: 211px; POSITION: absolute; TOP: 155px; HEIGHT: 124px" ms_positioning="FlowLayout">
				<P>ชามแกะลาย<BR>
					200&nbsp;g.
					<BR>
					ผ่านศูนย์กลาง 12 inch<BR>
					สูง 6 inch<BR>
					วัสดุ ไม้มะม่วง<BR>
					ราคา 250บาท <INPUT id="Button1" style="WIDTH: 83px; HEIGHT: 21px" type="button" value="หยิบใส่ตะกร้า" name="Button1" runat="server"></P>
			</DIV>
			<DIV style="Z-INDEX: 109; LEFT: 251px; WIDTH: 211px; POSITION: absolute; TOP: 521px; HEIGHT: 124px" ms_positioning="FlowLayout">
				<P>ถาดแกะลาย<BR>
					400&nbsp;g.
					<BR>
					ผ่านศูนย์กลาง 12 inch<BR>
					สูง 6 inch<BR>
					วัสดุ ไม้มะม่วง<BR>
					ราคา 400บาท <INPUT id="Button4" style="WIDTH: 83px; HEIGHT: 21px" type="button" value="หยิบใส่ตะกร้า" name="Button4" runat="server"></P>
			</DIV>
			<asp:label id="Label1" style="Z-INDEX: 114; LEFT: 138px; POSITION: absolute; TOP: 59px" runat="server" Height="17px" Width="141px">
				<a href="webformLogin.aspx">เข้าและออกจากระบบ</a></asp:label>
			<DIV style="DISPLAY: inline; Z-INDEX: 115; LEFT: 409px; WIDTH: 178px; POSITION: absolute; TOP: 676px; HEIGHT: 67px" ms_positioning="FlowLayout"><FONT face="Tahoma"><A href="http://161.246.6.4/projecttumbolthai/webapplicationCenter/index.htm">กลับสู่เว็บบริการตำบลไทย</A></FONT></DIV>
			<asp:textbox id="txtNameSearch" style="Z-INDEX: 118; LEFT: 236px; POSITION: absolute; TOP: 114px" runat="server" Width="118px" Height="21px"></asp:textbox>
			<asp:Label id="Label4" style="Z-INDEX: 119; LEFT: 493px; POSITION: absolute; TOP: 86px" runat="server" Width="85px" Height="21px">ราคาไม่เกิน</asp:Label>
			<asp:Label id="Label2" style="Z-INDEX: 120; LEFT: 355px; POSITION: absolute; TOP: 86px" runat="server" Width="130px" Height="21px">ลายระเอียดเพิ่มเติม</asp:Label>
			<asp:textbox id="txtPrice" style="Z-INDEX: 121; LEFT: 484px; POSITION: absolute; TOP: 114px" runat="server" Width="75px" Height="21px"></asp:textbox>
			<asp:textbox id="txtDetail" style="Z-INDEX: 122; LEFT: 359px; POSITION: absolute; TOP: 114px" runat="server" Width="118px" Height="21px"></asp:textbox>
			<asp:button id="btnSearch" style="Z-INDEX: 123; LEFT: 697px; POSITION: absolute; TOP: 112px" runat="server" Width="64px" Text="ค้นหา"></asp:button>
			<asp:dropdownlist id="ddlFrom" style="Z-INDEX: 124; LEFT: 565px; POSITION: absolute; TOP: 114px" runat="server" Width="122px">
				<asp:ListItem Value="0" Selected="True">ภายในร้าน</asp:ListItem>
				<asp:ListItem Value="1">ทุกๆร้าน</asp:ListItem>
			</asp:dropdownlist>
			<asp:label id="Label3" style="Z-INDEX: 125; LEFT: 144px; POSITION: absolute; TOP: 115px" runat="server" Width="81px" Height="17px">ค้นหาสินค้า</asp:label>
			<asp:Label id="Label5" style="Z-INDEX: 126; LEFT: 242px; POSITION: absolute; TOP: 86px" runat="server" Width="69px" Height="21px">ชื่อสินค้า</asp:Label>
			<asp:Label id="Label6" style="Z-INDEX: 127; LEFT: 508px; POSITION: absolute; TOP: 58px" runat="server" Width="141px" Height="20px">
				<a href="webformcheckstatusselled.aspx">ตรวจสอบสินค้าที่ซื้อ </a>
			</asp:Label>
		</form>
	</body>
</HTML>
