//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.42.
// 
namespace MapView.WebReference1 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service() {
            this.Url = "http://161.246.6.191/WebSite5/Service.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCapabilities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCapabilities() {
            object[] results = this.Invoke("GetCapabilities", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCapabilities(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCapabilities", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetCapabilities(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetMap(string request) {
            object[] results = this.Invoke("GetMap", new object[] {
                        request});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMap(string request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMap", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndGetMap(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateMap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode CreateMap(string request) {
            object[] results = this.Invoke("CreateMap", new object[] {
                        request});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateMap(string request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateMap", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndCreateMap(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Find", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Find(string name, string[] layer) {
            object[] results = this.Invoke("Find", new object[] {
                        name,
                        layer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFind(string name, string[] layer, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Find", new object[] {
                        name,
                        layer}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndFind(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FindAddress(string address, string street, string district, string province, string postcode) {
            object[] results = this.Invoke("FindAddress", new object[] {
                        address,
                        street,
                        district,
                        province,
                        postcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindAddress(string address, string street, string district, string province, string postcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindAddress", new object[] {
                        address,
                        street,
                        district,
                        province,
                        postcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndFindAddress(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindNearby", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode FindNearby(double Lat, double Long, double radius, string request, bool showText) {
            object[] results = this.Invoke("FindNearby", new object[] {
                        Lat,
                        Long,
                        radius,
                        request,
                        showText});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindNearby(double Lat, double Long, double radius, string request, bool showText, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindNearby", new object[] {
                        Lat,
                        Long,
                        radius,
                        request,
                        showText}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndFindNearby(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindNearest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FindNearest(double latitude, double longtitude, string name, string layer) {
            object[] results = this.Invoke("FindNearest", new object[] {
                        latitude,
                        longtitude,
                        name,
                        layer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindNearest(double latitude, double longtitude, string name, string layer, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindNearest", new object[] {
                        latitude,
                        longtitude,
                        name,
                        layer}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndFindNearest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateDistance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CalculateDistance(double beginLat, double beginLong, double endLat, double endLong) {
            object[] results = this.Invoke("CalculateDistance", new object[] {
                        beginLat,
                        beginLong,
                        endLat,
                        endLong});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCalculateDistance(double beginLat, double beginLong, double endLat, double endLong, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CalculateDistance", new object[] {
                        beginLat,
                        beginLong,
                        endLat,
                        endLong}, callback, asyncState);
        }
        
        /// <remarks/>
        public double EndCalculateDistance(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConvertAddressToCoordinate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double[] ConvertAddressToCoordinate(string address, string street, string district, string province, string postcode) {
            object[] results = this.Invoke("ConvertAddressToCoordinate", new object[] {
                        address,
                        street,
                        district,
                        province,
                        postcode});
            return ((double[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConvertAddressToCoordinate(string address, string street, string district, string province, string postcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConvertAddressToCoordinate", new object[] {
                        address,
                        street,
                        district,
                        province,
                        postcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public double[] EndConvertAddressToCoordinate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((double[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetXml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetXml(System.Xml.XmlNode kk) {
            object[] results = this.Invoke("GetXml", new object[] {
                        kk});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetXml(System.Xml.XmlNode kk, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetXml", new object[] {
                        kk}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetXml(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
