//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace WApplication.WReference3 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://161.246.5.112/WService3/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TitleAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TitleAll(string input, string fac, string dept, string year, int count) {
            object[] results = this.Invoke("TitleAll", new object[] {
                        input,
                        fac,
                        dept,
                        year,
                        count});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTitleAll(string input, string fac, string dept, string year, int count, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TitleAll", new object[] {
                        input,
                        fac,
                        dept,
                        year,
                        count}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndTitleAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TitleSome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TitleSome(string input, string fac, string dept, string year, int count) {
            object[] results = this.Invoke("TitleSome", new object[] {
                        input,
                        fac,
                        dept,
                        year,
                        count});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTitleSome(string input, string fac, string dept, string year, int count, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TitleSome", new object[] {
                        input,
                        fac,
                        dept,
                        year,
                        count}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndTitleSome(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KeywordAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KeywordAll(string input, string fac, string dept, string year, int count) {
            object[] results = this.Invoke("KeywordAll", new object[] {
                        input,
                        fac,
                        dept,
                        year,
                        count});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginKeywordAll(string input, string fac, string dept, string year, int count, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("KeywordAll", new object[] {
                        input,
                        fac,
                        dept,
                        year,
                        count}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndKeywordAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KeywordSome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KeywordSome(string input, string fac, string dept, string year, int count) {
            object[] results = this.Invoke("KeywordSome", new object[] {
                        input,
                        fac,
                        dept,
                        year,
                        count});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginKeywordSome(string input, string fac, string dept, string year, int count, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("KeywordSome", new object[] {
                        input,
                        fac,
                        dept,
                        year,
                        count}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndKeywordSome(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Uname", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Uname() {
            object[] results = this.Invoke("Uname", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUname(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Uname", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUname(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listFac", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet listFac() {
            object[] results = this.Invoke("listFac", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistFac(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listFac", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistFac(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listDept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet listDept(string fac) {
            object[] results = this.Invoke("listDept", new object[] {
                        fac});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistDept(string fac, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listDept", new object[] {
                        fac}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistDept(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listYear", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet listYear() {
            object[] results = this.Invoke("listYear", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistYear(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listYear", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistYear(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="listYear1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listYearDependOnFac", RequestElementName="listYearDependOnFac", RequestNamespace="http://tempuri.org/", ResponseElementName="listYearDependOnFacResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("listYearDependOnFacResult")]
        public System.Data.DataSet listYear(string fac) {
            object[] results = this.Invoke("listYear1", new object[] {
                        fac});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistYear1(string fac, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listYear1", new object[] {
                        fac}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistYear1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="listYear2")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listYearDependOnFacandDept", RequestElementName="listYearDependOnFacandDept", RequestNamespace="http://tempuri.org/", ResponseElementName="listYearDependOnFacandDeptResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("listYearDependOnFacandDeptResult")]
        public System.Data.DataSet listYear(string fac, string dept) {
            object[] results = this.Invoke("listYear2", new object[] {
                        fac,
                        dept});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistYear2(string fac, string dept, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listYear2", new object[] {
                        fac,
                        dept}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndlistYear2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/countResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string countResult() {
            object[] results = this.Invoke("countResult", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincountResult(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("countResult", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcountResult(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DetailP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DetailP(string title) {
            object[] results = this.Invoke("DetailP", new object[] {
                        title});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDetailP(string title, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DetailP", new object[] {
                        title}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndDetailP(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DetailA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DetailA(string title) {
            object[] results = this.Invoke("DetailA", new object[] {
                        title});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDetailA(string title, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DetailA", new object[] {
                        title}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndDetailA(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Name", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Name(string hname, string kind) {
            object[] results = this.Invoke("Name", new object[] {
                        hname,
                        kind});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginName(string hname, string kind, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Name", new object[] {
                        hname,
                        kind}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Group", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Group() {
            object[] results = this.Invoke("Group", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGroup(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Group", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGroup(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GroupDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GroupDB(string gr) {
            object[] results = this.Invoke("GroupDB", new object[] {
                        gr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGroupDB(string gr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GroupDB", new object[] {
                        gr}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGroupDB(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Mail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Mail(string gr) {
            object[] results = this.Invoke("Mail", new object[] {
                        gr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMail(string gr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Mail", new object[] {
                        gr}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndMail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
