
<!ELEMENT ETOUR (AIRLINE?,CULTURE?,CULTURE_DISTRICT?,DISTRICT?,FIRE?,FORM?,HOSPITAL?,ITEMS?,ITEMS_LOCALITY?,ITEMS_VENDOR?,LOCALITY?,MAIN?,MBOUNDARY?,PLACE?,PLACE_TYPE?,POLICE?,RESIDENCE?,RESIDENCE_TYPE?,RESIDENCE_VIEW?,ROAD?,ROOM?,STATION?,STATION_TYPE?,TEMPLATE?,VENDOR?,VENDOR_LOCALITY?)>
<!ELEMENT AIRLINE (Airline+)>
<!ELEMENT Airline (Air_name,Air_info,Air_logo,Air_tel,Air_mail,Air_moreinfo,Air_pic2)>
<!ATTLIST Airline order CDATA #REQUIRED>
<!ELEMENT Air_name (#PCDATA)>
<!ELEMENT Air_info (#PCDATA)>
<!ELEMENT Air_logo (#PCDATA)>
<!ELEMENT Air_tel  (#PCDATA)>
<!ELEMENT Air_mail (#PCDATA)>
<!ELEMENT Air_moreinfo (#PCDATA)>
<!ELEMENT Air_pic2 (#PCDATA)>

<!ELEMENT CULTURE (Culture+)>
<!ELEMENT Culture (Cul_name,Cul_info,Cul_time,Cul_pic,Cul_x,Cul_y,Cul_moreinfo,Cul_pic2,Cul_listdistrict+)>
<!ATTLIST Culture order CDATA #REQUIRED>
<!ELEMENT Cul_name (#PCDATA)>
<!ELEMENT Cul_info (#PCDATA)>
<!ELEMENT Cul_time (#PCDATA)>
<!ELEMENT Cul_pic (#PCDATA)>
<!ELEMENT Cul_x (#PCDATA)>
<!ELEMENT Cul_y (#PCDATA)>
<!ELEMENT Cul_moreinfo (#PCDATA)>
<!ELEMENT Cul_pic2 (#PCDATA)>
<!ELEMENT Cul_listdistrict (#PCDATA)>

<!ELEMENT CULTURE_DISTRICT (Culture_District+)>
<!ELEMENT Culture_District (Cul_name,Dis_name)>
<!ATTLIST Culture_District order CDATA #REQUIRED>
<!ELEMENT Cul_name (#PCDATA)>
<!ELEMENT Dis_name (#PCDATA)>

<!ELEMENT DISTRICT (district+)>
<!ELEMENT District (Dis_name,Dis_distance,Dis_x,Dis_y)>
<!ATTLIST District order CDATA #REQUIRED>
<!ELEMENT Dis_name (#PCDATA)>
<!ELEMENT Dis_distance (#PCDATA)>
<!ELEMENT Dis_x (#PCDATA)>
<!ELEMENT Dis_y (#PCDATA)>

<!ELEMENT FIRE (Fire+)>
<!ELEMENT Fire (Fir_name,Fir_addr,Fir_tel,Fir_x,Fir_y,Dis_name,Roa_name)>
<!ATTLIST Fire order CDATA #REQUIRED>
<!ELEMENT Fir_name (#PCDATA)>
<!ELEMENT Fir_addr (#PCDATA)>
<!ELEMENT Fir_tel (#PCDATA)>
<!ELEMENT Fir_x (#PCDATA)>
<!ELEMENT Fir_y (#PCDATA)>
<!ELEMENT Dis_name (#PCDATA)>
<!ELEMENT Roa_name (#PCDATA)>

<!ELEMENT FORM (Form+)>
<!ELEMENT Form (Topic)>
<!ATTLIST Form order CDATA #REQUIRED>
<!ELEMENT Topic (#PCDATA)>

<!ELEMENT HOSPITAL (Hospital+)>
<!ELEMENT Hospital (Hos_name,Hos_addr,Hos_tel,Hos_x,Hos_y,Dis_name,Roa_name)>
<!ATTLIST Hospital order CDATA #REQUIRED>
<!ELEMENT Hos_name (#PCDATA)>
<!ELEMENT Hos_addr (#PCDATA)>
<!ELEMENT Hos_tel (#PCDATA)>
<!ELEMENT Hos_x (#PCDATA)>
<!ELEMENT Hos_y (#PCDATA)>
<!ELEMENT Dis_name (#PCDATA)>
<!ELEMENT Roa_name (#PCDATA)>

<!ELEMENT ITEMS (Items+)>
<!ELEMENT Items (Ite_name,Ite_info,Ite_maxprice,Ite_minprice,Ite_pic,Ite_moreinfo,Ite_pic2,Ite_listlocality+)>
<!ATTLIST Items order CDATA #REQUIRED>
<!ELEMENT Ite_name (#PCDATA)>
<!ELEMENT Ite_info (#PCDATA)>
<!ELEMENT Ite_maxprice (#PCDATA)>
<!ELEMENT Ite_minprice (#PCDATA)>
<!ELEMENT Ite_pic (#PCDATA)>
<!ELEMENT Ite_moreinfo (#PCDATA)>
<!ELEMENT Ite_pic2 (#PCDATA)>
<!ELEMENT Ite_listlocality (#PCDATA)>

<!ELEMENT ITEMS_LOCALITY (Items_Locality+)>
<!ELEMENT Items_Locality (Ite_name,Loc_name)>
<!ATTLIST Items_Locality order CDATA #REQUIRED>
<!ELEMENT Ite_name (#PCDATA)>
<!ELEMENT Loc_name (#PCDATA)>

<!ELEMENT ITEMS_VENDOR (Items_Vendor+)>
<!ELEMENT Items_Vendor (Ite_name,Ven_name)>
<!ATTLIST Items_Vendor order CDATA #REQUIRED>
<!ELEMENT Ite_name (#PCDATA)>
<!ELEMENT Ven_name (#PCDATA)>
				
<!ELEMENT LOCALITY (Locality+)>
<!ELEMENT Locality (Loc_name,Loc_x,Loc_y)>
<!ATTLIST Locality order CDATA #REQUIRED>
<!ELEMENT Loc_name (#PCDATA)>
<!ELEMENT Loc_x (#PCDATA)>
<!ELEMENT Loc_y (#PCDATA)>

<!ELEMENT MAIN (Main+)>
<!ELEMENT Main (Main_part,Main_msg,Main_pic)>
<!ATTLIST Main order CDATA #REQUIRED>
<!ELEMENT Main_part (#PCDATA)>
<!ELEMENT Main_msg (#PCDATA)>
<!ELEMENT Main_pic (#PCDATA)>

<!ELEMENT MBOUNDARY (Mboundary+)>
<!ELEMENT Mboundary (Mbo_direction,Mbo_beside)>
<!ATTLIST Mboundary order CDATA #REQUIRED>
<!ELEMENT Mbo_direction (#PCDATA)>
<!ELEMENT Mbo_beside (#PCDATA)>

<!ELEMENT PLACE (Place+)>
<!ELEMENT Place (Pla_name,Pla_order,Pla_info,Dis_name,Pla_addr,Pla_tel,Pla_mail,Pla_price,Pla_pic,Pla_x,Pla_y,Pla_moreinfo,Pla_pic2)>
<!ATTLIST Place order CDATA #REQUIRED>
<!ELEMENT Pla_name (#PCDATA)>
<!ELEMENT Pla_order (#PCDATA)>
<!ELEMENT Pla_info (#PCDATA)>
<!ELEMENT Dis_name (#PCDATA)>
<!ELEMENT Pla_addr (#PCDATA)>
<!ELEMENT Pla_tel (#PCDATA)>
<!ELEMENT Pla_mail (#PCDATA)>
<!ELEMENT Pla_price (#PCDATA)>
<!ELEMENT Pla_pic (#PCDATA)>
<!ELEMENT Pla_x (#PCDATA)>
<!ELEMENT Pla_y (#PCDATA)>
<!ELEMENT Pla_moreinfo (#PCDATA)>
<!ELEMENT Pla_pic2 (#PCDATA)>


<!ELEMENT PLACE_TYPE (Place_Type+)>
<!ELEMENT Place_Type (Pla_order,Pla_type)>
<!ATTLIST Place_Type order CDATA #REQUIRED>
<!ELEMENT Pla_order (#PCDATA)>
<!ELEMENT Pla_type (#PCDATA)>

<!ELEMENT POLICE (Police+)>
<!ELEMENT Police (Pol_name,Pol_addr,Pol_tel,Pol_x,Pol_y,Dis_name,Roa_name)>
<!ATTLIST Police order CDATA #REQUIRED>
<!ELEMENT Pol_name (#PCDATA)>
<!ELEMENT Pol_addr (#PCDATA)>
<!ELEMENT Pol_tel (#PCDATA)>
<!ELEMENT Pol_x (#PCDATA)>
<!ELEMENT Pol_y (#PCDATA)>
<!ELEMENT Dis_name (#PCDATA)>
<!ELEMENT Roa_name (#PCDATA)>

<!ELEMENT RESIDENCE (Residence+)>
<!ELEMENT Residence (Res_name,Res_typorder,Res_vieorder,Res_logo,Res_info,Res_star,Dis_name,Res_addr,Res_tel,Res_mail,Res_price,Res_pic,Res_x,Res_y,Res_moreinfo,Res_pic2)>
<!ATTLIST Residence order CDATA #REQUIRED>
<!ELEMENT Res_name (#PCDATA)>
<!ELEMENT Res_typorder (#PCDATA)>
<!ELEMENT Res_vieorder (#PCDATA)>
<!ELEMENT Res_logo (#PCDATA)>
<!ELEMENT Res_info (#PCDATA)>
<!ELEMENT Res_star (#PCDATA)>
<!ELEMENT Dis_name (#PCDATA)>
<!ELEMENT Res_addr (#PCDATA)>
<!ELEMENT Res_tel (#PCDATA)>
<!ELEMENT Res_mail (#PCDATA)>
<!ELEMENT Res_price (#PCDATA)>
<!ELEMENT Res_pic (#PCDATA)>
<!ELEMENT Res_x (#PCDATA)>
<!ELEMENT Res_y (#PCDATA)>
<!ELEMENT Res_moreinfo (#PCDATA)>
<!ELEMENT Res_pic2 (#PCDATA)>

<!ELEMENT RESIDENCE_TYPE (Residence_Type+)>
<!ELEMENT Residence_Type (Res_typorder,Res_typname)>
<!ATTLIST Residence_Type order CDATA #REQUIRED>
<!ELEMENT Res_typorder (#PCDATA)>
<!ELEMENT Res_typname (#PCDATA)>

<!ELEMENT RESIDENCE_VIEW (Residence_View+)>
<!ELEMENT Residence_View (Res_vieorder,Res_viename)>
<!ATTLIST Residence_View order CDATA #REQUIRED>
<!ELEMENT Res_vieorder (#PCDATA)>
<!ELEMENT Res_viename (#PCDATA)>

<!ELEMENT ROAD (Road+)>
<!ELEMENT Road (Roa_name,Dis_name)>
<!ATTLIST Road order CDATA #REQUIRED>
<!ELEMENT Roa_name (#PCDATA)>
<!ELEMENT Dis_name (#PCDATA)>

<!ELEMENT ROOM (Room+)>
<!ELEMENT Room (Roo_order,Roo_type,Roo_info,Roo_price,Roo_lowseaprice,Roo_highseaprice,Res_name)>
<!ATTLIST Room order CDATA #REQUIRED>
<!ELEMENT Roo_order (#PCDATA)>
<!ELEMENT Roo_type (#PCDATA)>
<!ELEMENT Roo_info (#PCDATA)>
<!ELEMENT Roo_price (#PCDATA)>
<!ELEMENT Roo_lowseaprice (#PCDATA)>
<!ELEMENT Roo_highseaprice (#PCDATA)>
<!ELEMENT Res_name (#PCDATA)>

<!ELEMENT STATION (Station+)>
<!ELEMENT Station (Sta_name,Sta_addr,Sta_info,Sta_x,Sta_y,Sta_order)>
<!ATTLIST Station order CDATA #REQUIRED>
<!ELEMENT Sta_name (#PCDATA)>
<!ELEMENT Sta_addr (#PCDATA)>
<!ELEMENT Sta_info (#PCDATA)>
<!ELEMENT Sta_x (#PCDATA)>
<!ELEMENT Sta_y (#PCDATA)>
<!ELEMENT Sta_order (#PCDATA)>

<!ELEMENT STATION_TYPE (Station_Type+)>
<!ELEMENT Station_Type (Sta_order,Sta_type,Sta_pic)>
<!ATTLIST Station_Type order CDATA #REQUIRED>
<!ELEMENT Sta_order (#PCDATA)>
<!ELEMENT Sta_type (#PCDATA)>
<!ELEMENT Sta_pic (#PCDATA)>

<!ELEMENT TEMPLATE (Template+)>
<!ELEMENT Template (Template,Text_font,Text_size,Text_color,Back_color,Back_pic)>
<!ATTLIST Template order CDATA #REQUIRED>
<!ELEMENT Template (#PCDATA)>
<!ELEMENT Text_font (#PCDATA)>
<!ELEMENT Text_size (#PCDATA)>
<!ELEMENT Text_color (#PCDATA)>
<!ELEMENT Back_color (#PCDATA)>
<!ELEMENT Back_pic (#PCDATA)>

<!ELEMENT VENDOR (Vendor+)>
<!ELEMENT Vendor (Ven_name,Ven_info,Ven_addr,Ven_x,Ven_y,Ven_listitems+,Ven_listlocality+)>
<!ATTLIST Vendor order CDATA #REQUIRED>
<!ELEMENT Ven_name (#PCDATA)>
<!ELEMENT Ven_info (#PCDATA)>
<!ELEMENT Ven_addr (#PCDATA)>
<!ELEMENT Ven_x (#PCDATA)>
<!ELEMENT Ven_y (#PCDATA)>
<!ELEMENT Ven_listitems (#PCDATA)>
<!ELEMENT Ven_listlocality (#PCDATA)>

<!ELEMENT VENDOR_LOCALITY (Vendor_Locality+)>
<!ELEMENT Vendor_Locality (Ven_name,Loc_name)>
<!ATTLIST Vendor_Locality order CDATA #REQUIRED>
<!ELEMENT Ven_name (#PCDATA)>
<!ELEMENT Loc_name (#PCDATA)>


