#############################################
# Configuration for IsagNIDS Ver 1.001Alpha #
#############################################
[Sniffer]

# libpcap filter defaults to: pass only packet 
# that have network address same as your network address
# Example "tcp dst port 21"
pcap_filter = "dst net 161.246";

[Report]

# Generate report to terminal screen 
# 1 = generate report ; 0 = not 
report_screen = 1;

# Generate report to html format 
# 1 = generate report ; 0 = not 
report_html = 1;
www_directory = "/www/htdocs/nids";

# Generate report to syslog system API 
# 1 = generate report ; 0 = not 
report_syslog = 1;

# Generate report to log file 
# 1 = generate report ; 0 = not 
report_logfile = 1;
log_dir = "/var/log/isagnids.log";
#log_file =  "isagnids.log";

[Signature Detect]

# Signature file of Signature Class 
# look like rule file
signature_file = "/home/may/project/signature.txt";

[Scan port Detect]

# Time between 2 packets
# in Sec
scan_ttl = 15;

# Maximum packet that alert attack
scan_max_count =  30;

[flood Detect]

# Time between 2 packets
# in Sec
flood_ttl =  6;

# Maximum packet that alert attack
flood_max_count =  300;

