.TH IsagNids

.SH NAME
IsagNids \ - ISAG's Network Intrusion Detection System for Unix

.SH SYNOPSIS
.B IsagNids
[\ -option ...]
[\ -option ...]  ...

.SH DESCRIPTION
.PP
\fIIsagNids\fP is a complete application that useful for detect Denial of
.PP
Services Attack using TCP/IP protocol stack, port scaning and some exploit
.PP
on application layer.

.PP
It was written for system administrator to analyze their network.

.SH Config
.PP
Before using, please check IsagNids.conf in /etc/
.PP
This is a configuration file and should be re-config to fit your system.

.SH OPTIONS
.PP
You can choose:
.PP
-h	Help
.PP
-v	print packet information
.PP
-r	realtime analyze
.PP
	then choose these options :
.PP
	-b	run in background process (daemon)
.PP
	-q	no result display on screen
.PP
	-i	choose which network interface to use
.PP
	        default : first interface that is detect by program 
.PP
	-l	limit number of packet to capture
.PP

.SH RESOURCES
.PP
IsagNids developed in Linux operating system using C++ on UNIX. 
.PP
In order to run program, you will need Pcap Library installed on 
.PP
your system first.
.PP
Your memory has to larger than 400 KB and your storage has to larger 
.PP
than 63 KB
.PP
(only the programs, not include the storage for keeping any log files).
.PP
.SH COPYRIGHT
IsagNids (ISAG's Network Intrusion Detection System for UNIX)

Copyright (C) 2002, Mr. Apichon Witayungkurn and Ms. Angsana Wongratanavijit,
Information Security Advisory Group (ISAG), under authority of Computer
Engineering of King Mongkut's Institute of Technology (KMITL), Thailand.
All rights reserved.

.SH BUGS
-- to be found in future

.SH DISCLAIMER
The software developers and NECTEC absolutely have no responsibility in
any damage or error due to the use of this software you may obtain from
anywhere.

.SH AUTHOR
Mr. Apichon Witayungkurn and Ms. Angsana Wongratanavijit
members of Information Secerity Advisory Group (ISAG)
in Computer Engineering Department, King Mongkut's Institute of
Technology Ladkrabang (KMITL), Thailand
