<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=">
</head>

<body bgcolor="#FFFFFF" text="#000000">
<table width="606" border="0" cellspacing="0" cellpadding="0" height="870">
  <tr> 
    <td><img src="images/WELCOME.gif" width="107" height="25"></td>
  </tr>
  <tr> 
    <td> 
      <table width="98%" border="1" cellspacing="0" cellpadding="1" height="87%">
        <tr> 
          <td bordercolor="#000000" bgcolor="#000099" height="276"> <br>
            <table width="97%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td width="23%" height="143"> 
                  <div align="center"><img src="images/finger.gif" width="99" height="114"></div>
                </td>
                <td width="77%" height="143"><font face="Microsoft Sans Serif" size="-1" color="#FFFFFF">&gt;&gt; 
                  ขอต้อนรับเข้าสู่ THAICATALOG.COM<br>
                  <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;บลูเวฟ 
                  อี-เทรด จำกัดคือห้างสรรพสินค้าอุตสาหกรรมเพื่อธุรกิจ ซื้อขาย 
                  แลกเปลี่ยน ผ่านทางระบบอินเตอร์เน็ต บลูเวฟ อี-เทรด จำกัด คือหนึ่งเดียว 
                  ซึ่งมีความพร้อม ที่จะตอบสนอง ต่อความต้องการ ของภาคอุตสาหกรรม 
                  ในทุกขั้นตอน ของการผลิต ทั้งวัตถุดิบเคมี อะไหล่ซ่อมบำรุง<br>
                  เครื่องจักร พลังงานเชื้อเพลิง สินค้าแปรรูปอิเล็คทรอนิกส์ และเยื่อกระดาษบรรจุภัณฑ์ 
                  ทั้งหมดกว่า 13,700 รายการ<br>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;บลูเวฟ 
                  อี-เทรด จำกัดพร้อมแล้วที่จะก้าวเข้ามา เป็นผู้ช่วยในการ ดำเนินธุรกิจ 
                  ด้วยความรู้ ความเข้าใจ ในกลไกราคาสินค้าอุตสาหกรรม และระบบจัดซื้อจัดจำหน่าย 
                  แบบธุรกิจ สู่ ธุรกิจ หรือ<br>
                  ที่เราเรียกว่า B2B อย่างแท้จริง ผสานเข้ากับ เทคโนโลยีอันทันสมัย 
                  ซึ่งสามารถช่วยในการ ค้นหา และ เชื่อมโยง ผู้ซื้อ กับผู้ขายเข้าถึงกันได้อย่างรวดเร็ว 
                  และมีประสิทธิภาพ บลูเวฟ อี-เทรด จำกัด จึงสามารถลดงานเอกสาร และ 
                  ความสิ้นเปลือง ในการจัดซื้อ จัดจำหน่าย ได้เพียงแค่ปลายนิ้วสัมผัส</font></td>
              </tr>
            </table>
            <br>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr> 
    <td>&nbsp;</td>
  </tr>
  <tr> 
    <td><img src="images/Registration.gif" width="107" height="25"></td>
  </tr>
  <tr> 
    <td> 
      <table width="98%" border="1" cellspacing="0" cellpadding="1" height="18%">
        <tr> 
          <td bordercolor="#000000" bgcolor="#000099" height="158"> 
            <table width="97%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td width="23%" height="113"> 
                  <table width="76%" border="0" cellspacing="0" cellpadding="0" align="center">
                    <tr> 
                      <td width="99" height="13" bgcolor="#DF0070"><font color="#FFFFFF" size="-1"><b>&nbsp;ผู้ซื้อ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;258</b></font></td>
                    </tr>
                    <tr> 
                      <td width="99" height="13"><font color="#FFFFFF" size="-1">&nbsp;online&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;12</font></td>
                    </tr>
                    <tr> 
                      <td width="99" height="13"><font color="#FFFFFF" size="-1">&nbsp;offline&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;246</font></td>
                    </tr>
                    <tr> 
                      <td width="99" height="13" bgcolor="#DF0070"><font color="#FFFFFF" size="-1"><b>&nbsp;ผู้ขาย&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;247</b></font></td>
                    </tr>
                    <tr> 
                      <td width="99" height="13"><font color="#FFFFFF" size="-1">&nbsp;online&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                        &nbsp;&nbsp;77</font></td>
                    </tr>
                    <tr> 
                      <td width="99" height="13"><font color="#FFFFFF" size="-1">&nbsp;offline&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;170</font></td>
                    </tr>
                  </table>
                </td>
                <td width="77%" height="113"><font face="Microsoft Sans Serif" size="-1" color="#FFFFFF">&gt;&gt;สมัครเป็นสมาชิกวันนี้รับสิทธิพิเศษมากมาย<br>
                  <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                  รีบสมัครก่อน 31 พฤษภาคม นี้ ท่านจะได้รับสิทธิ์พิเศษมากมายบลูเวฟ 
                  อี-เทรด จำกัด<br>
                  ขอเรียนเชิญท่านผู้สนใจสมัคร เข้าเป็น สมาชิกกับทางเวบไซต์ www.bluewaveb2b.com 
                  ห้างสรรพสินค้า และศูนย์กลางในแลกเปลี่ยน ซื้อขายสินค้า อุตสาหกรรม 
                  บนอินเตอร์เน็ต รีบสมัครก่อน 31 พฤษภาคม นี้ ท่านจะได้รับสิทธิ์ 
                  ยกเว้น ค่าธรรมเนียม แรกเข้า และไม่เก็บค่าสมาชิก รายเดือน จนถึงสิ้นปี</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td>&nbsp;</td>
  </tr>
  <tr> 
    <td>&nbsp;</td>
  </tr>
  <tr> 
    <td><img src="images/Service.gif" width="107" height="25"></td>
  </tr>
  <tr> 
    <td> 
      <table width="98%" border="1" cellspacing="0" cellpadding="0">
        <tr> 
          <td height="224" bordercolor="#000000" bgcolor="#000099"> 
            <table width="97%" border="0" cellspacing="0" cellpadding="0" height="178">
              <tr> 
                <td width="23%" height="217"> 
                  <div align="center"><img src="images/Pic1.jpg" width="99" height="66"><br>
                    <br>
                    <img src="images/pic2.jpg" width="99" height="69"> </div>
                </td>
                <td width="77%" height="217"><font face="Microsoft Sans Serif" size="-1" color="#FFFFFF">&gt;&gt; 
                  ดำเนินงานฉับไวด้วยเอกสารอิเล็คทรอนิกส์<br>
                  <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;บลูเวฟ 
                  อี-เทรด จำกัด มุ่งเน้นไปที่การพัฒนาระบบเอกสารของ เว็ป ให้สอดคล้องกับ 
                  ระบบการทำงานเดิม ของบริษัทอุตสาหกรรมไทย ในทุกขั้นตอน www.bluewaveb2b.com 
                  สามารถประมวลผล และ ตอบสนอง ต่อคำสั่งซื้อของสมาชิก ได้โดยอัตโนมัติจากหน้าเวบ 
                  ในรูปของ eCatalogs, eSale Process, eP/O, eD/O ตามลำดับ จนเสร็จสิ้นกระบวนการซื้อขาย 
                  ได้อย่างแม่นยำ ภายใต้มาตรฐาน ของการส่งข้อมูล ในแบบ EDI (Electronic 
                  Data Interchange)<br>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;บริการใหม่ล่าสุดของ 
                  www.bluewaveb2b.com อยู่ในส่วนของ พื้นที่ Marketplace ซึ่งมีชื่อ 
                  เวบไซต์ อย่างเป็นทางการว่า marketplace.bluewaveb2b.com ได้ถูกจัดทำมาเพื่อ 
                  เป็นสื่อกลาง ในการรับฝาก และประกาศข้อมูลที่เกี่ยวข้องกับ ความต้องการซื้อ 
                  หรือขายสินค้าอุตสาหกรรม ทุกประเภท รวมไปถึงธุรกิจบริการ ระหว่างบริษัทถึงบริษัท 
                  โดยไม่มีการคิดค่า transactionใดๆทั้งสิ้น </font> </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td>&nbsp;</td>
  </tr>
</table>
</body>
</html>
