<!-- DTD for libraryinfo XML document -->

<!ELEMENT libraryinfo (title,engtitle,picture,description,info*) >
<!ATTLIST libraryinfo type CDATA #REQUIRED >
<!ATTLIST libraryinfo engname CDATA #REQUIRED >
<!ATTLIST libraryinfo thainame CDATA #REQUIRED >

	<!ELEMENT title (#PCDATA) >
		<!ATTLIST title meaning CDATA #REQUIRED >
	<!ELEMENT engtitle (#PCDATA) >
		<!ATTLIST engtitle meaning CDATA #REQUIRED >
	
	<!ELEMENT picture (atl,src,linkto,width,height) >
	<!ATTLIST picture meaning CDATA #REQUIRED >
		
		<!ELEMENT atl (#PCDATA) >
			<!ATTLIST atl meaning CDATA #REQUIRED >
		<!ELEMENT src (#PCDATA) >
			<!ATTLIST src meaning CDATA #REQUIRED >
		<!ELEMENT linkto (#PCDATA) >
			<!ATTLIST linkto meaning CDATA #REQUIRED >
		<!ELEMENT width (#PCDATA) >
		<!ELEMENT height (#PCDATA) >
	
	<!ELEMENT description (#PCDATA) >
		<!ATTLIST description meaning CDATA #REQUIRED >
	
	<!ELEMENT info (#PCDATA) >
	<!ATTLIST info about CDATA #IMPLIED >
	<!ATTLIST info meaning CDATA #REQUIRED >