<!-- DTD for rule XML document -->

<!ELEMENT rule (headline,maintitle,maindescription,data,signature)>
		<!ELEMENT headline (#PCDATA)>
		<!ELEMENT maintitle (#PCDATA)>
		<!ELEMENT maindescription (#PCDATA)>
		<!ELEMENT data (category*)>
			<!ELEMENT category (order,subject,description)>
			<!ATTLIST category order CDATA #REQUIRED>
				<!ELEMENT order (#PCDATA)>
				<!ELEMENT subject (#PCDATA)>
				<!ELEMENT description (item*)>
					<!ELEMENT item (#PCDATA)>
		<!ELEMENT signature (at,by,position)>
				<!ELEMENT at (#PCDATA)>
				<!ELEMENT by (#PCDATA)>
				<!ELEMENT position (#PCDATA)>