<!ELEMENT Invoice (SELLER*)>
<!ATTLIST Invoice
	Status CDATA ""
>
<!ELEMENT SELLER (InvoiceID, PONO, Line, NetAmount, VAT, TotalPrice, DueDate)>
<!ELEMENT InvoiceID (#PCDATA)>
<!ATTLIST InvoiceID
	xmlns: CDATA #FIXED ""
>
<!ELEMENT PONO (#PCDATA)>
<!ATTLIST PONO
	xmlns: CDATA #FIXED ""
>
<!ELEMENT Line (#PCDATA)>
<!ATTLIST Line
	xmlns: CDATA #FIXED ""
>
<!ELEMENT NetAmount (#PCDATA)>
<!ATTLIST NetAmount
	xmlns: CDATA #FIXED ""
>
<!ELEMENT VAT (#PCDATA)>
<!ATTLIST VAT
	xmlns: CDATA #FIXED ""
>
<!ELEMENT TotalPrice (#PCDATA)>
<!ATTLIST TotalPrice
	xmlns: CDATA #FIXED ""
>
<!ELEMENT DueDate (#PCDATA)>
<!ATTLIST DueDate
	xmlns: CDATA #FIXED ""
>
