<!ELEMENT PR (MARKET*)>
<!ATTLIST PR
	Status CDATA ""
>
<!ELEMENT MARKET (PRID, SellerID, BizName, PRFullDate, PRTerm, PRAddress, PRShipPrice, PRItemPrice, Line, OrderName, OrderSellerItemID, OrderUnit, OrderQTY, OrderItemPrice, OrderShipPrice, needDate, ShipMethod)>
<!ELEMENT PRID (#PCDATA)>
<!ELEMENT SellerID (#PCDATA)>
<!ELEMENT BizName (#PCDATA)>
<!ELEMENT PRFullDate (#PCDATA)>
<!ELEMENT PRTerm (#PCDATA)>
<!ELEMENT PRAddress (#PCDATA)>
<!ELEMENT PRShipPrice (#PCDATA)>
<!ELEMENT PRItemPrice (#PCDATA)>
<!ELEMENT Line (#PCDATA)>
<!ELEMENT OrderName (#PCDATA)>
<!ELEMENT OrderSellerItemID (#PCDATA)>
<!ELEMENT OrderUnit (#PCDATA)>
<!ELEMENT OrderQTY (#PCDATA)>
<!ELEMENT OrderItemPrice (#PCDATA)>
<!ELEMENT OrderShipPrice (#PCDATA)>
<!ELEMENT needDate (#PCDATA)>
<!ELEMENT ShipMethod (#PCDATA)>
