//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Winmain.rc
//
#define IDI_MAIN                        101
#define IDI_SMALL                       102
#define IDD_DIALOG                      103
#define IDD_DEVICE                      104
#define IDR_SKIN4                       116
#define IDC_LIST                        1000
#define IDC_EDIT                        1001
#define IDDEVICE                        1002
#define IDBACK                          1003
#define IDC_ADAPTERS_NAME               1004
#define IDC_ADAPTERS_SUMMERY            1005
#define IDC_MODE                        1006
#define IDC_FORMAT                      1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
