//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace PeopleApp {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dependentDataset : DataSet {
        
        private DEPENDENTDataTable tableDEPENDENT;
        
        public dependentDataset() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dependentDataset(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["DEPENDENT"] != null)) {
                    this.Tables.Add(new DEPENDENTDataTable(ds.Tables["DEPENDENT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DEPENDENTDataTable DEPENDENT {
            get {
                return this.tableDEPENDENT;
            }
        }
        
        public override DataSet Clone() {
            dependentDataset cln = ((dependentDataset)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["DEPENDENT"] != null)) {
                this.Tables.Add(new DEPENDENTDataTable(ds.Tables["DEPENDENT"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableDEPENDENT = ((DEPENDENTDataTable)(this.Tables["DEPENDENT"]));
            if ((this.tableDEPENDENT != null)) {
                this.tableDEPENDENT.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dependentDataset";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dependentDataset.xsd";
            this.Locale = new System.Globalization.CultureInfo("th-TH");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableDEPENDENT = new DEPENDENTDataTable();
            this.Tables.Add(this.tableDEPENDENT);
        }
        
        private bool ShouldSerializeDEPENDENT() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void DEPENDENTRowChangeEventHandler(object sender, DEPENDENTRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class DEPENDENTDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnPID;
            
            private DataColumn columnFPID;
            
            private DataColumn columnMPID;
            
            private DataColumn columnPID_SELECT;
            
            private DataColumn columnFLAG;
            
            internal DEPENDENTDataTable() : 
                    base("DEPENDENT") {
                this.InitClass();
            }
            
            internal DEPENDENTDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn PIDColumn {
                get {
                    return this.columnPID;
                }
            }
            
            internal DataColumn FPIDColumn {
                get {
                    return this.columnFPID;
                }
            }
            
            internal DataColumn MPIDColumn {
                get {
                    return this.columnMPID;
                }
            }
            
            internal DataColumn PID_SELECTColumn {
                get {
                    return this.columnPID_SELECT;
                }
            }
            
            internal DataColumn FLAGColumn {
                get {
                    return this.columnFLAG;
                }
            }
            
            public DEPENDENTRow this[int index] {
                get {
                    return ((DEPENDENTRow)(this.Rows[index]));
                }
            }
            
            public event DEPENDENTRowChangeEventHandler DEPENDENTRowChanged;
            
            public event DEPENDENTRowChangeEventHandler DEPENDENTRowChanging;
            
            public event DEPENDENTRowChangeEventHandler DEPENDENTRowDeleted;
            
            public event DEPENDENTRowChangeEventHandler DEPENDENTRowDeleting;
            
            public void AddDEPENDENTRow(DEPENDENTRow row) {
                this.Rows.Add(row);
            }
            
            public DEPENDENTRow AddDEPENDENTRow(string PID, string FPID, string MPID, string PID_SELECT, string FLAG) {
                DEPENDENTRow rowDEPENDENTRow = ((DEPENDENTRow)(this.NewRow()));
                rowDEPENDENTRow.ItemArray = new object[] {
                        PID,
                        FPID,
                        MPID,
                        PID_SELECT,
                        FLAG};
                this.Rows.Add(rowDEPENDENTRow);
                return rowDEPENDENTRow;
            }
            
            public DEPENDENTRow FindByPID(string PID) {
                return ((DEPENDENTRow)(this.Rows.Find(new object[] {
                            PID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                DEPENDENTDataTable cln = ((DEPENDENTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new DEPENDENTDataTable();
            }
            
            internal void InitVars() {
                this.columnPID = this.Columns["PID"];
                this.columnFPID = this.Columns["FPID"];
                this.columnMPID = this.Columns["MPID"];
                this.columnPID_SELECT = this.Columns["PID_SELECT"];
                this.columnFLAG = this.Columns["FLAG"];
            }
            
            private void InitClass() {
                this.columnPID = new DataColumn("PID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPID);
                this.columnFPID = new DataColumn("FPID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFPID);
                this.columnMPID = new DataColumn("MPID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMPID);
                this.columnPID_SELECT = new DataColumn("PID_SELECT", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPID_SELECT);
                this.columnFLAG = new DataColumn("FLAG", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFLAG);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnPID}, true));
                this.columnPID.AllowDBNull = false;
                this.columnPID.Unique = true;
            }
            
            public DEPENDENTRow NewDEPENDENTRow() {
                return ((DEPENDENTRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new DEPENDENTRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(DEPENDENTRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DEPENDENTRowChanged != null)) {
                    this.DEPENDENTRowChanged(this, new DEPENDENTRowChangeEvent(((DEPENDENTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DEPENDENTRowChanging != null)) {
                    this.DEPENDENTRowChanging(this, new DEPENDENTRowChangeEvent(((DEPENDENTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DEPENDENTRowDeleted != null)) {
                    this.DEPENDENTRowDeleted(this, new DEPENDENTRowChangeEvent(((DEPENDENTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DEPENDENTRowDeleting != null)) {
                    this.DEPENDENTRowDeleting(this, new DEPENDENTRowChangeEvent(((DEPENDENTRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveDEPENDENTRow(DEPENDENTRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class DEPENDENTRow : DataRow {
            
            private DEPENDENTDataTable tableDEPENDENT;
            
            internal DEPENDENTRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableDEPENDENT = ((DEPENDENTDataTable)(this.Table));
            }
            
            public string PID {
                get {
                    return ((string)(this[this.tableDEPENDENT.PIDColumn]));
                }
                set {
                    this[this.tableDEPENDENT.PIDColumn] = value;
                }
            }
            
            public string FPID {
                get {
                    try {
                        return ((string)(this[this.tableDEPENDENT.FPIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDEPENDENT.FPIDColumn] = value;
                }
            }
            
            public string MPID {
                get {
                    try {
                        return ((string)(this[this.tableDEPENDENT.MPIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDEPENDENT.MPIDColumn] = value;
                }
            }
            
            public string PID_SELECT {
                get {
                    try {
                        return ((string)(this[this.tableDEPENDENT.PID_SELECTColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDEPENDENT.PID_SELECTColumn] = value;
                }
            }
            
            public string FLAG {
                get {
                    try {
                        return ((string)(this[this.tableDEPENDENT.FLAGColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDEPENDENT.FLAGColumn] = value;
                }
            }
            
            public bool IsFPIDNull() {
                return this.IsNull(this.tableDEPENDENT.FPIDColumn);
            }
            
            public void SetFPIDNull() {
                this[this.tableDEPENDENT.FPIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsMPIDNull() {
                return this.IsNull(this.tableDEPENDENT.MPIDColumn);
            }
            
            public void SetMPIDNull() {
                this[this.tableDEPENDENT.MPIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsPID_SELECTNull() {
                return this.IsNull(this.tableDEPENDENT.PID_SELECTColumn);
            }
            
            public void SetPID_SELECTNull() {
                this[this.tableDEPENDENT.PID_SELECTColumn] = System.Convert.DBNull;
            }
            
            public bool IsFLAGNull() {
                return this.IsNull(this.tableDEPENDENT.FLAGColumn);
            }
            
            public void SetFLAGNull() {
                this[this.tableDEPENDENT.FLAGColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class DEPENDENTRowChangeEvent : EventArgs {
            
            private DEPENDENTRow eventRow;
            
            private DataRowAction eventAction;
            
            public DEPENDENTRowChangeEvent(DEPENDENTRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public DEPENDENTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
