//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace PeopleApp {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class updateOfficeDataset : DataSet {
        
        private UPDATE_OFFICEDataTable tableUPDATE_OFFICE;
        
        public updateOfficeDataset() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected updateOfficeDataset(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["UPDATE_OFFICE"] != null)) {
                    this.Tables.Add(new UPDATE_OFFICEDataTable(ds.Tables["UPDATE_OFFICE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public UPDATE_OFFICEDataTable UPDATE_OFFICE {
            get {
                return this.tableUPDATE_OFFICE;
            }
        }
        
        public override DataSet Clone() {
            updateOfficeDataset cln = ((updateOfficeDataset)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["UPDATE_OFFICE"] != null)) {
                this.Tables.Add(new UPDATE_OFFICEDataTable(ds.Tables["UPDATE_OFFICE"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableUPDATE_OFFICE = ((UPDATE_OFFICEDataTable)(this.Tables["UPDATE_OFFICE"]));
            if ((this.tableUPDATE_OFFICE != null)) {
                this.tableUPDATE_OFFICE.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "updateOfficeDataset";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/updateOfficeDataset.xsd";
            this.Locale = new System.Globalization.CultureInfo("th-TH");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableUPDATE_OFFICE = new UPDATE_OFFICEDataTable();
            this.Tables.Add(this.tableUPDATE_OFFICE);
        }
        
        private bool ShouldSerializeUPDATE_OFFICE() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void UPDATE_OFFICERowChangeEventHandler(object sender, UPDATE_OFFICERowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UPDATE_OFFICEDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnPID;
            
            private DataColumn columnDATE;
            
            internal UPDATE_OFFICEDataTable() : 
                    base("UPDATE_OFFICE") {
                this.InitClass();
            }
            
            internal UPDATE_OFFICEDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn PIDColumn {
                get {
                    return this.columnPID;
                }
            }
            
            internal DataColumn DATEColumn {
                get {
                    return this.columnDATE;
                }
            }
            
            public UPDATE_OFFICERow this[int index] {
                get {
                    return ((UPDATE_OFFICERow)(this.Rows[index]));
                }
            }
            
            public event UPDATE_OFFICERowChangeEventHandler UPDATE_OFFICERowChanged;
            
            public event UPDATE_OFFICERowChangeEventHandler UPDATE_OFFICERowChanging;
            
            public event UPDATE_OFFICERowChangeEventHandler UPDATE_OFFICERowDeleted;
            
            public event UPDATE_OFFICERowChangeEventHandler UPDATE_OFFICERowDeleting;
            
            public void AddUPDATE_OFFICERow(UPDATE_OFFICERow row) {
                this.Rows.Add(row);
            }
            
            public UPDATE_OFFICERow AddUPDATE_OFFICERow(string PID, string DATE) {
                UPDATE_OFFICERow rowUPDATE_OFFICERow = ((UPDATE_OFFICERow)(this.NewRow()));
                rowUPDATE_OFFICERow.ItemArray = new object[] {
                        PID,
                        DATE};
                this.Rows.Add(rowUPDATE_OFFICERow);
                return rowUPDATE_OFFICERow;
            }
            
            public UPDATE_OFFICERow FindByPIDDATE(string PID, string DATE) {
                return ((UPDATE_OFFICERow)(this.Rows.Find(new object[] {
                            PID,
                            DATE})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                UPDATE_OFFICEDataTable cln = ((UPDATE_OFFICEDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new UPDATE_OFFICEDataTable();
            }
            
            internal void InitVars() {
                this.columnPID = this.Columns["PID"];
                this.columnDATE = this.Columns["DATE"];
            }
            
            private void InitClass() {
                this.columnPID = new DataColumn("PID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPID);
                this.columnDATE = new DataColumn("DATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDATE);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnPID,
                                this.columnDATE}, true));
                this.columnPID.AllowDBNull = false;
                this.columnDATE.AllowDBNull = false;
            }
            
            public UPDATE_OFFICERow NewUPDATE_OFFICERow() {
                return ((UPDATE_OFFICERow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new UPDATE_OFFICERow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(UPDATE_OFFICERow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.UPDATE_OFFICERowChanged != null)) {
                    this.UPDATE_OFFICERowChanged(this, new UPDATE_OFFICERowChangeEvent(((UPDATE_OFFICERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.UPDATE_OFFICERowChanging != null)) {
                    this.UPDATE_OFFICERowChanging(this, new UPDATE_OFFICERowChangeEvent(((UPDATE_OFFICERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.UPDATE_OFFICERowDeleted != null)) {
                    this.UPDATE_OFFICERowDeleted(this, new UPDATE_OFFICERowChangeEvent(((UPDATE_OFFICERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.UPDATE_OFFICERowDeleting != null)) {
                    this.UPDATE_OFFICERowDeleting(this, new UPDATE_OFFICERowChangeEvent(((UPDATE_OFFICERow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveUPDATE_OFFICERow(UPDATE_OFFICERow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UPDATE_OFFICERow : DataRow {
            
            private UPDATE_OFFICEDataTable tableUPDATE_OFFICE;
            
            internal UPDATE_OFFICERow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableUPDATE_OFFICE = ((UPDATE_OFFICEDataTable)(this.Table));
            }
            
            public string PID {
                get {
                    return ((string)(this[this.tableUPDATE_OFFICE.PIDColumn]));
                }
                set {
                    this[this.tableUPDATE_OFFICE.PIDColumn] = value;
                }
            }
            
            public string DATE {
                get {
                    return ((string)(this[this.tableUPDATE_OFFICE.DATEColumn]));
                }
                set {
                    this[this.tableUPDATE_OFFICE.DATEColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UPDATE_OFFICERowChangeEvent : EventArgs {
            
            private UPDATE_OFFICERow eventRow;
            
            private DataRowAction eventAction;
            
            public UPDATE_OFFICERowChangeEvent(UPDATE_OFFICERow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public UPDATE_OFFICERow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
