#!/bin/sh -e

test -e /usr/share/debconf/confmodule && {
	. /usr/share/debconf/confmodule
	db_version 2.0
}
db_go
chmod 600 /etc/vtund.conf
 
[ -e /usr/share/debconf/confmodule ] && db_stop

#DEBHELPER#
exit 0
