'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace SkyHighTP
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TwoPhaseWSSoap", [Namespace]:="http://tempuri.org/skyhighWS/skyhighbooking")>  _
    Public Class TwoPhaseWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/skyhighWS/TwoPhaseWS.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/skyhighWS/skyhighbooking/Booking", RequestNamespace:="http://tempuri.org/skyhighWS/skyhighbooking", ResponseNamespace:="http://tempuri.org/skyhighWS/skyhighbooking", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Booking(ByVal BookedFlightSet As System.Data.DataSet, ByVal BookedDetailsString As String) As Boolean
            Dim results() As Object = Me.Invoke("Booking", New Object() {BookedFlightSet, BookedDetailsString})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginBooking(ByVal BookedFlightSet As System.Data.DataSet, ByVal BookedDetailsString As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Booking", New Object() {BookedFlightSet, BookedDetailsString}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndBooking(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/skyhighWS/skyhighbooking/Cancel", RequestNamespace:="http://tempuri.org/skyhighWS/skyhighbooking", ResponseNamespace:="http://tempuri.org/skyhighWS/skyhighbooking", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Cancel(ByVal BookRef As String, ByVal CancelType As String, ByVal Reason As String) As Boolean
            Dim results() As Object = Me.Invoke("Cancel", New Object() {BookRef, CancelType, Reason})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginCancel(ByVal BookRef As String, ByVal CancelType As String, ByVal Reason As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Cancel", New Object() {BookRef, CancelType, Reason}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCancel(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/skyhighWS/skyhighbooking/Changing", RequestNamespace:="http://tempuri.org/skyhighWS/skyhighbooking", ResponseNamespace:="http://tempuri.org/skyhighWS/skyhighbooking", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Changing(ByVal BookRef As String, ByVal NewBookedFlightSet As System.Data.DataSet, ByVal NewBookedDetailsString As String) As Boolean
            Dim results() As Object = Me.Invoke("Changing", New Object() {BookRef, NewBookedFlightSet, NewBookedDetailsString})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginChanging(ByVal BookRef As String, ByVal NewBookedFlightSet As System.Data.DataSet, ByVal NewBookedDetailsString As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Changing", New Object() {BookRef, NewBookedFlightSet, NewBookedDetailsString}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndChanging(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/skyhighWS/skyhighbooking/Paying", RequestNamespace:="http://tempuri.org/skyhighWS/skyhighbooking", ResponseNamespace:="http://tempuri.org/skyhighWS/skyhighbooking", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Paying(ByVal BookRef As String) As Boolean
            Dim results() As Object = Me.Invoke("Paying", New Object() {BookRef})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginPaying(ByVal BookRef As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Paying", New Object() {BookRef}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndPaying(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
    End Class
End Namespace
