#Edit IP honeywall
HONEYWALL=honeywall
#Edit snort_inline configuration path
CONF_FILE=/etc/snort_inline/snort_inline.conf
#Edit snort_inline rules path here
RULE_PATH=/etc/snort_inline/rules/
#Edit cage path here
CAGE_PATH=/home/darly/vmware/cage/
