/*
* ============================================================================
*  Name     : CBluetoothPMPExampleDocument from BluetoothPMPExampleDocument.h
*  Part of  : BluetoothPMPExample
*  Created  : 14.01.2004 by Forum Nokia
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: Nokia Corporation
* ============================================================================
*/

// INCLUDE FILES
#include "BluetoothPMPExampleDocument.h"
#include "BluetoothPMPExampleAppUi.h"


CBluetoothPMPExampleDocument* CBluetoothPMPExampleDocument::NewL(
        CEikApplication& aApp)     // CBluetoothPMPExampleApp reference
    {
    CBluetoothPMPExampleDocument* self = 
		new (ELeave) CBluetoothPMPExampleDocument( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();

    return self;
    }


// ----------------------------------------------------------------------------
// CBluetoothPMPExampleDocument::CBluetoothPMPExampleDocument(CEikApplication& 
//   aApp)
//
// constructor
// ----------------------------------------------------------------------------
CBluetoothPMPExampleDocument::CBluetoothPMPExampleDocument(
	CEikApplication& aApp): CAknDocument(aApp)    
    {
    }


// ----------------------------------------------------------------------------
// CBluetoothPMPExampleDocument::~CBluetoothPMPExampleDocument()
//
// destructor
// ----------------------------------------------------------------------------
CBluetoothPMPExampleDocument::~CBluetoothPMPExampleDocument()
    {
    }


// ----------------------------------------------------------------------------
// CBluetoothPMPExampleDocument::ConstructL()
//
// Standard EPOC 2nd phase constructor
// ----------------------------------------------------------------------------
void CBluetoothPMPExampleDocument::ConstructL()
    {
    }
    

// ----------------------------------------------------------------------------
// CBluetoothPMPExampleDocument::CreateAppUiL()
//
// constructs CBluetoothPMPExampleAppUi
// ----------------------------------------------------------------------------
CEikAppUi* CBluetoothPMPExampleDocument::CreateAppUiL()
    {
    return new (ELeave) CBluetoothPMPExampleAppUi;
    }

// End of File  
