//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SocialApp {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet2 : DataSet {
        
        private UPDATE_SOCIALDataTable tableUPDATE_SOCIAL;
        
        public DataSet2() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet2(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["UPDATE_SOCIAL"] != null)) {
                    this.Tables.Add(new UPDATE_SOCIALDataTable(ds.Tables["UPDATE_SOCIAL"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public UPDATE_SOCIALDataTable UPDATE_SOCIAL {
            get {
                return this.tableUPDATE_SOCIAL;
            }
        }
        
        public override DataSet Clone() {
            DataSet2 cln = ((DataSet2)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["UPDATE_SOCIAL"] != null)) {
                this.Tables.Add(new UPDATE_SOCIALDataTable(ds.Tables["UPDATE_SOCIAL"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableUPDATE_SOCIAL = ((UPDATE_SOCIALDataTable)(this.Tables["UPDATE_SOCIAL"]));
            if ((this.tableUPDATE_SOCIAL != null)) {
                this.tableUPDATE_SOCIAL.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet2";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet2.xsd";
            this.Locale = new System.Globalization.CultureInfo("th-TH");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableUPDATE_SOCIAL = new UPDATE_SOCIALDataTable();
            this.Tables.Add(this.tableUPDATE_SOCIAL);
        }
        
        private bool ShouldSerializeUPDATE_SOCIAL() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void UPDATE_SOCIALRowChangeEventHandler(object sender, UPDATE_SOCIALRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UPDATE_SOCIALDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnPID;
            
            private DataColumn columnDATE;
            
            private DataColumn columnCOUNTER;
            
            internal UPDATE_SOCIALDataTable() : 
                    base("UPDATE_SOCIAL") {
                this.InitClass();
            }
            
            internal UPDATE_SOCIALDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn PIDColumn {
                get {
                    return this.columnPID;
                }
            }
            
            internal DataColumn DATEColumn {
                get {
                    return this.columnDATE;
                }
            }
            
            internal DataColumn COUNTERColumn {
                get {
                    return this.columnCOUNTER;
                }
            }
            
            public UPDATE_SOCIALRow this[int index] {
                get {
                    return ((UPDATE_SOCIALRow)(this.Rows[index]));
                }
            }
            
            public event UPDATE_SOCIALRowChangeEventHandler UPDATE_SOCIALRowChanged;
            
            public event UPDATE_SOCIALRowChangeEventHandler UPDATE_SOCIALRowChanging;
            
            public event UPDATE_SOCIALRowChangeEventHandler UPDATE_SOCIALRowDeleted;
            
            public event UPDATE_SOCIALRowChangeEventHandler UPDATE_SOCIALRowDeleting;
            
            public void AddUPDATE_SOCIALRow(UPDATE_SOCIALRow row) {
                this.Rows.Add(row);
            }
            
            public UPDATE_SOCIALRow AddUPDATE_SOCIALRow(string PID, string DATE, int COUNTER) {
                UPDATE_SOCIALRow rowUPDATE_SOCIALRow = ((UPDATE_SOCIALRow)(this.NewRow()));
                rowUPDATE_SOCIALRow.ItemArray = new object[] {
                        PID,
                        DATE,
                        COUNTER};
                this.Rows.Add(rowUPDATE_SOCIALRow);
                return rowUPDATE_SOCIALRow;
            }
            
            public UPDATE_SOCIALRow FindByPIDDATE(string PID, string DATE) {
                return ((UPDATE_SOCIALRow)(this.Rows.Find(new object[] {
                            PID,
                            DATE})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                UPDATE_SOCIALDataTable cln = ((UPDATE_SOCIALDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new UPDATE_SOCIALDataTable();
            }
            
            internal void InitVars() {
                this.columnPID = this.Columns["PID"];
                this.columnDATE = this.Columns["DATE"];
                this.columnCOUNTER = this.Columns["COUNTER"];
            }
            
            private void InitClass() {
                this.columnPID = new DataColumn("PID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPID);
                this.columnDATE = new DataColumn("DATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDATE);
                this.columnCOUNTER = new DataColumn("COUNTER", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCOUNTER);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnPID,
                                this.columnDATE}, true));
                this.columnPID.AllowDBNull = false;
                this.columnDATE.AllowDBNull = false;
            }
            
            public UPDATE_SOCIALRow NewUPDATE_SOCIALRow() {
                return ((UPDATE_SOCIALRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new UPDATE_SOCIALRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(UPDATE_SOCIALRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.UPDATE_SOCIALRowChanged != null)) {
                    this.UPDATE_SOCIALRowChanged(this, new UPDATE_SOCIALRowChangeEvent(((UPDATE_SOCIALRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.UPDATE_SOCIALRowChanging != null)) {
                    this.UPDATE_SOCIALRowChanging(this, new UPDATE_SOCIALRowChangeEvent(((UPDATE_SOCIALRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.UPDATE_SOCIALRowDeleted != null)) {
                    this.UPDATE_SOCIALRowDeleted(this, new UPDATE_SOCIALRowChangeEvent(((UPDATE_SOCIALRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.UPDATE_SOCIALRowDeleting != null)) {
                    this.UPDATE_SOCIALRowDeleting(this, new UPDATE_SOCIALRowChangeEvent(((UPDATE_SOCIALRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveUPDATE_SOCIALRow(UPDATE_SOCIALRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UPDATE_SOCIALRow : DataRow {
            
            private UPDATE_SOCIALDataTable tableUPDATE_SOCIAL;
            
            internal UPDATE_SOCIALRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableUPDATE_SOCIAL = ((UPDATE_SOCIALDataTable)(this.Table));
            }
            
            public string PID {
                get {
                    return ((string)(this[this.tableUPDATE_SOCIAL.PIDColumn]));
                }
                set {
                    this[this.tableUPDATE_SOCIAL.PIDColumn] = value;
                }
            }
            
            public string DATE {
                get {
                    return ((string)(this[this.tableUPDATE_SOCIAL.DATEColumn]));
                }
                set {
                    this[this.tableUPDATE_SOCIAL.DATEColumn] = value;
                }
            }
            
            public int COUNTER {
                get {
                    try {
                        return ((int)(this[this.tableUPDATE_SOCIAL.COUNTERColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUPDATE_SOCIAL.COUNTERColumn] = value;
                }
            }
            
            public bool IsCOUNTERNull() {
                return this.IsNull(this.tableUPDATE_SOCIAL.COUNTERColumn);
            }
            
            public void SetCOUNTERNull() {
                this[this.tableUPDATE_SOCIAL.COUNTERColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UPDATE_SOCIALRowChangeEvent : EventArgs {
            
            private UPDATE_SOCIALRow eventRow;
            
            private DataRowAction eventAction;
            
            public UPDATE_SOCIALRowChangeEvent(UPDATE_SOCIALRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public UPDATE_SOCIALRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
