//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
// 
namespace HospitalComponent.WebReference1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://161.246.6.44/HealthyService/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryHealthy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet queryHealthy(string pid) {
            object[] results = this.Invoke("queryHealthy", new object[] {
                        pid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryHealthy(string pid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryHealthy", new object[] {
                        pid}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndqueryHealthy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registerHealthy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string registerHealthy(RegisterDataset inputData) {
            object[] results = this.Invoke("registerHealthy", new object[] {
                        inputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginregisterHealthy(RegisterDataset inputData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("registerHealthy", new object[] {
                        inputData}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndregisterHealthy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateHealthy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateHealthy(string pid, string hmain, string hsub) {
            object[] results = this.Invoke("updateHealthy", new object[] {
                        pid,
                        hmain,
                        hsub});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateHealthy(string pid, string hmain, string hsub, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateHealthy", new object[] {
                        pid,
                        hmain,
                        hsub}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndupdateHealthy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkPrivilegeAccident", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkPrivilegeAccident(string pid) {
            object[] results = this.Invoke("checkPrivilegeAccident", new object[] {
                        pid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckPrivilegeAccident(string pid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkPrivilegeAccident", new object[] {
                        pid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcheckPrivilegeAccident(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sendClearing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sendClearing(ClearingDataset datasend) {
            object[] results = this.Invoke("sendClearing", new object[] {
                        datasend});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendClearing(ClearingDataset datasend, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sendClearing", new object[] {
                        datasend}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsendClearing(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/receiveClearing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClearingDataset receiveClearing(string hnumber, string dateBill) {
            object[] results = this.Invoke("receiveClearing", new object[] {
                        hnumber,
                        dateBill});
            return ((ClearingDataset)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreceiveClearing(string hnumber, string dateBill, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("receiveClearing", new object[] {
                        hnumber,
                        dateBill}, callback, asyncState);
        }
        
        /// <remarks/>
        public ClearingDataset EndreceiveClearing(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ClearingDataset)(results[0]));
        }
    }
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class ClearingDataset : DataSet {
        
        private CLEARINGDataTable tableCLEARING;
        
        public ClearingDataset() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected ClearingDataset(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["CLEARING"] != null)) {
                    this.Tables.Add(new CLEARINGDataTable(ds.Tables["CLEARING"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CLEARINGDataTable CLEARING {
            get {
                return this.tableCLEARING;
            }
        }
        
        public override DataSet Clone() {
            ClearingDataset cln = ((ClearingDataset)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["CLEARING"] != null)) {
                this.Tables.Add(new CLEARINGDataTable(ds.Tables["CLEARING"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableCLEARING = ((CLEARINGDataTable)(this.Tables["CLEARING"]));
            if ((this.tableCLEARING != null)) {
                this.tableCLEARING.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "ClearingDataset";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/ClearingDataset.xsd";
            this.Locale = new System.Globalization.CultureInfo("th-TH");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableCLEARING = new CLEARINGDataTable();
            this.Tables.Add(this.tableCLEARING);
        }
        
        private bool ShouldSerializeCLEARING() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void CLEARINGRowChangeEventHandler(object sender, CLEARINGRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CLEARINGDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnHOSPMAIN;
            
            private DataColumn columnHOSPSUB;
            
            private DataColumn columnPID;
            
            private DataColumn columnBILL_ID;
            
            private DataColumn columnDATE_BILL;
            
            private DataColumn columnDISEASE;
            
            private DataColumn columnCOST_MEDICINE;
            
            private DataColumn columnCOST_DOCTOR;
            
            private DataColumn columnCOST_ROOM;
            
            private DataColumn columnCOST_TREAT;
            
            private DataColumn columnCOST_OTHER;
            
            private DataColumn columnCOST_SUM;
            
            internal CLEARINGDataTable() : 
                    base("CLEARING") {
                this.InitClass();
            }
            
            internal CLEARINGDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn HOSPMAINColumn {
                get {
                    return this.columnHOSPMAIN;
                }
            }
            
            internal DataColumn HOSPSUBColumn {
                get {
                    return this.columnHOSPSUB;
                }
            }
            
            internal DataColumn PIDColumn {
                get {
                    return this.columnPID;
                }
            }
            
            internal DataColumn BILL_IDColumn {
                get {
                    return this.columnBILL_ID;
                }
            }
            
            internal DataColumn DATE_BILLColumn {
                get {
                    return this.columnDATE_BILL;
                }
            }
            
            internal DataColumn DISEASEColumn {
                get {
                    return this.columnDISEASE;
                }
            }
            
            internal DataColumn COST_MEDICINEColumn {
                get {
                    return this.columnCOST_MEDICINE;
                }
            }
            
            internal DataColumn COST_DOCTORColumn {
                get {
                    return this.columnCOST_DOCTOR;
                }
            }
            
            internal DataColumn COST_ROOMColumn {
                get {
                    return this.columnCOST_ROOM;
                }
            }
            
            internal DataColumn COST_TREATColumn {
                get {
                    return this.columnCOST_TREAT;
                }
            }
            
            internal DataColumn COST_OTHERColumn {
                get {
                    return this.columnCOST_OTHER;
                }
            }
            
            internal DataColumn COST_SUMColumn {
                get {
                    return this.columnCOST_SUM;
                }
            }
            
            public CLEARINGRow this[int index] {
                get {
                    return ((CLEARINGRow)(this.Rows[index]));
                }
            }
            
            public event CLEARINGRowChangeEventHandler CLEARINGRowChanged;
            
            public event CLEARINGRowChangeEventHandler CLEARINGRowChanging;
            
            public event CLEARINGRowChangeEventHandler CLEARINGRowDeleted;
            
            public event CLEARINGRowChangeEventHandler CLEARINGRowDeleting;
            
            public void AddCLEARINGRow(CLEARINGRow row) {
                this.Rows.Add(row);
            }
            
            public CLEARINGRow AddCLEARINGRow(string HOSPMAIN, string HOSPSUB, string PID, string BILL_ID, string DATE_BILL, string DISEASE, int COST_MEDICINE, int COST_DOCTOR, int COST_ROOM, int COST_TREAT, string COST_OTHER, int COST_SUM) {
                CLEARINGRow rowCLEARINGRow = ((CLEARINGRow)(this.NewRow()));
                rowCLEARINGRow.ItemArray = new object[] {
                        HOSPMAIN,
                        HOSPSUB,
                        PID,
                        BILL_ID,
                        DATE_BILL,
                        DISEASE,
                        COST_MEDICINE,
                        COST_DOCTOR,
                        COST_ROOM,
                        COST_TREAT,
                        COST_OTHER,
                        COST_SUM};
                this.Rows.Add(rowCLEARINGRow);
                return rowCLEARINGRow;
            }
            
            public CLEARINGRow FindByHOSPMAINHOSPSUBPIDBILL_IDDATE_BILL(string HOSPMAIN, string HOSPSUB, string PID, string BILL_ID, string DATE_BILL) {
                return ((CLEARINGRow)(this.Rows.Find(new object[] {
                            HOSPMAIN,
                            HOSPSUB,
                            PID,
                            BILL_ID,
                            DATE_BILL})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                CLEARINGDataTable cln = ((CLEARINGDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new CLEARINGDataTable();
            }
            
            internal void InitVars() {
                this.columnHOSPMAIN = this.Columns["HOSPMAIN"];
                this.columnHOSPSUB = this.Columns["HOSPSUB"];
                this.columnPID = this.Columns["PID"];
                this.columnBILL_ID = this.Columns["BILL_ID"];
                this.columnDATE_BILL = this.Columns["DATE_BILL"];
                this.columnDISEASE = this.Columns["DISEASE"];
                this.columnCOST_MEDICINE = this.Columns["COST_MEDICINE"];
                this.columnCOST_DOCTOR = this.Columns["COST_DOCTOR"];
                this.columnCOST_ROOM = this.Columns["COST_ROOM"];
                this.columnCOST_TREAT = this.Columns["COST_TREAT"];
                this.columnCOST_OTHER = this.Columns["COST_OTHER"];
                this.columnCOST_SUM = this.Columns["COST_SUM"];
            }
            
            private void InitClass() {
                this.columnHOSPMAIN = new DataColumn("HOSPMAIN", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHOSPMAIN);
                this.columnHOSPSUB = new DataColumn("HOSPSUB", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHOSPSUB);
                this.columnPID = new DataColumn("PID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPID);
                this.columnBILL_ID = new DataColumn("BILL_ID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBILL_ID);
                this.columnDATE_BILL = new DataColumn("DATE_BILL", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDATE_BILL);
                this.columnDISEASE = new DataColumn("DISEASE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDISEASE);
                this.columnCOST_MEDICINE = new DataColumn("COST_MEDICINE", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCOST_MEDICINE);
                this.columnCOST_DOCTOR = new DataColumn("COST_DOCTOR", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCOST_DOCTOR);
                this.columnCOST_ROOM = new DataColumn("COST_ROOM", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCOST_ROOM);
                this.columnCOST_TREAT = new DataColumn("COST_TREAT", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCOST_TREAT);
                this.columnCOST_OTHER = new DataColumn("COST_OTHER", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCOST_OTHER);
                this.columnCOST_SUM = new DataColumn("COST_SUM", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCOST_SUM);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnHOSPMAIN,
                                this.columnHOSPSUB,
                                this.columnPID,
                                this.columnBILL_ID,
                                this.columnDATE_BILL}, true));
                this.columnHOSPMAIN.AllowDBNull = false;
                this.columnHOSPSUB.AllowDBNull = false;
                this.columnPID.AllowDBNull = false;
                this.columnBILL_ID.AllowDBNull = false;
                this.columnDATE_BILL.AllowDBNull = false;
            }
            
            public CLEARINGRow NewCLEARINGRow() {
                return ((CLEARINGRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new CLEARINGRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(CLEARINGRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CLEARINGRowChanged != null)) {
                    this.CLEARINGRowChanged(this, new CLEARINGRowChangeEvent(((CLEARINGRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CLEARINGRowChanging != null)) {
                    this.CLEARINGRowChanging(this, new CLEARINGRowChangeEvent(((CLEARINGRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CLEARINGRowDeleted != null)) {
                    this.CLEARINGRowDeleted(this, new CLEARINGRowChangeEvent(((CLEARINGRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CLEARINGRowDeleting != null)) {
                    this.CLEARINGRowDeleting(this, new CLEARINGRowChangeEvent(((CLEARINGRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveCLEARINGRow(CLEARINGRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CLEARINGRow : DataRow {
            
            private CLEARINGDataTable tableCLEARING;
            
            internal CLEARINGRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableCLEARING = ((CLEARINGDataTable)(this.Table));
            }
            
            public string HOSPMAIN {
                get {
                    return ((string)(this[this.tableCLEARING.HOSPMAINColumn]));
                }
                set {
                    this[this.tableCLEARING.HOSPMAINColumn] = value;
                }
            }
            
            public string HOSPSUB {
                get {
                    return ((string)(this[this.tableCLEARING.HOSPSUBColumn]));
                }
                set {
                    this[this.tableCLEARING.HOSPSUBColumn] = value;
                }
            }
            
            public string PID {
                get {
                    return ((string)(this[this.tableCLEARING.PIDColumn]));
                }
                set {
                    this[this.tableCLEARING.PIDColumn] = value;
                }
            }
            
            public string BILL_ID {
                get {
                    return ((string)(this[this.tableCLEARING.BILL_IDColumn]));
                }
                set {
                    this[this.tableCLEARING.BILL_IDColumn] = value;
                }
            }
            
            public string DATE_BILL {
                get {
                    return ((string)(this[this.tableCLEARING.DATE_BILLColumn]));
                }
                set {
                    this[this.tableCLEARING.DATE_BILLColumn] = value;
                }
            }
            
            public string DISEASE {
                get {
                    try {
                        return ((string)(this[this.tableCLEARING.DISEASEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCLEARING.DISEASEColumn] = value;
                }
            }
            
            public int COST_MEDICINE {
                get {
                    try {
                        return ((int)(this[this.tableCLEARING.COST_MEDICINEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCLEARING.COST_MEDICINEColumn] = value;
                }
            }
            
            public int COST_DOCTOR {
                get {
                    try {
                        return ((int)(this[this.tableCLEARING.COST_DOCTORColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCLEARING.COST_DOCTORColumn] = value;
                }
            }
            
            public int COST_ROOM {
                get {
                    try {
                        return ((int)(this[this.tableCLEARING.COST_ROOMColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCLEARING.COST_ROOMColumn] = value;
                }
            }
            
            public int COST_TREAT {
                get {
                    try {
                        return ((int)(this[this.tableCLEARING.COST_TREATColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCLEARING.COST_TREATColumn] = value;
                }
            }
            
            public string COST_OTHER {
                get {
                    try {
                        return ((string)(this[this.tableCLEARING.COST_OTHERColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCLEARING.COST_OTHERColumn] = value;
                }
            }
            
            public int COST_SUM {
                get {
                    try {
                        return ((int)(this[this.tableCLEARING.COST_SUMColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCLEARING.COST_SUMColumn] = value;
                }
            }
            
            public bool IsDISEASENull() {
                return this.IsNull(this.tableCLEARING.DISEASEColumn);
            }
            
            public void SetDISEASENull() {
                this[this.tableCLEARING.DISEASEColumn] = System.Convert.DBNull;
            }
            
            public bool IsCOST_MEDICINENull() {
                return this.IsNull(this.tableCLEARING.COST_MEDICINEColumn);
            }
            
            public void SetCOST_MEDICINENull() {
                this[this.tableCLEARING.COST_MEDICINEColumn] = System.Convert.DBNull;
            }
            
            public bool IsCOST_DOCTORNull() {
                return this.IsNull(this.tableCLEARING.COST_DOCTORColumn);
            }
            
            public void SetCOST_DOCTORNull() {
                this[this.tableCLEARING.COST_DOCTORColumn] = System.Convert.DBNull;
            }
            
            public bool IsCOST_ROOMNull() {
                return this.IsNull(this.tableCLEARING.COST_ROOMColumn);
            }
            
            public void SetCOST_ROOMNull() {
                this[this.tableCLEARING.COST_ROOMColumn] = System.Convert.DBNull;
            }
            
            public bool IsCOST_TREATNull() {
                return this.IsNull(this.tableCLEARING.COST_TREATColumn);
            }
            
            public void SetCOST_TREATNull() {
                this[this.tableCLEARING.COST_TREATColumn] = System.Convert.DBNull;
            }
            
            public bool IsCOST_OTHERNull() {
                return this.IsNull(this.tableCLEARING.COST_OTHERColumn);
            }
            
            public void SetCOST_OTHERNull() {
                this[this.tableCLEARING.COST_OTHERColumn] = System.Convert.DBNull;
            }
            
            public bool IsCOST_SUMNull() {
                return this.IsNull(this.tableCLEARING.COST_SUMColumn);
            }
            
            public void SetCOST_SUMNull() {
                this[this.tableCLEARING.COST_SUMColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CLEARINGRowChangeEvent : EventArgs {
            
            private CLEARINGRow eventRow;
            
            private DataRowAction eventAction;
            
            public CLEARINGRowChangeEvent(CLEARINGRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public CLEARINGRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class RegisterDataset : DataSet {
        
        private UCS_HEALTHYDataTable tableUCS_HEALTHY;
        
        public RegisterDataset() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected RegisterDataset(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["UCS_HEALTHY"] != null)) {
                    this.Tables.Add(new UCS_HEALTHYDataTable(ds.Tables["UCS_HEALTHY"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public UCS_HEALTHYDataTable UCS_HEALTHY {
            get {
                return this.tableUCS_HEALTHY;
            }
        }
        
        public override DataSet Clone() {
            RegisterDataset cln = ((RegisterDataset)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["UCS_HEALTHY"] != null)) {
                this.Tables.Add(new UCS_HEALTHYDataTable(ds.Tables["UCS_HEALTHY"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableUCS_HEALTHY = ((UCS_HEALTHYDataTable)(this.Tables["UCS_HEALTHY"]));
            if ((this.tableUCS_HEALTHY != null)) {
                this.tableUCS_HEALTHY.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "RegisterDataset";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/RegisterDataset.xsd";
            this.Locale = new System.Globalization.CultureInfo("th-TH");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableUCS_HEALTHY = new UCS_HEALTHYDataTable();
            this.Tables.Add(this.tableUCS_HEALTHY);
        }
        
        private bool ShouldSerializeUCS_HEALTHY() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void UCS_HEALTHYRowChangeEventHandler(object sender, UCS_HEALTHYRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UCS_HEALTHYDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnPID;
            
            private DataColumn columnPROCODE;
            
            private DataColumn columnRESULT;
            
            private DataColumn columnTITLE;
            
            private DataColumn columnFNAME;
            
            private DataColumn columnLNAME;
            
            private DataColumn columnBDATE;
            
            private DataColumn columnCARDID;
            
            private DataColumn columnINSCL;
            
            private DataColumn columnHOSPMAIN;
            
            private DataColumn columnHOSPSUB;
            
            private DataColumn columnIDATE;
            
            private DataColumn columnEDATE;
            
            private DataColumn columnSEX;
            
            private DataColumn columnNATION;
            
            private DataColumn columnOCCUPA;
            
            private DataColumn columnADDRESS;
            
            private DataColumn columnMOO;
            
            private DataColumn columnTAMBON;
            
            private DataColumn columnAMPHUR;
            
            private DataColumn columnPROVINCE;
            
            private DataColumn columnSTATUS;
            
            internal UCS_HEALTHYDataTable() : 
                    base("UCS_HEALTHY") {
                this.InitClass();
            }
            
            internal UCS_HEALTHYDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn PIDColumn {
                get {
                    return this.columnPID;
                }
            }
            
            internal DataColumn PROCODEColumn {
                get {
                    return this.columnPROCODE;
                }
            }
            
            internal DataColumn RESULTColumn {
                get {
                    return this.columnRESULT;
                }
            }
            
            internal DataColumn TITLEColumn {
                get {
                    return this.columnTITLE;
                }
            }
            
            internal DataColumn FNAMEColumn {
                get {
                    return this.columnFNAME;
                }
            }
            
            internal DataColumn LNAMEColumn {
                get {
                    return this.columnLNAME;
                }
            }
            
            internal DataColumn BDATEColumn {
                get {
                    return this.columnBDATE;
                }
            }
            
            internal DataColumn CARDIDColumn {
                get {
                    return this.columnCARDID;
                }
            }
            
            internal DataColumn INSCLColumn {
                get {
                    return this.columnINSCL;
                }
            }
            
            internal DataColumn HOSPMAINColumn {
                get {
                    return this.columnHOSPMAIN;
                }
            }
            
            internal DataColumn HOSPSUBColumn {
                get {
                    return this.columnHOSPSUB;
                }
            }
            
            internal DataColumn IDATEColumn {
                get {
                    return this.columnIDATE;
                }
            }
            
            internal DataColumn EDATEColumn {
                get {
                    return this.columnEDATE;
                }
            }
            
            internal DataColumn SEXColumn {
                get {
                    return this.columnSEX;
                }
            }
            
            internal DataColumn NATIONColumn {
                get {
                    return this.columnNATION;
                }
            }
            
            internal DataColumn OCCUPAColumn {
                get {
                    return this.columnOCCUPA;
                }
            }
            
            internal DataColumn ADDRESSColumn {
                get {
                    return this.columnADDRESS;
                }
            }
            
            internal DataColumn MOOColumn {
                get {
                    return this.columnMOO;
                }
            }
            
            internal DataColumn TAMBONColumn {
                get {
                    return this.columnTAMBON;
                }
            }
            
            internal DataColumn AMPHURColumn {
                get {
                    return this.columnAMPHUR;
                }
            }
            
            internal DataColumn PROVINCEColumn {
                get {
                    return this.columnPROVINCE;
                }
            }
            
            internal DataColumn STATUSColumn {
                get {
                    return this.columnSTATUS;
                }
            }
            
            public UCS_HEALTHYRow this[int index] {
                get {
                    return ((UCS_HEALTHYRow)(this.Rows[index]));
                }
            }
            
            public event UCS_HEALTHYRowChangeEventHandler UCS_HEALTHYRowChanged;
            
            public event UCS_HEALTHYRowChangeEventHandler UCS_HEALTHYRowChanging;
            
            public event UCS_HEALTHYRowChangeEventHandler UCS_HEALTHYRowDeleted;
            
            public event UCS_HEALTHYRowChangeEventHandler UCS_HEALTHYRowDeleting;
            
            public void AddUCS_HEALTHYRow(UCS_HEALTHYRow row) {
                this.Rows.Add(row);
            }
            
            public UCS_HEALTHYRow AddUCS_HEALTHYRow(
                        string PID, 
                        string PROCODE, 
                        string RESULT, 
                        string TITLE, 
                        string FNAME, 
                        string LNAME, 
                        string BDATE, 
                        string CARDID, 
                        string INSCL, 
                        string HOSPMAIN, 
                        string HOSPSUB, 
                        string IDATE, 
                        string EDATE, 
                        string SEX, 
                        string NATION, 
                        string OCCUPA, 
                        string ADDRESS, 
                        string MOO, 
                        string TAMBON, 
                        string AMPHUR, 
                        string PROVINCE, 
                        string STATUS) {
                UCS_HEALTHYRow rowUCS_HEALTHYRow = ((UCS_HEALTHYRow)(this.NewRow()));
                rowUCS_HEALTHYRow.ItemArray = new object[] {
                        PID,
                        PROCODE,
                        RESULT,
                        TITLE,
                        FNAME,
                        LNAME,
                        BDATE,
                        CARDID,
                        INSCL,
                        HOSPMAIN,
                        HOSPSUB,
                        IDATE,
                        EDATE,
                        SEX,
                        NATION,
                        OCCUPA,
                        ADDRESS,
                        MOO,
                        TAMBON,
                        AMPHUR,
                        PROVINCE,
                        STATUS};
                this.Rows.Add(rowUCS_HEALTHYRow);
                return rowUCS_HEALTHYRow;
            }
            
            public UCS_HEALTHYRow FindByPID(string PID) {
                return ((UCS_HEALTHYRow)(this.Rows.Find(new object[] {
                            PID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                UCS_HEALTHYDataTable cln = ((UCS_HEALTHYDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new UCS_HEALTHYDataTable();
            }
            
            internal void InitVars() {
                this.columnPID = this.Columns["PID"];
                this.columnPROCODE = this.Columns["PROCODE"];
                this.columnRESULT = this.Columns["RESULT"];
                this.columnTITLE = this.Columns["TITLE"];
                this.columnFNAME = this.Columns["FNAME"];
                this.columnLNAME = this.Columns["LNAME"];
                this.columnBDATE = this.Columns["BDATE"];
                this.columnCARDID = this.Columns["CARDID"];
                this.columnINSCL = this.Columns["INSCL"];
                this.columnHOSPMAIN = this.Columns["HOSPMAIN"];
                this.columnHOSPSUB = this.Columns["HOSPSUB"];
                this.columnIDATE = this.Columns["IDATE"];
                this.columnEDATE = this.Columns["EDATE"];
                this.columnSEX = this.Columns["SEX"];
                this.columnNATION = this.Columns["NATION"];
                this.columnOCCUPA = this.Columns["OCCUPA"];
                this.columnADDRESS = this.Columns["ADDRESS"];
                this.columnMOO = this.Columns["MOO"];
                this.columnTAMBON = this.Columns["TAMBON"];
                this.columnAMPHUR = this.Columns["AMPHUR"];
                this.columnPROVINCE = this.Columns["PROVINCE"];
                this.columnSTATUS = this.Columns["STATUS"];
            }
            
            private void InitClass() {
                this.columnPID = new DataColumn("PID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPID);
                this.columnPROCODE = new DataColumn("PROCODE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPROCODE);
                this.columnRESULT = new DataColumn("RESULT", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRESULT);
                this.columnTITLE = new DataColumn("TITLE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTITLE);
                this.columnFNAME = new DataColumn("FNAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFNAME);
                this.columnLNAME = new DataColumn("LNAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLNAME);
                this.columnBDATE = new DataColumn("BDATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBDATE);
                this.columnCARDID = new DataColumn("CARDID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCARDID);
                this.columnINSCL = new DataColumn("INSCL", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnINSCL);
                this.columnHOSPMAIN = new DataColumn("HOSPMAIN", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHOSPMAIN);
                this.columnHOSPSUB = new DataColumn("HOSPSUB", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHOSPSUB);
                this.columnIDATE = new DataColumn("IDATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIDATE);
                this.columnEDATE = new DataColumn("EDATE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEDATE);
                this.columnSEX = new DataColumn("SEX", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSEX);
                this.columnNATION = new DataColumn("NATION", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNATION);
                this.columnOCCUPA = new DataColumn("OCCUPA", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOCCUPA);
                this.columnADDRESS = new DataColumn("ADDRESS", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnADDRESS);
                this.columnMOO = new DataColumn("MOO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMOO);
                this.columnTAMBON = new DataColumn("TAMBON", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTAMBON);
                this.columnAMPHUR = new DataColumn("AMPHUR", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAMPHUR);
                this.columnPROVINCE = new DataColumn("PROVINCE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPROVINCE);
                this.columnSTATUS = new DataColumn("STATUS", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSTATUS);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnPID}, true));
                this.columnPID.AllowDBNull = false;
                this.columnPID.Unique = true;
            }
            
            public UCS_HEALTHYRow NewUCS_HEALTHYRow() {
                return ((UCS_HEALTHYRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new UCS_HEALTHYRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(UCS_HEALTHYRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.UCS_HEALTHYRowChanged != null)) {
                    this.UCS_HEALTHYRowChanged(this, new UCS_HEALTHYRowChangeEvent(((UCS_HEALTHYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.UCS_HEALTHYRowChanging != null)) {
                    this.UCS_HEALTHYRowChanging(this, new UCS_HEALTHYRowChangeEvent(((UCS_HEALTHYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.UCS_HEALTHYRowDeleted != null)) {
                    this.UCS_HEALTHYRowDeleted(this, new UCS_HEALTHYRowChangeEvent(((UCS_HEALTHYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.UCS_HEALTHYRowDeleting != null)) {
                    this.UCS_HEALTHYRowDeleting(this, new UCS_HEALTHYRowChangeEvent(((UCS_HEALTHYRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveUCS_HEALTHYRow(UCS_HEALTHYRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UCS_HEALTHYRow : DataRow {
            
            private UCS_HEALTHYDataTable tableUCS_HEALTHY;
            
            internal UCS_HEALTHYRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableUCS_HEALTHY = ((UCS_HEALTHYDataTable)(this.Table));
            }
            
            public string PID {
                get {
                    return ((string)(this[this.tableUCS_HEALTHY.PIDColumn]));
                }
                set {
                    this[this.tableUCS_HEALTHY.PIDColumn] = value;
                }
            }
            
            public string PROCODE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.PROCODEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.PROCODEColumn] = value;
                }
            }
            
            public string RESULT {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.RESULTColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.RESULTColumn] = value;
                }
            }
            
            public string TITLE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.TITLEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.TITLEColumn] = value;
                }
            }
            
            public string FNAME {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.FNAMEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.FNAMEColumn] = value;
                }
            }
            
            public string LNAME {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.LNAMEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.LNAMEColumn] = value;
                }
            }
            
            public string BDATE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.BDATEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.BDATEColumn] = value;
                }
            }
            
            public string CARDID {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.CARDIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.CARDIDColumn] = value;
                }
            }
            
            public string INSCL {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.INSCLColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.INSCLColumn] = value;
                }
            }
            
            public string HOSPMAIN {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.HOSPMAINColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.HOSPMAINColumn] = value;
                }
            }
            
            public string HOSPSUB {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.HOSPSUBColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.HOSPSUBColumn] = value;
                }
            }
            
            public string IDATE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.IDATEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.IDATEColumn] = value;
                }
            }
            
            public string EDATE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.EDATEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.EDATEColumn] = value;
                }
            }
            
            public string SEX {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.SEXColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.SEXColumn] = value;
                }
            }
            
            public string NATION {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.NATIONColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.NATIONColumn] = value;
                }
            }
            
            public string OCCUPA {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.OCCUPAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.OCCUPAColumn] = value;
                }
            }
            
            public string ADDRESS {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.ADDRESSColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.ADDRESSColumn] = value;
                }
            }
            
            public string MOO {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.MOOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.MOOColumn] = value;
                }
            }
            
            public string TAMBON {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.TAMBONColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.TAMBONColumn] = value;
                }
            }
            
            public string AMPHUR {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.AMPHURColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.AMPHURColumn] = value;
                }
            }
            
            public string PROVINCE {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.PROVINCEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.PROVINCEColumn] = value;
                }
            }
            
            public string STATUS {
                get {
                    try {
                        return ((string)(this[this.tableUCS_HEALTHY.STATUSColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUCS_HEALTHY.STATUSColumn] = value;
                }
            }
            
            public bool IsPROCODENull() {
                return this.IsNull(this.tableUCS_HEALTHY.PROCODEColumn);
            }
            
            public void SetPROCODENull() {
                this[this.tableUCS_HEALTHY.PROCODEColumn] = System.Convert.DBNull;
            }
            
            public bool IsRESULTNull() {
                return this.IsNull(this.tableUCS_HEALTHY.RESULTColumn);
            }
            
            public void SetRESULTNull() {
                this[this.tableUCS_HEALTHY.RESULTColumn] = System.Convert.DBNull;
            }
            
            public bool IsTITLENull() {
                return this.IsNull(this.tableUCS_HEALTHY.TITLEColumn);
            }
            
            public void SetTITLENull() {
                this[this.tableUCS_HEALTHY.TITLEColumn] = System.Convert.DBNull;
            }
            
            public bool IsFNAMENull() {
                return this.IsNull(this.tableUCS_HEALTHY.FNAMEColumn);
            }
            
            public void SetFNAMENull() {
                this[this.tableUCS_HEALTHY.FNAMEColumn] = System.Convert.DBNull;
            }
            
            public bool IsLNAMENull() {
                return this.IsNull(this.tableUCS_HEALTHY.LNAMEColumn);
            }
            
            public void SetLNAMENull() {
                this[this.tableUCS_HEALTHY.LNAMEColumn] = System.Convert.DBNull;
            }
            
            public bool IsBDATENull() {
                return this.IsNull(this.tableUCS_HEALTHY.BDATEColumn);
            }
            
            public void SetBDATENull() {
                this[this.tableUCS_HEALTHY.BDATEColumn] = System.Convert.DBNull;
            }
            
            public bool IsCARDIDNull() {
                return this.IsNull(this.tableUCS_HEALTHY.CARDIDColumn);
            }
            
            public void SetCARDIDNull() {
                this[this.tableUCS_HEALTHY.CARDIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsINSCLNull() {
                return this.IsNull(this.tableUCS_HEALTHY.INSCLColumn);
            }
            
            public void SetINSCLNull() {
                this[this.tableUCS_HEALTHY.INSCLColumn] = System.Convert.DBNull;
            }
            
            public bool IsHOSPMAINNull() {
                return this.IsNull(this.tableUCS_HEALTHY.HOSPMAINColumn);
            }
            
            public void SetHOSPMAINNull() {
                this[this.tableUCS_HEALTHY.HOSPMAINColumn] = System.Convert.DBNull;
            }
            
            public bool IsHOSPSUBNull() {
                return this.IsNull(this.tableUCS_HEALTHY.HOSPSUBColumn);
            }
            
            public void SetHOSPSUBNull() {
                this[this.tableUCS_HEALTHY.HOSPSUBColumn] = System.Convert.DBNull;
            }
            
            public bool IsIDATENull() {
                return this.IsNull(this.tableUCS_HEALTHY.IDATEColumn);
            }
            
            public void SetIDATENull() {
                this[this.tableUCS_HEALTHY.IDATEColumn] = System.Convert.DBNull;
            }
            
            public bool IsEDATENull() {
                return this.IsNull(this.tableUCS_HEALTHY.EDATEColumn);
            }
            
            public void SetEDATENull() {
                this[this.tableUCS_HEALTHY.EDATEColumn] = System.Convert.DBNull;
            }
            
            public bool IsSEXNull() {
                return this.IsNull(this.tableUCS_HEALTHY.SEXColumn);
            }
            
            public void SetSEXNull() {
                this[this.tableUCS_HEALTHY.SEXColumn] = System.Convert.DBNull;
            }
            
            public bool IsNATIONNull() {
                return this.IsNull(this.tableUCS_HEALTHY.NATIONColumn);
            }
            
            public void SetNATIONNull() {
                this[this.tableUCS_HEALTHY.NATIONColumn] = System.Convert.DBNull;
            }
            
            public bool IsOCCUPANull() {
                return this.IsNull(this.tableUCS_HEALTHY.OCCUPAColumn);
            }
            
            public void SetOCCUPANull() {
                this[this.tableUCS_HEALTHY.OCCUPAColumn] = System.Convert.DBNull;
            }
            
            public bool IsADDRESSNull() {
                return this.IsNull(this.tableUCS_HEALTHY.ADDRESSColumn);
            }
            
            public void SetADDRESSNull() {
                this[this.tableUCS_HEALTHY.ADDRESSColumn] = System.Convert.DBNull;
            }
            
            public bool IsMOONull() {
                return this.IsNull(this.tableUCS_HEALTHY.MOOColumn);
            }
            
            public void SetMOONull() {
                this[this.tableUCS_HEALTHY.MOOColumn] = System.Convert.DBNull;
            }
            
            public bool IsTAMBONNull() {
                return this.IsNull(this.tableUCS_HEALTHY.TAMBONColumn);
            }
            
            public void SetTAMBONNull() {
                this[this.tableUCS_HEALTHY.TAMBONColumn] = System.Convert.DBNull;
            }
            
            public bool IsAMPHURNull() {
                return this.IsNull(this.tableUCS_HEALTHY.AMPHURColumn);
            }
            
            public void SetAMPHURNull() {
                this[this.tableUCS_HEALTHY.AMPHURColumn] = System.Convert.DBNull;
            }
            
            public bool IsPROVINCENull() {
                return this.IsNull(this.tableUCS_HEALTHY.PROVINCEColumn);
            }
            
            public void SetPROVINCENull() {
                this[this.tableUCS_HEALTHY.PROVINCEColumn] = System.Convert.DBNull;
            }
            
            public bool IsSTATUSNull() {
                return this.IsNull(this.tableUCS_HEALTHY.STATUSColumn);
            }
            
            public void SetSTATUSNull() {
                this[this.tableUCS_HEALTHY.STATUSColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UCS_HEALTHYRowChangeEvent : EventArgs {
            
            private UCS_HEALTHYRow eventRow;
            
            private DataRowAction eventAction;
            
            public UCS_HEALTHYRowChangeEvent(UCS_HEALTHYRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public UCS_HEALTHYRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
