;
; Packet driver interrupt vectors (required):
;
local_pdi=0x61
remote_pdi=0x60
;
; IP address and net mask of NAPT box on the local subnet (required):
;
local_ip=10.64.1.32
local_mask=255.255.255.0
;
; IP address and net mask of NAPT box on the remote network:
; (Note: Leave one or more commented to use BOOTP values instead).
;
;remote_name=ksp.com
;remote_ip=161.246.5.167
;remote_mask=255.255.255.0
;remote_gateway=161.246.5.254
;
; IP address of gateway (router) on the local subnet:
; (Note: Most subnets won't have gateways to other subnets.)
;
;local_gateway=192.168.1.3
;
; IP address and port numbers of servers listening on the local subnet:
;
;tcp_server=192.168.1.2:21
;udp_server=192.168.1.2:53
;
; Optional (local) DNS data follows: dns=<MX-name>,<full-hostname>
;                                or: dns=<full-hostname>,<ip-address>
;
;dns=ksp.com,mail.ksp.com
;dns=www.dtac.co.th,203.155.33.1
;dns=mail.ksp.com,192.168.1.4

