<!ELEMENT PO (BUYER*)>
<!ATTLIST PO
	Status CDATA ""
>
<!ELEMENT BUYER (PONO, POID, BuyerID, BizName, PODate, POTerm, POAddress, POShipPrice, POItemPrice, Line, OrderName, OrderSellerItemID, OrderUnit, OrderQTY, OrderItemPrice, OrderShipPrice, needDate, ShipMethod, BuyerBizName, BuyerAddress)>
<!ELEMENT PONO (#PCDATA)>
<!ATTLIST PONO
	xmlns: CDATA #FIXED ""
>
<!ELEMENT POID (#PCDATA)>
<!ATTLIST POID
	xmlns: CDATA #FIXED ""
>
<!ELEMENT BuyerID (#PCDATA)>
<!ATTLIST BuyerID
	xmlns: CDATA #FIXED ""
>
<!ELEMENT BizName (#PCDATA)>
<!ATTLIST BizName
	xmlns: CDATA #FIXED ""
>
<!ELEMENT PODate (#PCDATA)>
<!ATTLIST PODate
	xmlns: CDATA #FIXED ""
>
<!ELEMENT POTerm (#PCDATA)>
<!ATTLIST POTerm
	xmlns: CDATA #FIXED ""
>
<!ELEMENT POAddress (#PCDATA)>
<!ATTLIST POAddress
	xmlns: CDATA #FIXED ""
>
<!ELEMENT POShipPrice (#PCDATA)>
<!ATTLIST POShipPrice
	xmlns: CDATA #FIXED ""
>
<!ELEMENT POItemPrice (#PCDATA)>
<!ATTLIST POItemPrice
	xmlns: CDATA #FIXED ""
>
<!ELEMENT Line (#PCDATA)>
<!ATTLIST Line
	xmlns: CDATA #FIXED ""
>
<!ELEMENT OrderName (#PCDATA)>
<!ATTLIST OrderName
	xmlns: CDATA #FIXED ""
>
<!ELEMENT OrderSellerItemID (#PCDATA)>
<!ATTLIST OrderSellerItemID
	xmlns: CDATA #FIXED ""
>
<!ELEMENT OrderUnit (#PCDATA)>
<!ATTLIST OrderUnit
	xmlns: CDATA #FIXED ""
>
<!ELEMENT OrderQTY (#PCDATA)>
<!ATTLIST OrderQTY
	xmlns: CDATA #FIXED ""
>
<!ELEMENT OrderItemPrice (#PCDATA)>
<!ATTLIST OrderItemPrice
	xmlns: CDATA #FIXED ""
>
<!ELEMENT OrderShipPrice (#PCDATA)>
<!ATTLIST OrderShipPrice
	xmlns: CDATA #FIXED ""
>
<!ELEMENT needDate (#PCDATA)>
<!ATTLIST needDate
	xmlns: CDATA #FIXED ""
>
<!ELEMENT ShipMethod (#PCDATA)>
<!ATTLIST ShipMethod
	xmlns: CDATA #FIXED ""
>
<!ELEMENT BuyerBizName (#PCDATA)>
<!ATTLIST BuyerBizName
	xmlns: CDATA #FIXED ""
>
<!ELEMENT BuyerAddress (#PCDATA)>
<!ATTLIST BuyerAddress
	xmlns: CDATA #FIXED ""
>
