----------------------Olala Wedding Planner------------------------------------

CREATE TABLE Customer (
       Customer_ID          NUMBER NOT NULL,
       Username             VARCHAR2(30) NULL,
       Password             VARCHAR2(30) NULL,
       M_name               VARCHAR2(30) NULL,
       M_surname            VARCHAR2(30) NULL,
       M_birthdate          VARCHAR2(20) NULL,
       M_phone              VARCHAR2(11) NULL,
       M_address            VARCHAR2(100) NULL,
       M_email              VARCHAR2(50) NULL,
       F_name               VARCHAR2(30) NULL,
       F_surname            VARCHAR2(30) NULL,
       F_birthdate          VARCHAR2(20) NULL,
       F_phone              VARCHAR2(11) NULL,
       F_address            VARCHAR2(100) NULL,
       F_email              VARCHAR2(50) NULL
);

CREATE TABLE Olala_wedding_Contact (
       Wedding_Contact_ID       NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       DeadLine             VARCHAR2(30) NULL,
       Wedding_Contact_Name     VARCHAR2(30) NULL,
       Wedding_Allprice     NUMBER NULL
);
----------------------Olala Wedding Planner------------------------------------


------------------------------- Entertain -------------------------------------
CREATE TABLE Entertain (
       Entertain_name       VARCHAR2(30) NOT NULL,
       Eaddress             VARCHAR2(100) NULL,
       Ephone               VARCHAR2(11) NULL,
       Eusername            VARCHAR2(20) NULL,
       Epassword            VARCHAR2(20) NULL
);

CREATE TABLE Entertain_Contact (
       Entertain_Contact_ID NUMBER NOT NULL,
       Wedding_Contact_ID       NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       Entertain_name       VARCHAR2(30) NOT NULL,
       Entertain_Allprice   NUMBER NULL
);
CREATE TABLE Entertain_service (
       Entertain_Job_ID     NUMBER NOT NULL,
       Entertain_Contact_ID NUMBER NOT NULL,
       Wedding_Contact_ID       NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       Entertain_name       VARCHAR2(30) NOT NULL,
       Entertain_price      NUMBER NULL
);
------------------------------- Entertain -------------------------------------




------------------------------- DISTRICT -------------------------------------
CREATE TABLE DISTRICT(
       DISTRICT_ID     NUMBER      NOT NULL,
       DISTRICT_NAME   VARCHAR(30) NOT NULL,
       X               NUMBER      NOT NULL,
       Y               NUMBER      NOT NULL
);

INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(1, 'คลองเตย'	,	5758	,	7111	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(2,	'คลองสาน'	,	5059	,	7197	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(3, 'คลองสามวา'	,	7435	,	8707	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(4,	'คันนายาว'	,	6809	,	8174	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(5,	'จตุจักร'	,	5687	,	8215	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(6,	'จอมทอง'	,	4685	,	6833	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(7,	'ดอนแมือง'	,	5930	,	9208	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(8,	'ดินแดง'	,	5666	,	7714	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(9,	'ดุสิต'	,	5217	,	7761	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(10,	'ตลิ่งชัน'	,	4374	,	7698	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(11,	'ทวีวัฒนา'	,	3677	,	7732	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(12,	'ทุ่งครุ'	,	4995	,	6235	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(13,	'ธนบุรี'	,	4877	,	7093	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(14,	'บางกอกน้อย'	,	4758	,	7582	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(15,	'บางกอกใหญ่'	,	4791	,	7320	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(16,	'บางกะปิ'	,	6460	,	7660	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(17,	'บางขุนเทียน'	,	4307	,	5830	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(18,	'บางเขน'	,	6434	,	8649	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(19,	'บางคอแหลม'	,	5124	,	6932	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(20,	'บางแค'	,	4006	,	7096	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(21,	'บางซื่อ'	,	5296	,	8146	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(22,	'บางนา'	,	6179	,	6673	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(23,	'บางบอน'	,	3995	,	6538	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(24,	'บางพลัด'	,	4992	,	7833	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(25,	'บางรัก'	,	5259	,	7233	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(26,	'บึ่งกุ่ม'	,	6544	,	8033	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(27,	'ปทุมวัน'	,	5359	,	7371	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(28,	'ประเวศ'	,	6801	,	6970	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(29,	'ป้อมปราบ'	,	5146	,	7480	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(30,	'พญาไท'	,	5476	,	7784	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(31,	'พระโขนง'	,	6154	,	6911	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(32,	'พระนคร'	,	5006	,	7523	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(33,	'ภาษีเจริญ'	,	4465	,	7209	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(34,	'มีนบุรี'	,	7577	,	8013	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(35,	'ยานนาวา'	,	5430	,	6862	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(36,	'ราชเทวี'	,	5438	,	7524	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(37,	'ราษฎร์บูรณะ'	,	5011	,	6689	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(38,	'ลาดกระบัง'	,	7871	,	7428	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(39,	'ลาดพร้าว'	,	6104	,	8207	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(40,	'วังทองหลาง'	,	6136	,	7728	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(41,	'วัฒนา'	,	5873	,	7286	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(42,	'สวนหลวง'	,	6292	,	7211	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(43,	'สะพานสูง'	,	6928	,	7568	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(44,	'สัมพันธวงศ์'	,	5114	,	7366	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(45,	'สาธร'	,	5335	,	7102	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(46,	'สายไหม'	,	6467	,	9082	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(47,	'หนองแขม'	,	3583	,	6931	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(48,	'หนองจอก'	,	8587	,	8554	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(49,	'หลักสี่'	,	5719	,	8744	);
INSERT INTO DISTRICT(DISTRICT_ID,DISTRICT_NAME,X,Y) VALUES(50,	'ห้วยขวาง'	,	5870	,	7605	);
------------------------------- DISTRICT -------------------------------------

--------------------------------- Photo ----------------------------------------
CREATE TABLE Photo (
       Photo_name           VARCHAR2(30) NOT NULL,
       Photo_ID             NUMBER NULL,
       Pphone               VARCHAR2(11) NULL,
       Paddress             VARCHAR2(100) NULL,
       Pusername            VARCHAR2(20) NULL,
       Ppassword            VARCHAR2(20) NULL,
       PCust_ID              NUMBER NULL
);
ALTER TABLE PHOTO 
 ADD (
  PROVINCE INTEGER,
  DISTRICT INTEGER
 );


CREATE TABLE Photo_Contact (
       Photo_Contact_ID     NUMBER NOT NULL,
       Wedding_Contact_ID       NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       Photo_ID             NUMBER NOT NULL,
       Photo_Allprice       NUMBER NULL
);

CREATE TABLE Photoinwedding_service (
       Photoinwedding_Job_ID NUMBER NOT NULL,
       Photo_Contact_ID     NUMBER NOT NULL,
       Wedding_Contact_ID       NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       Photo_ID             NUMBER NOT NULL,
       Photoinwedding_price NUMBER NULL
);

CREATE TABLE Photoinstudio_service (
       Photoinstudio_Job_ID NUMBER NOT NULL,
       Photo_Contact_ID     NUMBER NOT NULL,
       Wedding_Contact_ID   NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       Photo_ID             NUMBER NOT NULL,
       Photoinstudio_price  NUMBER NULL
);

CREATE TABLE Photovdo_service (
       Photovdo_Job_ID      NUMBER NOT NULL,
       Photo_Contact_ID     NUMBER NOT NULL,
       Wedding_Contact_ID   NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       Photo_ID             NUMBER NOT NULL,
       Photovdo_price       NUMBER NULL
);

CREATE TABLE Photomulti_service (
       Photomulti_Job_ID    NUMBER NOT NULL,
       Photo_Contact_ID     NUMBER NOT NULL,
       Wedding_Contact_ID   NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       Photo_ID             NUMBER NOT NULL,
       Photomulti_price     NUMBER NULL
);
-------------------------------- Drop Table-------------------------------------
drop table photo;
drop table photo_contact;
drop table photoinwedding_service;
drop table photoinstudio_service;
drop table photovdo_service;
drop table photomulti_service;

--------------------------------- Photo ----------------------------------------

--------------------------------- Tour -----------------------------------------
CREATE TABLE Tour (
       Tour_ID              NUMBER NOT NULL,
       Tour_name            VARCHAR2(30) NOT NULL,
       Taddress             VARCHAR2(100) NULL,
       Tphone               VARCHAR2(11) NULL,
       Tusername            VARCHAR2(20) NULL,
       Tpassword            VARCHAR2(20) NULL,
       Tcust_ID              NUMBER NULL  
);

CREATE TABLE Tour_Contact (
       Tour_Contact_ID      NUMBER NOT NULL,
       Wedding_Contact_ID   NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       Tour_ID              NUMBER NOT NULL,
       Tour_Allprice        NUMBER NULL
);

CREATE TABLE Tour_service (
       Tour_Job_ID          NUMBER NOT NULL,
       Tour_Contact_ID      NUMBER NOT NULL,
       Wedding_Contact_ID   NUMBER NOT NULL,
       Customer_ID          NUMBER NOT NULL,
       Tour_ID              NUMBER NOT NULL,
       Tour_price           NUMBER NULL
);
--------------------------------- Tour -----------------------------------------

------------------------------- Province ---------------------------------------
CREATE TABLE PROVINCE(
       PROVINCE_ID     INTEGER     NOT NULL,
       PROVINCE_NAME   VARCHAR(30) NOT NULL,
       REGION          INTEGER     NOT NULL
);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	1	,	'กำแพงเพชร	',	6	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	2	,	'เชียงราย',	1	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	3	,	'เชียงใหม่',	1	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	4	,	'ตาก',	6	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	5	,	'นครสวรรค์'	,	6	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	6	,	'น่าน'	,	1	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	7	,	'พะเยา'	,	1	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	8	,	'พิจิตร'	,	6	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	9	,	'พิษณุโลก'	,	6	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	10	,	'เพชรบูรณ์'	,	6	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	11	,	'แพร่'	,	1	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	12	,	'แม่ฮ่องสอน'	,	1	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	13	,	'ลำปาง'	,	1	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	14	,	'ลำพูน'	,	1	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	15	,	'สุโขทัย'	,	6	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	16	,	'อุตรดิตถ์'	,	1	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	17	,	'อุทัยธานี'	,	6	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	18	,	'กรุงเทพฯ'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	19	,	'กาญจนบุรี'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	20	,	'ชัยนาท'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	21	,	'นครนายก'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	22	,	'นครปฐม'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	23	,	'นนทบุรี'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	24	,	'เพชรบุรี'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	25	,	'ปทุมธานี'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	26	,	'ประจวบคีรีขันธ์'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	27	,	'ราชบุรี'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	28	,	'ลพบุรี'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	29	,	'สระบุรี'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	30	,	'สิงห์บุรี'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	31	,	'สุพรรณบุรี'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	32	,	'สมุทรปราการ'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	33	,	'สมุทรสงคราม'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	34	,	'สมุทรสาคร'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	35	,	'อยุธยา'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	36	,	'อ่างทอง'	,	2	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	37	,	'จันทบุรี'	,	3	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	38	,	'ฉะเชิงเทรา'	,	3	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	39	,	'ชลบุรี'	,	3	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	40	,	'ตราด'	,	3	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	41	,	'ปราจีนบุรี'	,	3	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	42	,	'ระยอง'	,	3	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	43	,	'สระแก้ว'	,	3	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	44	,	'กาฬสินธุ์'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	45	,	'ขอนแก่น'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	46	,	'ชัยภูมิ'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	47	,	'นครพนม'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	48	,	'นครราชสีมา'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	49	,	'มหาสารคาม'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	50	,	'มุกดาหาร'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	51	,	'ยโสธร'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	52	,	'ร้อยเอ็ด'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	53	,	'เลย'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	54	,	'ศรีสะเกษ'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	55	,	'สกลนคร'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	56	,	'สุรินทร์'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	57	,	'หนองบัวลำภู'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	58	,	'บุรีรัมย์'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	59	,	'หนองคาย'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	60	,	'อำนาจเจริญ'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	61	,	'อุบลราชธานี'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	62	,	'อุดรธานี'	,	4	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	63	,	'กระบี่'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	64	,	'ชุมพร'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	65	,	'ตรัง'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	66	,	'นครศรีธรรมราช'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	67	,	'นราธิวาส'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	68	,	'ปัตตานี'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	69	,	'พังงา'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	70	,	'พัทลุง'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	71	,	'ภูเก็ต'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	72	,	'ระนอง'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	73	,	'ยะลา'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	74	,	'สงขลา'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	75	,	'สตูล'	,	5	);
INSERT INTO PROVINCE(PROVINCE_ID,PROVINCE_NAME,REGION) VALUES(	76	,	'สุราษฎร์ธานี'	,	5	);
------------------------------- Province ---------------------------------------





commit
