<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://gisoncampusservices" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://gisoncampusservices" xmlns:intf="http://gisoncampusservices" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.2.1
Built on Aug 08, 2005 (11:49:10 PDT)-->

   <wsdl:message name="updatePositionResponse">

      <wsdl:part name="updatePositionReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="getContactsPositionRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="updatePositionRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

      <wsdl:part name="posX" type="xsd:string"/>

      <wsdl:part name="posY" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="getBusPositionResponse">

      <wsdl:part name="getBusPositionReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="updateBusPositionRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

      <wsdl:part name="posX" type="xsd:string"/>

      <wsdl:part name="posY" type="xsd:string"/>

      <wsdl:part name="busID" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="getMyRecordPositionResponse">

      <wsdl:part name="getMyRecordPositionReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="getMyRecordPositionRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="updateBusPositionResponse">

      <wsdl:part name="updateBusPositionReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="getBusPositionRequest">

      <wsdl:part name="sessionkey" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="getContactsPositionResponse">

      <wsdl:part name="getContactsPositionReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:portType name="PositionServices">

      <wsdl:operation name="updatePosition" parameterOrder="sessionkey posX posY">

         <wsdl:input message="impl:updatePositionRequest" name="updatePositionRequest"/>

         <wsdl:output message="impl:updatePositionResponse" name="updatePositionResponse"/>

      </wsdl:operation>

      <wsdl:operation name="updateBusPosition" parameterOrder="sessionkey posX posY busID">

         <wsdl:input message="impl:updateBusPositionRequest" name="updateBusPositionRequest"/>

         <wsdl:output message="impl:updateBusPositionResponse" name="updateBusPositionResponse"/>

      </wsdl:operation>

      <wsdl:operation name="getMyRecordPosition" parameterOrder="sessionkey">

         <wsdl:input message="impl:getMyRecordPositionRequest" name="getMyRecordPositionRequest"/>

         <wsdl:output message="impl:getMyRecordPositionResponse" name="getMyRecordPositionResponse"/>

      </wsdl:operation>

      <wsdl:operation name="getContactsPosition" parameterOrder="sessionkey">

         <wsdl:input message="impl:getContactsPositionRequest" name="getContactsPositionRequest"/>

         <wsdl:output message="impl:getContactsPositionResponse" name="getContactsPositionResponse"/>

      </wsdl:operation>

      <wsdl:operation name="getBusPosition" parameterOrder="sessionkey">

         <wsdl:input message="impl:getBusPositionRequest" name="getBusPositionRequest"/>

         <wsdl:output message="impl:getBusPositionResponse" name="getBusPositionResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="PositionServicesSoapBinding" type="impl:PositionServices">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="updatePosition">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="updatePositionRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="updatePositionResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="updateBusPosition">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="updateBusPositionRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="updateBusPositionResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="getMyRecordPosition">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getMyRecordPositionRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="getMyRecordPositionResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="getContactsPosition">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getContactsPositionRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="getContactsPositionResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="getBusPosition">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getBusPositionRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="getBusPositionResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://gisoncampusservices" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="PositionServicesService">

      <wsdl:port binding="impl:PositionServicesSoapBinding" name="PositionServices">

         <wsdlsoap:address location="http://localhost:8080/GISonCampusServices/services/PositionServices"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
