'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace Thaiairway
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TGServicesSoap", [Namespace]:="http://tempuri.org/allianceWS/TGBooking")>  _
    Public Class TGServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/allianceWS/TGServices.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/allianceWS/TGBooking/Booking", RequestNamespace:="http://tempuri.org/allianceWS/TGBooking", ResponseNamespace:="http://tempuri.org/allianceWS/TGBooking", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Booking(ByVal BookedFlightSet As System.Data.DataSet, ByVal BookedDetailsString As String) As String
            Dim results() As Object = Me.Invoke("Booking", New Object() {BookedFlightSet, BookedDetailsString})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginBooking(ByVal BookedFlightSet As System.Data.DataSet, ByVal BookedDetailsString As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Booking", New Object() {BookedFlightSet, BookedDetailsString}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndBooking(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/allianceWS/TGBooking/CancelFlight", RequestNamespace:="http://tempuri.org/allianceWS/TGBooking", ResponseNamespace:="http://tempuri.org/allianceWS/TGBooking", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelFlight(ByVal BookRef As String) As String
            Dim results() As Object = Me.Invoke("CancelFlight", New Object() {BookRef})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginCancelFlight(ByVal BookRef As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CancelFlight", New Object() {BookRef}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCancelFlight(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/allianceWS/TGBooking/ChangeFlight", RequestNamespace:="http://tempuri.org/allianceWS/TGBooking", ResponseNamespace:="http://tempuri.org/allianceWS/TGBooking", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChangeFlight(ByVal BookRef As String) As String
            Dim results() As Object = Me.Invoke("ChangeFlight", New Object() {BookRef})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginChangeFlight(ByVal BookRef As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ChangeFlight", New Object() {BookRef}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndChangeFlight(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/allianceWS/TGBooking/PaymentUpdate", RequestNamespace:="http://tempuri.org/allianceWS/TGBooking", ResponseNamespace:="http://tempuri.org/allianceWS/TGBooking", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PaymentUpdate(ByVal BookRef As String) As String
            Dim results() As Object = Me.Invoke("PaymentUpdate", New Object() {BookRef})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginPaymentUpdate(ByVal BookRef As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PaymentUpdate", New Object() {BookRef}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndPaymentUpdate(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/allianceWS/TGBooking/UpdateSeat", RequestNamespace:="http://tempuri.org/allianceWS/TGBooking", ResponseNamespace:="http://tempuri.org/allianceWS/TGBooking", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateSeat(ByVal UpdateSeatSet As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("UpdateSeat", New Object() {UpdateSeatSet})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateSeat(ByVal UpdateSeatSet As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateSeat", New Object() {UpdateSeatSet}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateSeat(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
