#ifndef _CPTDEFINEH
#define _CPTDEFINEH


//////CPT silence/////
#define CPTsilence -5500	//dBm divide by 100 
#define SAMP_RATE 8000
/////state//////
#define START	100
#define SPECIAL1	4
#define SPECIAL2	5
#define SPECIAL3	6
#define PAYPHONE1	8
#define RECALL_CONFIRM1	11
#define RECALL_CONFIRM2	12
#define RECALL_CONFIRM3	13
#define INTERCEPT1	14
#define BUSY_VERIFICATION1	17
#define	CALLER_WAITING1	19
#define	CALLER_WAITING2	20
/////end state///////

//GENERATE CPT
#define GEN_DIAL_FREQ0 350
#define GEN_DIAL_FREQ1 440
//#define GEN_DIAL_FREQ0 394;
//#define GEN_DIAL_FREQ1 477;
#define GEN_DIAL_NUM  2
#define GEN_DIAL_TONE_DURATION  2500
//#define GEN_DIAL_PAUSE_DURATION  100;

#define GEN_RING_FREQ0 425
#define GEN_RING_NUM  1
#define GEN_RING_TONE_DURATION  1000
#define GEN_RING_PAUSE_DURATION  4000

#define GEN_BUSY_FREQ0 425
#define GEN_BUSY_NUM  1
#define GEN_BUSY_TONE_DURATION  500
#define GEN_BUSY_PAUSE_DURATION  500

//#define GEN_CONGESTION_FREQ0 476
#define GEN_CONGESTION_FREQ0 425
#define GEN_CONGESTION_NUM  1
#define GEN_CONGESTION_TONE_DURATION  300
#define GEN_CONGESTION_PAUSE_DURATION  200

#define GEN_SPECIAL_FREQ0 950
#define GEN_SPECIAL_FREQ1 1400
#define GEN_SPECIAL_FREQ2 1800
#define GEN_SPECIAL_NUM  1
#define GEN_SPECIAL_TONE_DURATION0  330
#define GEN_SPECIAL_PAUSE_DURATION0  30
#define GEN_SPECIAL_TONE_DURATION1  330
#define GEN_SPECIAL_PAUSE_DURATION1  30
#define GEN_SPECIAL_TONE_DURATION2  330
#define GEN_SPECIAL_PAUSE_DURATION2  1000

#define GEN_WARNING_FREQ0 1400
#define GEN_WARNING_NUM  1
#define GEN_WARNING_TONE_DURATION  425
#define GEN_WARNING_PAUSE_DURATION  15000

#define GEN_PAYPHONE_FREQ0 1100
#define GEN_PAYPHONE_FREQ1 1425
#define GEN_PAYPHONE_NUM  1
#define GEN_PAYPHONE_TONE_DURATION0  200
#define GEN_PAYPHONE_PAUSE_DURATION0  200
#define GEN_PAYPHONE_TONE_DURATION1  200
#define GEN_PAYPHONE_PAUSE_DURATION1  2000

#define GEN_CALL_WAIT_FREQ0 425
#define GEN_CALL_WAIT_NUM  1
#define GEN_CALL_WAIT_TONE_DURATION  300
#define GEN_CALL_WAIT_PAUSE_DURATION  9000

//#define GEN_INTERCEPT_FREQ0 440
//#define GEN_INTERCEPT_FREQ1 620
#define GEN_INTERCEPT_FREQ0 440
#define GEN_INTERCEPT_FREQ1 620
#define GEN_INTERCEPT_NUM  1
#define GEN_INTERCEPT_TONE_DURATION0  230
#define GEN_INTERCEPT_PAUSE_DURATION0  270
#define GEN_INTERCEPT_TONE_DURATION1  230
#define GEN_INTERCEPT_PAUSE_DURATION1  270

#define GEN_CONFIRM_FREQ0 350
#define GEN_CONFIRM_FREQ1 440
//#define GEN_CONFIRM_FREQ0 394;
//#define GEN_CONFIRM_FREQ1 477;
#define GEN_CONFIRM_NUM  2
#define GEN_CONFIRM_TONE_DURATION0  100
#define GEN_CONFIRM_PAUSE_DURATION0  100
#define GEN_CONFIRM_TONE_DURATION1  100
#define GEN_CONFIRM_PAUSE_DURATION1  100
#define GEN_CONFIRM_TONE_DURATION2  100
#define GEN_CONFIRM_PAUSE_DURATION2  100

#define GEN_COMFORT_FREQ0 480
#define GEN_COMFORT_NUM  1
#define GEN_COMFORT_TONE_DURATION  2500
#define GEN_COMFORT_PAUSE_DURATION  100

#define GEN_BUSY_VER_FREQ0 440
#define GEN_BUSY_VER_NUM  1
#define GEN_BUSY_VER_TONE_DURATION0  1000
#define GEN_BUSY_VER_PAUSE_DURATION0  9000
#define GEN_BUSY_VER_TONE_DURATION1  300
#define GEN_BUSY_VER_PAUSE_DURATION1  9000

#define GEN_CALLER_FREQ0 425
#define GEN_CALLER_NUM  1
#define GEN_CALLER_TONE_DURATION  1000
#define GEN_CALLER_PAUSE_DURATION  200
//END GENERATE CPT
#endif
