//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TcpScan.rc
//
#define IDI_TCPSCAN                     101
#define IDD_TCPSCAN_DIALOG              102
#define IDD_SERVICESPAGE                102
#define IDD_PAGE_SERVICES               102
#define IDD_CONNECTPAGE                 106
#define IDD_PAGE_CONNECT                106
#define IDM_PORTMENU                    107
#define IDM_SERVICES                    107
#define IDD_DIALOG_ADDSERVICE           109
#define IDD_SMTPPAGE                    110
#define IDD_POP3PAGE                    111
#define IDI_ICONPORT                    112
#define IDI_ICONPORTERROR               121
#define IDD_PAGE_MINE                   124
#define IDM_SCAN                        126
#define IDM_SCAN_EMPTY                  127
#define IDM_SERVICES_EMPTY              128
#define IDM_MINE                        129
#define IDD_SCANPAGE                    130
#define IDD_PAGE_SCAN                   130
#define IDM_MINE_EMPTY                  131
#define IDD_DIALOG_ADDURL               132
#define IDM_MINED                       133
#define IDD_OPTIONSPAGE                 140
#define IDD_PAGE_OPTIONS                140
#define IDC_EDIT_STARTIPADDR            1000
#define IDC_COMBO_SMTPMAILTO            1000
#define IDC_EDIT_STARTHOST              1000
#define IDC_EDIT_ENDIPADDR              1001
#define IDC_LIST_SERVICESLIST           1001
#define IDC_EDIT_MAXDATABASEENTRY       1001
#define IDC_EDIT_ENDHOST                1001
#define IDC_LIST_SERVICES               1001
#define IDC_EDIT_PORTLIST               1002
#define IDC_EDIT_HOSTIP                 1002
#define IDC_EDIT_MAXHOSTENTRY           1002
#define IDC_EDIT_STARTPORT              1003
#define IDC_EDIT_HOSTPORT               1003
#define IDC_EDIT_MAXPORTENTRY           1003
#define IDC_EDIT_ENDPORT                1004
#define IDC_EDIT_HOSTSEND               1004
#define IDC_SPIN_MAXDATABASEENTRY       1004
#define IDC_EDIT_SEND                   1004
#define IDC_EDIT_LOGFILE                1005
#define IDC_EDIT_HOSTRECV               1005
#define IDC_LIST_SCAN                   1005
#define IDC_EDIT_RECV                   1005
#define IDC_BTN_CONNECT_SEND            1006
#define IDC_SPIN_MAXHOSTENTRY           1006
#define IDC_LIST_PORTLIST               1007
#define IDC_EDIT_SERVICESFILE           1007
#define IDC_SPIN_MAXPORTENTRY           1007
#define IDC_CHECK_SHOW                  1008
#define IDC_CHECK_SHOWCONN              1008
#define IDC_BUTTON_SCAN                 1009
#define IDC_CHECK_DATABASESERVICE       1009
#define IDC_EDIT_SCANDELAY              1009
#define IDC_BUTTON_BROWSE               1010
#define IDC_SPIN_SCANDELAY              1010
#define IDC_BUTTON_SERVICES             1010
#define IDC_COMBO_DATABASE              1011
#define IDC_CHECK_SESSIONLOG            1011
#define IDC_COMBO_SERVICES              1011
#define IDC_BUTTON_SAVETOREG            1012
#define IDC_EDIT_MINEDELAY              1012
#define IDC_RADIO_PORTRANGE             1013
#define IDC_BUTTON_LOADFROMREG          1013
#define IDC_EDIT_SERVICENAME            1013
#define IDC_SPIN_MINEDELAY              1013
#define IDC_EDIT_PORTNUMBER             1014
#define IDC_EDIT_POP3HOST               1014
#define IDC_CHECK_MINEUSETHREADS        1014
#define IDC_RADIO_PORTLIST              1015
#define IDC_EDIT_PROTOCOLNAME           1015
#define IDC_EDIT_POP3PORT               1015
#define IDC_CHECK_MINERPATH             1015
#define IDC_EDIT_COMMENT                1016
#define IDC_EDIT_POP3USER               1016
#define IDC_EDIT_MINERPATH              1016
#define IDC_EDIT_POP3PASS               1017
#define IDC_EDIT_POP3MESSAGE            1018
#define IDC_COMBO_HOST                  1019
#define IDC_EDIT_SMTPHOST               1020
#define IDC_COMBO_PORT                  1020
#define IDC_EDIT_SMTPMESSAGE            1022
#define IDC_BUTTON_CLEANDATABASEENTRY   1022
#define IDC_EDIT_SMTPATTACH             1023
#define IDC_BUTTON_CLEANHOSTENTRY       1023
#define IDC_EDIT_SMTPPORT               1024
#define IDC_BUTTON_CLEANPORTENTRY       1024
#define IDC_EDIT_EXTRAHEADER            1024
#define IDC_EDIT_SMTPSUBJECT            1025
#define IDC_LIST_MINE                   1025
#define IDC_EDIT_SMTPFROM               1026
#define IDC_LIST_MINER                  1026
#define IDC_EDIT_URL                    1026
#define IDC_EDIT_SMTPUSER               1027
#define IDC_EDIT_SMTPPASS               1028
#define IDC_EDIT_SMTPCC                 1029
#define IDC_BUTTON_MINERPATH            1030
#define IDM_PORTMENU_SETENDPORT         40003
#define IDM_SERVICES_SETENDPORT         40003
#define IDM_PORTMENU_ADDTOLIST          40004
#define IDM_SERVICES_ADDPORT            40004
#define IDM_PORTMENU_SETSTARTPORT       40005
#define IDM_SERVICES_SETSTARTPORT       40005
#define IDM_PORTMENU_CLEARPORTS         40006
#define IDM_SERVICES_CLEARPORTS         40006
#define IDM_PORTMENU_LOADALL            40007
#define IDM_SERVICES_LOADALLPORTS       40007
#define IDM_SERVICES_SAVETOREGISTRY     40008
#define IDM_SERVICES_LOADFROMREGISTRY   40009
#define IDM_SERVICES_LOADFROMDATABASE   40010
#define IDM_SERVICES_ADDSERVICE         40011
#define IDM_SERVICES_REMOVESERVICE      40012
#define IDM_SERVICES_SAVETODATABASE     40013
#define IDM_SCAN_SAVETOREGISTRY         40014
#define IDM_SCAN_ADDTOSERVICES          40016
#define IDM_SCAN_REMOVEFROMSERVICES     40017
#define IDM_SCAN_LOADFROMREGISTRY       40019
#define IDM_SCAN_REMOVEPORT             40020
#define IDM_SCAN_LOADSERVICES           40021
#define IDM_MINE_REMOVEURL              40023
#define IDM_MINE_SAVETOREGISTRY         40024
#define IDM_SCAN_CLEARPORTS             40025
#define IDM_SCAN_LOADFROMSERVICES       40026
#define IDM_MINE_ADDURL                 40027
#define IDM_MINE_LOADFROMREGISTRY       40028
#define IDM_MINE_EDITURL                40029
#define IDM_MINE_EXTRAHEADER            40030
#define IDM_MINER_LOADDOCUMENT          40031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         40032
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
