/*
 * MATLAB Compiler: 4.0 (R14)
 * Date: Wed Mar 15 00:52:58 2006
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "avi.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_avi_public_data[] = {'3', '0', '8', '1', '9', 'D',
                                               '3', '0', '0', 'D', '0', '6',
                                               '0', '9', '2', 'A', '8', '6',
                                               '4', '8', '8', '6', 'F', '7',
                                               '0', 'D', '0', '1', '0', '1',
                                               '0', '1', '0', '5', '0', '0',
                                               '0', '3', '8', '1', '8', 'B',
                                               '0', '0', '3', '0', '8', '1',
                                               '8', '7', '0', '2', '8', '1',
                                               '8', '1', '0', '0', 'C', '4',
                                               '9', 'C', 'A', 'C', '3', '4',
                                               'E', 'D', '1', '3', 'A', '5',
                                               '2', '0', '6', '5', '8', 'F',
                                               '6', 'F', '8', 'E', '0', '1',
                                               '3', '8', 'C', '4', '3', '1',
                                               '5', 'B', '4', '3', '1', '5',
                                               '2', '7', '7', 'E', 'D', '3',
                                               'F', '7', 'D', 'A', 'E', '5',
                                               '3', '0', '9', '9', 'D', 'B',
                                               '0', '8', 'E', 'E', '5', '8',
                                               '9', 'F', '8', '0', '4', 'D',
                                               '4', 'B', '9', '8', '1', '3',
                                               '2', '6', 'A', '5', '2', 'C',
                                               'C', 'E', '4', '3', '8', '2',
                                               'E', '9', 'F', '2', 'B', '4',
                                               'D', '0', '8', '5', 'E', 'B',
                                               '9', '5', '0', 'C', '7', 'A',
                                               'B', '1', '2', 'E', 'D', 'E',
                                               '2', 'D', '4', '1', '2', '9',
                                               '7', '8', '2', '0', 'E', '6',
                                               '3', '7', '7', 'A', '5', 'F',
                                               'E', 'B', '5', '6', '8', '9',
                                               'D', '4', 'E', '6', '0', '3',
                                               '2', 'F', '6', '0', 'C', '4',
                                               '3', '0', '7', '4', 'A', '0',
                                               '4', 'C', '2', '6', 'A', 'B',
                                               '7', '2', 'F', '5', '4', 'B',
                                               '5', '1', 'B', 'B', '4', '6',
                                               '0', '5', '7', '8', '7', '8',
                                               '5', 'B', '1', '9', '9', '0',
                                               '1', '4', '3', '1', '4', 'A',
                                               '6', '5', 'F', '0', '9', '0',
                                               'B', '6', '1', 'F', 'C', '2',
                                               '0', '1', '6', '9', '4', '5',
                                               '3', 'B', '5', '8', 'F', 'C',
                                               '8', 'B', 'A', '4', '3', 'E',
                                               '6', '7', '7', '6', 'E', 'B',
                                               '7', 'E', 'C', 'D', '3', '1',
                                               '7', '8', 'B', '5', '6', 'A',
                                               'B', '0', 'F', 'A', '0', '6',
                                               'D', 'D', '6', '4', '9', '6',
                                               '7', 'C', 'B', '1', '4', '9',
                                               'E', '5', '0', '2', '0', '1',
                                               '1', '1', '\0'};

const char *__MCC_avi_name_data = "avi";

const char *__MCC_avi_root_data = "";

const unsigned char __MCC_avi_session_data[] = {'3', 'D', '9', 'C', 'B', '6',
                                                '9', '0', 'C', '9', 'D', '5',
                                                '0', '6', '8', '9', '9', 'E',
                                                'F', '4', 'D', '6', '8', 'E',
                                                '0', '6', '7', 'E', 'F', '2',
                                                'E', '8', 'A', '3', 'C', '5',
                                                'E', '3', '7', '1', '3', '6',
                                                'C', '9', '6', '6', 'A', '1',
                                                'B', '8', '3', '1', '2', '8',
                                                'B', 'E', '9', 'B', 'A', '1',
                                                '4', 'B', 'E', '3', 'F', '6',
                                                '4', 'C', 'B', 'D', 'A', '8',
                                                '7', 'C', 'E', '0', '7', '7',
                                                '9', '2', 'B', '1', '3', '6',
                                                'A', '2', '6', '7', '3', '4',
                                                '1', '6', '4', '9', '7', '2',
                                                '7', '6', '1', 'F', '9', '6',
                                                '6', 'C', '5', 'D', '5', '7',
                                                '7', '6', 'F', '4', '2', '9',
                                                'A', '8', '2', '5', 'D', '6',
                                                '1', 'F', '6', '1', '1', '4',
                                                '0', 'C', '3', '0', '5', '5',
                                                'F', '9', 'B', 'D', '8', '4',
                                                '2', '8', '7', '0', 'B', 'B',
                                                '6', '8', '9', '9', 'F', '7',
                                                'A', '3', 'D', '6', '3', 'B',
                                                'D', '0', 'B', 'D', '1', '2',
                                                '4', '3', '0', 'A', 'B', '9',
                                                'E', 'C', '8', 'D', '1', '9',
                                                '3', 'E', 'E', 'F', '8', 'B',
                                                '3', '5', '0', '5', '7', '1',
                                                '8', '6', 'B', '9', '6', '2',
                                                'F', '8', 'D', 'C', 'B', '9',
                                                '3', '8', 'C', 'C', '0', '4',
                                                'A', '9', '9', '0', 'C', '8',
                                                '4', 'C', '0', 'F', 'F', 'F',
                                                '5', '2', '9', 'B', '7', 'B',
                                                '9', '6', '8', '4', '1', '8',
                                                'D', 'B', '9', '2', 'E', '5',
                                                'C', '4', '7', 'D', '7', '9',
                                                '1', '2', 'C', '2', '9', '4',
                                                'A', '0', 'D', '8', '5', '5',
                                                '8', '3', 'B', '6', '\0'};

const char *__MCC_avi_matlabpath_data[] = {"avi/", "toolbox/compiler/deploy/",
                                           "$TOOLBOXMATLABDIR/general/",
                                           "$TOOLBOXMATLABDIR/ops/",
                                           "$TOOLBOXMATLABDIR/lang/",
                                           "$TOOLBOXMATLABDIR/elmat/",
                                           "$TOOLBOXMATLABDIR/elfun/",
                                           "$TOOLBOXMATLABDIR/specfun/",
                                           "$TOOLBOXMATLABDIR/matfun/",
                                           "$TOOLBOXMATLABDIR/datafun/",
                                           "$TOOLBOXMATLABDIR/polyfun/",
                                           "$TOOLBOXMATLABDIR/funfun/",
                                           "$TOOLBOXMATLABDIR/sparfun/",
                                           "$TOOLBOXMATLABDIR/scribe/",
                                           "$TOOLBOXMATLABDIR/graph2d/",
                                           "$TOOLBOXMATLABDIR/graph3d/",
                                           "$TOOLBOXMATLABDIR/specgraph/",
                                           "$TOOLBOXMATLABDIR/graphics/",
                                           "$TOOLBOXMATLABDIR/uitools/",
                                           "$TOOLBOXMATLABDIR/strfun/",
                                           "$TOOLBOXMATLABDIR/imagesci/",
                                           "$TOOLBOXMATLABDIR/iofun/",
                                           "$TOOLBOXMATLABDIR/audiovideo/",
                                           "$TOOLBOXMATLABDIR/timefun/",
                                           "$TOOLBOXMATLABDIR/datatypes/",
                                           "$TOOLBOXMATLABDIR/verctrl/",
                                           "$TOOLBOXMATLABDIR/codetools/",
                                           "$TOOLBOXMATLABDIR/helptools/",
                                           "$TOOLBOXMATLABDIR/winfun/",
                                           "$TOOLBOXMATLABDIR/demos/",
                                           "toolbox/local/",
                                           "toolbox/compiler/",
                                           "toolbox/control/control/",
                                           "toolbox/database/database/",
                                           "toolbox/images/images/",
                                           "toolbox/map/map/",
                                           "toolbox/map/mapdisp/",
                                           "toolbox/map/mapproj/"};
const int __MCC_avi_matlabpath_data_count = 38;

const char *__MCC_avi_mcr_application_options[] = { "" };
const int __MCC_avi_mcr_application_option_count = 0;
const char *__MCC_avi_mcr_runtime_options[] = { "" };
const int __MCC_avi_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


