<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebFormerror.aspx.vb" Inherits="WebApplicationSeller2.WebFormerror"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebFormerror</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body MS_POSITIONING="GridLayout" BGCOLOR="#cc9966">
		<form id="Form1" method="post" runat="server">
			<FONT face="Tahoma">
				<asp:Label id="Label1" style="Z-INDEX: 103; LEFT: 187px; POSITION: absolute; TOP: 151px" runat="server" Font-Size="X-Large" Font-Bold="True" ForeColor="Red" Height="104px" Width="405px">เกิดความผิดพลาดกรุณาทำรายการนั้นใหม่อีกครัง</asp:Label>
				<asp:Button id="btnOK" style="Z-INDEX: 102; LEFT: 506px; POSITION: absolute; TOP: 280px" runat="server" Height="31px" Width="92px" Text="ต่อไป"></asp:Button></FONT>
		</form>
	</body>
</HTML>
