#if !defined(AFX_VIDEOOCX_H__196736F8_924B_4214_B97C_944EF15355A8__INCLUDED_)
#define AFX_VIDEOOCX_H__196736F8_924B_4214_B97C_944EF15355A8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CVideoOCX wrapper class

class CVideoOCX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CVideoOCX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa91e1e79, 0x6ae7, 0x11d4, { 0xad, 0x8, 0xa8, 0xab, 0x2e, 0x81, 0x8b, 0x70 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetDriver();
	void SetDriver(long);
	short GetMode();
	void SetMode(short);
	BOOL GetScaledDisplay();
	void SetScaledDisplay(BOOL);
	long GetControlWidth();
	void SetControlWidth(long);
	long GetControlHeight();
	void SetControlHeight(long);
	CPicture GetPicture();
	void SetPicture(LPDISPATCH);
	BOOL GetAudio();
	void SetAudio(BOOL);

// Operations
public:
	BOOL ShowDriverDlg();
	BOOL Start();
	BOOL Stop();
	BOOL ShowDisplayDlg();
	BOOL ShowFormatDlg();
	void Rewind();
	BOOL Next();
	BOOL Back();
	void SetErrorMessages(BOOL flag);
	long GetLen();
	BOOL SetOverlay(BOOL flag);
	BOOL Close();
	long GetFrameNumber();
	long GetWidth();
	long GetHeight();
	BOOL SetPreview(BOOL flag);
	void Transform(long sx, long sy, long* dx, long* dy);
	void ShowRectangle(long x0, long y0, long x1, long y1);
	BOOL InitFromFile(LPCTSTR filename);
	BOOL ShowInfoDlg();
	long GetFPS();
	BOOL SetResolution(long width, long height);
	BOOL Init();
	void Show(long image);
	BOOL SaveBMP(long image, LPCTSTR name);
	void ReleaseImageHandle(long image);
	long GetGrayImageHandle();
	long GetColorImageHandle();
	long GetDataPointer(long imagehandle);
	BOOL CaptureStripe(long imagehandle, long startrow, long num);
	long Capture(long imagehandle);
	long GetDataSize();
	void GetImageInfo(long imagehandle, long* width, long* height, long* datasize);
	long GetImageWidth(long imagehandle);
	long GetImageHeight(long imagehandle);
	long GetImageDataSize(long imagehandle);
	long GetLastErrorNum();
	CString GetLastErrorString();
	BOOL ShowSourceDlg();
	BOOL ToGray(long colorimagehandle, long grayimagehandle);
	BOOL AVISaveFrameClose();
	BOOL AVISaveFrameAdd(long imagehandle);
	BOOL AVISaveFrameSetFps(long framerate);
	BOOL AVISaveFrameInit(LPCTSTR filename, long imagehandle, BOOL compressiondialog);
	BOOL AVISaveFrameSetSpeed(long scale);
	long CreateColorImageHandle(long width, long height);
	long CreateGrayImageHandle(long width, long height);
	BOOL AVISaveFrameShowCompressionDlg(long imagehandle);
	BOOL AVISaveFrameSetCompression(long imagehandle, LPCTSTR fourcc, long quality);
	BOOL ToClipboard(long imagehandle);
	BOOL CaptureToClipboard();
	BOOL SaveJPEG(long imagehandle, long quality, LPCTSTR filename);
	CPicture ToPicture(long imagehandle);
	BOOL AVISaveMovieShowAudioDlg();
	BOOL AVISaveMovieStart();
	BOOL AVISaveMovieInit(LPCTSTR filename);
	BOOL AVISaveMovieStop();
	BOOL AVISaveMovieShowCompressionDlg();
	BOOL AVISaveMovieClose();
	void GetVersion(LPCTSTR versionstring);
	void AVISaveMovieSetFrameRate(float framespersecond);
	BOOL ReleaseMatrixToImageHandle(long imagehandle);
	BOOL ReleaseMatrix();
	VARIANT GetMatrix(long imagehandle);
	BOOL Seek(long framenumber);
	BOOL ShowInWindow(long imagehandle, long window, long left, long top, long width, long height);
	long GetDriverCount();
	CString GetDriverName(long drivernum);
	BOOL Initialize();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VIDEOOCX_H__196736F8_924B_4214_B97C_944EF15355A8__INCLUDED_)
